### ISSUE TITLE
Allow `pulumi import` to "guess" dependencies

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#10025]
The `pulumi import` command supports bulk import via a JSON input file `pulumi import -f import.json`.  This allow a large number of resource to be imported and code-generated at once.

The biggest shortcoming of this bulk import is that the resulting code doesn't know about any dependencies between resources, all inputs are just listed as literals.  So if a Bucket and BucketObject are important, instead of the object refering to `bucket: bucket.id`, the two resources will be unrelated, except for a literal reference to a bucket name that happens to be the same as the one imported.

We could, at the very least heuristically, do much better.  Among the ideas in this direction:
1. If any input to a resource is the same as the `id` output of another resource, assume there is a dependency on the other.
2. If any input to a resource is the same as the output value of any output-only  property of another resource, assume there is a dependency on the other resource.
3. Allow users to provide "hints" about dependencies in `import.json` - either just a set of resources that it should depend on, or a set of specific resource properties - which can either/both be included in `dependsOn` or used to apply the hints in (1) and (2) above.

There are probably some even smarter heuristics that might be possible, but I assume the above would capture the 80% case, with the remaining being more in the class of things where users really would need to get involved directly (like reverse engineering loops, etc.).

**Comment by samene** [comment]
This would be a really nice feature to have, like allowing to specify explicit dependencies in the `import.json` (option 3).

We have around 200 helm charts, 20 namespaces and 20 secrets (one docker registry secret in each namespace) which we are bulk importing from terraform to pulumi using the `import.json` method. In our pulumi code some of the charts and namespaces are missing (because they are no longer needed). However since the import did not include any dependencies, the namespace secret and chart are deleted all at once, leaving behind CRD's which would not have happened if the imported state had dependencies.

Is there a workaround to this problem?

**Comment by alexvaut** [comment]
+1

**Comment by Zaid-Ajaj** [comment]
We have improved the import feature such that it will do a best effort approach to find dependencies of resources in the codegen step. The idea is that if the literal value of a resource property is the same the `id`, `name` or `arn` value of another resource's property (a dependency), then we generate a symbolic reference `<dependency>.id`, `<dependency>.name` or `<dependency>.arn` in the code instead of emitting the literal value. 

This resolves point 1. and 2. (although we are only guessing a subset of properties). As for point 3. there are no concrete plans at the moment for special hints in the import file as the current improvements might work for most use-cases.

**Comment by justinvp** [comment]
Closing this as complete. I opened https://github.com/pulumi/pulumi/issues/17419 to track point 3, allowing users to provide hints.
