### ISSUE TITLE
pulumi refresh is different than pulumi up

### ISSUE THREAD

**Issue by rkpawaz** [pulumi/pulumi#10084]
### What happened?

Duration: 3s
```
```

Resources:
    + 2 to create
    - 46 to delete
    48 changes

Do you want to perform this update?  [Use arrows to move, enter to select, type to filter]
  yes
> no
  details
```

### Steps to reproduce

Our setup has: (s3 is backend for stack)
a) all auto naming turned off
b) Someone created lambda with deleteOnReplace - Stack A
c) Im being asked to import the lambda by name and deploy code to it.
d) I deploy code it works (deleteOnReplace is false though)
e) then pulumi refresh vs pulumi up shows a difference
d) running pulumi up via LocalWorkspace is same as pulumi refresh --diff, but pulumi up cli wants to delete everything.

### Expected Behavior

should be same

### Actual Behavior

is different

### Versions used

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ranikamala** [comment]
The reason is pulumi refresh takes remote stack details
while pulumi up takes local index.ts and tries to overwrite remote stack.
If this is expected behavior please close bug. I wish pulumi cli has an option to make this check (somehow)

**Comment by iwahbe** [comment]
Hi @ranikamala.
I'm not sure I understand your "Steps to reproduce". It sounds like
1. Someone created a stack: `A` and deployed a resource: `a` to it. They set `a.replaceOnDelete = true`.
2. You imported resource `a` into a new stack `B`. Lets call this Pulumi resource `B.a`. This import did not (and would not) preserve the `a.replaceOnDelete`.
3. You made changes to the `index.ts` that describes `B.a`.
4. You deployed `B` via `pulumi up`
5. You run `pulumi up` and `pulumi refresh` on stacks `A` and/or `B` and get different results.

Step 5 is where it is no longer clear to me what happened. Can you clarify your "Steps to reproduce"?

### In general

It sounds like you are managing the same lambda in multiple stacks. You should try to avoid this since the stacks will compete with one another. Each resource should be managed by 1 stack only. Import is a facility to move a resource into a stack, not to share the resource between stacks. 

`pulumi up` takes your program and local state and makes changes so that your state matches what your program described. It doesn't fetch the state of the world. `pulumi refresh` updates your local state to reflect the actual state in the cloud providers. If you want to run `pulumi refresh` as part of the `pulumi up` you can use `pulumi up --refresh`.

If you are changing a resource from multiple stacks, it makes sense that `pulumi refresh` and `pulumi up` will show different diffs.
