### ISSUE TITLE
Resource level RBAC 

### ISSUE THREAD

**Issue by waraposn** [pulumi/pulumi#10324]
## Stack restriction on resource access (using stack reference from another stack)

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We have n stacks that rely on a common stack that holds our secrets etc. Those n stacks consume secrets from that common stack but not every stack will have access to every secret in that common stack. Having RBAC at resource level will help address that security concern. 

### Affected area/feature

Automation API, RBAC for stacks at a resource level

**Comment by AaronFriel** [comment]
Hey @waraposn, thanks for suggesting this. If I understand this correctly, you're requesting that there be a way to:

1. Mark outputs on a stack as having some role based access control authorization policy to read them.
2. Modify the service/backends to be able to enforce these policies, so that StackReferences would fail when the logged in user lacks authorization.

It seems you're suggesting Automation API may be running untrusted programs, or programs with untrusted inputs to StackReferences.

I believe we have users using Automation API in scenarios similar to this, but I think you'd be best served by our services team or customer engineering to mitigate security concerns and guide implementation. If that sounds like it'd be helpful, I can connect you with the right folks.

**Comment by waraposn** [comment]
Hi @AaronFriel -- thanks for the quick response. 

> 1. Mark outputs on a stack as having some role based access control authorization policy to read them.
> 2. Modify the service/backends to be able to enforce these policies, so that StackReferences would fail when the logged in user lacks authorization.
>
> It seems you're suggesting Automation API may be running untrusted programs, or programs with untrusted inputs to StackReferences.

Not quite. Here's an example:
Stack A has 20 resources (secrets)
Stack B references 2 resources from Stack A 

The way StackReferences currently work, Stack B will have access to all resources in Stack A. What we're looking to do is restrict Stack B to only read the 2 resources that it needs from Stack A. 

Now take the above example and imagine having tens of stacks and they all read `n` different resources from a `common stack`. We want to be able to add policies that let other stacks read only the allowed resources from the `common stack`. Let me know if that makes sense, if not, happy to jump on a call too :)

**Comment by AaronFriel** [comment]
It does make sense. I think that if you could split "Stack A" into separate stacks, separated by the "security level" of each, it's possible [Team Access Tokens](https://www.pulumi.com/docs/intro/pulumi-service/team-access-tokens/) could be used to limit access. E.g.:

* Stack Prod-Security has 18 secrets
* Stack Staging-Security has 2 secrets
* Stack B is operated using a CI account with a Team Token that has read access Staging-Security

Stack B will then be able to read stack references from `Staging-Security` (the two secrets that it needs), but not from `Prod-Security`.

I think since that's a feature of the service offering, not the CLI per-se, I'd have to refer you over to sales or customer engineering. Would that work?

**Comment by AaronFriel** [comment]
@waraposn if this was helpful, please let me know. Closing this for now.
