### ISSUE TITLE
[auto] Allow accessing current user organization membership and current backend URL via API

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#10356]
We expose [`whoami`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/automation/#LocalWorkspace-whoAmI) in Automation API, which provides the user's identity.  However, we do not expose the other two pieces of data in `pulumi whoami --verbose`:
* Organizations
* Backend URL

Ideally these would be accessible directly via Automation API as well.

Most likely we should expand the return type of WhoAmI to include this data (in TypeScript, Python and .NET that can be done without a breaking change.  In Go it appears we directly return a string instead of a struct - so it may be a breaking change).

**Comment by lukehoban** [comment]
Alternatively or additionally, consider adding `About` to Automation API to expose `pulumi about`.

**Comment by Frassle** [comment]
Note that "pulumi org" prints this:
```
$ pulumi org
Current Backend: https://api.pulumi.com
Default Org: Frassle
```

**Comment by mrod-io** [comment]
I'd be happy to pick this one up for node / go / python! 👍  cc @RobbieMcKinstry @Frassle

**Comment by Frassle** [comment]
https://github.com/pulumi/pulumi-dotnet/pull/120 for dotnet

**Comment by Frassle** [comment]
That PR did flag an issue with this change actually. Old CLI versions won't have a "--json" flag and so running the new WhoAmI methods with an old CLI will throw an error.

Awkward, we clearly didn't trigger this would be an issue in the first PR because that runs the automation tests with the freshly built CLI that had just had --json added to it.

I don't think we should reverse this change (it's generally a good one) but I do think we'll need to go through and mark these new fields as optional, and work out some way in each auto api to only use "--json" if the cli supports it. Will ping internally for the team to think about this.

**Comment by Frassle** [comment]
We've added a version check for the dotnet sdk. I'll fix up the other SDKs shortly. We haven't had anyone complain about this so it seems low impact but should be an easy fixup.

**Comment by justinvp** [comment]
Looks like there's nothing else to do and this work is complete. https://github.com/pulumi/pulumi/pull/12466
