### ISSUE TITLE
Enable a configuration value to pass flags to the runtime

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#10641]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We ran into an issue where we need to troubleshoot eventSink, however we can not pass flags to node. Please add a config option for runtime_flags. 
`
I0826 00:10:23.061554   65436 eventsink.go:78] eventSink::Infoerr(<{%reset%}>(Use `node --trace-warnings ...` to show where the warning was created)
`

### Affected area/feature

Pulumi cli.

**Comment by gitsan13** [comment]
I would like to try and implement this feature. Since I am beginner to this, can you please guide me through the process?

**Comment by RobbieMcKinstry** [comment]
Hi @gitsan13, I'd be happy to help guide you. Please check out our [Contributor Guide](https://github.com/pulumi/pulumi/blob/master/CONTRIBUTING.md) on how to get started developing Pulumi locally.

For this particular issue, the intent is to add a new CLI flag to `pulumi preview` and `pulumi up` to pass extra arguments to the runtime.

For example, in a Pulumi TypeScript project, something like:

```bash
$ pulumi preview --extra-args='--jitless'
```

... since `--jitless` is an argument to the `node` CLI tool.

**Comment by justinvp** [comment]
There's actually already a way to specify arguments to `node`, via the `nodeargs` runtime option added in #8655.

In `Pulumi.yaml`, replace:

```yaml
runtime: nodejs
```

with:

```yaml
runtime:
   name: nodejs
   options:
     nodeargs: "--trace-warnings"
```

I've gone ahead and added some documentation for `nodeargs` in https://github.com/pulumi/pulumi-hugo/pull/1924, which will soon go live at https://www.pulumi.com/docs/reference/pulumi-yaml/#runtime-options
