### ISSUE TITLE
[filestate backend] Pulumi stack ls --json always returns updateInProgress False, even when there is actually an update in progress

### ISSUE THREAD

**Issue by drf7** [pulumi/pulumi#10677]
### What happened?

When running `pulumi stack ls --json` the returned field updateInProgress is always False, even when an update is taking place

### Steps to reproduce

Run: `pulumi up`
Meanwhile pulumi is updating the stack run: `pulumi stack ls --json`

You can run multiple times the command `pulumi stack ls --json` meanwhile the update is going through and it will never show True in the updateInProgress field

### Expected Behavior

Expected output:
```
[
  {
    "name": "dev",
    "current": true,
    "lastUpdate": "2022-09-12T11:41:08.686Z",
    "updateInProgress": true,
    "resourceCount": 3
  }
]
```

### Actual Behavior

Actual output:
```
[
  {
    "name": "dev",
    "current": true,
    "lastUpdate": "2022-09-12T11:41:08.686Z",
    "updateInProgress": false,
    "resourceCount": 3
  }
]
```

### Output of `pulumi about`

```
CLI          
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.67.0
python        unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/anaconda/envs/py38_default/bin/python3' version='3.8.13
'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           ruizfad001
URL            file://~/pulumifirststeps/backend
User           ruizfad
Organizations  

Dependencies:
NAME                 VERSION
pip                  22.2.2
pulumi-azure-native  1.67.0
setuptools           63.4.2
wheel                0.37.1

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like this is because the service sets lastUpdate time to 0 when an update is in progress, the cli then uses that to decide the value of updateInProgress. The filestate backend doesn't set last update to 0, instead just returning the manifest time recorded in the snapshot, which is always set when writing out to the current time.

**Comment by ahmed-wajid** [comment]
Does that mean that any backend, which is not using the Pulumi Service, should behave this way? We are using Azure Blob Storage as a backend, and see the same behavior. It is rather misleading to have `updateInProgress` in the output, when it is always false unless using the Pulumi Service as a backend.

**Comment by Frassle** [comment]
> Does that mean that any backend, which is not using the Pulumi Service, should behave this way?

"Should" no, "Will" yes. I'd agree this is a bug, but I don't think it's a quick fix.

**Comment by lukehoban** [comment]
Just to summarize a few things:
1. This issue is specific to the filestate backends.  The httpstate backend (Pulumi Cloud) does not have this issue and does correctly report whether updates are in progress.
2. It appears that this feature has never been supported in the filestate backend, so there is a feature request to add support for tracking "update in progress" to the filestate backends
3. We should likely disable showing this at all in the filestate backend as a first step, since in practice this just isn't implemented, and then track a feature to add support in.

**Comment by tgummerer** [comment]
I just merged the changes to no longer display the `updateInProgress` field in the json output if we are using filestate backends, so I think we can consider the bug fixed.  This still leaves the feature request, and I opened https://github.com/pulumi/pulumi/issues/14423 to track that.

**Comment by pierskarsenbarg** [comment]
re-opening for internal tracking of customer issue
