### ISSUE TITLE
Allow specifying a team when creating a stack

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#10784]
Similar to the way that you can specify an org to parent a stack to at create time, we should support parenting to a team as well. 

This could be accomplished via adding a team flag: `pulumi stack create --team`. There is a fair amount of friction around managing team and stack membership, and this would help streamline getting stacks appropriately configured from the beginning. 

Related https://github.com/pulumi/pulumi/issues/10783

Vote on this issue by adding a 👍 reaction

**Comment by Frassle** [comment]
@EvanBoyle whats the API flow for doing this? Looks like a PATCH to "/orgs/{orgName}/teams/{teamName}" with the UpdateTeamRequest struct?

Should we move that type to go/common/apitypes like other service types (e.g. https://github.com/pulumi/pulumi/pull/10912), although I'll repeat again it would be really nice to have openapi generated types for all this.

**Comment by EvanBoyle** [comment]
Yes, the bit we'd want to specify is `AddStackPermission  *TeamStackPermission`:

```go
type TeamStackPermission struct {
	ProjectName string          `json:"projectName"`
	StackName   string          `json:"stackName"`
	Permission  StackPermission `json:"permission"`
}

const (
	StackPermissionNone  StackPermission = 0
	StackPermissionRead  StackPermission = 101
	StackPermissionWrite StackPermission = 102
	StackPermissionAdmin StackPermission = 103
)
```

We'd want to set `StackPermissionWrite` (if you create a stack the first thing you'll likely do is update it). 

> I'll repeat again it would be really nice to have openapi generated types for all this.

Agreed. We have an issue open for this. I'm hoping we get to it next quarter https://github.com/pulumi/service-requests/issues/100

**Comment by RobbieMcKinstry** [comment]
Note: we should implement this in the Automation API once we add it to the CLI. I'll open an issue to track that.

**Comment by RobbieMcKinstry** [comment]
Hello! I have a draft PR implemented in #11974 . However, I've been considering the API design a bit, and I want to revisit [this discussion that we had previously](https://pulumi.slack.com/archives/C8A7QG1CZ/p1674063697007969?thread_ts=1674063208.912349&cid=C8A7QG1CZ). Specifically, we originally said we want the backend to accept a list of team names, and assign some default permission to those teams. My concern is in designing the CLI and the HTTP JSON shape to be forward-compatible for when we inevitably receive a customer request to support more than just a default permission.

--------

The CLI command will look like this:

```bash
$ pulumi stack init --stack dev --team red --team blue
```

When this CLI command is run, a stack named `dev` is created, and the `StackPermissionWrite` permission is assigned to the Red and Blue teams.

Currently, the body of the POST request is designed to look like this:

```
Method: POST
Route: /api/stacks/<owner>/<project>
```

```
{
  stackName: "dev",
  tags: {...},
  teams: ["Red", "Blue"],
}
```

The `teams` field receives an array of strings. Its likely users will request setting `StackPermissionRead` and `StackPermissionAdmin` in the future. While we should aim to keep it simple at first, we should aim to be forward-compatible because otherwise, we could get blocked waiting until a Pulumi v4.0 release.


------

Here's how I propose we change the API and CLI commands:

```bash
$ pulumi stack init --stack dev --team-write red --team-read blue
```

```
{
  stackName: "dev",
  tags: {...},
  teams: {
    // In case we want to add other team-related fields later.
    permissions: {
        { team_name: "Red", permission: "StackPermissionWrite" },
        { tean_name: "Blue", permission: "StackPermissionRead"},
    }
  }
}
```

WDYT?

(S/o to Steve for reminding me we about having flags per permissions.)

-----------

**Alternative CLI UX:** _(I don't think there's precedent for this format elsewhere in the CLI.)_

```bash
$ pulumi stack init --stack dev --team red=write --team blue=read
```

cc stakeholders: @stevesloka @EvanBoyle @meagancojocar @justinvp

**Comment by RobbieMcKinstry** [comment]
From the CLI side, we could start with only adding a `--team-write` flag since this was what the Service team expected.

**Comment by stevesloka** [comment]
The other alternative is to have defaults in the service which would allow for a preconfigured settings to populate if not defined. That wouldn't be needed if we enable the CLI to specify. But in the end that's still less flexible then what you are proposing.

**Comment by justinvp** [comment]
For the service API, I will leave it to @EvanBoyle, @stevesloka, @meagancojocar, and team, but I think it's fine if the `teams` flag is a simple list of strings for now. The `teams` property can be evolved in the future to support either a simple list of team names or a map of more detailed objects in the future, if necessary. Although, at that point, rather than evolving `teams` it may make more sense for the CLI to be calling the existing API to modify the stack permissions (https://www.pulumi.com/docs/reference/service-rest-api/#grant-stack-access-to-team) after it creates the stack.

In terms of CLI UX, it'd be worth discussing with the rest of the Platform team. I like the simplicity of `--team red --team blue` (defaulting to whatever the service defaults it to) and don't think I'd want to complicate our CLI flags with `--team-write`, `--team-read`, and `--team-admin` (and have to add new `--team-<whatever>` flags for any future new permissions).

I don't mind the `--team blue=read` UX (or perhaps `--team blue:read`), and there is precedent with `pulumi up --config foo=bar`.

Another alternative is `--team blue --team-permission read`. This would be separate `--team` and `--team-permission` flags that would have to have the same number of values and the order would matter. We do something similar with `pulumi up --policy-pack <path> --policy-pack-config <config-path>` flags.

**Comment by EvanBoyle** [comment]
From a product perspective, my instinct is to not worry about permissions at the moment and only support the default permission. 

For the implementation, I don't care either way. @stevesloka  added support to the create stack API for a teams field: 

https://github.com/pulumi/pulumi/blob/eaed8a95cc39b9e1a433e4ea7410df5db82ce9fa/sdk/go/common/apitype/stacks.go#L53

However, if we think we'll get really detailed in the future (big if in my mind) then calling the grant stack access API might make more sense. 

One thing I would be sure to verify here is whether or not there are any gotchas with the auth model. For instance, does it matter if a stack is assigned to a team at create time or if it is done as a separate step? I would hope that the two would behave the same, but in practice updating a team requires the `TeamAdmin` role. 

I think that requiring that users have team-admin to use this feature kinda defeats the purpose. Having this happen via the createStack request might make it easier to adjust the auth requirements (if you are a team member you can init a stack and parent it to the team as long as you are a member with write permissions).
