### ISSUE TITLE
'refresh: true' option results in type error (v3.40.1)

### ISSUE THREAD

**Issue by nicholasgibson2** [pulumi/pulumi#10824]
### What happened?

Running Pulumi CLI command with `refresh: true` option results in the following error:
```bash
error: could not load current project: 1 error occurred:
	* #/options/refresh: expected boolean, but got string
```

### Steps to reproduce

Add the following configuration in `Pulumi.yaml` and run any pulumi command:
```yaml
options:
  refresh: true
```

### Expected Behavior

Stack refreshes, then performs specified command.

### Actual Behavior

Stack does not refresh, command does not run, and the following error is displayed:
```bash
error: could not load current project: 1 error occurred:
	* #/options/refresh: expected boolean, but got string
```

### Output of `pulumi about`

```bash
CLI
Version      3.40.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.20.2
python      unknown

Host
OS       darwin
Version  12.6
Arch     x86_64

This project is written in python: executable='/Users/XXX/anaconda/anaconda3/bin/python3' version='3.9.7
'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/XXX
User           XXX
Organizations  XXX, XXX

Dependencies:
NAME                    VERSION
azure-identity          1.10.0
azure-keyvault-secrets  4.4.0
pip                     22.2.2
pulumi-kubernetes       3.20.2
setuptools              63.4.2
wheel                   0.37.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tedchang77** [comment]
We're seeing this error as well. All deployments broke so we had to rollBack to the previous version.

**Comment by justinvp** [comment]
Thanks for opening this issue @nicholasgibson2. Looks like this regression was introduced by #10596.

Note the repo steps mention setting `refresh: true`, but this didn't reproduce the error for me. The problem is that the feature expects `refresh: always`, and setting that does lead to the `#/options/refresh: expected boolean, but got string` error.

It looks like our schema and documentation for the `refresh` option is incorrectly expecting a bool value, when instead it should be a string value.

**Comment by justinvp** [comment]
The fix has been merged. We're planning to release a new version which includes the fix some time today.
