### ISSUE TITLE
Get StackReference outputs as non-Output values (avoid need for apply)

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#10839]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As stack references are always available to the pulumi program, I would like to use them without Apply. I think they should be automatically derived to their types.

**Comment by mikhailshilkov** [comment]
@rshade Thank you for opening this issue. For the sake of completeness, could you please add code snippets for the current behavior and your proposed API. Thank you!

**Comment by Frassle** [comment]
I think the [go generics](https://github.com/pulumi/pulumi/issues/9143) work will help a lot with this, but even with that it's still not clear to users that it's OK to ApplyT a StackReference output because it always resolves even at preview time.

**Comment by lukehoban** [comment]
I'm going to use this issue to track the fundamental issue of being able to get StackReference outputs as non-Output values.  

As @Frassle notes, this problem is a bit deeper than the thing requested in https://github.com/pulumi/pulumi/issues/10839#issuecomment-1260735424.  That itself will be addressed by https://github.com/pulumi/pulumi/issues/9143.  It can also already be written like this (since https://github.com/pulumi/pulumi/pull/10085):

```go
privateSubnets := vpc.GetOutput(pulumi.String("privateSubnetIds")).AsStringArrayOutput()
```

But the friction of having to deal with `Output` at all in this case will still remain.  

This is also the same fundamental issue that leads to https://github.com/pulumi/pulumi/issues/5035. 

In the TypeScript SDK we added [`getOutputValue`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#StackReference-getOutputValue) as a solution to this need.  My sense is that something like that is the only way to address this.  

A few thoughts/suggestions:
1. We could/should add `getOutputValue` to the other languages
2. `getOutputValue` currently errors on reading secret values, which is somewhat frustratingly limiting.  We could/should either (a) allow accessing secrets but returning a boolean to indicate this so user code can handle or (b) offer a `getSecretOutputValue` as well to access known-secret config.  I think (a) is better, because the authors of this code don't *know* for sure whether the value from the other stack will be secret (and it could change from non-secret to secret without them having a chance to change their code).

**Comment by abhinav** [comment]
Hey, just an update:
We added a new feature called StackReferenceOutputDetails.
StackReference now has a method called outputDetails (may be PascalCase or with an Async suffix depending on language) that provides non-Output access to StackReference outputs, including secrets.

As of now, this feature is available in all SDKs:

- Go: https://github.com/pulumi/pulumi/pull/12034
- Python: https://github.com/pulumi/pulumi/pull/12071
- Node: https://github.com/pulumi/pulumi/pull/12072
- .NET: https://github.com/pulumi/pulumi-dotnet/pull/103
- Java: https://github.com/pulumi/pulumi-java/pull/986

We'll be adding this to the documentation website soon (https://github.com/pulumi/pulumi-hugo/issues/2547) but this is ready to use now.

Marking as resolved.
