### ISSUE TITLE
Azure Devops support for multiple project templates under one directory

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi#10886]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

From a customer:

> I followed the pulumi/template github repo and made a repo in ADO that contained multiple templates under directories and when I run pulumi new it just throws "no templates" It doesn't list the templates in the repo. If I try a repo that only contains a single template that isn't nested in a directory it works as expected.

Add support for multiple templates under one directory. 

### Affected area/feature

`pulumi new`

**Comment by Frassle** [comment]
There's nothing ADO specific about how we read the template directory after cloning. If a single template works in ADO then multiple templates should work. Can we confirm that they had a repo layout _exactly_ like the templates repo, that is just one level of folders and each folder containing a "Pulumi.yaml" file?

**Comment by zbuchheit** [comment]
yes, the repo structure is like this
```
├───template1
│   │   Pulumi.yaml
│
├───template2
│   |   Pulumi.yaml
│
├───template3
│   |   Pulumi.yaml
```

**Comment by Frassle** [comment]
Ok thanks, I think that must be a bug in cloning the ADO repo then. The template code should have cloned the whole repo and found those directories.

**Comment by zbuchheit** [comment]
@Frassle I believe this may be known and there was some discussion on various ways to tackle it here on this issue 
https://github.com/pulumi/pulumi/issues/6360

**Comment by Frassle** [comment]
> @Frassle I believe this may be known and there was some discussion on various ways to tackle it here on this issue
https://github.com/pulumi/pulumi/issues/6360

That was for cloning the set of templates from a sub-path, e.g. if your repo had a "templates" folder with all the templates within it, that is not supported because we don't have a way to parse a subpath off an ADO url.

This was just that even if we cloned the whole repo we had a path bug that meant we didn't return the set of templates in the repo. This would have kind of worked before in that if you had one single template at the root of the repo it would have been picked up, but that should still work _plus_ a layout like you commented above should also work as well with the fix in https://github.com/pulumi/pulumi/pull/10954.
