### ISSUE TITLE
Presence of pulumi.DependsOn results in a runtime error 

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#10951]
### What happened?

Presence of pulumi.DependsOn results in an error: resources.MyComponent.MyEnumProp is typed as *string but must be a type that implements pulumi.Input or pulumi.Output for input with dependencies

### Steps to reproduce

Using a go generated MLC, create a simple example that creates a resource and uses `pulumi.DependsOn` targeting a dependent resource.

### Expected Behavior

`pulumi up` succeeds

### Actual Behavior

Program fails with `resources.MyComponent.MyEnumProp is typed as *string but must be a type that implements pulumi.Input or pulumi.Output for input with dependencies`

### Additional context

Internal Slack Thread: https://pulumi.slack.com/archives/C01028X5X3K/p1665508743426729

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
When the Go SDK marshals properties, it builds-up a `propertyDependencies` map of property names to dependencies associated with the property. If a property doesn't have any dependencies, it's not added to the map:

https://github.com/pulumi/pulumi/blob/f7136112231abade55f815eed0b8be6a61d466fa/sdk/go/pulumi/rpc.go#L146-L148

If none of the properties have any dependencies, then the `propertyDependencies` will be empty.

This is different from the Node.js and Python SDKs (I need to check the behavior of the other SDKs), where the `propertyDependencies` map will always be filled with property names, even if a property has an empty set of dependencies.

When the engine receives a `RegisterResource` call, it has the following code:

https://github.com/pulumi/pulumi/blob/f7136112231abade55f815eed0b8be6a61d466fa/pkg/resource/deploy/source_eval.go#L1057-L1062

If the `propertyDependencies` is empty, it treats each property as depending on every resource in the request's dependency list (i.e. the resources specified in `pulumi.DependsOn` `ResourceOption`). This was intended for very older clients that didn't have support for `propertyDependencies`.

So in this particular case, there are no dependencies associated with any of the properties, so the Go SDK is sending an empty `propertyDependencies`, and when the engine sees that there are no property dependencies, it creates a `propertyDependencies` map and fills it in with dependencies from `pulumi.DependsOn`.

There are a few changes we should consider making here to address this:
1. Change the Go SDK to always send a filled-in `propertyDependencies`, even if the properties have an empty set of dependencies.
2. Fix the engine (CLI) to not back-fill `propertyDependencies` when the `RegisterResource` request is for a remote component -- because any SDK that supports that, already supports property dependencies, so no need to backfill.
3. I need to dust-off and get back to this old PR to deprecate `propertyDependencies` when sending output values to `RegisterResource`: #8410
