### ISSUE TITLE
Stack corrupted by "parent coming after child..." error

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#10950]
### What happened?

During an update with a S3 backend stack, an error occurred and state became corrupted. The error is:

```
pulumi:pulumi:Stack aws-s3-stack running 
pulumi:providers:aws aws-provider-source  
pulumi:providers:aws aws-provider-destination  
pulumi:providers:pulumi default  error: post-step event returned an error: failed to save snapshot: .pulumi/stacks/aws-s3-stack.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/aws-s3-stack.json.bak): child resource urn:pulumi:aws-s3-stack::aws-to-primary::pulumi:providers:pulumi::default's parent urn:pulumi:aws-s3-stack::aws-s3-stack::pulumi:pulumi:Stack::aws-s3-stack comes after it
pulumi:pulumi:Stack aws-s3-stack running error: update failed
pulumi:providers:pulumi default **failed** 1 error
pulumi:pulumi:Stack aws-s3-stack **failed** 1 error
```

Possibly related to: https://github.com/pulumi/pulumi/issues/5577 

### Steps to reproduce

Unknown...TBD

### Expected Behavior

`pulumi up` succeeds

### Actual Behavior

Stack state gets corrupted.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I suspect this isn't actually a problem with the S3 backend itself, but an issue elsewhere.

It looks like somehow the pulumi default provider was recorded to state before it's parent stack resource was. The stack _must_ have been registered first because the step generator asserts that the parent for resources can be found. 

It would help to know what language SDK this was using, and if they're doing anything special about how they're creating the stack resource.

**Comment by rh4ll** [comment]
I have experienced a similar thing:
- in a code branch
- change parent of resource with children
- run pulumi up on stack
- on main branch run pulumi up on stack
- Get error

**Comment by dougludlow** [comment]
Just ran into the same issue, with the same steps @rh4ll mentioned. Pulumi version: `3.64.0`.
