### ISSUE TITLE
Refactor the resource model

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1108]
We need to change the way we model resource properties.  It's a subtly small change, but very deeply semantically meaningful.  @pgavlin could you attach your design notes for this?

This is a prerequisite for doing refresh and more.

Also, note to self, as part of doing this, let's factor all checkpoint-related types into a separate package.  For example, instead of `CheckpointV2`, we will have `apitypev2.Checkpoint`, including the transitive closure.

**Comment by lukehoban** [comment]
@pgavlin Will we make this change in 0.16?

**Comment by pgavlin** [comment]
That's a good question, and my answer depends on its relation to the k8s provider in particular. If we feel that the k8s provider requires this in order to be at its best, then we should plan on getting this done in 0.16, yes. Otherwise we should move it out.

**Comment by lukehoban** [comment]
@pgavlin I'm moving this out of 0.16 since we decided to focus on other issues around 1st class providers and parallelism.  But this feels critical to prioritize in 0.17.

**Comment by chrsmith** [comment]
If we are making any changes to the resource model this milestone, I'll add one quick note:

> Resources are identified by type, name, and parent

In the past we've discussed areas where this is insufficient, i.e. the URN isn't specific enough in some cases. For example, in a Delete+Create scenario both resources would have the same URN but  may need to be tracked differently IIRC. Do I have that right?

It would make our lives a little easier on the service if every resource had a UUID assigned to it upon creation, in addition a URN, since it would allow us to more conveniently lookup and differentiate resources. As well as have a fixed key length than an arbitrarily long URN.

I don't believe this is a requirement that needs to be piped through the engine however, as I assume it's possible we can just do a URN -> UUID mapping entirely service side. But having the UUIDs be at the underlying engine level would ensure that we wouldn't have any issues related to name conflicts and/or duplicate URNs during the lifetime of an update.

**Comment by lukehoban** [comment]
Let's take a bit more time before jumping into this deep re-architecture work.  This is not currently deeply blocking any high-priority user scenarios as far as I'm aware.

**Comment by lukehoban** [comment]
Removing an explicit milestone from this for now.  Let's plan to do this if/when necessary to deliver on one or more critical user-facing feature(s).

**Comment by leezen** [comment]
In an effort to keep the issues backlog clean, I'm closing this issue out until the use case arises. Also related: https://github.com/pulumi/pulumi/issues/918
