### ISSUE TITLE
Missing numbered list content in .Net reference docs

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#11120]
### What happened?

In the [.Net reference Output docs](https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.Output-1.html), the text for a numbered list is missing.

<img width="758" alt="Screen Shot 2022-10-21 at 9 50 26 AM" src="https://user-images.githubusercontent.com/12074/197306973-372aefb9-992c-4aa3-9eb4-2042c88acc96.png">

The expected text is in the [source comment in Output.cs](https://github.com/pulumi/pulumi/blob/79c0af75e8265c2979a6ab027c4abfaacb546758/sdk/dotnet/Pulumi/Core/Output.cs#L133-L134).

### Steps to reproduce

Navigate to https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.Output-1.html

### Expected Behavior

Numbered list from source comment is rendered in documentation.

### Actual Behavior

a void of text is enumerated

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @thomas11 I've been looking into this issue, I suspect the [docfx](https://dotnet.github.io/docfx) version we use in pulumi/docs is outdated. I've trying it out myself but without luck because it needed a _MONO_ runtime 😱 on macOS and linux (mono runtime is dotnet cross-platform implementation when dotnet wasn't cross-platform 10 years ago or so 😓)
