### ISSUE TITLE
Support a pseudo-org for StackReference and GetOrganization API on filestate 

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#11390]
We have a number of features that now depend on detecting an organization and rendering it into a string. Among these, the get organization API in the SDKs and the StackReference resource.

The blocker here is deciding on how to handle the org or user name portion of the `$org/$project/$stack` string. 

Resolving this for filestate backend will enable more integration tests to run locally, a significant win for test velocity, and remove potential panics and special casing logic in user programs. 

Pulumi YAML in particular needs a pseudo-org to ensure the "organization" API does not panic, as we lack conditionals or the ability to branch on an optional value.

**Comment by Frassle** [comment]
I've actually been thinking about maybe just support orgs and projects in filestate. They would both just be folders really, but by default if you had a backend set to "s3://my_bucket" we'd save stacks to full path like "s3://my_bucket/fraser/the_project/the_stack/state.json"

By default the org would just be the username, but you could use `pulumi org set-default` to change it to anything else.

**Comment by courtland** [comment]
Now that self-hosted backends (e.g. S3) are project aware (3.61.0), are there any plans to include org as well?

**Comment by justinvp** [comment]
We're not planning to add support for orgs in self-managed backends. New and upgraded self-managed backends with v3.61.0 and later all have a virtual organization named "organization" which allows for a consistent `organization/project/stack` syntax for StackReferences across backends, which is what this issue is tracking and can now be closed.

Fixed by https://github.com/pulumi/pulumi/pull/12437
