### ISSUE TITLE
Can the state be shared cross different languages?

### ISSUE THREAD

**Issue by anemptyair** [pulumi/pulumi#11403]
For example,
I created S3 bucket(example01) with golang languages, and then other members are going to update the S3 bucket(example01) with Python languages. Will it be doable and the state is shared cross golang & python code?

Best wishes,

**Comment by aq17** [comment]
Hi @anemptyair, a Pulumi program determines the state, so if you were to start with instantiating resources with a go program, you can definitely reference the same resources in a python program after [importing](https://www.pulumi.com/docs/guides/adopting/import/) those resources. However, if you wanted to subsequently manage the resources again with your original go program, you should make sure to [refresh](https://www.pulumi.com/docs/reference/cli/pulumi_refresh/) your go program state, so that any changes the python program made to the resources will be reflected first.
