### ISSUE TITLE
Play nice with /tmp mounted with noexec

### ISSUE THREAD

**Issue by daenney** [pulumi/pulumi#11687]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi uses `/tmp` or whatever `$TMPDIR` points at when running `pulumi up`. However, for security reasons many (Linux) systems have `/tmp`/`$TMPDIR` mounted with `noexec` (and usually also `nosuid` and `nodev` though they shouldn't affect this) resulting in the following error:

```
Diagnostics:
  pulumi:pulumi:Stack (infra-prod):
    error: an unhandled error occurred: command errored unexpectedly: fork/exec /tmp/pulumi-go.813906212: permission denied
```

I can work around this by always invoking `pulumi` with something like `env TMPDIR="somewhere else" pulumi up`. However, this is a bit annoying and it would be nice to have that configurable. For example, Go lets me explicitly set a `GOTMPDIR` using `go env` which takes precedence. I do not wish to rewrite `TMPDIR` to a different location globally as things that want to create temp files may do so in `/tmp` just fine, but they may not be executed.

Aside from a configuration option, there's a couple of alternatives:
* Respect `$GOTMPDIR` if set (probably shouldn't use it though, it's Go's, so maybe a `PULUMITMPDIR` instead)
* Detect `/run/user/<id>` (created by pam_systemd) and default to that instead

`/run/user/<id>` is what you'll find on systemd systems, is unique to the user (so no writable by everyone things in `/tmp` issues) and gets cleaned up on logout for added benefits.

**Comment by RobbieMcKinstry** [comment]
Hey there @daenney that's an interesting point.

It sounds like this issue isn't necessarily specific to Go. I'm not quite sure how Dotnet and Java store compiled artifacts, but it's possible they drop them into `$TMP` as well. However, it sounds like your use case is Go.

If that's true, then I think there's already a configuration option that would fix this for you.
Have you seen the `buildTarget` runtime configurable? When set, this specifies the path that the compiled Go binary will be saved to. That way, you could set it to something like `.pulumi_program`, and it store the binary in your working directory instead of in `$TMP`.

If that works for you, I'll mark this issue as resolved. We can always reopen if we discover Java and Dotnet have the same problem. Let me know what you think :) Thanks!

**Comment by daenney** [comment]
It doesn't seem to quite work unfortunately but I'm not sure why.

I'm using `/run/user/1000` in my case which is mounted as: `tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1416308k,nr_inodes=354077,mode=700,uid=1000,gid=1000,inode64)`. `noexec` is missing so things should work and when using `TMPDIR` they do:

```
$ env TMPDIR=/run/user/1000 pulumi preview
...
Resources:
    - 1 to delete
    +-3 to replace
    4 changes. 1 unchanged
```

However, if I configure that as the `buildTarget` it doesn't:
```yaml
runtime:
  name: go
  options:
    buildTarget: /run/user/1000
```

```
$ pulumi preview
Diagnostics:
  pulumi:pulumi:Stack (infra-prod):
    error: an unhandled error occurred: command errored unexpectedly: fork/exec /run/user/1000: permission denied
```

According to the output it's using the right directory, but the `fork/exec` permission denied clearly suggests it's still doing something somewhere on a path that's mounted with `noexec` or it otherwise doesn't have permissions to.

**Comment by RobbieMcKinstry** [comment]
Sorry if I'm misunderstanding, but it looks to me like you're `/run/user/1000` is a directory. The `buildTarget` argument takes a path to a file (which is where the program is written to). I think that's happening is this:
1. The runtime receives a request to compile-or-execute the Go program.
2. It checks the cache (i.e. where the compiled binary is expected to be) to see if the file exists. This `stats` /run/user/1000`, which exists.
3. The runtime tries to execute this file, assuming it's the executable that is expected.
4. Execution fails because the directory isn't executable.

That's my hunch, but it's far deviated from the simplest possible explanation. Would you mind trying one more time with...

```yaml
runtime:
  name: go
  options:
    buildTarget: /run/user/1000/out
```

...or another file name in place of `out`?

I appreciate your assistance here. I expect this feature to work as intended, but if it's not, then it could be bugged. It's a relative new feature but I haven't seen other bug reports for it, so my intuition is that the error messages are unhelpful.

**Comment by daenney** [comment]
Ahh, I misunderstood the `buildTarget`. I thought it was meant to be a directory. The docs mention it as "Path to save the compiled go binary to." so by "path" I took it to mean directory in which we'll drop it, not actual file itself.

Specifying it as a file does make it work. Thanks for the help!

**Comment by RobbieMcKinstry** [comment]
I'm glad we were able to solve this for you! Have a good one! :D

**Comment by hellt** [comment]
Hi all,
great that this issue exists, otherwise it would be quite hard to navigate this error.

As @daenney said, `/tmp` is often mounted with `noexec` for security reasons and for Go projects indeed the common workaround is to set GOTMPDIR env var that sets the temp dir for go programs.
It would be great if pulumi would respect this env var.

PS. The workaround worked for me as well.

**Comment by pdemagny** [comment]
It's also interesting to note that you get this very same error (`error: an unhandled error occurred: command errored unexpectedly: fork/exec ./pulumi-organization: permission denied`) if for some reason your pulumi program package name is not main ! (found it thanks to https://github.com/golang/go/issues/33889).
