### ISSUE TITLE
Pulumi Convert > CSharp to Yaml

### ISSUE THREAD

**Issue by TheRubble** [pulumi/pulumi#11730]
Hi,

I'm trying to convert a CSharp project to YAML, The documentation suggests that it should be able to convert between supported languages.

https://www.pulumi.com/docs/reference/cli/pulumi_convert/

```
pulumi convert --language yaml --out yaml-from-csharp --from csharp
```
However I get:

```
error: unrecognized source csharp
```

The documentation makes no reference to the allowed --from params, any help would be gratefully received.

![image](https://user-images.githubusercontent.com/482262/209313783-ab20eb09-709a-43a6-b28f-e2ccdc0346a2.png)

Thanks

**Comment by aureq** [comment]
@TheRubble I tried to reproduce the issue and right now, it's not possible to convert from `csharp` into `yaml`. Right now, using `--from` only accepts `yaml` (the default as mentioned in the [doc](https://www.pulumi.com/docs/reference/cli/pulumi_convert/)) or `tf` or `pcl`.

You may check the code here https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/convert.go#L214-L235

That said, you may be interested to look at `pulumi stack export` as a way to export the stack state and eventually perform some scanning.

**Comment by Zaid-Ajaj** [comment]
Hi @TheRubble, unfortunately converting csharp to yaml is possible from Pulumi nor is it something achievable given that csharp, python, typescript etc. can express complex programs that otherwise cannot be expressed by our YAML program specifications (for example for-loops). 

Currently we only convert from our intermediate language called PCL (short for Pulumi Configuration Language) and from Terraform code. The latter being worked on at the moment to improve the resulting Pulumi programs. 

Will consider your question as answered and close the issue. If you have further questions, please let us know!
