### ISSUE TITLE
Pulumi stopped supporting .netcoreapp 3.1

### ISSUE THREAD

**Issue by jlovald** [pulumi/pulumi#11768]
### What happened?

Pulumi stopped supporting .netcoreapp 3.1 in the latest release. There is no mention of this in the release notes, so this should not be expected behavior.
![Uploading image.png…]()

### Steps to reproduce

Reference Pulumi version 3.51.0 from a .NET project running on .netcoreapp 3.1

### Expected Behavior

Pulumi to support .netcoreapp 3.1

### Actual Behavior

.NET projects running on Core 3.1 and referencing Pulumi 3.51.0 won't compile.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Sorry this wasn't clearly visible in the release notes. That's due to the dotnet SDKs now releasing from their own repo not from this repo. In the dotnet repo the release notes do mention that 3.1 is not supported: https://github.com/pulumi/pulumi-dotnet/releases/tag/v3.51.0

This is also in line with out support policy of "Pulumi supports writing your infrastructure as code in any .NET language programs running on dotnet using any [supported version](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle)."

Microsoft dropped support for 3.1 on the 13th of December and so officially so do we. It's just we've only just released the SDK to match that.

If you want to stay on 3.1 you'll need to lock your Pulumi dependency to 3.49.

**Comment by Frassle** [comment]
Although interestingly we're going to have to revert this due to internal dependencies.
But all our provider libraries will be updating to net6.0 in due course so you will probably still want to update your apps to net6.0.
