### ISSUE TITLE
Community PRs Are Unmergeable

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi#11890]
### What happened?

Community PRs are currently unmergeable. This extends to all community PRs I've seen.

**Examples:**
* https://github.com/pulumi/pulumi/pull/11788
* https://github.com/pulumi/pulumi/pull/11498
* https://github.com/pulumi/pulumi/pull/11876

It appears that unit and integ tests are disabled for Community PRs. Bors requires certain status checks to pass before the PR can be merged. Community PRs don't trigger those checks anymore. 

<img width="879" alt="Screenshot 2023-01-17 at 12 48 50 PM" src="https://user-images.githubusercontent.com/4955075/212973931-19f022aa-bb25-4427-ba98-c5a54936237d.png">

### Steps to reproduce

Inspect linked community PRs

### Expected Behavior

I should be able to `:bors merge` PRs that are approved, and those PRs should be able to be tested.

### Actual Behavior

Cannot trigger tests on PRs

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Community PRs should not be running integration tests or unit tests due to security concerns - it is extremely easy to accidentally offer "credentials/crypto mining as a service" to drive-by PRs.

Instead, external PRs require `/run-acceptance-tests` slash commands or `bors merge` **after review**. 

Clicking the option to run checks on community PRs **is generally dangerous**, because that option typically allows external contributors to then make changes to GitHub workflows or even just run arbitrary code in code in their PR.

**Comment by RobbieMcKinstry** [comment]
Resolved offline. I was confused by a confluence of unrelated issues.
