### ISSUE TITLE
Previously working: ResourceOptions.provider not getting passed to ComponentResource resource in python

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#12161]
### What happened?

When using the Component Resources and setting a provider at the parent level they aren't inherited at the component. 

### Expected Behavior

It should pass the provider down. 

### Steps to reproduce

Code will be provided. 

### Output of `pulumi about`

CLI
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.28.0
awsx        1.0.1
docker      3.6.1
eks         1.0.1
kubernetes  3.23.1
python      unknown
random      4.8.2

Host
OS       ubuntu
Version  20.04
Arch     x86_64

Current Stack: richard-shade-pulumi/aws-eks-cr-poy2/dev

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
The repro for this involved the following:

```py
class Traefik(ComponentResource):

    def __init__(self,
                 name: str,
                 cluster: Cluster,
                 opts: ResourceOptions,
                 namespace: Optional[str] = "traefik"):

        super().__init__('custom:resource:k8s', name, {}, opts)
        self.name = name,
        self.cluster = cluster
        self.namespace_name = namespace
        self.namespace = Namespace(
            "test-namespace",
            api_version="v1",
            kind="Namespace",
            metadata=ObjectMetaArgs(
                name=self.namespace_name
            ),
            opts=ResourceOptions(parent=self, depends_on=[cluster])
        )

        self.register_outputs(outputs=None)

namespace = Traefik(
    "test",
    cluster=cluster.cluster,
    opts=pulumi.ResourceOptions(provider=cluster.k8s_provider, depends_on=[cluster.finalizer])
)
```

It works if the last line is changed to 

```py
opts=pulumi.ResourceOptions(providers=[cluster.k8s_provider], depends_on=[cluster.finalizer])
```

or:

```py
opts=pulumi.ResourceOptions(providers={'kubernetes': cluster.k8s_provider}, depends_on=[cluster.finalizer])
```

Components should take a list or map of providers, one or each kind of resource they need to create (in this case, Kubernetes child resources - but in general, there could be several different kinds).

That said - I'm unclear on why this silently fails.  I would expect it to either work as written, or to error early about trying to pass the wrong type of provider to a component?

**Comment by rshade** [comment]
It looks like this stopped working between 3.43.1 and 3.54.0.

**Comment by abhinav** [comment]
This may be related to @Frassle's comment in https://github.com/pulumi/pulumi/pull/12123#issuecomment-1426793060.
SDKs are merging `provider` and `providers`, but the order/precedence may be incorrect between SDKs.

**Comment by abhinav** [comment]
FYI, the behavior of how provider vs providers is treated was standardized in https://github.com/pulumi/pulumi/issues/8796.
That change was released in https://github.com/pulumi/pulumi/releases/tag/v3.23.0.

**Comment by abhinav** [comment]
Okay, following some digging:

**Why it doesn't work**

The provider is saved only if the resource is a custom resource:
https://github.com/pulumi/pulumi/blob/e21c6b83e5112ff772f4bbb912f76cb05cd1ad4a/sdk/python/lib/pulumi/resource.py#L854

So the ComponentResource doesn't save the provider, and therefore the children don't get it.

**Why we shouldn't make it work**

It would be easy enough to save the provider, but I don't think we should.
Per #8796, the `provider` option passed to a resource basically says "use this provider for yourself"
and if the type of the resource being created doesn't match that provider's package,
the SDK should error out.

> SDKs error if provider does not agree with the type of the resource being created.

And we _do_ have a check that does this, except it only works for custom resources right now.

https://github.com/pulumi/pulumi/blob/e21c6b83e5112ff772f4bbb912f76cb05cd1ad4a/sdk/python/lib/pulumi/resource.py#L855-L865

It doesn't get hit for component resources because of the previous snippet: the provider is just not stored for component resources.

**What we should do**

ComponentResources don't have a concept of "my provider" (yet) so the `provider` option doesn't make sense for them (yet). The right thing here will be for ComponentResources to return an error if they receive a `provider` option; the error can suggest to users that they probably meant to use the `providers` option. The `providers` bag will be inherited by child resources, matched by package.

This leaves our options open if we want a future where hybrid resources are backed by component resources (we can just drop the error), and doesn't block us if we decide hybrid resources are done a different way.
(Thanks to @AaronFriel for the insightful discussion on possibly hybrid resources and how they could happen in the future.)

**Comment by rshade** [comment]
@abhinav do you know if this is how it works across the sdks? This code seems to indicate a provider safety switch: https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/resource.ts#L342, this also doesn't seem to have custom qualifier: https://github.com/pulumi/pulumi/blob/master/sdk/go/pulumi/context.go#L838. I could be reading these wrong also. So let me know.

**Comment by abhinav** [comment]
Update: yeah, digging further into what the other SDKs do, I take back my original recommendation.
I've got roughly the following test for Go, .NET, Python, and Node:

- create a provider resource, "prov"
- create a component resource, "comp", and pass in "prov" as a provider
- create a custom resource "custom", with "comp" as parent
- check that the registered provider for "custom" is "prov"

This test passes for all but Python.

Given this, I'll update my recommendation: We should make this work in Python too.

**Comment by abhinav** [comment]
Working on fixing this for Python, I'm adding tests to all SDKs to cover this:

- .NET: https://github.com/pulumi/pulumi-dotnet/pull/109
- Go: https://github.com/pulumi/pulumi/pull/12290
- Node: https://github.com/pulumi/pulumi/pull/12291
- Java: https://github.com/pulumi/pulumi-java/pull/1003

**Comment by abhinav** [comment]
Reopening because the fix is getting reverted https://github.com/pulumi/pulumi/pull/12522
