### ISSUE TITLE
Adding (or changing) a stack output does not report as a change

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1227]
If I make a change which either adds, or changes the value of, a stack output - it does not get reported as though any change is happening.  This is misleading, as there is a change that will be applied to the stack and checkpoint file.

```
$ pulumi update
Previewing stack 'website-testing' in the Pulumi Cloud ☁️
Previewing changes:

#: Resource Type        Name                       Plan         Extra Info
1: pulumi:pulumi:Stack  s3website-website-testing  * no change

info: no changes required:
      3 resources unchanged

 Do you want to proceed? yes
Updating stack 'website-testing' in the Pulumi Cloud ☁️
Performing changes:

#: Resource Type        Name                       Status  Extra Info
1: pulumi:pulumi:Stack  s3website-website-testing  done

info: no changes required:
      3 resources unchanged

Permalink: https://pulumi.com/lukehoban/s3website/s3website/website-testing/updates/2
```

**Comment by pbzdyl** [comment]
I think I have this issue now with pulumi v0.16.8:

1. added `export const output1 = 'abc'` and run `pulumi up` and applied the change. The output is applied and visible in pulumi web console
2. added `export const output2 = 'def'` and running `pulumi up` gives:

```
$ pulumi up
Previewing update (unifi-infra-dev):

     Type                 Name                         Plan     
     pulumi:pulumi:Stack  unifi-infra-unifi-infra-dev           
 
Resources:
    11 unchanged
```

As you can see no change is reported. Then I run the update:

```
Do you want to perform this update? yes
Updating (sample-stack):

     Type                 Name                         Status     
     pulumi:pulumi:Stack  sample-stack             
 
Outputs:
    output1: "abc"
  + output2: "def"

Resources:
    11 unchanged

Duration: 49s
```

Now the new output is reported correctly. I am not sure if this ticket was regarding the preview or update phase but I think the preview phase should indicate a change in outputs too.

The same happens when I just change output value of an existing output or I remove an output.

Shall this ticket be reopened or a new one created?

**Comment by ellismg** [comment]
> Shall this ticket be reopened or a new one created?

Thanks for the report, I'm just going to re-open this one.

**Comment by joeduffy** [comment]
I've run into this several times -- definitely would be good to fix, as it's pretty confusing.

**Comment by joeduffy** [comment]
I just noticed another symptom of this: after running `pulumi destroy`, we don't show the old, now deleted outputs (neither in the preview nor in the actual update itself). It would seem we'd want to be consistent and show them here too -- in my case, I actually wanted to know what the old values were afterwards, so that I could go do some manual cleanup for one of the deleted resources.
