### ISSUE TITLE
README.md :-it does not create three web servers. it launches three ec2 instances

### ISSUE THREAD

**Issue by Harshalyadav** [pulumi/pulumi#12343]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by dixler** [comment]
Hi. The example in the readme should create 3 ec2 instances that are running web servers via the user data field running a python web server on startup. Because of that we have opted to label them as web servers rather than EC2s for the users that may be familiar with software development for web, but not as much with AWS cloud terminology. 🙂 

I hope this answers your question!

**Comment by Harshalyadav** [comment]
Ok, I understand
