### ISSUE TITLE
[go] Pulumi installs the latest plugin versions if the `go list -m -json ...` command fails

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#12526]
### What happened?

Currently, pulumi-go uses `go list -m -json -mod=mod all` to get a list of go deps for a given program, so that it can determine which pulumi plugin versions should be utilized. 

This works fine with most of the time, but encounters an issue when program deps are included via `go mod vendor` and some of those deps are sourced from private github repos.

Since all deps are located in the `vendor` directory of the program, Pulumi has all the required bits to execute a Pulumi program. The issue occurs when Pulumi tries to determine what version to use of a given Pulumi plugin. Pulumi uses the above mentioned `go list ..` command but this does not respect the presence of vendored deps and reaches out to github.com. This operation silently fails and Pulumi happily chooses the latest version of the plugin available.

### Expected Behavior

If a vendor directory is present, Pulumi should use the dependencies, and versions, located within the directory to correctly resolve the appropriate Pulumi plugin version(s) to be utilized.

### Steps to reproduce

1. Clone https://github.com/phillipedwards/go-output
2. cd go-output 
3. `pulumi stack init {your_stack}
4. remove all plugins - `pulumi plugin rm -a -y`
5. `pulumi pre`
6. Program specifies random@4.8.2, however, Pulumi downloaded the latest available.

### Output of `pulumi about`

CLI
Version      3.59.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown

Host
OS       debian
Version  11.6
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by phillipedwards** [comment]
This effectively means you cannot use Pulumi go programs, that reference private github repos, in connection with `go mod vendor`. Plugin acquisition will not respect what the language host (go) determines because the process silently fails.

**Comment by sfc-gh-jelsesiy** [comment]
Relates to https://github.com/pulumi/pulumi/issues/7089

**Comment by abhinav** [comment]
High-level thoughts on working towards the solution:

- `go list` should be preferred because it has a fuller view of the world.  e.g., if you imported something that's not yet in your go.mod, it'll add it.
- `go list -m -json -mod=vendor $importPath` is a completely offline operation. We can [parse go.mod with modfile](https://pkg.go.dev/golang.org/x/mod@v0.9.0/modfile#ParseLax), and get information about each module separately instead of `go list -m all` (which is disallowed in `-mod=vendor` mode).

Strawman suggestion:
We add an env var (something like `PULUMI_GO_VENDOR`?) that, if set, specifies that we should use the vendor/ directory's contents. If set, the user is giving us their word that go.mod is up-to-date (they ran `go mod tidy`, etc.).

If the env var is too high touch right now, we can also try to do the "right thing" by default:
If original `go list -m all` fails for any reason, and a vendor directory is present, parse go.mod and list in `-mod=vendor` mode.
I suggest this as a fallback behavior because I don't know if there's a way to be certain that go.mod and vendor/ are up-to-date. If there's a way to check that, then it doesn't need to be a fallback, it can be an automatic behavior: if vendor is present, and up-to-date, operate "offline".

Useful reference: https://go.dev/ref/mod
