### ISSUE TITLE
Support stock Terraform Providers in Pulumi programs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#12536]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider supporting stock Terraform Providers in Pulumi programs. As a Pulumi user, I would like to be able to reference any provider I find in https://registry.terraform.io by name and version in my program and have it provision resources managed by that provider in my Pulumi stack, alongside with other Pulumi resources. 

Background: the current approach for reusing TF providers in Pulumi involves building [bridged providers](https://github.com/pulumi/pulumi-terraform-bridge/). This is advantageous in providing a much nicer experience, including inferring a precise Pulumi Package Schema through static analysis, populating docs in Pulumi Registry, language-specific packages on NPM, NuGet, Maven, and other package managers, doing some quality control and reducing breaking changes between major releases.

However the bridging approach is expensive and requires a fair bit of maintenance work.  As a result, not all providers from the Terraform registry have been bridged to Pulumi yet, and it is unclear if this is feasible for Pulumi core team and/or community to accomplish this any time soon and keep up to date with the TF ecosystem.

The approach outlined here would be complementary to the bridging approach. There will be some compromises on the quality of experience, precise operation, avoiding breaking changes, or publishing documentation to Pulumi registry. However the approach would enable users to immediately consume resources from the entirety of TF registry. A less polished experience but a much broader immediately-up-to-date ecosystem.

### Technical Approach

There's currently a few feasibility risks on the way to building support for stock TF providers:

- Pulumi Terraform Bridge can talk Terraform v6 protocol to plugins, but still relies on static schema inference. It appears that recovering the schema from the v6 protocol is a lossy process. It currently was not found suitable for the level of quality expected from Pulumi bridged providers, but further research might find some suitable compromises and workarounds.

- The approach involves an on-demand construction of Pulumi Package Schema. Possibilities to work with partial schemes computed on-demand from the resources actually used in a program sound promising to reduce startup time, but are not necessary in principle.
 
- YAML programs are at an advantage that they require no on-demand construction of language-specific SDKs such as Python or TypeScript packages. They should be the first obvious candidate to benefit from this approach.

- Other languages require provider-specific SDKs. For programs that use a stock Terraform provider P, pulumi CLI and language plugins will need to orchestrate on-demand construction and linking of a language-specific package for P prior to invoking the language runtime. This needs infrastructure not available today but can be in principle built. The approach requires the dependency on a stock Terraform provider P to be specified outside of the program in a medium that can be consulted without evaluating the language-specific code, such as Pulumi Project File.

### Affected area/feature

Providers, Terraform Bridge, Language SDKs

**Comment by t0yv0** [comment]
Thanks for the notes @Frassle that's great input wrt feasibility! To me the bigger question is if this is indeed worth doing. Let us let this issue sit in the tracker for a bit and see if it resonates or collects upvotes to gauge interest - I mostly wanted to have an issue to track the idea, because I don't think we had a good issue about this.

**Comment by FollieHiyuki** [comment]
Hi! I'd like to contribute some thoughts, based on my experience with both tf-cdk and pulumi.

For context, we have a small Go monorepo for all of the infrastructure in our company. We heavily use Pulumi (as much as possible), leaving tf-cdk for providers currently not available in the Pulumi registry.

From a developer's point of view, the Go provider code generated by tf-cdk loses a lot of types. All maps and slices are treated as `interface{}`, so we have to look into the provider's docs to know which struct fits into their values. This might just be a problem with `jsii` go runtime, which is used by tf-cdk to generate the provider code. Also, tf-cdk lacks testing capability, with only basic assert available.

So, if Pulumi supports this workflow, it'd be a nice improvement for us:
- Provider mocking + integration testing
- Better types experience. Even if the generated Go code from Pulumi is just as good as the one from tf-cdk, we'll still have `pulumi.*` types to aid. It's already more comfortable than only 3 types (string, bool and float64) available in `jsii` libray.
- Native secret encryption

Otherwise, the "writing code" experience will be pretty much the same. Each project will still be a separated Go module, and they still can reference variables from each other, whether it is pulumi or tf-cdk one. It's not like tf-cdk and pulumi projects can't coexist in the same repository.

**Comment by iwahbe** [comment]
This is effectively implemented by [any TF provider](https://www.pulumi.com/blog/any-terraform-provider/) support.
