### ISSUE TITLE
Cross-package API dependencies don't render correctly

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#12765]
If a component exposes a part of its API which is defined in a separate package, the resource properties don't seem to link correctly. For example, see https://www.pulumi.com/registry/packages/kubernetes-cert-manager/api-docs/certmanager/#inputs. Many of the types are defined in the Kubernetes package, but don't link properly.

![image](https://user-images.githubusercontent.com/3953235/137790048-94e82b9e-891a-4cd8-8cc6-4e19f61047a4.png)

Notice the names of the types are squished, and they just link to the local page, rather than types in the Kubernetes docs.

**Comment by cnunciato** [comment]
Taking at look at this one, but I'm wondering: Where would we want these links to go? For example for `affinity`, should we link to the [selected language SDK on GitHub](https://github.com/pulumi/pulumi-kubernetes/blob/ed99a3613101f41ed01d9c889faf188df154c831/sdk/nodejs/types/input.ts#L11238)? To the [Kubernetes docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#affinity-v1-core)?

**Comment by sean1588** [comment]
I believe the intention would be to link to the docs page that contains that nested type defined on it. As possible resolutions, I think we could either find a way to determine which resource page in the external package has this type defined and link directly to that page and the part of it where the type definition is rendered, or render that type definition under the supporting types section directly within the same page and link locally within the page as we do for all the other nested types. 

I did do some quick grepping through that schema for the kubernetes-cert-manager package and the types that are missing on the page are listed under the `types` property at the root of the schema with a ref to that type in the external kubernetes package so we do have a reference as to where that type is be defined in the external schema. So in theory we could walk down that type structure if we had access to it. The issue is the full type definition exists in a different schema (i.e. the kubernetes schema in this case) which I think is what @lukehoban was referring to, and the context of the codegen is only aware of the current schema it is operating on as far as I know.

```
  "kubernetes-cert-manager:index:CertManagerCaInjector": {
    "properties": {
      "affinity": {
        "$ref": "/kubernetes/v3.8.1/schema.json#/types/kubernetes:core/v1:Affinity"
      },
```

... maps to in the kuberenetes provider schema:

```
"kubernetes:core/v1:Affinity": {
    "description": "Affinity is a group of affinity scheduling rules.",
    "properties": {
      "nodeAffinity": {
        "$ref": "#/types/kubernetes:core/v1:NodeAffinity",
        "description": "Describes node affinity scheduling rules for the pod."
      },
      "podAffinity": {
        "$ref": "#/types/kubernetes:core/v1:PodAffinity",
        "description": "Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s))."
      },
      "podAntiAffinity": {
        "$ref": "#/types/kubernetes:core/v1:PodAntiAffinity",
        "description": "Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s))."
      }
```

and the type refs within that are all locally defined in that schema I think we just need a way to make an external schema accessible to codegen or maybe embedding external types in the schema itself may be an option but am unclear of the nuances that may be involved in doing so. cc @iwahbe

**Comment by iwahbe** [comment]
We definitely do the work to resolve external types in SDK generation ([example](https://github.com/pulumi/pulumi/blob/69d179ae6e617b1db56a83e19dfeaa4f4084d259/pkg/codegen/go/gen.go#L780-L796)). 

Docs generation should be able to do the same.

**Comment by cnunciato** [comment]
@iwahbe That helps, thanks much. Would it make sense, do you think, to expose the functionality of `resolveObjectType()` externally to allow it to be used for docs generation? I'm having trouble seeing how to do this, for example, without duplicating much of what's in `codegen/go/gen.go` to get there.

**Comment by iwahbe** [comment]
> @iwahbe That helps, thanks much. Would it make sense, do you think, to expose the functionality of `resolveObjectType()` externally to allow it to be used for docs generation? I'm having trouble seeing how to do this, for example, without duplicating much of what's in `codegen/go/gen.go` to get there.

I think it would make sense to move `resolveObjectType` into the `codegen` package, since it should be shared by all codegen backends who need to look up import and naming overrides. 

CC @Zaid-Ajaj

**Comment by sean1588** [comment]
Based on our discussion about this during the docs sync, it sounds like we are in agreement to address this by taking a slightly different approach. @cnunciato had suggested further above that we could add a page at the package level that contains all the types with their definitions that are defined for that package. This page may also be helpful to our users in general. If we have this page, then we can just link to that package's types page where that type is rendered. We can infer what the link to that types page would be just by parsing through the type ref in the local schema rather than needing to depend on any external packages in the docsgen process to get a hold of this data. 

cc @iwahbe

**Comment by sean1588** [comment]
We have addressed this issue by indicating the type is defined externally and linking to that package in which it is defined in this [PR]( https://github.com/pulumi/pulumi/pull/15651).

I opened a follow up [issue](https://github.com/pulumi/registry/issues/4200) to render out the full type definition which is the more ideal solution and will be addressed once we move to building docs from metadata files emitted by sdkgen, since sdkgen has the ability to resolve the externally defined type definitions.
