### ISSUE TITLE
GCP AppEngine NodeJS documentation examples don't camel case automaticScaling and basicScaling

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#12782]
From https://github.com/pulumi/docs/pull/4051

**Comment by justinvp** [comment]
This has long since been fixed.

<img width="696" alt="Screen Shot 2023-07-26 at 11 38 57 PM" src="https://github.com/pulumi/pulumi/assets/710598/ce04ef5e-dcab-42ba-a332-419995a08bac">

<img width="690" alt="Screen Shot 2023-07-26 at 11 39 14 PM" src="https://github.com/pulumi/pulumi/assets/710598/f8050a65-609d-4bcf-ba74-3f9c90948a84">
