### ISSUE TITLE
Historical reasons ....

### ISSUE THREAD

**Issue by GustavoGama-DBACheck** [pulumi/pulumi#13067]
The architect's decision of Output(T) is a complete nightmare, breaking all the developer experience.

## General Feedback
The idea is excellent and has huge potential. It would be very appreciated if a better set of examples, better documentation (generated documentation lacks the human side), and reducing the confusion between versions.

**Comment by RobbieMcKinstry** [comment]
Hi @GustavoGama-DBACheck thanks for the feedback! Unfortunately, `Output(T)` is a cornerstone of Pulumi's architecture, so we won't be able to remove it from the SDKs.

`Output(T)` serves to suspend computation, allowing Pulumi to determine at `preview` time which resources will change without knowing the actual values until `up` time. I'm hard-pressed to find an alternative design.

That said, there's always room to improve documentation. I'm going to close this issue for now since it's not particularly actionable. If you have specific suggestions to improve documentation, I'd encourage you to open them at https://github.com/pulumi/pulumi-hugo or https://github.com/pulumi/docs.
