### ISSUE TITLE
Fail when LocalProviders don't exist

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#13061]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There's an option when running program tests to specify LocalProviders - a provider name and a path at which to find the provider. This appends to the `plugins/providers` in the `Pulumi.yaml` of the test program to set an explicit path for the specific named provider.

However, if there is no binary of the expected name at the specified path, Pulumi will fall back to resolving the plugin from the $PATH or by downloading the last release of the plugin.

It would be helpful to be able to disable this fallback behaviour for testing so that we're notified when the test is mis-configured rather than the test continuing to run but not validating the intended local version of the provider.

### Affected area/feature

- Program testing
- Plugin resolution

**Comment by Frassle** [comment]
I'm tempted to just change the behavior of the "plugins" section in Pulumi.yaml (which is what LocalProviders is editing).
If you've gone to the point of adding a specific path into the project to say "this provider lives here" I kinda feel it would be ok to just respect that, and if it's missing return an error rather than ignoring the users instructions and going and searching PATH and plugins.

**Comment by RobbieMcKinstry** [comment]
Yes. The last thing we want is to have a missing plugin load code from elsewhere on the computer.

**Comment by Frassle** [comment]
Checking the code for this it looks like this is how it should be working already. If a project plugin is set, we'll always use that path and not search $PATH. I'll see if I can get a test written up to confirm that.

**Comment by Frassle** [comment]
This seems to already work as requested.
