### ISSUE TITLE
plugin [/opt/homebrew/bin/pulumi-resource-pulumi-nodejs] wrote a non-numeric port to stdout ('0')

### ISSUE THREAD

**Issue by mattfysh** [pulumi/pulumi#13150]
### What happened?

I upgraded my to v3.70 on macOS (via homebrew) and started receiving the following error when attempted to run my deployment

> pulumi:providers:pulumi-nodejs default  error: pulumi-nodejs (resource) plugin [/opt/homebrew/bin/pulumi-resource-pulumi-nodejs] wrote a non-numeric port to stdout ('0'): strconv.Atoi: parsing "\x1b[33m64263\x1b[39m": invalid syntax

The port number is coming through but it's surrounded by ANSI color codes

Note: I am running with the Automation API in an inline typescript program, which is being run with `tsx`

### Expected Behavior

The dynamic resource should deploy without error

### Steps to reproduce

Create a dynamic resource in typescript/javascript, according to these instructions:
https://www.pulumi.com/docs/concepts/resources/dynamic-providers/

### Output of `pulumi about`

```
CLI          
Version      3.70.0
Go Version   go1.20.5
Go Compiler  gc

Host     
OS       darwin
Version  13.4
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by abhinav** [comment]
Thanks for the report, @mattfysh. I dug into this a bit more.

Apparently, Node's `console.log` colors numbers by default if it thinks that the output is a terminal (unless `NO_COLOR` is set).

![node-console-color](https://github.com/pulumi/pulumi/assets/41730/c884c737-39f3-4fc3-a9b4-1bb7a6bf6fe2)

This is weird because the component that that error is from specifically [starts the command with a pipe](https://github.com/pulumi/pulumi/blob/684b290577e4a456ffdde1300b82d6cf9990c7f0/sdk/go/common/resource/plugin/plugin.go#L367) that should not be detected as a terminal.

Would you mind sharing more about how you're running the command?

Meanwhile, as we try to fix it on our end, you should be able to work around the issue by setting `NO_COLOR=1` when running the command.

**Comment by mattfysh** [comment]
Thanks @abhinav - I am using `tsx` to execute my deployment script which is written in typescript, and uses the Automation API. For now I am just manually updating `cmd/dynamic-provider/index.js` with `console.log(String(port));` in my node_modules directory

I am using the latest version of node (v20.3.0) and I've spotted this version of node causing issues in other repos too, e.g. esbuild, so perhaps it is this version of node. If I get time I will try to downgrade and re-run the test
