### ISSUE TITLE
Support descriptions on stack outputs

### ISSUE THREAD

**Issue by johncclayton** [pulumi/pulumi#13617]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We document the intention of our stacks using Docusaurus. 

It's also a great place to put the documentation related to the stack configuration as well as the stack outputs.

I would like to autogenerate Markdown documentation for the stack outputs and stack configuration.  The documentation I'm after need to contain: 
 * field name
 * description / purpose
 * optional: data type - less important
 * desirable: an example of what you might set this to

Because this is a real programming language, I'd like to be able to have Pulumi throw an exception if I define a stack output that doesn't have a description.  This will enforce complete field documentation during development.

In C# it's possible to add 'description meta-data' by making use of the existing Output property attribute?

I don't believe the Pulumi system should generate Markdown.  I think that's the domain of the developer - and I'd want a way to be called back (or provide a function) such that I can consume a validation array of output fields - then I can choose how to turn this into markdown, or XML, or whatever it is I'm looking for. 

At the end of the day, my need to is produce a file that would look something like this:

The following configuration parameters are available for the `name-of-your-stack` stacks:

| Parameter                        | Description                                                                                       | Example                     |
|----------------------------------|---------------------------------------------------------------------------------------------------|-----------------------------|
| `azure-native:location`          | The location of resources in Azure.                                                               | `SwitzerlandNorth`          |
| `EnvironmentStackName`   | The name of the environment stack, where this cluster is to be created.                           | `your-org/environment/example` |
| `KubernetesVersion` | The version of Kubernetes to install.                                                             | `1.26`                      |
| `NodePoolSize`      | The type of nodes to have in the node pool.                                                       | `Standard_D2s_v3`           |
| `NodePoolCount`     | The number of nodes to have in the node pool.                                                     | `3`                         |
| `ApplicationNamespaces`  | An ARRAY of namespace names, the system sets up federated identity credentials for each namespace | `['default', 'my-namespace']`  |

### Affected area/feature

SDK's

**Comment by Zaid-Ajaj** [comment]
Hi there @johncclayton I think this is a nice idea to be able to documents config variables and outputs. Assuming you are using C# from the context of the issue, it is possible to _tag_ outputs and config variables, then generate some kind of documentation from them. In the following, I will show how it can be done for outputs. A similar approach can be taken for config variables.

Here is an example of a plain Pulumi C# program with AWS that I generated using `pulumi new aws-csharp`:
```csharp
return await Deployment.RunAsync(() =>
{
   // Create an AWS resource (S3 Bucket)
   var bucket = new Bucket("my-bucket");

   // Export the name of the bucket
   return new Dictionary<string, object?>
   {
      ["bucketName"] = bucket.Id
   };
});
```
In this example, we return the outputs immediately as values of a dictionary. However, we can wrap that operation inside a class which _requires_ that each exported output has a description.

<details>
<summary>Helper class implementation</summary>

```csharp
class TaggedOutput
{
   public string Name { get; set; }
   public object? Value { get; set; }
   public string Description { get; set; }
}

class StackOutputs
{
   private readonly List<TaggedOutput> _outputs = new();
   public void Export<T>(string name, T value, string description)
   {
      _outputs.Add(new TaggedOutput
      {
         Name = name,
         Value = value,
         Description = description
      });
   }

   public void BuildDocsJson(string outputFile)
   {
      var json = JsonSerializer.Serialize(_outputs);
      File.WriteAllText(outputFile, json);
   }

   public IDictionary<string, object?> ToDictionary()
   {
      return _outputs.ToDictionary(item => item.Name, item => item.Value);
   }
}
```
</details>

Using this `StackOutputs` class, you can write your C# Pulumi program as follows:
```csharp
return await Deployment.RunAsync(() =>
{
   // Create an AWS resource (S3 Bucket)
   var bucket = new Bucket("my-bucket");

   var outputs = new StackOutputs();
   outputs.Export(
      name: "bucketName",
      value: bucket.Id,
      description: "The name of the bucket"
   );

   outputs.BuildDocsJson("docs.json");
   return outputs.ToDictionary();
});
```
The function `Export` requires an argument `description` so it won't compile unless a description is provided. You can even further by specifying that it should non-null at compile time. Then `BuildDocsJson("docs.json")` takes those outputs and write them to a JSON file at `docs.json`. This could have been a function that generates markdown instead. Finally we return the dictionary that Pulumi expects. 

By simply _wrapping_ the way we export variables, we add metadata and post-processing step to the data. 

For config variables, you could implement a similar wrapper class which expects a description input for every config variable that is required.

Full [gist](https://gist.github.com/Zaid-Ajaj/3db1f0862ea61fb5d1313ba575ecac91) here

I am not sure this is something we add to the different SDKs since it is very specific to this use case and doesn't really work with the way users generally export the outputs but is it something to think about.

**Comment by johncclayton** [comment]
Great solution, thank you for the directional hint AND implementation :-)  I'm happy to close this issue entirely at this stage as the idea works perfectly.

**Comment by Zaid-Ajaj** [comment]
@johncclayton I am glad to hear the solution works for you 😄 I'll go ahead and close out the issue. Feel free to open a new one when needed 🙏
