### ISSUE TITLE
Run full test suite before merging PRs

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13741]
https://github.com/pulumi/pulumi/pull/13729 was the first real PR merged with GitHub merge queues. Once it was merged, a test in master is failed (see https://github.com/pulumi/pulumi/issues/13740).

The intention is these tests would be run _before_ merging (that's how it worked with bors), preventing the merge when a test fails. But now the tests appear to be running _after_ merging.

We need to fix CI to make sure the full tests are run _before_ merging.

**Comment by blampe** [comment]
Tests did run as part of the queue, and they failed as expected https://github.com/pulumi/pulumi/actions/runs/5874822298

I'm not sure why it was still allowed to merge, or why the details show the [PR's tests](https://github.com/pulumi/pulumi/actions/runs/5874428520) instead of the queue's.

My best guess is it's trying to do some optimization where if the queue only has 1 item, and its PR is rebased on master, then don't bother running the queue's tests? But that doesn't seem right because the queue's tests _did_ run. 

![image](https://github.com/pulumi/pulumi/assets/848843/7270caaa-3f3c-4fff-b3fa-ceb96478afbb)
