### ISSUE TITLE
Premium Policies PULUMI_ACCESS_TOKEN 

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi#13881]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When calling `pulumi policy new`, you need to have `PULUMI_ACCESS_TOKEN` as an env var to be set correctly in order to install the policies marked premium. It's documented in the `[README.md](https://github.com/pulumi/templates-policy/tree/master/aws-premium-policies-typescript)` here:

> Pulumi Premium Policies require minimum configuration. Before creating an empty Policy Pack, simply make sure you've set the PULUMI_ACCESS_TOKEN environment variable with a Pulumi access token linked to your Pulumi organization.

>  The PULUMI_ACCESS_TOKEN is expected to be present in your local development environment, CI/CD and anywhere you deploy your Pulumi applications.

### Affected area/feature

We'd love to be able to infer this instead of needing the user to set it.

**Comment by lukehoban** [comment]
The issue here is because some of the policy templates use a private NPM registry whose access is gated on a `PULUMI_ACCESS_TOKEN` (and the permissions it has).  This is configured via e.g. https://github.com/pulumi/templates-policy/blob/master/aws-premium-policies-typescript/.npmrc#L2.

A feature we could add to the CLI to enable this to pass the `PULUMI_ACCESS_TOKEN` inferred from the current user context (via the same approaches used for the access token passed to the app.pulumi.com backend), as an environment variable into the spawned `npm install` commands invoked by `pulumi policy new`.  This would allow the private registry to authenticate automatically without the user taking any additional action.

**Comment by justinvp** [comment]
Note that there are two places where this is needed:
1. When `pulumi policy new` is called
2. During a pulumi operation like `pulumi up` when the policy pack is downloaded from Pulumi Cloud and [its dependencies are installed](https://github.com/pulumi/pulumi/blob/d02306824582111bfc8b634fdc22a359b8e35007/pkg/backend/httpstate/policypack.go#L309-L316)
