### ISSUE TITLE
Double colons (::) used to be accepted as valid URN name but is now causing "invalid URN" errors

### ISSUE THREAD

**Issue by vazexqi** [pulumi/pulumi#13968]
### What happened?

I was using an older version of @pulumi/pulumi (3.58.0). 

I upgraded to @pulumi/pulumi (3.82.1) and my application that uses pulumi/automation broke. I see errors about invalid URN. 

```
[cloudflare:index/accessPolicy:AccessPolicy]: 3 INVALID_ARGUMENT: invalid dependency URN: invalid URN "urn:pulumi:zuplo-prod::access-tokens::cloudflare:index/accessApplication:AccessApplication::carp::zuplo-prod::websocket-as-a-customer::working-copy"
```

New to the source code but I traced down the issue and I _believe_ that https://github.com/pulumi/pulumi/pull/13531 might have introduced too strict a check. That means that the issue probably started before 3.82.1 (likely in [3.76.0](https://github.com/pulumi/pulumi/releases/tag/v3.76.0))

```
// IsValid returns true if the URN is well-formed.
func (urn URN) IsValid() bool {
	if !strings.HasPrefix(string(urn), URNPrefix) {
		return false
	}
	return len(strings.Split(string(urn), URNNameDelimiter)) == 4
}
```

`URNNameDelimiter` is `::`

I am pretty sure the `return len(strings.Split(string(urn), URNNameDelimiter)) == 4` is overly strict and is preventing me from using `::` which I was able to do before. Perhaps this can be changed. A simple `len(strings.Split(string(urn), URNNameDelimiter)) >= 4` might be acceptable if there is no desire for more advanced parsing.

I read https://www.pulumi.com/docs/concepts/resources/names/#urns and it doesn't say that `::` are invalid characters for URNs and it was also accepted before.

**I think this is a real bug since it breaks existing states that might have used `::` before in the names.**

### Example

I think it's easier to use the test cases in https://github.com/pulumi/pulumi/pull/13531/files and create a resource with `::` in them.

### Output of `pulumi about`

This is not dependent on the CLI as far as I can tell. But here it is for completeness

```
CLI
Version      3.82.1
Go Version   go1.21.0
Go Compiler  gc

Host
OS       alpine
Version  3.16.5
Arch     x86_64
```

### Additional context

If this is a working-as-designed, could you suggest a workaround for how I can safely migrate my 100s of resources in the pulumi state that already use the `::` convention?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by vazexqi** [comment]
Possibly related to https://github.com/pulumi/pulumi-cloudflare/issues/489

**Comment by mikhailshilkov** [comment]
> Possibly related to https://github.com/pulumi/pulumi-cloudflare/issues/489

See https://github.com/pulumi/pulumi-cloudflare/issues/489#issuecomment-1725283826

**Comment by vazexqi** [comment]
@justinvp - Any updates on this? It's still blocking us from upgrading.

**Comment by mark-bixler** [comment]
We're experiencing odd behavior where this issue is present during a pipeline run in a container, but does NOT happen when running locally on my machine.

**Comment by Frassle** [comment]
> I read https://www.pulumi.com/docs/concepts/resources/names/#urns and it doesn't say that :: are invalid characters for URNs and it was also accepted before.
>
> I think this is a real bug since it breaks existing states that might have used :: before in the names.

So this was never really intended to work, resource names were expected to match `[A-Za-z0-9_-]+` but it turned out the engine never validated that. Lots of other strings happened to work, but not always, double colons in a provider name for example will [panic the engine](https://github.com/pulumi/pulumi/issues/8949) today.

We had gone through all the data we had in the service a while ago to try and find the sorts of strings users were using (although I didn't see "::" in that). We'd loosened some of the validators to match that already.

I'm going to see about fixing this in three parts.
1. I'll loosen the validations further to allow "::"
2. I'll add more validation checks in the engine to check Names not just URNs
3. I'll fix up the tests to ensure all the strange names we see work for all sorts of resources and as option parameters.

**Comment by justinvp** [comment]
@vazexqi, @mark-bixler, I expect we'll have a fix very soon, but here are a couple of workarounds in the meantime, if you can't wait:

1. Continue using a version of the CLI that works, until the fix is available.

2. Rename your resources to not have the double colons. If you'd like help with this, let me know. I can see two possible approaches:

    1. Write a short script that uses the output of `pulumi stack export` along with `jq` to get a list of URNs for the resources, and then pipe that through to `pulumi state rename` to rename the resources with double colons. After running this operation, you'd also have to update your Pulumi program to the make the resource names match the renamed names in the state.

    2. Use the `aliases` option to rename the resources in your program, specifying the old name with the double colons for the alias: https://www.pulumi.com/docs/concepts/options/aliases/#resource-option-aliases. You'd have to use an older CLI to do the deployment.

If you'd like help with (2) let me know.
