### ISSUE TITLE
JSON diffs don't pretty print for nested properties

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#13981]
### What happened?

We made some changes in #5831 whereby we pretty print JSON diffs for things like IAM roles to help with debugging.

However, this doesn't appear to work for nested properties, specifically for an AWS ECS Task Definition with a nested container definition, see the attached screenshot

### Example

**
![CleanShot 2023-09-18 at 11 26 36](https://github.com/pulumi/pulumi/assets/1622940/7bb6344c-334b-4042-95c1-85464e405c0b)
**

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by gunzy83** [comment]
This is still happening for IAM Policy objects on update as well:

![image](https://github.com/pulumi/pulumi/assets/2989525/b7bb6f36-8990-4084-8061-dfa8077ef61e)

This diff was far worse before I ran the generated policy document through `JSON.stringify(JSON.parse(policyDoc), null, 0)` to minify it.

Create operations seem to identify the input as JSON:
![image](https://github.com/pulumi/pulumi/assets/2989525/a992afc4-f67b-42f2-8492-c61aea99fe72)

I think this might have something to do with how the JSON is stored in state which prevents the JSON diff from happening, we get a plaintext diff instead.

Both of the diffs above are running through the same codepaths in the same project/stack.

Pulumi version: `3.60.1`
@pulumi/aws: `5.31.0`

**Comment by gunzy83** [comment]
I believe this change https://github.com/pulumi/pulumi/pull/11803 introduced a bug where the json diff is never reached because the string comparison will before it will cause it to always print the string diff. Someone who is less green with go can correct me if I am wrong.

**Comment by Frassle** [comment]
I don't think that's a bug, looks like #11803 is doing what it was intended to do. There is no semantic JSON diff between the text strings so it shows the text diff instead.
It looks like that's the same for Lee's example in the initial message here as well.

This behaviour was suggested by @lukehoban at https://github.com/pulumi/pulumi/issues/11799#issuecomment-1374176261 because the original behaviour was confusing but clearly this current style is also confusing just in a different way.

Maybe something as simple as prefixing it with "(json equivalent, showing text diff)" would help?

**Comment by gunzy83** [comment]
I have added more to my comment above, maybe I am misunderstanding where the json diff is being done, to me it looks like the text diff is being done before the json diff. See my screenshot below for what I mean:

![image](https://github.com/pulumi/pulumi/assets/2989525/056ecac0-0003-401c-b967-c553cffc091d)

The json is clearly not equivalent, I added an extra character only :)

**Comment by gunzy83** [comment]
> Maybe something as simple as prefixing it with "(json equivalent, showing text diff)" would help?

I think that would help in the case it is just a diff in the input vs stored text in state but I think we are talking about different things here?

**Comment by Frassle** [comment]
> The json is clearly not equivalent, I added an extra character only :)

Yeh ok that's clearly bugged then. I think your assessment that #11803 broke it is correct.

**Comment by D3-LucaPiombino** [comment]
This is kinda problematic.
We have  a lot of string json resources and diff are very difficult to parse at the moment.

Is there any plan to pick this up/revisit?

Sorry, i did an attempt to see if i could contribute (instead of simply complaining :)) by playing around a little bit with the codebase.
Unfortunately i did not have much success as i am not very familiar with the go ecosystem/stack.
