### ISSUE TITLE
Restore spans from plugin RPCs, pluging startup delay in trace file. 

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi#13986]
While investigating https://github.com/pulumi/pulumi-aws/issues/2799 with the `--tracing` flag, I noticed that we are not capturing server side spans from RPCs to the plugin or any spans for the plugin startup time. @t0yv0 indicated that both of those were captured by tracing at some point in the past so this appears to be a regression in our tracing capabilities.

**Comment by t0yv0** [comment]
This very well may depend on provider; bridged providers might behave differently from native ones. I think this is likely something we can fixup/solve on the providers side.

**Comment by justinvp** [comment]
@Frassle, can you confirm if this is a regression on our side or if this is something that can be fixed up on the providers side?

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/1412 gRPC server spans are 100% not supported for bridged providers (such as AWS). Filed this one in the bridge to fix that. 

Looking around at aws-native I don't think this is supported either. https://github.com/pulumi/pulumi-aws-native/issues/1116

https://github.com/pulumi/ci-mgmt/issues/642 to track this across all providers.

**Comment by t0yv0** [comment]
Spans for **plugin startup time** are a bit harder. First of all it's harder to correlate the trace from the parent Context to the plugin Context since it's not really mapping to a gRPC call directly. Also it's tough to decide if this should go in the plugin itself or pulumi engine (or both? that'd be a bit redundant). 

If traced in the plugin itself there's more opportunities to show fine-grained detail on what the plugin is doing at startup.

If traced in Pulumi CLI it's a bit unclear where the start and stop of the span should be.

Perhaps this is a good candidate
https://github.com/pulumi/pulumi/blob/9f85e7a3dedbab67f8bc7f9f3ffa8d68cd29f65f/sdk/go/common/resource/plugin/plugin.go#L300-#L300 or https://github.com/pulumi/pulumi/blob/9f85e7a3dedbab67f8bc7f9f3ffa8d68cd29f65f/sdk/go/common/resource/plugin/plugin.go#L172-#L172

When should the span stop? Perhaps we can stop it after the resource plugin has written out its gRPC port. That's probably easiest.

We could also maybe consider first gRPC interaction with it, but that's harder to correlate lexically.

**Comment by t0yv0** [comment]
A while back that I worked on startup perf none of this was reliably in place, so I don't think we're regressing here, just a lot of nice-to-have that did not quite make it.

**Comment by mjeffryes** [comment]
>Also it's tough to decide if this should go in the plugin itself or pulumi engine (or both? that'd be a bit redundant).
I'd assumed that we'd measure in the engine; as you say, it's hard to get timings from the plugin for this and honestly, the time that the engine is waiting is what I would be looking for from this span anyway.

> When should the span stop? Perhaps we can stop it after the resource plugin has written out its gRPC port. That's probably easiest.
I think it's also the easiest to reason about as well.
