### ISSUE TITLE
Suggest adding a hyphen between username and autogenerated code

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1419]
Beta user feedback:

> Would be nice to have a hyphen between my app name and the 8-digit generated resource id

Since this is a major breaking change, this can be done when there are other big changes, but I wanted to make sure the feedback is recorded.

**Comment by joeduffy** [comment]
We used to have this, but it got broken at some point. I believe we can do this in a non-breaking way, since the name only gets generated the first time a resource is provisioned.

**Comment by joeduffy** [comment]
@jen20 mind taking a look at this one? I think we did this due to name length constraints in, for example, AWS resources, but I'd personally err on the side of better names. So, I give this a :+1: but it's worth a deeper discussion, perhaps alongside the various knobs we've talked about giving people over the auto-name generation.

**Comment by lukehoban** [comment]
Haven't heard this feedback much over last 2 years - and it's an even more disruptive change at this point.  Closing until/unless we hear more feedback.
