### ISSUE TITLE
Plugin progress is scrambled when there are multiple

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#14250]
If multiple plugins are being downloaded at once, the progress display in the CLI occupies the same line, yielding what appears to be "jumping progress." As they complete, the lines get jumbled up, presumably just based on happenstance and when specific downloads complete relative to one another. Ideally each plugin progress display would occupy a single line and stack cleanly.

Screenshot of the final state:

![image](https://github.com/pulumi/pulumi/assets/3953235/336a7081-9f2b-495a-b851-a1a958c92d89)

**Comment by tgummerer** [comment]
We were wondering internally if there was a relatively simple fix we could do for this, similar to https://github.com/pulumi/pulumi/pull/15186.

Unfortunately there's a little bit more to it, although https://github.com/pulumi/pulumi/pull/15201 maybe helps a little bit, though not with the overlapping progress bars.  There's a couple of problems and potential solutions here:
1) The library we're using for progress bars defaults to using a single progress bar.  If we create multiple of them at a time, as we do for plugin installs, they overlap eachother.  The library does support a mode for multiple progress bars, but it's considered experimental and unstable, so I don't think we want to rely on that: https://github.com/cheggaaa/pb/blob/master/README_V1.md#multiple-progress-bars-experimental-and-unstable.
2) We're writing more output to the terminal while still displaying other progress bars, which makes the output interfere with that display.  We should probably just avoid doing that.
3) I gave another progress bar library (https://github.com/vbauerster/mpb) a quick try, however it seems to not be working since we're setting the terminal to raw mode for our own purposes.  So we'd need to either find a library that has multi progress bar support, or reset the terminal to regular mode, and put it back into raw mode when the plugin install is done.

**Comment by joeduffy** [comment]
I just upgraded to v3.110.0, and now see excessive newlines throughout a single plugin's installation; e.g.

![image](https://github.com/pulumi/pulumi/assets/3953235/894c7ade-967f-4bdb-b444-4abaaec1fc43)

The plugin installation line just keeps hopping down a single newline every second or so until the download finishes. I think this might come from https://github.com/pulumi/pulumi/pull/15201?

Some about info:

```
CLI
Version      3.110.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.25.1
awsx    2.5.0
docker  4.5.1
docker  3.6.1
nodejs  unknown

Host
OS       darwin
Version  12.7.1
Arch     x86_64
```

**Comment by Frassle** [comment]
Yeh was raised in https://github.com/pulumi/pulumi/issues/15668. https://github.com/pulumi/pulumi/pull/15201 changed this area but it merged many releases ago, this bug seems to be something recent.

**Comment by joeduffy** [comment]
IMHO, what we want is for the downloads to neatly stack and draw in parallel with one another:

```
// normal console output
[downloading resource plugin-random-4.12.0]: 27.91 MiB / 34.66 MiB [=================>-----] 71.59% 1m41s
[downloading resource plugin-awsx-1.11.3]:   20.00MiB / 27.94MiB.  [===============>-------] 80.54% 0m31s
// after completing, we carry onwards...
```

I suspect that’s “hard” although whatever tricks @pgavlin's various terminal drawing improvements use could probably be used here too.

**Comment by julienp** [comment]
One dumb workaround would be to only download one plugin at a time.

A slightly better workaround would be to downloads still happen concurrently, but only show one progress bar at a time. See the video in https://github.com/pulumi/pulumi/pull/16937

**Comment by joeduffy** [comment]
My $0.02: I'd prefer not to download one plugin at a time, because that would have a user-visible performance impact. Showing one bar at a time could be a reasonable compromise. If we showed the soonest-to-finish at all times, then you're naturally see what is being downloaded, and finished, with the longest also being evident because it would be the last progress bar to display.

**Comment by justinvp** [comment]
We should consider making https://github.com/pulumi/pulumi/pull/16094 work correctly with great UX. I tried that change out as-is and it didn't appear to be working correctly. Also, from the description, it says it shows progress the bottom third of the screen. I'm curious what that would look like, or if it'd be better to keep at the top.
