### ISSUE TITLE
[codegen] kube2pulumi hangs on pcl.BindProgram

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi#14317]
### What happened?

While doing a routine upgrade of pu/pu to v3.90.0 for kube2pulumi, the existing unit tests for this repository hangs and does not complete within 10 minutes. Prior to this, the test suite usually finishes within 2.5 minutes.

I was able to trace the issue with the hanging program to this line within kube2pulumi (where we use `pcl.BindProgram`): https://github.com/pulumi/kube2pulumi/blob/master/pkg/pcl2pulumi/pcl2pulumi.go#L108

Debugging further down the call stack, it looks like it occurs when the destType is a `NoneType`, and the program is hangs at: https://github.com/pulumi/pulumi/blob/e59f8b03b1ff71c625a1e89fae5b46ef6e941125/pkg/codegen/hcl2/model/diagnostics.go#L48

In particular, it's when we attempt to pretty print `destType`. If I switch that method over from `.Pretty()` to `.String()`, then kube2pulumi is able to proceed, however, the program still fails to convert our source code, where prior to the upgrade, conversion is successful.

### Example

Example failing tests for kube2pulumi:
https://github.com/pulumi/kube2pulumi/pull/104

Note, I've noticed this happening since v3.88.1

### Output of `pulumi about`

Upgrade pu/pu to >= v3.88.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@Zaid-Ajaj I dug deeper, and it turns out that this only occurs when the initial resource config does not contain all the required fields. For example, with the following PCL where some required Kubernetes fields are commented out:

```
resource "argocd_serverDeployment" "kubernetes:apps/v1:Deployment" {
apiVersion = "apps/v1"
kind = "Deployment"
metadata = {
labels = {
"app.kubernetes.io/component" = "server"
"app.kubernetes.io/instance" = "argocd"
"app.kubernetes.io/managed-by" = "pulumi"
"app.kubernetes.io/name" = "argocd-server"
"app.kubernetes.io/part-of" = "argocd"
"app.kubernetes.io/version" = "v1.6.1"
"helm.sh/chart" = "argo-cd-2.5.4"
}
name = "argocd-server"
}
spec = {
# selector = {
# matchLabels = {
# "app.kubernetes.io/component" = "server"
# "app.kubernetes.io/instance" = "argocd"
# "app.kubernetes.io/name" = "argocd-server"
# }
# }
template = {
spec = {
containers = [
{
# name = "argocd-server"
# image = "argoproj/argocd:v1.6.1"
readinessProbe = {
httpGet = {
port = 8080
}
}
}
]
}
}
}
}
```

Codegen used to be able to convert these to a Pulumi program, which obviously would not run on `pulumi up` since they are missing required fields, but would at least get users further along.

It would be nice to have this supported again. Or at the very least, not have pcl.BindProgram freeze and consume CPU.

**Comment by Zaid-Ajaj** [comment]
Hi there @rquitales thanks a lot for investigating this. I am able to reproduce it locally. It is indeed the pretty printing the destination type that is causing the hang. This happens when there is a bind error and the binder tries to give a nice error message with pretty printed types but this is certainly not ideal. My tests locally shows that there isn't an infinite loop going on and the program actually returns after ~10 minutes so the implementation is horribly slow. 

I was able to reproduce the issue by using the PCL program above and trying to convert to itself. Putting the content in a file `main.pp` in a directory then running:
```
pulumi convert --from pcl --language pcl --out pcl --strict
```
Notice here the `--strict` flag that is required for the repro. Without `--strict` the program binder doesn't return any errors and actually converts. That is because without `--strict` we add a couple of bind options: `pcl.NonStrictBindOptions()` to be exact which make the conversion more lenient for example when missing required fields. 

You can add `pcl.NonStrictBindOptions()` when [binding the program](https://github.com/pulumi/kube2pulumi/blob/master/pkg/pcl2pulumi/pcl2pulumi.go#L108) in kube2pulumi without having to revert to an old version of Pulumi until we get this sorted out
