### ISSUE TITLE
After Upgrading to Pulumi 3.88.0, aliasURNs are not longer populated for Mocks

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#14340]
### What happened?

We upgraded from 3.87.0 to 3.88.0 and one of our mock tests that check for aliases stopped working. We use the following code to populate mocks. 

```python
class MockResourceDetails:
    urn: str
    aliases: List[str]
    parent: str
    name: str
    protect: bool
    type: str
    importId: str
    dependencies: List[str]

    def __init__(self, request: Any, response: Any) -> None:
        # Coerce to strings. We don't want the protocol buffer types.
        # They cannot easily be serialized to json/yaml.
        self.urn = f"{response.urn}"
        self.aliases = list(map(lambda x: f"{x}", request.aliasURNs))
        self.dependencies = list(map(lambda x: f"{x}", request.dependencies))
        self.name = f"{request.name}"
        self.parent = f"{request.parent}"
        self.type = f"{request.type}"

    def as_dict(self) -> dict:
        return {
            "type": self.type,
            "name": self.name,
            "urn": self.urn,
            "parent": self.parent,
            "dependencies": self.dependencies,
            "aliases": self.aliases,
        }
```
I suspect this is because of #14118

### Example

Working on example.

### Output of `pulumi about`

Pulumi cli - 3.86.0
pulumi-command==0.8.2
pulumi==3.88.0
pulumi_aws==6.6.0
pulumi_cloudinit==1.3.0
pulumi_datadog==4.17.1
pulumi_kubernetes==3.30.2
pulumi_random==4.13.0
pulumi_tls==4.10.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This was a deliberate change to the internal `MockMonitor` class. We changed it in  https://github.com/pulumi/pulumi/pull/14118 to say it supports all features (other than `"outputValues"`). This means the mock monitor now says it supports the `"aliasSpecs"` feature, which tells SDKs to stop computing aliases (sent via `request.aliasURNs`) and instead to send just the [alias "specs"](https://github.com/pulumi/pulumi/blob/6e94043cfb37ff54832c09b0d69d76ddf1c75f94/proto/pulumi/alias.proto#L21-L38) (sent via `request.aliases`). When alias specs are sent, the engine will compute the alias URNs and combination of aliases for parents, etc. This aligns with the behavior of real usage, as SDKs are no longer computing aliases when running with current releases of the CLI.

[`MockMonitor`](https://github.com/pulumi/pulumi/blob/6e94043cfb37ff54832c09b0d69d76ddf1c75f94/sdk/python/lib/pulumi/runtime/mocks.py#L138) isn't intended to be used directly by users&mdash;it's an internal implementation detail of the mocking capability that isn't "exported" from the `runtime` subpackage. It probably should have been named `_MockMonitor` to make this more clear. But certainly understand why it's being used to get at some of this extra data to validate in tests.

I've opened https://github.com/pulumi/pulumi/issues/14421 to track adding an officially supported way to expose such additional data needed for unit tests, which won't be affected by changes to internals like this.

In the meantime, since you're already subclassing `MockMonitor`, you can easily go back to the previous behavior by overriding the `SupportsFeature` method and returning `"hasSupport": False` when `request.id == "aliasSpecs"`, e.g. something like:

```python
class MyMockMonitor(MockMonitor):
    def SupportsFeature(self, request):
        # Disable aliasSpecs so we continue to get aliases populated in request.aliasURNs
        # in RegisterResource.
        if request.id == "aliasSpecs":
            return type("SupportsFeatureResponse", (object,), {"hasSupport": False})

        return super().SupportsFeature(request)
```

This will make the SDK go back to computing aliases and sending them as `request.aliasURNs` in `RegisterResource`.

**Comment by rshade** [comment]
Thank you @justinvp, closing this now.
