### ISSUE TITLE
Existing go generics double memory consumption during SDK compilation

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#14344]
### What happened?

When go generics was initially rolled out, we needed to upgrade a bunch of our runners because the `build_sdk` failed with OOM.

Profiling the aws s3 package yielded the following result:

| pulumix | Max Memory |
|---|---|
| Current | 965.75MB |
| Removed | 475.26MB |

This shows that the existing `pulumix` code doubled the memory usage during compilation.

### Example

NA

### Output of `pulumi about`

NA

### Additional context

Profile code is https://github.com/pulumi/pulumi-aws/blob/iwahbe/profile-pulumix/profile.org.

This exacerbates https://github.com/pulumi/pulumi-gcp/issues/1283.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for the profile code, that makes it really easy to reproduce.  

I had a look at a couple of different options to try and reduce the memory usage.  Doing a relatively simple method to function conversion for a couple of the current methods yields some improvements (thanks @justinvp for the suggestion), getting us to 787.79MB.

<details>
<summary> diff </summary>

```
 ❯ g diff       
diff --git a/sdk/go/pulumix/array.go b/sdk/go/pulumix/array.go
index 47f2e1817e..5219237b6d 100644
--- a/sdk/go/pulumix/array.go
+++ b/sdk/go/pulumix/array.go
@@ -41,7 +41,7 @@ func (a Array[T]) ToOutput(ctx context.Context) Output[[]T] {
 
 // AsAny turns the array into an Output[any].
 func (a Array[T]) AsAny() Output[any] {
-       return a.ToOutput(context.Background()).AsAny()
+       return AsAny(a.ToOutput(context.Background()))
 }
 
 // GArrayOutput is an Output value holding a slice of type T.
diff --git a/sdk/go/pulumix/map.go b/sdk/go/pulumix/map.go
index e4c509e374..ef1f4fa2af 100644
--- a/sdk/go/pulumix/map.go
+++ b/sdk/go/pulumix/map.go
@@ -41,7 +41,7 @@ func (m Map[T]) ToOutput(ctx context.Context) Output[map[string]T] {
 
 // AsAny turns the map into an Output[any].
 func (m Map[T]) AsAny() Output[any] {
-       return m.ToOutput(context.Background()).AsAny()
+       return AsAny(m.ToOutput(context.Background()))
 }
 
 // GMapOutput is an Output value holding a map[string]T.
diff --git a/sdk/go/pulumix/types.go b/sdk/go/pulumix/types.go
index 0cea2863fa..fca3d0ae5f 100644
--- a/sdk/go/pulumix/types.go
+++ b/sdk/go/pulumix/types.go
@@ -125,12 +125,12 @@ func InputElementType(t reflect.Type) (e reflect.Type, ok bool) {
 //
 //     var o pulumix.Output[string] = // ...
 //     legacyAPI(o.Untyped().(pulumi.StringOutput))
-func (o Output[T]) Untyped() internal.Output {
+func Untyped[T any](o Output[T]) internal.Output {
        return internal.ToOutput(o)
 }
 
 // AsAny casts this Output[T] to an Output[any].
-func (o Output[T]) AsAny() Output[any] {
+func AsAny[T any](o Output[T]) Output[any] {
        return Apply[T](o, func(v T) any { return v })
 }
 
```

</details>

I also had a look whether a newer version of go could improve anything here.  And indeed it does.  With the latest version of go compiled from the main branch we get to 727.12MB with the improvements above, so another ~50MB reduction.  

Though all that doesn't get us close to where we started, without the generics.  I'll keep looking to see if there's any other places we can save some memory.

**Comment by tgummerer** [comment]
I got curious and tried to have a look at what the situation was like before we first started using `pulumix` in `pulumi-aws` in the first place, and it makes the memory situation look even worse.  The result I get then is ~315.49MB, so we actually end up tripling the memory usage.

**Comment by tgummerer** [comment]
I'm getting towards the end of my timeboxed investigation here, and unfortunately I didn't find any other easy knobs to tune here.   A couple things I tried:
- set `GOMEMLIMIT` env variable to 400MiB.  This had pretty much no effect
- See if we can limit the types for `Output` instead of using `any`, but that ends up being pretty much impossible.
- use `massif` (and `heapstack`) to try and profile the memory, which unfortunately also didn't give me any useful information. (This takes a long time to run, so I'll give it another try now)

In general, reading about Go generics, and seeing how many different types of `Output`s we have though, it seems pretty hard to avoid an increased memory consumption from the compiler here as long as we want to support generics.

**Comment by iwahbe** [comment]
Reading about how Go generics is implemented,[^1] it seems like it might be worth experimenting to get our types to have the same GC "shape". For our purposes, that would mean replacing `pulumix.Output[SomeType]` with `pulumix.Output[*SomeType]`. This would IMO mean a degradation in API quality, but not a terrible one. It would be worth it to make the API viable vis a vis memory usage.

[^1]: https://planetscale.com/blog/generics-can-make-your-go-code-slower

**Comment by tgummerer** [comment]
It's maybe worth trying that, if we really can't afford the additional memory used by the compiler.  I guess there would be two main risks to that:
- I'm not sure it's guaranteed that all pointers will always have the same GCShape, so future versions of the Go compiler might just end up using more memory and it's going to be harder to do something about it.
- Passing pointers around everywhere instead of values seems like quite a big change from the api perspective.

At this point I'm tempted to say we should just revert https://github.com/pulumi/pulumi/pull/13510 for the time being, and have a discussion about how we want to move forward here.

**Comment by iwahbe** [comment]
Ok. Go doesn't make any guarantees about it's memory usage during compilation AFAIK.

**Comment by justinvp** [comment]
Thanks for the investigation, @tgummerer and the GC "shape" idea @iwahbe (definitely something to explore further).

Let's go ahead and revert. I've asked @Zaid-Ajaj to do that.

@Zaid-Ajaj, what do you think about making it so the changes in https://github.com/pulumi/pulumi/pull/13510 are only emitted when https://github.com/pulumi/pulumi/blob/8c3b65b19a393304f85641a22c55c2635fcf275f/pkg/codegen/go/importer.go#L100 is set to a value other than `"none"`? Or do you think we should not emit these methods at all in the non-generic variant of the SDK for the time being, and only emit them in the generic variant (i.e. the `"side-by-side"` or `"only-generics"` variant)>
