### ISSUE TITLE
Inconsistence CLI output for unsecreted secrets (C#)

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#14438]
### What happened?

With the code provided below, when I output an unsecreted secret, both `pulumi up` and `pulumi pre` don't show the revealed secret. However, running `pulumi stack output` shows the clear text value. The Pulumi Service is consistent.

![image](https://github.com/pulumi/pulumi/assets/1161681/dc937072-dbc3-48d4-95ae-767ce8cdf679)

![image](https://github.com/pulumi/pulumi/assets/1161681/056ce904-65b4-4ccd-a604-197c362e2594)

### Example

Run:
```
pulumi config set apiKey --secret
```

Use the C# code:
```cs
using System.Collections.Generic;
using Pulumi;

return await Pulumi.Deployment.RunAsync(() =>
{
    var config = new Pulumi.Config();

    // TODO: 9. Create stack outputs (See README.md)
    return new Dictionary<string, object?>
    {
        ["apiKey"] = config.RequireSecret("apiKey"),
        ["insecureApiKey"] = Output.Unsecret(config.RequireSecret("apiKey")),
    };
});
```

### Output of `pulumi about`

```
CLI          
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.14.0
dotnet        unknown
random        4.14.0

Host     
OS       debian
Version  12.2
Arch     x86_64

This project is written in dotnet: executable='/usr/bin/dotnet' version='6.0.416'

Current Stack: menfin/pulumi-az-cs-training-session-2/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::pulumi-az-cs-training-session-2::pulumi:pulumi:Stack::pulumi-az-cs-training-session-2-dev


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi
Token type     personal

Dependencies:
NAME                VERSION
Pulumi              3.58.0
Pulumi.AzureNative  2.14.0
Pulumi.Random       4.14.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
For the CLI this intended. The CLI keeps track of all secret values it's been told about and if it sees the same substring in a plain text value it will also hide it. It does this for output and log files.

**Comment by aureq** [comment]
First, it's not related to .NET but the experience is not consistent.

Give the example below, `clearpassword` is shown as plain text value, not `"[secret]"`. The original value comes from an actual Pulumi resource. But `clearapiKey` which comes from an encrypted configu secrets behaves differently.

I'm pretty sure a change has been introduce because `unsecret`-ing a config is part of a training I gave a few times and it's there to demonstrate secret manipulation. The config secret used to be shown in plain text as an output.

![image](https://github.com/pulumi/pulumi/assets/1161681/794b8ab5-05d5-4f49-9114-8c659e1aa68b)

```ts
import * as pulumi from "@pulumi/pulumi";
import * as password from "@pulumi/random";

const config = new pulumi.Config();

export = async () => {

    const apiKey = config.requireSecret("apiKey");
    const pass = new password.RandomPassword("p", {
        length: 20
    });

    return {
        apiKey: apiKey,
        clearapiKey: pulumi.unsecret(apiKey),
        password: apiKey,
        clearpassword: pulumi.unsecret(pass.result),
    }
};
```

**Comment by justinvp** [comment]
As Fraser mentions, this is intended behavior in the CLI. When running `pulumi preview` or `pulumi up`, it sets a filter on text written to logs and stdout/stderr which automatically masks config values that are secrets:

https://github.com/pulumi/pulumi/blob/0e3c5a1d3309d4a12e4c107cecfdd9a28a2bb7de/pkg/cmd/pulumi/config.go#L1151-L1157

In this case:

- `apiKey` is a secret, so it is shown as `[secret]`
- `clearapiKey` itself is not a secret, but it has the same value as `apiKey`, which is a secret, so it is masked by the output filter, hence why it shows the quotes, but the value itself is masked
- `password` (which I think you intended to be `pass.result`) is a secret, so it is shown as `[secret]`
- `clearpassword` is not a secret, so it's shown as clear text

When running `pulumi stack output`, there's no output filtering because it isn't looking at config or running a program and this command isn't as concerned about config secrets leaking to output/logs. Since `clearapiKey` isn't a secret, its value is shown as-is.

> I'm pretty sure a change has been introduce because `unsecret`-ing a config is part of a training I gave a few times and it's there to demonstrate secret manipulation. The config secret used to be shown in plain text as an output.

I checked as far back as v3.40.0 from September of 2022 and the behavior is the same as the current release.

**Comment by aureq** [comment]
Thanks @justinvp 

Sorry, I'm still confused. I don't understand then why `clearapiKey` and `clearpassword` behave differently then. Both values originate from their respective secret and yet, `pulumi up` shows a different result for each.

**Comment by justinvp** [comment]
- `clearapiKey` originates from a _config_ secret. We only setup the output filtering for secrets we know up-front from config.
- `clearpassword` originates from running the program. Such secrets aren't applied to the filtering.

The output filtering happens up-front in the CLI. It doesn't dynamically change as the program runs & new secrets are created.

**Comment by aureq** [comment]
Thank you. Marking a closed.
