### ISSUE TITLE
Deleting resource in Azure AD leaves resource in state but flagged for deletion

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#14740]
### What happened?

Customer has around 3k resources that should have been deleted and are marked as deleted in the state but it's adding extra ones in. They're also marked as "retain on delete" so presumably that was added because there were issues when deleting.

The resource is Azure AD Invitation: https://www.pulumi.com/registry/packages/azuread/api-docs/invitation/

This resource doesn't really exist (it's sending an invitation email out) so it can't be imported or theoretically deleted.

### Example

Working on reproducing this. Waiting for customer to come online so I can verify the version of pulumi and azure ad provider in use

### Output of `pulumi about`

```
CLI         

Version      3.72.2

Go Version   go1.20.5

Go Compiler  gc

 

Plugins

NAME     VERSION

azuread  5.28.0

python   unknown
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
Root caused this with the customer who reported it.  

The stack in question had updates which had been consistently failing on every update for some period of time.

Pulumi by design deletes resources at the end of an update operation, because until the program runs fully to completion, it is possible that something will still request that the resource be in the desired state, in which case it must not be deleted.  

As a result, if updates fail consistently, replaced resources will not be deleted, and will accumulate in the state file.  

These resources are marked `"delete": true` indicating that they need to be deleted.

There are two options to help manage this:
1. Ensure that the updates are completing and running to completion without failure
2. Use `deleteBeforeReplace` to force the delete to be processed before the new resource is created
