### ISSUE TITLE
Pulumi CLI command return warning: "GOCOVERDIR not set, no coverage data emitted"

### ISSUE THREAD

**Issue by avetkhov** [pulumi/pulumi#14799]
### What happened?

Each pulumi cli command get the warning: "GOCOVERDIR not set, no coverage data emitted". This is actual only for MS Windows OS.

### Example

<img width="770" alt="image" src="https://github.com/pulumi/pulumi/assets/120332335/6b0357d9-09bc-472f-96e7-5e96c7d10c09">

### Output of `pulumi about`

`pulumi about`
warning: GOCOVERDIR not set, no coverage data emitted
CLI
Version      3.96.1
Go Version   go1.21.4
Go Compiler  gc
 
Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Thanks for reporting this! We're seeing it as well, I've pinged the maintainers internally.

**Comment by dixler** [comment]
Hi. Thanks for reporting this. I can repro this on Linux as well and I'm working on a fix. This is undesirable. This is due to CI building the pulumi binaries that were included with the release with coverage. It looks like versions v3.95.0 and prior are unaffected.

You can downgrade your CLI to the v3.95.0 in the meantime to remove the message while we're working on the fix.

**Comment by dixler** [comment]
Thanks for your patience! We're cutting release `v3.96.2` which no longer contains this defect.
