### ISSUE TITLE
Invoked functions should not accept `Input<T>` as inputs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1483]
At the moment, `runtime.invoke` -- for accessing provider functions -- returns a `Promise<T>`.  This feels wrong, since the input arguments may very well carry dependencies, and it complicates composing returned values with other inputs to resource operations, which are usually `Output<T>`s.

It seems this should instead return an `Output<T>` that carries the complete dependency information.

**Comment by lukehoban** [comment]
We discussed this today, and decided on an alternate approach.

Today, these function accept `Input`s on their argument interface, and return a `Promise<T>` where T does not include `Output`s.  This is clearly wrong, as the resources tracked by the `Output<T>` will get lost.

However, since these functions really don't themselves deal with dependencies, it actually makes sense to solve this problem in the other direction.  That is, don't allow `Inputs` on the argument interface, and just let users call the function inside `.apply` in the case that they need to use an `Output<T>` as an input to the function.  Since `.apply(f)` handles `f` returning a `Promise` in the right way (coalescing that promise into the internal promise of the `Output<T>`), this will in general compose quite nicely.

This would be a breaking change, but we could phase it as a breaking change in the typings which initially just warns in the JavaScript implementation.  The breaking change also only impacts a case which is fairly rare.

**Comment by lukehoban** [comment]
This issue was moved to pulumi/pulumi-terraform#204
