### ISSUE TITLE
Consider a finite default value for --parallel

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#14989]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi CLI has a `--parallel` value that needs to be set for large programs to not explode in RAM usage. For example this program:

```python
import pulumi
import pulumi_aws as aws

for i in range(0, 1000):
    aws.kms.Key(f"key-{i}",
                deletion_window_in_days=7,
                description=f"KMS key {i}")
```

It allocates 8GB RAM or more by default but only 50MB RAM with `--parallel 20` for the `pulumi` process. 

It is difficult to pick the exact value but some default is better than no default, as casual users are likely to simply conclude Pulumi hangs or uses too much RAM without finding the right setting.

**Comment by Frassle** [comment]
NumCPU * some small multiplier (4ish?) is probably a reasonable default.

**Comment by justinvp** [comment]
cc: @PollRobots as FYI

**Comment by lukehoban** [comment]
Doing this will of course also have a significant impact on performance for these cases. 

It’s ultimately unfortunate (and I believe a somewhat new issue?) that memory scales so poorly with concurrent resource operations.  Especially weird that it appears to scale worse than linearly (8MB/resource at 1k concurrent resources vs 2.5MB/resource at 20 concurrent resources). I certainly hope we can continue to improve this.

That said - Terraform, whose memory usage and performance profile is the anchor for design of many of the providers that contribute most heavily to memory pressure, sets parallelism to 10 by default.  So there certainly is precedent. https://developer.hashicorp.com/terraform/cli/commands/apply#parallelism-n

**Comment by Frassle** [comment]
Raised https://github.com/pulumi/pulumi/pull/15016 to set this to "cpu * 4" if anyone wants to play with that scaling factor a bit before merging feel free.

**Comment by codethief** [comment]
I'm a bit late to the party but the default `cpu * 4` doesn't make much sense to me, at least not more than setting a fixed value (like 10 in Terraform's case). Pulumi is largely I/O-bound, not CPU-bound, so parallelism shouldn't depend on the CPU. If RAM is the issue, then RAM usage should be estimated.

The reason I'm bringing this up is that I have a couple thousand resources which take *ages* to deploy / redeploy, even though they shouldn't (since they're all independent from each other). So I started looking into how many resource operations are being parallelized and ended up here.

> It’s ultimately unfortunate (and I believe a somewhat new issue?) that memory scales so poorly with concurrent resource operations. Especially weird that it appears to scale worse than linearly (8MB/resource at 1k concurrent resources vs 2.5MB/resource at 20 concurrent resources).

This is what I'd like to understand better. What's going on there? Why are simple HTTP requests taking up such an incredible amount of memory? Which providers are the worst offenders? Maybe it'd make sense to have Pulumi output RAM usage of the providers it's calling, so that provider maintainers become aware of the issue.
