### ISSUE TITLE
`pulumi new ... --dir ...` does not cd into the project directory

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#1508]
This is probably okay--it's consistent with e.g. `git clone`--but it does mean that the final line of the output is very slightly misleading:

```
[pgavlin@odin sandbox]$ pulumi new aws-javascript --dir ahoy-pulumi
...
New project is configured and ready to deploy with 'pulumi update'.
```

**Comment by justinvp** [comment]
So the suggestion is to improve the message?

When `--dir` is specified, I could change the message to something like:

```
New project is configured and ready to deploy with 'pulumi update -C ahoy-pulumi'.
```

I'll have to basically compare the original working directory at the start of the command with the working directory after changing it based on the `--dir` value. If there's no need to specify `-C` I'll leave it off. If I can extract a relative path, I'll use that (e.g. `-C ahoy-pulumi`), otherwise I'll specify the full path (e.g. `-C /full/path/to/ahoy-pulumi`). And if there's any whitespace, I'll wrap the path in double quotes.

Or did you have something else in mind? /cc @lindydonna & @lukehoban in case they have a preference.

**Comment by lindydonna** [comment]
It would be nice if it would change to the directory, but most tools don't do this. The problem with `-C` is that it makes the command line longer each time. Perhaps we should just suggest that people `cd` to the new folder?

**Comment by justinvp** [comment]
> It would be nice if it would change to the directory, but most tools don't do this.

I can change the working directory for the `pulumi` process itself, but I don't know of a way to change the shell's working directory from within the `pulumi` command.

> Perhaps we should just suggest that people cd to the new folder?

So something like the following?

```
New project is configured and ready to deploy with 'cd ahoy-pulumi && pulumi update'.
```

Or:

```
New project is configured and ready to deploy.
Run 'cd ahoy-pulumi' then 'pulumi update'.
```

?

**Comment by lindydonna** [comment]
> New project is configured and ready to deploy.
> Run 'cd ahoy-pulumi' then 'pulumi update'.

I have a slight preference for this version, since the `&&` syntax might not be familiar to everyone.
