### ISSUE TITLE
Upgrade the Pulumi build system

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1537]
Today we're using `make` for everything. This has worked fine for us up to this point, but there are some major downsides for us:

1. `make` doesn't work on Windows, so we have to maintain clones of our build scripts as MSBuild projects to build on Windows
2. As we expand our language support matrix, it is annoying for the developer inner loop to constantly build SDKs for languages that they did not change nor care about
3. It is difficult to configure per-SDK variables when building. For example, our current build system is hard-coded to use Python 2.
4. Our current build system must build everything in order to test a single SDK, which makes our CI times unnecessarily long when testing multiple versions of the same language runtime
5. We can't do incremental builds

I propose that we take some time to invest in our build system. The limitation of `make` not working on Windows and our intention for devs to be productive on Windows implies that we should be using something else to run our build tasks.

There's no shortage of tools for this. A few that I'm aware of:

* https://github.com/go-task/task - Written in Go, task definitions are YAML
* https://github.com/magefile/mage - Written in Go, task definitions are Go
* https://github.com/gulpjs/gulp - Written in JS, task definitions are JS

**Comment by tamsky** [comment]
> `make` doesn't work on Windows
Citation required.
I'll admit, I've never developed on Windows, but...

I do see maintenance activity and a modern v4.x build of gnu `make` in the MSYS2 project:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-make/PKGBUILD

Is there a reason that port (or any another) is ineligible for consideration?

> `make` not working on Windows and our intention for devs to be productive on Windows implies that we should be using something else to run our build tasks.

`Make` is finished technology.  It's 40 years old, and has been working great for a long time.
Choosing less mature technology, simply because Windows support is lacking, seems... backwards.

The rest of the points mentioned...
> • It is difficult to configure per-SDK variables when building. For example, our current build system is hard-coded to use Python 2.
> • Our current build system must build everything in order to test a single SDK, which makes our CI times unnecessarily long when testing multiple versions of the same language runtime
> • We can't do incremental builds

will benefit from the suggestion I do agree with:
> I propose that we take some time to invest in our build system. 

\+ 💯 

Being able to do rapid incremental builds of just one sdk will be a big win.

**Comment by joeduffy** [comment]
I was speaking to @jen20 this morning about this very topic. He suggested looking into https://please.build/, which I hadn't seen before. It appears to have a lot of the benefits of Bazel (which I would love, were it not for the JVM dependency), but in single Go binary form. It's worth a look.

**Comment by stack72** [comment]
Going to close this out - this isn't really something we are going to track at this time.
