### ISSUE TITLE
In a component resource, if you're setting a resource as an input, you can't access outputs (easily)

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#15501]
### What happened?

Have two component resources, A and B. A has an output of a resource that is then consumed by B. We're using `initialize()` and `getData()` in both. If the resource is passed into B as `pulumi.Input<Resource>` we can't access any of the outputs of that resource without first using `pulumi.output()` or instead, passing the resource as `pulumi.Output<Resource>`.

### Example

Component Resource A:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

interface IamRoleArgs {
    managedPolicy: string
}

interface IamRoleData {
    role: aws.iam.Role
}

export class IamRole extends pulumi.ComponentResource<IamRoleData> {
    public readonly role: pulumi.Output<aws.iam.Role>
    public readonly roleArn: pulumi.Output<string>;
    constructor(name:string, args:IamRoleArgs, opts?: pulumi.ComponentResourceOptions) {
        super("x:index:S3Bucket", name, { name, args, opts }, opts);
        const data = pulumi.output(this.getData());
        
        this.role = data.role;
        this.roleArn = data.role.arn;
    } 

    protected async initialize(props: {
        name: string;
        args: IamRoleArgs;
        opts: pulumi.ComponentResourceOptions;
      }) {
        const {name, args} = props;
        const role = new aws.iam.Role(`${name}-rolw`, {
            assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal(aws.iam.Principals.LambdaPrincipal),
            managedPolicyArns: [args.managedPolicy]
        })
        return {
            role
        }
    }
}
```

Component Resource B:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

interface LambdaFunctionArgs {
    role: pulumi.Input<aws.iam.Role>
}

interface LambdaFunctionData {
    lambdaFunction: aws.lambda.Function
}

export class LambdaFunction extends pulumi.ComponentResource<LambdaFunctionData> {
    public readonly lambdaFunction: pulumi.Output<aws.lambda.Function>
    constructor(name:string, args:LambdaFunctionArgs, opts?: pulumi.ComponentResourceOptions) {
        super("x:index:S3Bucket", name, { name, args, opts }, opts);
        const data = pulumi.output(this.getData());
        
        this.lambdaFunction = data.lambdaFunction;
    } 

    protected async initialize(props: {
        name: string;
        args: LambdaFunctionArgs;
        opts: pulumi.ComponentResourceOptions;
      }) {
        const {name, args} = props;
        const lambdaFunction = new aws.lambda.Function(`${name}-function`, {
            role: args.role.arn,
            code: new pulumi.asset.AssetArchive({
                ".": new pulumi.asset.FileArchive("./app")
            }),
            handler: "index.handler",
            runtime: aws.lambda.Runtime.NodeJS18dX
        })
        return {
            lambdaFunction
        }
    }
}
```

### Workaround

To be able to use `args.role.arn` it's necessary to either do `role: pulumi.output(args.role).arn,` or to change `LambdaFunctionArgs` to be:

```typescript
interface LambdaFunctionArgs {
    role: pulumi.Output<aws.iam.Role>
}
```

### Output of `pulumi about`

```
CLI          
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.22.2
nodejs  unknown

Host     
OS       darwin
Version  14.2.1
Arch     x86_64

This project is written in nodejs: executable='/Users/piers/.nvm/versions/node/v20.10.0/bin/node' version='v20.10.0'

Current Stack: pierskarsenbarg/component-resource-output-input/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, karsenbarg, team-ce, demo
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.22.2
@pulumi/pulumi  3.107.0
@types/node     18.19.17
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
The reduced repro here is just this:

```ts
let role!: pulumi.Input<aws.iam.Role>;
const roleArn1: pulumi.Input<string> = role.arn;                 // (1) error
const roleArn2: pulumi.Input<string> = pulumi.output(role).arn;  // (2) okay
```

The error in case (1) is:

```
Property 'arn' does not exist on type 'Input<Role>'.
  Property 'arn' does not exist on type 'Promise<Role>'.
```

That error points at why this doesn't work.  

The type `pulumi.Input<T>` is just a union of three possible types an input can have - `export declare type Input<T> = T | Promise<T> | Output<T>;`

If it were just `T | Output<T>`, case (1) above would work - because an `arn` property is available on T (`aws.iam.Role`) and on Output<T> (due to "lifting" of properties onto Output types in TypeScript).  But Promise<T> does not lift properties, so there is no `arn` property on that. 

More generally - Pulumi's TypeScript typings do not "lift resource properties onto Input<T>".

So you must convert the Input into an Output so that you can either access the lifted property or use `apply`.  That is what option (2) above does.  This isn't just a type system thing - the data is actually being changed (from a Promise object to an Ouput, or even wrapping a Role in an Output object).

For component authoring, this is fairly "normal" in Pulumi.  You want to accept either T or Output<T> (or Promis<T>), but then to use those values, you need to project them into a consistent value you can operate on - and the lowest common denominator they can all be turned into is Output<T> (via pulumi.output). 

This is in a sense a reflection of the general "be loose in what you accept and strict in what you produce".  Resources and components accept a loose bag of things (a union of plain types, promises and Outputs called "Input<T>"), and expose back out a very specific thing (always an Output).  For component *authors*, this means they have to handle the conversion from the loose bag to the strict thing when they want to operate on their inputs.
