### ISSUE TITLE
Receiving error `GetLatestVersion is not supported for plugins from http sources` when using the CloudInit Provider with Python

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15536]
### What happened?

When using the cloudinit provider, I am occasionally getting a `GetLatestVersion is not supported for plugins from http sources` error. This error appears to happen sporadically. It seems only to happen on runs when the sdk is cached. 

### Example

TODO

### Output of `pulumi about`

TODO

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Some info from the run logs:

Python 3.9
Pulumi CLI: 3.104.2
`pulumi` python package: 3.75.0

```
Collecting pulumi-cloudinit<1.3.1,>=1.3.0
  Using cached pulumi_cloudinit-1.3.0-py3-none-any.whl 
```

```
@ Updating.... 
    pulumi:providers:cloudinit foo-cloudinit  error: could not find latest version for provider cloudinit: GetLatestVersion is not supported for plugins from http sources 
```

**Comment by zbuchheit** [comment]
Adding some notes after some discovery here. The provider as of 1.4.0 was switched to the plugin framework. I noticed in attempting a repro that during `GetRequiredPlugins` pulumi_cloudinit wasn't being picked up prior to version 1.4.0. I don't admittedly have a full explanation of the sporadic failing of the plugin being downloaded, but I believe the issue shouldn't appear in versions later than 1.4.0. In my testing after version 1.4.0 `GetRequiredPlugins` picks up pulumi_cloudinit and is able to determine a version correctly.

**Comment by justinvp** [comment]
We think we understand what's going on.

`pulumi-cloudinit` 1.3.0 is an older package from 11/18/2021.

It's `setup.py` has code that shells out to `pulumi plugin install resource cloudinit v1.3.0` to install the plugin when the package is installed.

https://github.com/pulumi/pulumi-cloudinit/blob/678e0710dd94952f9a37edcb5fb5865a053c4e02/sdk/python/setup.py#L18

However, in the customer's logs, we see that a cached `.whl` is being used:

```
Collecting pulumi-cloudinit<1.3.1,>=1.3.0
  Using cached pulumi_cloudinit-1.3.0-py3-none-any.whl
```

Which means for this particular run, it's not running `setup.py`, so `pulumi plugin install ...` is not being called.

That's ok, though. Newer versions of provider packages are published as wheels, so those don't have calls out to `pulumi plugin install ...` anyway. Another approach is used to install the plugin for such cases.

Before the program runs, the CLI asks the language host what plugins are needed by the program (`GetRequiredPlugins`). Pulumi's Python langhost looks over all the packages installed (via calling `python -m pip list -v --format json` internally). It checks each package to see if it has a `pulumi-plugin.json` file, which indicates whether the package has an associated Pulumi plugin.

cloudinit 1.3.0 is old and doesn't have a `pulumi-plugin.json` file.

For older packages that don't have `pulumi-plugin.json`, such as cloudinit 1.3.0, the langhost falls back and considers any package prefixed with `pulumi-` to have a Pulumi plugin. Which is what would happen in this case.

https://github.com/pulumi/pulumi/blob/697c8216ca0fd868c9232b4f7723198ecaa79f4e/sdk/python/cmd/pulumi-language-python/main.go#L464

However, this fallback no longer works when using recent versions of `setuptools` because of a behavior change in v69.0.3 and later (introduced by https://github.com/pypa/setuptools/pull/4159).

Previously, `python -m pip list --format json` would return the name of the package as `pulumi-cloudinit`:

```json
{"name": "pulumi-cloudinit", "version": "1.3.0"}
```

But now with setuptools v69.0.3 and later, it returns the name as `pulumi_cloudinit` (with an underscore rather than dash):

```json
{"name": "pulumi_cloudinit", "version": "1.3.0"}
```

The underscore in the name is now preserved and the name is no longer prefixed with `pulumi-`, so the langhost no longer considers it to have an associated Pulumi plugin.

Now, if this was just a regular Python program that was creating `cloudinit` resources, the plugin would still get installed on-demand as soon as a resource was created/updated. The `pulumi-cloudinit` python package has the version details of the package which it passes along to the engine as part of register resource requests, so the engine knows which version of the plugin to install if it's missing.

However, in this particular case, the `cloudinit` resources are being created by an MLC written in Go, and unfortunately, the Go provider SDK for `cloudinit` does not have the version information available (https://github.com/pulumi/pulumi/issues/13012). So when it tries to create the `cloudinit` resource, it doesn't have an associated version to pass to the engine, so the engine doesn't know which version of the plugin to install, so it tries to look up the latest version, which does not work for http plugin sources, hence the error.

The randomness of the behavior can be explained by whether there was a cached `.whl` or not (if not, `setup.py` would run and install the plugin) or if the plugin was already installed.

We definitely need to address https://github.com/pulumi/pulumi/issues/13012 for Go. It's not generally a problem for regular Go programs, as the langhost will usually be able to determine the needed plugins before running the program by looking at the go modules. But it doesn't do that for Go Automation API programs or MLCs. For MLCs, the system is relying on the calling program to have a dependency on the package so that the plugin can be installed. And it's not in this case due to the `setuptools` behavior change.

Even if we did fix https://github.com/pulumi/pulumi/issues/13012, it likely would not help with this case, because it looks like this is happening during a test of upgrading from an old version of the customer's SDK to a new version. So it wouldn't really be possible to upgrade the Go provider SDKs used by the old version of the customer's SDK.

The fix we should consider is to workaround the `setuptools` behavior change. We should update the Python langhost to fall back to considering packages prefixed with `pulumi_` in addition to `pulumi-`.
