### ISSUE TITLE
Pulumi new fails with "not a valid zip"

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi#15644]
### What happened?

Running `pulumi new --ai` and then accepting the prompt failed with `error: failed to retrieve zip archive: zip: not a valid zip file`

### Example

Prompt: `pulumi new --language YAML --ai "minimal valid program using aws:rds:subnetgroup, vpc and ec2:subnet`

Conversation: `https://www.pulumi.com/ai/conversations/d0668fac-b84c-4083-b862-c88fae27261f`

### Output of `pulumi about`

```
CLI          
Version      3.108.1
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/subnet-group/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/venelin-pulumi-corp
User           venelin-pulumi-corp
Organizations  venelin-pulumi-corp, demo, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/82/nqnqw81s1h56l5nv940f9mq00000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@AaronFriel, would you mind taking a look at this?

**Comment by AaronFriel** [comment]
## Root cause

The AI backend is throwing an error when generating the zip template. After extracting the program from the markdown of the conversation, the backend also parses the YAML to ensure certain keys are set:
* `name: ${PROJECT}`
* `runtime: yaml`
* `template.description: ...` the prompt

This template has a YAML syntax error though:
```yaml
      subnetIds: [${mySubnet.id}]
```

The YAML grammar accepts quoted strings or unquoted strings as long as they don't have certain symbols, but `{` is one of those symbols, and it should instead be:

```yaml
      subnetIds: ["${mySubnet.id}"]
```

**Comment by AaronFriel** [comment]
That leaves us with a few issues:

## Incorrect code generation

We can prompt and train the model to try to prevent this statistically. I'll open an issue and make a quick change to the prompt to address that.

## Unhelpful error on invalid AI template

```
error: failed to retrieve zip archive: zip: not a valid zip file
```

Occurs for any error reading an invalid ZIP archive, though practically speaking that would be mostly Pulumi AI templates today.

https://github.com/pulumi/pulumi/blob/3a8d92b15f244ad06d89a7910e6a9f46180e2070/sdk/go/common/workspace/templates_zip.go#L66

And bubbles up here:

https://github.com/pulumi/pulumi/blob/3a8d92b15f244ad06d89a7910e6a9f46180e2070/pkg/cmd/pulumi/new.go#L183-L186

### CLI error on invalid project file

In the event that the user obtains an invalid template, e.g.: if we returned the invalid Pulumi.yaml project file from the AI backend, `new.go` would return a different error:

```console
$ pulumi new ../template/ --test
error: could not unmarshal '../template/Pulumi.yaml': invalid YAML file: yaml: line 18: did not find expected ',' or ']'
```

That error seems specific enough to me, but in the case of zip templates, the filepath could be a temp location. And we'd see it bubble up from here:

https://github.com/pulumi/pulumi/blob/3a8d92b15f244ad06d89a7910e6a9f46180e2070/sdk/go/common/workspace/templates.go#L103-L109

To here:

https://github.com/pulumi/pulumi/blob/3a8d92b15f244ad06d89a7910e6a9f46180e2070/pkg/cmd/pulumi/new.go#L191-L195

## Next steps

@justinvp aside from prompting, sending the YAML program unmodified when it's invalid will shift the error to another location in the middle of `new.go`. Adjusting the prompt to try to address the root cause - invalid code generation - seems like the best tact to take right now.

**Comment by mikhailshilkov** [comment]
> The AI backend is throwing an error when generating the zip template

@AaronFriel Shouldn't `runAINew` fail in this case [here](https://github.com/pulumi/pulumi/blob/7ab7f00ced775a0915103723057568d3fed6051c/pkg/cmd/pulumi/new.go#L176)? Why do we even get to `workspace.RetrieveTemplates`?

**Comment by VenelinMartinov** [comment]
Hey, just wanted to say I just ran into the error again, not sure if we ever fixed the error message.
