### ISSUE TITLE
Rename @pulumi/pulumi to just pulumi

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1589]
We had to name the `@pulumi/pulumi` package using an organization scope because we started out private, but we should now just simplify the package name to `pulumi`.  We can then use the `@pulumi` resource as a standard scope for Pulumi packages, similar to how TypeScript uses `@types`.

I realize this will be perturbing, however perhaps we can find a way to mirror them for a period of time.

**Comment by ellismg** [comment]
When we do this, we'll need to ensure the language plugin can find `run.js` in either the old or new locations.

See: https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L56

We probably also want to rework this such that we do a `require` instead of pointing into `node_modules` directly, in order to support cases where the package has been installed globally.

**Comment by lukehoban** [comment]
> We can then use the @pulumi resource as a standard scope for Pulumi packages, similar to how TypeScript uses @types.

I didn't quite follow why we need to rename `@pulumi/pulumi` in order to enable this.  More generally, I'm not clear on what the motivation is for churning the name at this point?  I'll admit the consistency of `@pulumi/pulumi` with other Pulumi package imports actually feels net better to me than the alternative.

**Comment by joeduffy** [comment]
I'm fine sticking with the current names for now.

I vastly prefer the simplicity of just `pulumi`, since scoped packages are definitely foreign to many people. And the repetition of `@pulumi` followed by `pulumi` feels unfortunate.

But we have no shortage of work and we can come back to this later if it's not a slam dunk for you guys.
