### ISSUE TITLE
TypeScript/Node.js SDK - Consider modules to export a function?

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#1611]
Since [JavaScript lacks top-level await][jswait], and there are contentious issues around potential implementations of it, many Pulumi programs written using TypeScript today seem to use an "async main" function pattern to allow use of awaited values (primarily from data sources) in control flow constructs:

```typescript
interface Outputs {
	a: Output<string>,
	b: Output<string>[]
}

async function main(): Promise<Outputs> {
    // do everything, await allowed
    return {
        a: ...,
        b: ...,
    };
}

let outputs = main();
export let a = outputs.then(out => out.a);
export let b = outputs.then(out => out.b);```
```

This is obviously not ideal, since it requires duplicating a statement of each "output" three times if a return interface is defined - one of which is just to extract the value from a returned object.

Instead, it would seem logical to allow the module for which a stack is created to return an async function as a default export:

```typescript
interface Outputs {
	a: Output<string>,
	b: Output<string>[]
}

export default async function(): Promise<Outputs> {
    // do everything, await allowed
    return {
        a: ...,
        b: ...,
    };
}
```

And have the Pulumi runtime execute this function, and treat each property of the returned object as an output in the same way as exports are currently treated.

I don't know enough about either TypeScript or the Pulumi Node.js runtime to know whether this would be a backwards compatiblity concern, but it seems like it would be a usability improvement, at least until such time (if that comes) as JavaScript supports top-level await.

[jswait]: https://github.com/tc39/proposal-top-level-await

**Comment by CyrusNajmabadi** [comment]
@jen20 would it be acceptable to have something like:

```ts
async function exec() {
    await ...
   return {
      ...
   };
}

export outputs = exec();
```

We could then take promise-valued exports and await them.  We could also treat their properties as individual stack outputs. Would that work for you?   I think i like the idea of introspecting normal objects (or promises) more than i like runnin arbitrary functions.  But i could be convinced otherwise :)

**Comment by jen20** [comment]
@CyrusNajmabadi  I don't particularly have a particularly strong opinion on whether returning a function vs an object is better - both options remove the duplication of output names and mapping, which is the most important thing for me here.

**Comment by CyrusNajmabadi** [comment]
@jen20 I totally agree with that.  :)

**Comment by eropple** [comment]
@joeduffy just pointed me here, because right now I'm pretty stuck with Pulumi. My natural inclination is to treat it as code, and without being able to effectively get values out of a `Promise` it's hard to really do anything.

I like @jen20's outlined solution a lot. If there's

This is how the set I would suggest, as far as top-level exports go (and it matches the way people shim old Node modules to current ones):

- Is the exported module itself a function (`module.exports = function() {}`)? That's the complete set of the module's exports; call it.
- Is `PulumiModule.default` (i.e., `export default`) a function? That's the complete set of the module's exports; call it.
- Is the complete set of module exports a Promise? Await on it and return the whole thing. (I personally don't really care about nested Promises, because I'll pretty naturally end up `await`ing in my output tree, but that might be a bigger thing for other folks.)

If the default isn't set, then the current behavior seems fine (but maybe is best discouraged?).

I get @CyrusNajmabadi's discomfort with executing a default function blindly, but TBH it's such a common pattern in JavaScript that I naturally expected it to Just Work so was very confused.

**Comment by CyrusNajmabadi** [comment]
> I get @CyrusNajmabadi's discomfort with executing a default function blindly, but TBH it's such a common pattern in JavaScript that I naturally expected it to Just Work so was very confused.

Hi @eropple.  Could you link me to some examples of this in the JS ecosystem so i can take a look?

**Comment by CyrusNajmabadi** [comment]
I'm definitely leaning toward accepting where we are at this point *now that* Joe's promise-exports PR has gone in.  With this form you can just write:

```ts
async function main() {
   await ...
   return {
      ...
   };
}

module.exports = main();
```

And it will `Just Work ™`.  I'm *very* hesitant about just randomly invoking exported functions.  After all... how do you know that they're even functions that take no args?  Or that they're not an exported function intended for someone else to call in as if this was a library being generated.  For example, 'express' and 'JQuery' both export functions by default.  But nothing ever calls those exported functions implicitly.  Instead, someone else imports that library and then explicitly calls those functions with the documented arguments they have.

**Comment by CyrusNajmabadi** [comment]
i'm moving this out for now as i think Joe's work makes the current experience good enough.  I'm leaving open though so we can continue to discuss and determine if there's anything else we should be doing here.

**Comment by CyrusNajmabadi** [comment]
@jen20 Are you ok with the current state of things thanks to https://github.com/pulumi/pulumi/pull/1866 ?  I'd like to close this out if so.  If you still think other work is definitely necessary, let me know.  Thanks!

**Comment by jen20** [comment]
Yes, I think that solves the worst of the problem and removes the boilerplate. Thanks @CyrusNajmabadi!
