### ISSUE TITLE
Don't return `codes.Unknown` everywhere

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1615]
When addressing the #1590, we noticed that we're returning `codes.Unkown` everywhere, and that other error codes are [liberally interpreted as `status.OK`](https://github.com/pulumi/pulumi/blob/ad3b5e7ee88346bc7e960de9f953957a72f84516/pkg/resource/plugin/provider_plugin.go#L574) by our error protocol.

This is a known anti-pattern, but it seemed bad to change the core Pulumi error protocol while introducing a subtle change like partial updates. While not immediately pressing, we should come back and decide what the right thing to do here is.

**Comment by swgillespie** [comment]
This has gotten pretty stale. For better of for worse, this is the error protocol we're stuck with.

I think that, in general, we could be using gRPC better than we currently are. That said, gRPC is primarily designed for services, and we're using it in a way that departs pretty far from that. gRPC's error codes like "UNIMPLEMENTED" or "NOT_AVAILABLE" are not super useful for us, since we're launching the gRPC server as a process on the same machine.

I doubt we need to address this, as long as we understand what's going on, which I think we do.
