### ISSUE TITLE
Output.all with multiple types throws mypy error about needing an object

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#16194]
### What happened?

Upgrading to pulumi-3.116.0 throws an error when running mypy when you use different types in Output.all:
```
__main__.py:18: error: Argument 1 to "return_text" has incompatible type "object"; expected "str"  [arg-type]
__main__.py:18: error: Argument 2 to "return_text" has incompatible type "object"; expected "str"  [arg-type]
__main__.py:18: error: Argument 3 to "return_text" has incompatible type "object"; expected "bool"  [arg-type]
```

### Example

```python
"""A Python Pulumi program"""

from typing import Optional
import pulumi
from pulumi import Output, Input

a: Input[str] = "Hello"
b: Input[str] = "World"
c: Optional[Input[bool]] = True


def return_text(first: str, second: str, third: bool) -> str:
    return f"{first} {second} is {third}"


text = Output.all(
    Output.from_input(a), Output.from_input(b), Output.from_input(c or False)
).apply(lambda x: return_text(x[0], x[1], x[2]))


print(text)```

### Output of `pulumi about`

```
CLI
Version      3.116.0
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='venv/bin/python3' version='3.11.9'

Dependencies:
NAME     VERSION
mypy     1.10.0
pip      24.0
pulumi   3.116.0
pyright  1.1.362
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
From internal discussion, sounds like we'll likely want to add overloads up to a certain number of arguments to better model this for type checkers.

**Comment by julienp** [comment]
I don't think this is possible, because Output returns a list, but you can't have something like `list[T1, T2, T3]`. List assumes all elements are of the same type.

To have different types we need to return a tuple, but I think that would be a breaking change.

Here's an example of typing it using `tuple` return [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAUAUFKVAOICmKlISAxgDQlkCCA7gIZIycBGAG0rMyUAKookYFCLIAVRJQBqnELNJgAbrQFhOAE3VQQlbZwEB9eAmFEAlESJyL9MFAC8UBTZUgCAImdXf0YoV01VJE4UGHc5EABXSgc5Dy9FXwC5fxSARjTvZVUs3JynACYCjOLA8rK5AGYqnxrG%2BoAWZqK-QPayogBJFAQE-E8JKRQAbTlQjm5eQUoZgF1Q-wB5UZGYVf8Vx3oBTgBnE6gtmB2CKho6ehmXMBW7AC4WUgABE94YBghKDAABZgfQfKD6SjAKCgSAWVDXJCvKBDHarOxQAC0AD4oJttqM9siAHSkxyiT5aHR6MEUn6cP70AHA0HgyHQ8wCAicZGowlyXJrKAAegxOLxlzRMASCCEM0FK38JNJUHJZEp2hAugM4O%2Bv3%2BgJBtLI7KgnO5vOG-MFoT4lrRcnKQtFWNx%2BKuhOlsuWAtCjpWiuVxNIaq%2BVK1NN19MZzKNbKhZoEXPBoh5KKtuwFQrt6YdTtC9Ht-IazvBYrdks9Mrlvq85T9JcDUFJwdVuvD2uNX2jBpZXYhCfNKbIab5mZtUBzY5m%2BbCRczJdC%2BnnM3apdE5YlBN2XpruT99a8DT9a6bLbbFI7kbp%2BqZhtZolNQ9EqZXcjWw9IU4zqyMokLub8h%2BL4mm%2BwEgVAlBgX%2BZDCjBpAAFSqGgJzQWWrpbh6O7Vj6oQtgGSrNiqjicGklYwMS5rkcSsIQPCGYELkdihNRtH0dc-hApQSZgDkLHbjR4B0QiowEPESR2A4RAmGYljWJQ3IOEAA)

**Comment by julienp** [comment]
Our best option might be to weaken the `all` types to better match reality https://github.com/pulumi/pulumi/pull/16172/commits/d0ce289b9456474c07a347c459420a656cf79582
