### ISSUE TITLE
Cannot use a pulumi.Output<string> to construct a resource name

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1631]
The "name" argument for our resources is typed as `string`.  But this means you can't use an Output<string> to help influence the name of the resource.

I've run into this a few places now.  One real example is that in aws.serverless.FunctionOptions, we have a list of policies to apply to the lambda.  This is typed as `ARN[]`:

https://github.com/pulumi/pulumi-aws/blob/master/overlays/nodejs/serverless/function.ts#L58

Ideally, this would be typed as `pulumi.Input<ARN>[]` so when I create a policy explicitly I can pass the Output<ARN> as part of the policy I attach.  However, this falls apart here:

https://github.com/pulumi/pulumi-aws/blob/master/overlays/nodejs/serverless/function.ts#L135-L142

Where we use the policy's ARN as part of the name of the resource.

You could imagine playing tricks today, for example, doing something along the lines of getting the underlying promise from the output and then waiting for it to resolve and handling the case where it is unknown "somehow".

But that's a lot to expect folks to do.  I think we need some more first-class way of doing this.

**Comment by lukehoban** [comment]
Would be interesting to see an explicit example of the original need for this.

Given this:

```
let bucket = new aws.s3.Bucket("mybucket");
```

The `name` parameter is used for two purposes:
1. To create the URN for the resource so that we can give it an identity that can be related to resources from previous checkpoints
2. As a seed for AutoName generation of the `name` property on the resource itself

For 2, you can pass `name` explicitly via an `Output<string>`, so it's always possible to control the actual name of the cloud resource based on an output.  You cannot opt-in to auto-naming using this approach though - at least not directly.  Making that easier is tracked by https://github.com/pulumi/pulumi/issues/381.

For 1, it's dangerous to allow not knowing a name to use for resource identity until after some other resource resolves.  This would for example make the identity of the resource un-knowable during preview.  This is mostly equivalent to creating a resource inside an `apply` (and in fact, that's a way of working around this).  I'd be interested in seeing a real compelling case where this is needed.

Do you have examples of either/both of these in practice?

**Comment by ellismg** [comment]
Sure, here's a concrete example.  I create a policy that allows access to kms for a lambda:

```typescript
const policy = new aws.iam.Policy("kmsDecryptPolicy", {
    policy: JSON.stringify({
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "kms:*",
            "Effect": "Allow",
            "Resource": "arn:aws:kms:us-west-2:153052954103:key/1a0f1f7d-d96e-4651-914c-e5e99672b362"
          }
        ]
      })
});

const api = new serverless.apigateway.API("api", {
    routes: [{
        method: "GET",
        path: "/",
        handler: createLambdaFunction("get-handler", async (req, res) => {
            return {
                statusCode: 200,
                body: "hello",
            }
        }, undefined, {
            policies: [aws.iam.AWSLambdaFullAccess, /* what do I put here? */]
        }),
    }]
});
```

Today, the `policies` array is typed as `ARN[]`, because it ends up getting passed into `aws.serverless.FunctionOptions`, and that value is flown into the name of the role policy attachment we create.

Now, you can imagine us inverting this.  If the `api` object returned allowed me to get access to the `role` that was created, I could manually construct the role policy attachment object myself at the same level where I define the policy and api itself.  But I'd still have the problem of understanding what name I give to the resource, and the comment here: https://github.com/pulumi/pulumi-aws/blob/master/overlays/nodejs/serverless/function.ts#L136-L138 implies that I need to involve the actual ARN itself (which puts be back to square one).

> This would for example make the identity of the resource un-knowable during preview. This is mostly equivalent to creating a resource inside an apply (and in fact, that's a way of working around this).

And I suppose in this case it's on me to ensure that every resource I create in the apply explicitly sets `DependsOn` for every logically captured resource, are there other things I need to watch out for?

**Comment by lukehoban** [comment]
>  it ends up getting passed into aws.serverless.FunctionOptions, and that value is flown into the name of the role policy attachment we create.

I think this is where the bug/limitation is.  We shouldn't have to flow this ARN into the name of the role policy attachment we create. We currently do that because we haven't addressed https://github.com/pulumi/pulumi/issues/918.  My sense is that we need to remove these cases where it feels necessary to flow computed values into resource names - that is going to generally cause complications.  It may be that there is some more targeted way to fix this for `aws.serverless.Function`, which we should try to do to unblock this particular case ahead of a solution for #918.

> are there other things I need to watch out for?

Well - the apply won't run at all during preview, so the biggest concern is that some subset of your resources won't be visible as part of the preview, but then will get created/updated/deleted anyway.

**Comment by lukehoban** [comment]
I believe we should not do any fix here, but should instead address the underlying issues that lead to wanting to try to do this - in particular #918.

Please reactivate if there are new scenarios motivating the need for this that we should reconsider.

**Comment by smcoll** [comment]
> Would be interesting to see an explicit example of the original need for this.

@lukehoban Route53 zones and records use a domain name as the value.  In my case, i set the hostname in a stack config, so i can use the same project to deploy stacks to various domains.  i'm trying to split this project into multiple projects using stack-based dependencies, and was hoping to declare the hostname in one stack (for basic DNS setup) and then output it for use in other stacks (along with the hosted zone ID).  For example, i'd like the stack defining an ALB to also create the DNS record for the same the hostname.  It looks like i'll need to coordinate matching config values for the related stacks rather than inherit the hostname from a single stack through an output, since resource names can't be constructed using outputs.

**Comment by lukehoban** [comment]
>  i'm trying to split this project into multiple projects using stack-based dependencies, and was hoping to declare the hostname in one stack (for basic DNS setup) and then output it for use in other stacks (along with the hosted zone ID).

Got it.  I think this is https://github.com/pulumi/pulumi/issues/5035.
