### ISSUE TITLE
Ignore Changes still showing up in drift detection

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi#16334]
### What happened?

I added ignoreChanges to my resources (in an existing stack), but they are still showing up in drift detection.

### Example
```
const iam = new IAMMember(`${prefix}-${_account.accountId}-bq-editor-member`, {
  project: gcpConfig.require('project'),
  role: 'roles/bigquery.dataEditor',
  member: account.email.apply(email => `serviceAccount:${email}`)
}, { ignoreChanges: ['etag'] })
```
But it’s still showing up in the drift pulumi refresh --preview-only
```
~ gcp:projects/iAMMember:IAMMember: (update)
...
--outputs:--
~ etag     : "BwYWTNS0Q6s=" => "BwYY98HnOng="
```
### Output of `pulumi about`

latest

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by automagic** [comment]
Relates to: https://github.com/pulumi/pulumi/pull/16146

**Comment by justinvp** [comment]
Yes, I believe https://github.com/pulumi/pulumi/pull/16146 will address this.

**Comment by ababo** [comment]
Hey,

I’ve been following this issue because we’re hitting exactly the same class of drift / reconciliation / state-mismatch problems.

We’re building a completely different approach: **no persistent state file at all**.  
Desired state lives only in Git (Nickel configuration), observed state is derived from live infrastructure scans, and reconciliation is fully deterministic and ephemeral.

We already have a **working prototype** (successfully demonstrated with AWS EC2), but it’s still **early stage** — not a production-ready product yet.  
We are actively looking for **2–3 platform/infra teams** as the very first design partners to try the prototype in real environments, adapt it together and shape the next version.

If this resonates with the drift/reconciliation problems you’re seeing, I’d love to:
- show you the prototype live, and
- hear how this impacts your day-to-day.

No sales, no pressure — just honest technical discussion and the chance to influence the solution.

Details in these two posts:
• What if managing infrastructure felt like using git? → https://www.linkedin.com/posts/simon-golbert_what-if-managing-infrastructure-felt-like-activity-7447176625881837569-yKNO
• If deterministic, stateless, Git-driven infrastructure resonates with you → https://www.linkedin.com/posts/simon-golbert_most-infrastructure-tools-separate-configuration-activity-7434492903369891840-TfP2

Would you be open to a quick call or async feedback?
