### ISSUE TITLE
Add an import command

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1635]
We have `get` functions that let you read in the existing state of a resource, by its ID, without adding it to your checkpoint file. And we have a `refresh` command that will take existing resources in your checkpoint, and synchronize your checkpoint's state with the live values of the resources.

What we are missing is a way to import existing resources into your checkpoint, essentially "adopting" them for use within Pulumi.  For large existing cloud applications and infrastructure, this capability will be a requirement.

As described, the above idea is actually trivial to achieve.  Import some IDs into the checkpoint, and then refresh their state.  This is probably a fine place to start just for simplicity (it's a little better than just editing the checkpoint by hand to achieve the same thing).

One could imagine something like

```
$ pulumi import aws:elasticloadbalancingv2:Listener mylb-42dc3ff4
```

and having it result in an imported resource in your checkpoint file, with the live resource state.  Presumably running `pulumi update` after this would think the resource had been deleted from your program, until you manually added the source code.

The problem gets complicated by two matters

1. How to discover those IDs, particularly when the mapping of physical resources to logical ones in a Pulumi program are not always evident (and not always even 1-to-1)

2. How to generate the source code for the program that would have created that checkpoint state

Those feel like longer term problems that we'll need to tackle, perhaps as follow-on activities.

I should note that all these issues share a lot in common with our ongoing design discussion of conversion tools.

**Comment by lukehoban** [comment]
Let's come up with a design and implementation strategy for this as part of 0.17.

**Comment by lukehoban** [comment]
Going to tackle this in 0.18.

**Comment by casey-robertson** [comment]
Up vote for this.... realized when muddling my way around creating GCP KMS keyrings and secrets that they can't be destroyed.  So while still in the iteration phase where stacks are changing a lot, I'm in a pickle: I destroyed the stack, discovered the keyring cannot be deleted but now I cannot update the stack again because the Plan apply fails trying to create the keyring.  No way that I can tell to adopt this already existing object.  I've now flagged my code to protect it and I've parented the key creation to the keyring but looks like too little too late.

**Comment by lukehoban** [comment]
https://github.com/pulumi/pulumi/issues/1662 is related, and may ultimately be a more natural way to support this.  We should look at both of these together and come up with a plan for how we'll support this.

**Comment by joeduffy** [comment]
I spoke to @jen20 just last week about a command versus program approach. I think there are tradeoffs here that he identified which I agree with. Ultimately, both are probably useful, so I'm keen to identify which is the first we will pursue.

**Comment by lukehoban** [comment]
Resource adoption (#1662) and import (#1635) are important and we should continue to drive toward a design, but let's move these to M21 to give time to flesh out a thorough design.

**Comment by pgavlin** [comment]
One note about a command-based approach:

> Presumably running pulumi update after this would think the resource had been deleted from your program, until you manually added the source code.
> ...
> How to generate the source code for the program that would have created that checkpoint state

I think that this deserves some extra stress, as I believe it to be a particularly important issue with an `import` command. The code generation aspect is complicated by the fact that a property value that is present in a resource's state is not necessarily correctly-formed for use as an input to that resource. Indeed, this issue is what sunk the first iteration of `pulumi refresh`, which passed resource state as resource inputs.

I can think of a couple avenues of attack:

- Guided code generation that uses a combination of the result `Provider.Check` and user input to determine and correct invalid input values
- Add a bit to resource state that indicates that a resource has been imported but is in a liminal state where it is not yet represented in the program. Such a resource will only participate in `refresh` and `destroy`

I think that these are complementary. The second allows the user to do the easy bit of the process quickly and defer the difficult part until a more opportune time, while the first makes that difficult part easier.

Note that we can do better in cases such as `tf2pulumi` where we know what the inputs are at the time of import/conversion.

**Comment by gwkunze** [comment]
As someone who would really like this feature might I suggest splitting the mentioned two matters into separate tasks. The first one would be enough to get people started, we can manually write the pulumi code until `pulumi update` no longer considers the resource changed. This is (as far as I know) all that Terraform does.

Implementing the second matter sounds very cool, very tricky to implement but ultimately not as essential to migrating from another tool to Pulumi.

**Comment by agolomoodysaada** [comment]
This would be especially useful when migrating from Helm to pulumi. I imagine an API like

`pulumi import tiller` that talks to the existing Tiller server, pulls all existing Helm releases and generates a file for each release and their corresponding values. The output pulumi files can then be easily modified and added to CI.

The same can be applied with cloud resources: `pulumi import gcloud`, `pulumi import aws`, `pulumi import az`. The `import` command would interact with the local cli tools that are already authenticated, pulls info and converts them to pulumi files.

**Comment by pgavlin** [comment]
For the time being, we intend to take a code-first approach to importing resources. Once https://github.com/pulumi/pulumi/pull/2893 lands, you will be able to indicate that the state for a particular resource requested by your Pulumi program should be imported by specifying the ID of the resource to import when instantiating the resource. `pulumi up` will then indicate the differences that exist (if any) between the inputs passed to the resource instantiation and the resource's actual state, and will require that the two match before the import succeeds.

For a concrete example, here is a recording of a session that creates a Kubernetes service and deployment using `kubectl`, then imports them into a Pulumi stack that is then used to manage them: https://asciinema.org/a/Ov7s3Xxa0YtXzWwVtleyGYfCw

The initial and final programs used to import the k8s resources in that recording are below. Note the `import:` property that is specified when instantiating these resources.

Initial (no input properties specified):
```typescript
import * as k8s from "@pulumi/kubernetes";

const service = new k8s.core.v1.Service("redis-master", {
}, { import: "redis-master-import" });

const deployment = new k8s.apps.v1.Deployment("redis-master", {
}, { import: "redis-master-import" });
```

Final:
```typescript
import * as k8s from "@pulumi/kubernetes";

const service = new k8s.core.v1.Service("redis-master", {
    metadata: {
        name: "redis-master-import",
        namespace: "default",
        labels: {
            app: "redis",
            role: "master",
            tier: "backend",
        },
    },
    spec: {
        ports: [{
            port: 6379,
            targetPort: 6379,
        }],
        selector: {
            app: "redis",
            role: "master",
            tier: "backend",
        },
    },
}, { import: "redis-master-import" });

const deployment = new k8s.apps.v1.Deployment("redis-master", {
    metadata: {
        name: "redis-master-import",
        namespace: "default",
    },
    spec: {
        replicas: 1,
        selector: {
            matchLabels: {
                app: "redis",
                role: "master",
                tier: "backend",
            },
        },
        template: {
            metadata: {
                labels: {
                    app: "redis",
                    role: "master",
                    tier: "backend",
                },
            },
            spec: {
                containers: [{
                    image: "k8s.gcr.io/redis:e2e",
                    name: "master",
                    ports: [{
                        containerPort: 6379,
                    }],
                    resources: {
                        requests: {
                            cpu: "100m",
                            memory: "100Mi",
                        },
                    },
                }],
            },
        },
    },
}, { import: "redis-master-import" });
```

**Comment by gpduck** [comment]
Would it be possible for me to get an example of what a resource ID would look like for importing Azure resources?  Like an example of a resource group or something.  I've tried several permutations and can't seem to make it happy...

**Comment by lukehoban** [comment]
> Would it be possible for me to get an example of what a resource ID would look like for importing Azure resources? 

It is different for each resource - but in general is the full ARM resource name - like `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/microsoft.compute/virtualMachines/machine1`

**Comment by lukehoban** [comment]
For folks interested in this - see https://www.pulumi.com/blog/adopting-existing-cloud-resources-into-pulumi/ for the currently supported resource adoption features.

**Comment by LouisAmon** [comment]
One of the caveats of the programmatic approach I encountered today is that there is no easy way to pull the config from the currently deployed cloud resources.

The example below illustrates the problem with a Bucket that I'm trying to import in Pulumi but can't because of the CORS configuration:
![image](https://user-images.githubusercontent.com/6024791/71329414-374c8200-2525-11ea-9df2-d0cea93a00d2.png)
I had no idea what CORS rules I put there and how to properly write them in Pulumi's syntax, and it seemed very slow to open side by side the AWS Console & Pulumi AWS documentation to find the right specification.

It makes sense that the Pulumi template should absolutely reflect the currently deployed resource, but the whole purpose of an `import` command is to be able to decompose that into two steps:
1. Run `pulumi import` to inspect the cloud
2. Run `pulumi up` to perform the import with all values properly set

In the case of my S3 example above, I had to `terraform import` then copy my CORS rules from the `.tfstate` file into the Pulumi config, then my `pulumi up` managed to import the Bucket.

**Comment by ringods** [comment]
IMO a big shortcomming to the programmatic approach is that it the IDs you import are specific to a stack. If you use your Pulumi code for multiple stacks, you have to change the code multiple times. On top of that, if you use reusable packages with Pulumi code, it is very hard to add the import IDs to the resource descriptors of the third-party code.

Conclusion: I'm in favor of an import command.

**Comment by jen20** [comment]
Hi @ringods! A good way to deal with this in the short term is to source the ID from configuration, and then it can be set per-stack. Indeed, some people have implemented novel approaches to this, including sourcing them from Terraform state files, or from API calls using cloud SDKs and so forth.

**Comment by ringods** [comment]
@jen20 Is the sourcing of the IDs from configuration something core to Pulumi? You have a pointer on that?

So far, I read this blog post:
https://www.pulumi.com/blog/adopting-existing-cloud-resources-into-pulumi/#adopting-existing-resources
but it only talks about the `import` property in the code.

**Comment by jen20** [comment]
Sure - so what you'd do is create a config point for the stack (I'm assuming TypeScript but this works across all languages):

```ts
var config = new Config();

// Naming to be obvious in examples, not an actual recommendation!
var securityGroupIdToImport = config.require("security_group_id_to_import")
```

This can be set per stack using:

```shell
$ pulumi config set security_group_id_to_import "sg-123456"
```

The variable can be passed as the name to the `import` property.

```ts
const importedSecurityGroup = new aws.ec2.SecurityGroup("imported-sg", {
    // other properties
}, { import: securityGroupIdToImport});
```

Hopefully this clarifies things?

**Comment by ringods** [comment]
@jen20 thanks for the example. However, this still doesn't solve the case of importing resources when the resources are created by a third-party package (npm, pip, ...).

Adding support for `import` in reusable pulumi code libraries can be done, but the issue here is that everybody could be doing it their own way. IMO, `import` should work for all stacks and with reusable code without any special setup.

What's wrong with `pulumi import ...`? Such a command is typically a one-time command and shouldn't be resolved in the code.

**Comment by jen20** [comment]
@ringods I don't think there is anything wrong with the idea of an import command per se, it's just that there is not yet one - in the meantime the example I posted covers a majority of cases, but there are definitely cases where this can be improved. Now that the import primitives are in place it should be substantially easier to implement a CLI command for this.

**Comment by pgavlin** [comment]
> What's wrong with pulumi import ...? Such a command is typically a one-time command and shouldn't be resolved in the code.

The fundamental challenge with an import command is that a naive approach that simply adds the resource to the state file isn't very ergonomic: it would require exposing type tokens, parent resources, and other resource properties in a novel fashion, and would also require that the resource be immediately added to the user's program in order to prevent its deletion during the next update. These two points--especially the latter--are what motivated the code-first approach.

**Comment by lukehoban** [comment]
There is some work on a proposed implementation of a `pulumi import` command in https://github.com/pulumi/pulumi/pull/4765.  This provides a way to emit Pulumi code in the project's language which can be added to the Pulumi program, significantly simplifying the overall import process.
