### ISSUE TITLE
Go programgen example has an incorrect module: `index`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#16461]
### What happened?

As part of https://github.com/pulumi/pulumi-ns1/pull/482, I found this programgen diff: https://github.com/pulumi/pulumi-ns1/pull/482/commits/4a50819a06142139232892958b36fbea34dcbd28.

### Example

See the above diff:

```patch
 //
-//	"github.com/pulumi/pulumi-external/sdk/go/external"
+//	"github.com/pulumi/pulumi-external/sdk/v1/go/external"
 //	"github.com/pulumi/pulumi-ns1/sdk/v3/go/ns1"
 //	"github.com/pulumi/pulumi-std/sdk/go/std"
 //	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
 //
 // )
 //
 //	func main() {
 //		pulumi.Run(func(ctx *pulumi.Context) error {
 //			_, err := ns1.NewZone(ctx, "example", &ns1.ZoneArgs{
 //				Zone: pulumi.String("terraform.example.io"),
 //			})
 //			if err != nil {
 //				return err
 //			}
 //			...
 //			// Some other non-NS1 provider that returns a zone with a trailing dot and a domain with a leading dot.
-//			_, err = external.NewSource(ctx, "baz", &external.SourceArgs{
+//			_, err = index.NewSource(ctx, "baz", &index.SourceArgs{
```

### Output of `pulumi about`

NA

### Additional context

This is a regression.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
@iwahbe do you have a version range for what version of Pulumi this _did_ work in?

**Comment by iwahbe** [comment]
We are running on latest, so this broke when the GH runner's version of Pulumi upgraded, between 4 days and 1 week ago. I'm guessing this broke in the last 2 releases.

I can't point to specific versions right now, we have shipped that fix in CI but it wasn't rolled out last week.

**Comment by Zaid-Ajaj** [comment]
I am investigating this issue right now. It seems like we only emit `index` module for resources which don't have a schema reference. Likewise, we choose `/v1` as a best guess for the import path when there is a missing schema. Fix incoming for this so that we don't emit `index` for unknown schemas.

@iwahbe Did the converted example above have a schema for a real provider called "external" or it was just mock code for an example resource?

**Comment by justinvp** [comment]
@Zaid-Ajaj, do you know what caused the regression?

**Comment by Zaid-Ajaj** [comment]
@justinvp I don't think this was a regression in behavior of program-gen. I believe the bound PCL program didn't have access to a schema of the resource `Source` and so it emitted "best-guess" code when we encounter unknown resources. 

The real question here is what I asked @iwahbe about which is why `external.Source` doesn't have a schema in the first place and how it was bound before. 

The logic for "best-guess" code that emitted `index` was introduced a year ago in https://github.com/pulumi/pulumi/pull/13172 so this is not a new piece of code which is why I think the problem is in how the example program was bound, not program-gen.

**Comment by justinvp** [comment]
OK, thanks. Untagged `impact/regression` and closed the postmortem issue.

**Comment by iwahbe** [comment]
I'm not 100% sure where the regression occurred, but it was a regression. Code that used to work stoped working. That is the definition of a regression.

I assumed that the regression was due to a changed version of `pulumi`, so I'm assuming that the regression was in this repo. It may be because of a change in pulumi-external, in which case the regression was in another repo (pulumi/pulumi-external).

**Comment by Zaid-Ajaj** [comment]
> Code that used to work stoped working. That is the definition of a regression.

@iwahbe I did not disagree that it was a regression. 

The availability of providers can cause program generators to behave different so if the environment changes in which the example program is being converted, it could cause this kind of issues. For example, you might install a version of a provider that doesn't have a resource that you are trying to convert. 

Looking at the [schema](https://github.com/pulumi/pulumi-external/blob/main/provider/cmd/pulumi-resource-external/schema.json) of pulumi-external, it only has a single function/invoke and the program tried to convert a resource called `Source` that does not exist.
