### ISSUE TITLE
Consider adding `--preview` for destroy, refresh, and import

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1666]
As the CLI has evolved, the `--preview` flag for the `destroy` command has been replaced by our insistence to run previews automatically. And you can skip the preview by passing `--skip-preview` OR `--yes`.

However, there is no option to _just_ see the results of the preview. e.g. what resources `pulumi refresh` bring up to date? If I imported this particular checkpoint file, what resources would be clobbered? etc.

We already support the notion of "previewing" imports, destroys, and refreshes on pulumi.com. So it's just a matter of doing the wiring on the CLI.

```[tasklist]
### Tasks
- [ ] #15301 
- [ ] https://github.com/pulumi/pulumi/issues/15303
- [ ] https://github.com/pulumi/pulumi/issues/15304
```

**Comment by boillodmanuel** [comment]
To be consistent, I will add a `pulumi up --preview` which is a synonym to `pulumi preview` but make all `pulumi x` consistent.

We often see `--dry` for that.

By the way, I vote for this (because this is a requirement I have too). I apply GitOps method and this requires to check state is still sync will real world. For this, I plan to do:
- `pulumi preview --expect-no-changes` (stack is sync with state)
- `pulumi refresh --preview --expect-no-changes` (state is sync with real resources) 

Additional notes about `pulumi refresh --preview  --expect-no-changes`
- I expect `expect-no-changes` to returns an error from preview, without doing the refresh action)
- As cloud provider add additional metadata, `pulumi refresh` often returns changes (which are safe to ignore). What I really want is to know if some resources have been really modified. So these kind of diff could be ignored:
```diff
     ├─ azure:core:ResourceGroup            rg-tests   [diff: +tags]
     ├─ azure:network:NetworkSecurityGroup  nsg-test   [diff: +securityRules,tags]
     ├─ azure:network:VirtualNetwork        vnet-test  [diff: +subnets,tags]

```

**Comment by boillodmanuel** [comment]
Note that `printf 'no\n' | pulumi refresh` does not work (due to non-interactive mode I presume)

**Comment by boillodmanuel** [comment]
Yesterday I got another issue related to that github issue.

We had to do a `pulumi refresh` **on some targets only** (due to a terraform provider bug on one type of resource that prevents us to do a full refresh).
But we were **unable to preview the pulumi refresh** without doing the refresh (in order to get the resource names to refresh) because the interactive mode only fit the terminal size, and we didn't find a way to redirect refresh preview in a file.

So adding a `--preview` or `--non-interactive --no` could solve this issue.

**Comment by boillodmanuel** [comment]
I looked a bit at the source code, but it seems that it's too deep for me (I stopped at [backend/stack.go](https://github.com/pulumi/pulumi/blob/master/pkg/backend/stack.go)).

But I feel that a great option to get a preview of the pulumi refresh (and solve the issue I mentioned in my previous comment) would be to add a dedicated command like `preview-refresh` or `refresh-preview` which copies the `pulumi preview` and `pulumi up` behaviour.

Otherwise, I would be happy to help (if I can 😉)

**Comment by RobbieMcKinstry** [comment]
Since `--dry` is supported for `up`, it sounds like adding:

1. `pulumi import --dry`
2. `pulumi destroy --dry`(surprised this isn't already implemented)
3. `pulumi refresh --dry` 
...would be sufficient to close this issue. Is that correct?
