### ISSUE TITLE
Pulumi CLI on Windows considerably slower since v3.124.0

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#16863]
### What happened?

Customer reports that the Windows version of Pulumi CLI is considerably slower since v3.124.0

During a live call I just had with said customer, we tested versions from 3.113.0 to the latest and narrowed it down the `git bisect` way. We ended up on v3.124.0 where the performance got considerably slower.

How much slower: running the plain Windows version and the Linux version (in WSL) of v3.124.0 shows a minimum of 5 times slower on almost all commands:

* pulumi about
* pulumi preview
* pulumi up

### Example

TBD

### Output of `pulumi about`

Pulumi CLI v3.124.0 on Windows

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
https://github.com/pulumi/pulumi/compare/v3.123.0...v3.124.0

Nothing stands out at first glance as being especially problematic there for Windows. If I had to guess I'd say maybe https://github.com/pulumi/pulumi/commit/f251d3142cde6560a964ed3b6fd8b7d78c5045bf because that will get called for About and Preview/Up.

In fact it's highly likely to be that change because that's going to trigger upwards directory walks over and over for large projects. Can you confirm the customer is using NodeJS?

cc @julienp

**Comment by ringods** [comment]
@Frassle yes, this is Pulumi with Azure & Typescript.
