### ISSUE TITLE
Permit single resources in `dependsOn`

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1690]
The `dependsOn` property for a resource currently takes an array. This is great for cases where you want multiple dependencies, but it's very common to just have a single dependency. We can change this to be of type `Resource | Resource[]`, and accept both, very easily.

**Comment by CyrusNajmabadi** [comment]
Note: this is one of those things that can work as long as we can have a good versioning story here.  If we update `@pulumi/pulumi` to support this, a user will need to ensrue that all other packages they're referencing end up pulling in this support as well.  Tagging @ellismg in case there's anything we need to do to make sure that happens.

I'm not sure if this would count as necessitating a major version change.  However, if someone really wants to use it, they need to ensure their entire package change is properly using this.

**Comment by lukehoban** [comment]
It's definitely not a breaking change, but it is true that users don't get to use it until the library they are using directly has updated to take a dependency on the new `@pulumi/pulumi`.  

This is one of the arguments for pulling forward dependencies on `@pulumi/pulumi` rapidly in higher layers instead of just specifying "minimal compatible version".  I suspect we will want to pull version requirements in all our packages forward as part of the next wave of releases.

**Comment by CyrusNajmabadi** [comment]
> It's definitely not a breaking change, but it is true that users don't get to use it until the library they are using directly has updated to take a dependency on the new @pulumi/pulumi.

Yeah.  I'm not sure what to call that.  it would certainly seem 'strange' though.  The API says you can use it, but if you aren't properly pulling things forward, you end up just failing at runtime.
