### ISSUE TITLE
Pulumi CLI not returning error code when running in container

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#17256]
### What happened?

Running CLI in a container. When the container is stopped mid-update, the CLI just stops and does not return any sort of error code

### Example

Repo here: https://github.com/pierskarsenbarg/container-stop-issue 

Instructions in readme. Can get on a call to go through if necessary.

### Output of `pulumi about`

(From running `pulumi about` in the container):

```
CLI
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  kubernetes  4.18.0
language  nodejs      unknown

Host
OS       debian
Version  12.7
Arch     aarch64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.17.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, team-ce, gitlab-test-piers, piers-gh-test, demo
Token type     personal

Dependencies:
NAME                VERSION
@types/node         18.19.50
typescript          5.6.2
@pulumi/kubernetes  4.18.0
@pulumi/pulumi      3.132.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment]
A big question here is, what's the expected behavior of the autoapi? I think we'd expect the `UpdateResult` to be `failed` ([ref](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/types/automation.UpdateResult.html)).  Ideally

In Kubernetes (and as described [here](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace)), the container receives an advisory SIGTERM, then Kubernetes waits until the pod's termination grace period has passed. I believe the ideal behavior is for Pulumi to behave as though CTRL-C was pressed; gracefully cancel further steps, save state, unlock the stack.

Relatedly: Pulumi Kubernetes Operator v2 doesn't use the Pulumi CLI as the entrypoint, it uses an agent that uses the autoapi (Go SDK) to run Pulumi deployment operation. The agent receives the SIGTERM signal and cancels the ongoing operation (see https://github.com/pulumi/pulumi/pull/16783).

**Comment by julienp** [comment]
You could do something similar to how @EronWright made Automation API turn a cancellation into a SIGINT for the CLI, by using a bash wrapper in the container.

When we receive a SIGTERM, as you get from `docker stop`, we forward that as a `SIGINT` to the CLI:

```bash
#!/bin/bash
PID=""
function cancel_pulumi() {
    if [ -n "$PID" ]; then
        echo "Sending SIGINT to pulumi process $PID"
        kill -SIGINT $PID
    fi
}

trap cancel_pulumi SIGTERM
pulumi up -f -s dev &
PID=$!
echo "Pulumi started with PID $PID"
wait $PID
EXIT_CODE=$?
sleep 3 # This gives us time to see the output logged by the background pulumi process before the script exits
echo "Pulumi finished with exit code $EXIT_CODE"
```
