### ISSUE TITLE
Running pulumi install in a pnpm monorepo

### ISSUE THREAD

**Issue by seangal2** [pulumi/pulumi#17292]
Hi,

I was about to try out pulumi in our existing project, but I encounter issues when trying to install it. 
Our project is a monorepo, and I want to create the pulumi project in a sub-diectory. 
The folder structure is:
```
root
|-- node_modules/
|-- package.json
|-- ops/
     |-- pulumi/
          |-- Pulumi.yaml 
          |-- package.json
          |-- (etc...)
```
When running either `pulumi install` from the subdir or `pulumi -C ops/pulumi install` I get the error:
```
❯ pnpm pulumi -C ops/pulumi install
Installing dependencies...

Scope: all 6 workspace projects
../../webapp postinstall$ 
│ 
│ 
│ 
│ 
└─ Done in 1.4s
Done in 2.5s
error: installing dependencies: pnpm install reported success, but node_modules directory is missing
```

The issue comes from the fact that pnpm in a monorepo setup installs all the dependencies in a centralized folder (the root node_modules), and then the pulumi CLI doesn't find it correctly. 
I looked for options/env vars to specify the `node_modules` path and couldn't find any.

Looking at the code, it looks like this issue is known: https://github.com/pulumi/pulumi/blob/04771f8b5f34b8acaa293f48c3ce8d88ae5c1f84/sdk/nodejs/npm/manager.go#L85

I would like to know if there are plans to support the pnpm monorepo setup I described, or if there is a workaround for now.

**Comment by justinvp** [comment]
Hi @seangal2, I tried to reproduce the issue you're seeing but it's working for me with v3.133.0 of the Pulumi CLI.

What version of the Pulumi CLI are you using? Also, what does your `Pulumi.yaml` look like, does it specify `pnpm` for the `packagemanager` runtime option?

```yaml
name: pnpmproject
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
description: Test project
```

**Comment by julienp** [comment]
Even though pnpm puts the actual files in the monorepo root `node_modules` folders, it should still create a `node_modules` next to each `package.json` that's part of the monorepo and symlink packages to the root.

Do you have a [pnpm-workspace.yaml](https://pnpm.io/pnpm-workspace_yaml) file that includes your pulumi project?

**Comment by julienp** [comment]
I was able to reproduce this by using a `main` property in `Pulumi.yaml`, and not having a `ppm-workspace.yaml`.

Installation succeeds when a `ppm-workspace.yaml` is present, because we detect this file and run the installation relative to its location (aka the root directory of the monorepo). When there is no workspace configuration, and we are using Pulumi's `main` property, the installation runs relative to the folder specified by it (aka program directory). If the package.json file is next to `Pulumi.yaml` (aka project directory), these directories are different, and we get the failure to find `<project_dir>/node_modules` because we look for `<program_dir>/node_modules`.
