### ISSUE TITLE
computeCodePaths should not hard-fail on malformed semver in package version

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1750]
Currently, using `"version": "0.1"` in a package.json file causes our creation of ZIPs for upload to Lambda/Functions to fail due to it technically being an invalid semver (should be `"0.0.1"`).  This is due to a dependency we use to parse the package json file.  We should find some way to be more lenient here, since we don't actually use this information - and many/most other things in the Node.js ecosystem will work fine without this being correct (including running the Pulumi deployment program in the first place).

**Comment by CyrusNajmabadi** [comment]
Tiny notes from looking into: 
https://github.com/npm/read-package-json/blob/latest/read-json.js which calls:
https://github.com/npm/normalize-package-data/blob/master/lib/normalize.js which calls into:
https://github.com/npm/normalize-package-data/blob/master/lib/fixer.js

Effectively, as far as i can tell, there are some fallback paths here so that people can write stuff like:

`dependencies: "..."`

i.e. a string, instead of an object.  In that case, the string will be split on whitespace/command to get a list of strings:

https://github.com/npm/normalize-package-data/blob/df8ea05b8cd38531e8b70ac7906f420344f55bab/lib/fixer.js#L384 

`dependencies: [...]` is also supported (and is waht the above string codepath calls into).

There an array of strings is allowed.  Those string are then split, and the pairs of each string become a key/value dependency here:

https://github.com/npm/normalize-package-data/blob/df8ea05b8cd38531e8b70ac7906f420344f55bab/lib/fixer.js#L392-L397

---

Now: if we ignore htat funky logic, hte only other special thing this library does is to call addOptionalDepsToDeps: 

https://github.com/npm/normalize-package-data/blob/df8ea05b8cd38531e8b70ac7906f420344f55bab/lib/fixer.js#L371-L379

This then allows for a `optionalDependencies: { ... }` section which is merged into the normal `dependencies` section.

---

This is the only special logic that happens.  Otherwise, we can effectively just json parse the package.json file, then extract the .dependencies section, and just read its property names.
