### ISSUE TITLE
Do not upload the checkpoint to Pulumi when there are no changes

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1769]
When processing a same operation, it appears we still upload the checkpoint to Pulumi, even though there is no change.  I believe in this cases we should not be doing this.  For no-op updates on stacks with many resources, this adds a substantial amount of wall-clock time for the update, and there is no observable output from the CLI.

**Comment by swgillespie** [comment]
I think there are a couple places in `SnapshotManager` that we can now be a little more intelligent about when we send updates to the service. In addition to same steps, we should also be able to avoid sending a snapshot to a service when

1. We do a `Replace` step (that never mutates the snapshot)
2. We do a `RegisterResourceOutputs` that doesn't change anything

**Comment by pgavlin** [comment]
This is less straightforward than I thought.

Specifically, we can only elide writes to the snapshot on same steps if the dependencies for a resource have not changed. For example, consider the following case:

Resources are described as `ID(dependencies)`.
Base order: `A(nil), B(A)`
Diff order: `B(nil), A(B)`

The base snapshot will have the following contents in order: `[A, B]`.
Assuming that the inputs to B did not change in the diff program, the snapshot manager will see the following events:
`SameStep(B), SameStep(A)`
If the snapshot is not written when the same steps are processed and the program terminates without ever writing the snapshot (e.g. because it crashes), the order of these resources in the snapshot will be incorrect, as the snapshot will retain the original ordering.
