### ISSUE TITLE
Custom Resource Definition (CRD's) supported?

### ISSUE THREAD

**Issue by jensneuse** [pulumi/pulumi#1978]
How to use pulumi .ts e.g. with istio gateway/virtualservice or cert-manager clusterissuer/certificate? Is there a "type safe" way to create such resources?

**Comment by hausdorff** [comment]
@jensneuse There is not currently a way to use CRDs in a typesafe way. At some point we will probably allow users to generate type definitions from CRD schemas, but right now even this is only a partial solution, because most CRDs actually do not have schemas. I've opened [a bug](https://github.com/pulumi/pulumi-kubernetes/issues/219) to track this work.

The non-typesafe way to do it is to use `apiextensions.CustomResource`. (BTW, I have [a bug open](https://github.com/pulumi/pulumi-kubernetes/issues/220) on this class, which I will fix tonight, that requires you have to cast the object to `<any>`. But this should otherwise work.)

Lastly, let's close this in favor of https://github.com/pulumi/pulumi-kubernetes/issues/219, since placing this issue in that repository will make it easier to track. :)
