### ISSUE TITLE
`pulumi stack import` updates the deployment version

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1982]
This is not necessarily desired, especially when carefully migrating a 0.14 checkpoint up to a 0.15 one.

**Comment by lukehoban** [comment]
What can go wrong due to this exactly?

**Comment by ellismg** [comment]
@pgavlin Can you think of something awful that could go wrong here?  I think that this is no different than saying "a no-op update" updates the deployment version.  I can sort of imagine cases where this behavior is surprising (e.g. I do something like `pulumi stack export | pulumi stack import` to remove all the pending operations from my stack and I've upgraded my CLI and that version uses a newer checkpoint format and I'm working with others so now they have to upgrade their stacks as well, but it feels like this is something we should just say is by design?

Regardless - I don't think we really need to do work here for Q3, and I sort of wonder if we should be doing any work at all...

**Comment by leezen** [comment]
Closing out old issues
