### ISSUE TITLE
Pulumi doesn't run on Alpine Linux

### ISSUE THREAD

**Issue by jeremy-pedersen** [pulumi/pulumi#1986]
Build and run Docker image:
```
FROM node:8.12-alpine

ENV PATH=$PATH:/root/.pulumi/bin

RUN apk update && \
    apk add --no-cache bash curl && \
    curl -fsSL https://get.pulumi.com | sh
```
Run the following commands in the container:
```
/ # pulumi version
sh: pulumi: not found
/ # bash pulumi version
/root/.pulumi/bin/pulumi: /root/.pulumi/bin/pulumi: cannot execute binary file
```

Is it possible to identify and document the dependencies required to run pulumi on Alpine Linux?

Thanks,
Jeremy

**Comment by ellismg** [comment]
Thanks for opening this Jeremy,

We don't test on Alpine today, and if I had to hazard a guess, I would expect the reason it doesn't work out of the box is due to the the fact that we build our binaries on Ubuntu, which is glibc based, and when running on Alpine with musl, things don't work as expected.

I was able to reproduce the behavior you saw using docker on my machine as well.  I'm going to try to get a development environment set up in a container so I can build pulumi from source using the go toolchain from Alpine and see if the binary produced there works.  If so, we can probably start producing alpine binaries as well.  I think we'll have to do a little work on our end to support fetching plugins for glibc based distros vs musl ones, but it should be doable.

If you have the interest, it would be interesting to know if you are able to build the pulumi CLI from source in Alpine (if you have a working go toolchain and `dep` installed, it should be as simple as `dep ensure` followed by `go install github.com/pulumi/pulumi`.  If that works, it at least lets us know that if we were to build on Alpine as well, we'd be able to produce binaries you'd run.

For my own edification, why did you choose Alpine?  Do you use it as your daily driver or are you trying to run `pulumi` inside a container as part of CI or something (and hence you want the small base image that you get from alpine)?

**Comment by jeremy-pedersen** [comment]
Yes, we typically use Alpine-based images in our CI pipelines because of the small footprint.  We're trying pulumi with node:8.12-slim for now, but can build from source on Alpine and let you know how it goes.

**Comment by ellismg** [comment]
> We're trying pulumi with node:8.12-slim for now, but can build from source on Alpine and let you know how it goes.

Awesome! I suspect that if you are able to build `pulumi` on alpine, you'll still have problems getting things to work end to end, right now, because when `pulumi` install's plugins (like the resource providers for aws or azure) it's going to pull down binaries which were compiled for a glibc based distro.  But if the CLI itself works, we can figure out how to deliver the correct binary in the case, and in the interim I can help unblock you if you do need to run end to end in alpine.

**Comment by ellismg** [comment]
FWIW, @jeremy-pedersen, I took the same base image an installed `libc6-compat` from apk and then installed pulumi.  With that additional package, things just worked.  I did some limited testing spinning up and down some AWS resources and everything worked as expected.

So it's possible that could be another workaround.

**Comment by jeremy-pedersen** [comment]
Excellent!  Thank you for investigating!  I'll try this out.

**Comment by jeremy-pedersen** [comment]
Apologies for taking so long to follow up, Matt.  I had some other issues to sort out before I was able to try this.  Pulumi installed from https://get.pulumi.com works great on the `node:8.12-alpine` base image with `libc6-compat` installed.  Thanks again for your help!

**Comment by ellismg** [comment]
Glad to help!  Thanks for trying it out and thanks for using Pulumi!

**Comment by nesl247** [comment]
Is there any plan for this? I see it was closed, but it's still linked to in the Dockerfile.

**Comment by boillodmanuel** [comment]
Hi,

I wrote my own Dockerfile to resolve the same issue and reduced the image size from 1,98Gb to 189Mb \o/:

```Dockerfile
FROM node:8.16-alpine

# Passing --build-arg PULUMI_VERSION=vX.Y.Z will use that version
# of the SDK. Otherwise, we use whatever get.pulumi.com thinks is
# the latest
ARG PULUMI_VERSION=latest

ENV PATH=$PATH:/root/.pulumi/bin

RUN apk update && \
    apk add --no-cache curl libc6-compat && \
    if [ "$PULUMI_VERSION" = "latest" ]; then \
      curl -fsSL https://get.pulumi.com/ | sh; \
    else \
      curl -fsSL https://get.pulumi.com/ | sh -s -- --version $(echo $PULUMI_VERSION | cut -c 2-); \
    fi
```
Build with:
```bash
docker build --build-arg PULUMI_VERSION=v1.3.4 -t pulumi:v1.3.4-node-alpine .
```

Here is image sizes:
```
pulumi                 v1.3.4-node-alpine   7b0c8361f8b3        2 hours ago         189MB
pulumi/pulumi    v1.3.4                          8879e6be4c8e       3 days ago          1.98GB
```
