### ISSUE TITLE
Example showing how to create access policies for developers

### ISSUE THREAD

**Issue by breathe** [pulumi/pulumi#1993]
Pulumi looks very interesting to me — dealing in higher level abstractions makes a lot of sense.

Before I get to far into it though - I’m curious if there are any simple, reliable strategies to manage/scope developer access with multiple pulumi stacks deployed to a single provider account.  To make that question more concrete — is there a way to grant permissions so that developer A can do anything they want with resources managed by stack A and developer B can do anything with resources managed by stack B but neither can do anything with any resources that are not part of a stack to which they have been assigned access ...?

**Comment by joeduffy** [comment]
Great questions. We've thought a lot about this area, so definitely eager to hear your feedback on the current approach. There are two related, but orthogonal, concerns here

1) Pulumi Roles and Access Controls
2) Your Cloud Provider's Identity and Access Management System

For the former, Pulumi RBAC, you are absolutely right that the stack is the granularity at which you can control these things. We have an RBAC system centered around Teams and Organizations, and it is documented at https://pulumi.io/reference/service/roles-and-access-controls.html. This allows you to let certain teams perform certain operations (or not) on certain stacks. For instance, a common use case is granting permissions to update low level security, networking, and clustering stacks to your DevOps team, and restricting your dev team to just deploying applications (containers, Kubernetes resources, etc) on top of that underlying infrastructure.

For the latter, your cloud's IAM, this is something you would need to manage entirely independent of Pulumi. Most teams have their own mechanism for managing IAM, distributing keys, etc., and our goal with Pulumi was not to interfere with this. It does mean, however, that even if you get Pulumi RBAC perfect, a developer could circumvent that by going straight to your cloud provider's SDK, CLI, console, etc. Our goal was to provide a "belts and suspenders" approach, so that both work well together.

Does this help to answer the question? I'd love to hear whether this works for your scenario.

**Comment by breathe** [comment]
Interesting thank you!  So here's the mental model I'm understanding ...:

(1) developer or ci machine invokes pulumi cli -> pulumi computes desired resource state from program -> pulumi computes diff vs infrastructure state as represented by checkpoint state -> pulumi  computes operations needed to bring infrastructure state to application desired state -> pulumi applies RBAC to the operation log to determine if the command should actually execute against the provider -> if so, pulumi uses provider credentials on developer/ci machine to communicate with provider.

So at the end of the day, to execute the last step, the credentials used to connect to the provider from  the developer/ci machine will need to have an appropriate policy to actually touch all the cloud resource api endpoints associated with the stack.  Can pulumi synthesize an appropriate policy that would allow all stack-scoped operations to occur or would such a policy need to be constructed by the developer by hand?

For a little more context -- the motivation for my question comes after the experience I had attempting to use the serverless framework within a large organization which had a preference/requirement that all their operations targeted a single aws organization account ...  The serverless framework design really seems to prefer that each developer works within their own isolated aws account and it was really kind of onerous to arrive at a workflow that made for semi-manageable semi-safe per-developer versions of stacks within the same org account ...  I found it pretty confusing simply identifying the minimal set of permissions needed that also avoided breakage of parts of the framework features (I think the surface area for confusion with the serverless framework was inherently larger than pulumi because of the seemingly non-principled way that some operations in the ecosystem were delegated to cloudformation and some were performed via direct provider api calls ) ...  In our organization, the ops team acted as ultimate party responsible for all access control policy's in the aws account -- which meant that the ops team was in theory responsible for constructing appropriate policy's to manage each 'applications' access to cloud resource at deploy time and runtime.  In the context of serverless meant that they were attempting to manage an appropriate set of access policies per serverless stack to ensure that each stack deployment couldn't accidentally affect another stack's resources...  The team was overloaded though and the policies required to handle serverless deployment in practice were either under-specified (more broad permissions than were desirable) or over-specified (breakage/debugging difficulty/extra overhead when adding features dependent on new resources because of insuficient permission somewhere).

Would synthesizing appropriate provider policies based on RBAC be possible with pulumi?

**Comment by lukehoban** [comment]
> Can pulumi synthesize an appropriate policy that would allow all and only stack-scoped operations to occur or would such a policy need to be constructed by the developer by hand?

Definitely understand the scenario you have in mind here.  This is something we would love to enable.  It's not deeply easy to do this - as AWS does not provide any clear way to synthesize this list directly.  Most attempts I've seen to do this sort of thing work by doing a deployment with broad rights, and recording what permissions were needed - and then generating a restricted role based on just what was  seen.  But every time a new kind of resource is used - additional permissions will likely be needed.

We're eager to offer any additional help we can here - if you have thoughts on specific things we could do to help - let us know!

**Comment by lukehoban** [comment]
This is a great area to explore in the future - but likely something that users will need to manage directly given the state of the cloud provider permissions models in the near term.

**Comment by leezen** [comment]
Closing out old issues
