### ISSUE TITLE
inappropriate ioctl for device when running on Debian

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi#2017]
I ran this on CircleCI and received the below error.
```
$ pulumi stack output --stack ComputeSoftware/datomic-prod
error: inappropriate ioctl for device
```

I am using the image `circleci/clojure:tools-deps-1.9.0.381` which is based on Debian GNU/Linux 9. Running the command in my local terminal or via the CircleCI SSH terminal pops open the interactive login.

**Comment by joeduffy** [comment]
I've been running into this just recently when attempting to pop the browser for login in a Docker container. We've been discussing what to do, I'm sure @ellismg has some thoughts.

Note that we now respect `--non-interactive`, which will prevent popping the dialog, and require you to supply a `PULUMI_ACCESS_TOKEN`.

**Comment by ellismg** [comment]
The `inappropriate ioctl for device` message is due to us trying to disable local echo in cases where standard in is not a terminal (the most common code path where we try to disable echo is `pulumi login` when prompting for an access token, or any operation that causes `pulumi` to run, such as the stack outputs call in the above).

While Joe fixed the specific case around logging in where not connected to a terminal, I've opened https://github.com/pulumi/pulumi/pull/2265 to address the core issue by not trying to disable echo when not connected to a terminal.
