### ISSUE TITLE
Change stack identity from <org>/<stackname> to <org>/<project>/<stackname>

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#2039]
Conceptually a stack is more or less an “instance” / “deployment” of a project. 
Or in other words, each stack conceptually belongs to exactly 1 project. 
It is safe to assume that most organizations will have more than 1 project. 
However for some reason the pulumi cloud backend requires each stack name to be unique across the entire organization, not just within the project the stack is contained. In other words the stack identity is currently `<org>/<stackname>` instead of `<org>/<project>/<stackname>` which is a "gotcha" to many users. 
In practice that means if I want to use common stack names like: `staging` or `prod` I always have to prefix or suffix the stack name with the name of the project in which it is contained, which seems pretty redundant and actually leads to really verbose stack names. It would be better if stack names are only required to be unique within a project.

To depict this via an example:
Ideally It’d like to have names like this:
- project: my-fancy-project
   - stack: staging
   - stack: prod

However because of the limitations above I have to use names like this:
- project: my-fancy-project
   - stack: my-fancy-project-staging
   - stack: my-fancy-project-prod

The pulumi CLI also shows in the preview an odd and quite long looking name like this:

  TYPE                                             NAME
  pulumi:pulumi:Stack                    my-fancy-project-my-fancy-project-staging

A really concrete problem with the long stack names is that the `name` column of the pulumi:pulumi:Stack resource in the `pulumi preview` uses up so much space that on a notebook there’s barely any space left for the `Info` column and I’m often not able to decypher what a particular error message in the Info column actually says.

Multiple users shared their frustration and/or confusion with the current stack identity behaviour:
https://pulumi-community.slack.com/archives/C84L4E3N1/p1537128934000100
https://pulumi-community.slack.com/archives/C84L4E3N1/p1539026546000100?thread_ts=1539019478.000100&cid=C84L4E3N1

**Comment by lukehoban** [comment]
Re: this part:

> A really concrete problem with the long stack names is that the name column of the pulumi:pulumi:Stack resource in the pulumi preview uses up so much space that on a notebook there’s barely any space left for the Info column and I’m often not able to decypher what a particular error message in the Info column actually says.

See also https://github.com/pulumi/pulumi/issues/1417.  We could, and had planned to, fix this part separately from making a larger change to project/stack naming structure.  In fact, interestingly, this specific issue is actually caused by the fact that we used to have an `<org>/<project>/<stack>` structure, and so presented both the project name and stack name in this context.  When we moved to `<org>/<stack>` naming, we didn't fix this up to use only the stack name. If we instead decide to change back to `<org>/<project>/<stack>` naming, we would likely want to not fix #1417.

**Comment by rawkode** [comment]
I'd vote for this over #1417 :+1:

**Comment by geekflyer** [comment]
@lukehoban I'm actually curious what were the reasons to change the stack identity from `<org>/<project>/<stack>` to `<org>/<stack>` previously. Is there an issue which provides context or could you provide some info why this seemed useful at the time? Just curious

**Comment by ellismg** [comment]
>  Is there an issue which provides context or could you provide some info why this seemed useful at the time? Just curious.

@lukehoban simplifies a little here.  The original identity model was actually much more closely tied to GitHub (or an SCM in general) and included the repository, so the full identity of a stack was `<org>/<repo>/<project>/<stack>`.  To create a "repository" you would the since removed `pulumi init` command, which would try to figure out your repository root (by looking for a .git folder) and then it created a `.pulumi` folder in your repository root with some metadata.  When using the local backend, checkpoints where also stored in this folder, as well as bookkeeping data about the currently selected stack, and the like.

This ended up being pretty confusing and also required us to track this extra piece of metadata (the "repository") around.  There was general confusion on the best practices of checking in the `.pulumi` folder.  We did it in some places, but not in others, opting to just run `pulumi init` anytime you cloned a repository.

We were unhappy with the existing model and when designing a new one one, we wanted to try to radically simplify the identity of a stack.  We looked at how our closed beta users were using the product, and at the time they were naturally including the project name in the stack name itself.  So we decided to throw all the hierarchy out.  Organizations now just had a bunch of stacks, which had to have unique names.  Metadata like `project` (which we always have by virtue of it being in the Pulumi.yaml file) and repository (which we can sometimes detect when your project is in a git repository and it has an origin we understand) are added as tags, which we use for filtering and grouping operations later.

So we never actually tried just `<org>/<project>/<stack>`.  We actually discussed it at the time but thought: "Well, we got kinda burned the last time we tried to put too much hierarchy here, so lets just put in the model we can think of and see how that works".

FWIW, I think that `<org>/<project>/<stack>` would be an improvement as well.  It does make renaming the project (i.e. the `name` property in Pulumi.yaml) even trickier than it is today, so we'd have to think through how we envision that working).  We'd also need to carefully think through how we'd roll this change out, given we'd want to support older clients in some form, but I think it is worth exploration.

**Comment by ellismg** [comment]
FWIW, https://github.com/pulumi/pulumi/pull/1226 is the PR where we moved from the old model to the new one.

**Comment by mazamats** [comment]
I'm planning to use a stack per Pull Request and per environment in the future. Having the project prefix removed would be great.

Especially if you load secure config values from an external provider (e.g. vault endpoint with some npm module).

This is my current solution

```javascript
environment = pulumi.getStack().split("-").pop();
```

**Comment by joeduffy** [comment]
@ellismg Let's keep this in M19. This is a fundamental change that it appears we have near-universal consensus on making, so I'd love to get a head start on figuring this out so we can plan the rollout.

**Comment by ellismg** [comment]
Per our in person discussion, we'll try to come up with a credible plan during this milestone that we can execute on next milestone, but actually pushing the change through is likely to be a large amount of work, and probably doesn't fit given everything else way to to be doing now.  Hard as it is to say that.
