### ISSUE TITLE
Modernize `computed<T>` terminology to outputs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2093]
We still call output properties that show up in diffs by their legacy name, `computed<T>`. I was demoing to someone today and this caused confusion, because I was in the middle of describing how outputs work. We should probably adopt consistent terminology (and also consider printing information about dependencies, etc).

**Comment by CyrusNajmabadi** [comment]
Definitely agree on calling it an output.  Printing dependencies is trickier simply because of the noise (IMO).  i.e. what's the right thing to even show a person?  The dependencies are resources, so we could show their URNs... or some portion of them.  But that's still likely a huge stirng to show someone.  We could do something like:

```
foo: Output<string> computed from:
      full_resource1,
      full_resource2,
      etc.
```

Or maybe we trim down the info about the resource to just `FinalTypeName:ResourceName` (i.e. `Function:topic_subscription`) and we could then show:

```foo: Output<string> computed from: Function:topic_subscription, Permission:topic```

This wouldn't have as much information, and it could technically be ambiguous given the shortening.  But it would provide more information than today, and woudl give insight into things.  

Any thoughts @joeduffy ?

**Comment by joeduffy** [comment]
For now, I think just unifying terminology is fine. For advanced dependency printing, just something to keep pondering for the future. It may be more confusing than not to cram too much information into a small space.
