### ISSUE TITLE
Pulumi with proxy RPC errors

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi#2134]
Im having trouble running Pulumi commands with a proxy active and `HTTPS_PROXY` var set. Keep getting `error: failed to load language plugin nodejs: nodejs plugin [/root/.pulumi/bin/pulumi-language-nodejs] did not begin responding to RPC connections`. Been trying various `NO_PROXY` values but no luck.

**Comment by protometa** [comment]
The proxy itself is a socks proxy started with `ssh -N bastion -D 38500` and `export HTTPS_PROXY=socks5://localhost:38500`. I'm basically trying to restrict access to the k8s api for security reasons. It does work as expected with `kubectl`.

**Comment by pgavlin** [comment]
This is interesting. From [the code](https://golang.org/src/vendor/golang_org/x/net/http/httpproxy/proxy.go?s=3306:3336#L183), it looks like a proxy should never be used for localhost. I wonder if this is because we're using ":<port>" as the address to dial when making gRPC connections instead of "localhost:<port>". I'll see if I can repro this locally.

**Comment by pgavlin** [comment]
Confirmed. This is arguably a bug in `httpproxy`; I'll look about filing an issue.
