### ISSUE TITLE
Expose provider resources in Go

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2149]

**Comment by DuskEagle** [comment]
Until this is implemented, how do we target multiple AWS regions? Do we need to create a separate stack for each region?

**Comment by joeduffy** [comment]
@DuskEagle It turns out this is already designed and half implemented, so I'm going to take a look this week and see what we can do. In the meantime, using a stack per region sounds like a fine workaround.

**Comment by dcaba** [comment]
yep, but that does not help when there are inter-dependencies between resources (creating a service account, granting access to a resource in a different region, and then creating a resource that uses the service account...).. if you can target different regions/accounts/projects from the same stack, you can deal with these scenarios.

**Comment by joeduffy** [comment]
@dcaba Agree 100%. You can accomplish some of this more clumsily with stack exports, but it's definitely not nearly as useful as having support for this. It turns out this is already half implemented -- support is there in the engine, this needs to be projected in the providers -- so we are going to take a look at bumping the priority of this.

**Comment by dcaba** [comment]
Great, is very appreciated! Needing to split very interconnected resources in stacks and several deployments/executions is not ideal, but you are right, you can make it work. Worth to say, because of this and some other gaps in the golang packages, switching to your python api...  In any case, thanks so much for investing your efforts on this project... its very valuable, and it will be great if the golang version is at feature-parity at some point. Keep rocking!!

**Comment by lukehoban** [comment]
I believe this is part of https://github.com/pulumi/pulumi/pull/3506/?

**Comment by jaredallard** [comment]
I'm looking at using this w/ the Go SDK and I'm a bit confused on how we'd utilize the providers now. Would this be passed in where `opts ...ResourceOption` is right now? If so, `Provider` doesn't implement that right now.

Hope you can shed some light on this @pgavlin!

**Comment by pgavlin** [comment]
> It looks like this can be done with pulumi.Provider(RESOURCE.NewProvider()...)

Yep, that's right :)
