### ISSUE TITLE
Port the Datadog Terraform Provider

### ISSUE THREAD

**Issue by mazamats** [pulumi/pulumi#2154]
It would be great if we could setup [DataDog] alerts in Pulumi.

https://github.com/terraform-providers/terraform-provider-datadog

**Comment by ckelner** [comment]
We have the unfortunate case of where our GitHub org name is incorrectly camelcased, but at this point we have some downstream dependencies which are sensitive to a case change and thus will likely never correct this issue. I only mention this because of the "[DataDog]" reference in the issue comment above. Please use "Datadog" vs "DataDog" <3

**Comment by igorshapiro** [comment]
Implemented basic DD provider (based on the TF one): https://github.com/lemonade-hq/pulumi-datadog

**Comment by lukehoban** [comment]
Available at https://github.com/pulumi/pulumi-datadog
