### ISSUE TITLE
pulumi new for Python should create and activate virtual environment

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#2201]
Today, instantiating a Python template using `pulumi new` installs the Pulumi package and dependencies outside of a virtual environment, which is fraught with peril and outside of what users will expect if they intend to use virtual environments. We should consider creating a virtual environment for users when running `pulumi new`.

We should decide whether or not we should push `pipenv` on people or if we should just use `virtualenv` for this. Either way, we should be installing packages into a virtual environment.

**Comment by lukehoban** [comment]
I think we'll need two things here:
1. Short term - make sure that `pulumi new` works  for Python.  That may mean skipping auto-`update` for Python templates and printing out instructions for what to do manually.
2. Make end-to-end smooth but automatically creating virtualenv and installing dependencies so that we can go all the way to `update` succesfully.

**Comment by swgillespie** [comment]
Agreed. I will shoot for 1) ASAP.

**Comment by swgillespie** [comment]
The M19 component of this bug is done, moving the rest out to M20 (creating and activating a virtual environment).

**Comment by swgillespie** [comment]
Since we're not a shell, I don't believe it's particularly useful to activate a virtual environment from the CLI since a user will have to source it again anyway. If there's any demand for this feature, we can re-open this issue.
