### ISSUE TITLE
Console output on CircleCI very messed up.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2259]
Reported by @kennyjwilli:

![image](https://user-images.githubusercontent.com/4564579/49265151-dd52b900-f405-11e8-9641-c902d075a667.png)

Something is very strange here.  it's clearly the progress spinner.  Instead of properly cycling through `-|/\` it's somehow cycling, but adding those weird checkmarks!

**Comment by ellismg** [comment]
I suspect the issue is related to the fact that the Spinner code used `"\b \b"` to try to erase the old value.

I would not be surprised if this is throwing CircleCI for a loop.

Note that in the past we had used carriage return but that caused issues in Travis where their terminal emulator does not handle carriage return (which appeared to be by design at the time).

**Comment by joeduffy** [comment]
Interestingly, I am seeing similar output in Travis too. E.g.

![image](https://user-images.githubusercontent.com/3953235/50378597-b7769980-05ea-11e9-9254-15a17ecd7093.png)
