### ISSUE TITLE
Allow changes to property values to be ignored

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#2277]
Currently there is no way to mark that we don't care about changed values of a particular property - similar to Terraform's `ignore_changes` block.

Although not required often, there are some use cases which would benefit. For example, enabling DynamoDB AutoScaling alters the read and write capacities at the provider end. Since these are required, and are set to their initial values in the Pulumi program, a refresh will give a diff to reset the values to their initial state.

**Comment by lukehoban** [comment]
From a user who asked about this:

-----


I'm using a wildcard to select the AMI, a la
  ```typescript
const kibanaAmiId = aws.getAmi({
        filters: [{
            name: "name",
            // values: ["amzn-ami-hvm-2018.03.0.20181116-x86_64-ebs"],
            values: ["amzn-ami-hvm-*-x86_64-ebs"],
        }],
        mostRecent: true,
        owners: ["amazon"],
    }).then(ami => ami.imageId);
```
However, if AWS publishes an updated version of the AMI, my existing EC2 instance is rebuilt. What I'd rather do is have Pulumi exclude the AMI as making a choice to destroy and recreate the instance. Is that something easy to do?

----

If we had the feature requested here, it would be possible to mark the `image` property on the EC2 instance as ignored on updates so that only new deployments picked up the new image.

**Comment by joshimhoff** [comment]
@lukehoban is this feature available from the golang SDK? Is it available for all resources? I see this comment from https://github.com/pulumi/pulumi/commit/0550f71a35df8bce291d299f5b4c653968f1fe8c:

> This is a feature of the Pulumi engine, not of the resource providers, so no new logic is needed in providers to support this feature. Instead, the engine simply replaces the values of input properties in the goal state with old inputs for properties marked as ignoreChanges.

**Comment by lukehoban** [comment]
@joshimhoff Not yet.  I've added it to https://github.com/pulumi/pulumi/issues/1614.

**Comment by joshimhoff** [comment]
Thanks!
