### ISSUE TITLE
Enable constraining an update or refresh to a preview result

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2318]
Today we run a `preview` operation prior to an `update` by default.  However, there is not firm guarantee that the update will do only what was presented in the `preview`.  The `preview` output itself is only guaranteed to be a conservative estimate - it may include changes that *might* happen (depending on how updates change other resources), but also may not need to happen.

It would be nice to offer an option to be stricter here, and to constrain an `update` to only be allowed to make changes that were reported during the `preview`.  The `update` would fail if any operation the update needs to preform is not a subset of what the preview reported.

There are several pieces to this:
1. How to serialize out preview results in a way that could be used as a constraint (and potentially as an input to analyzers and other tools that want to be able to report feedback on a preview).
2. Whether there is a sufficiently robust interpretation for "subset of" between an update operation and corresponding element(s) in a serialized preview output.
3. Whether this can be applied to `update`, `refresh`, `import` in a consistent way

**Comment by casey-robertson** [comment]
We have what we think is a bug related to this.  Getting our info together and will open a new issue and/or reach out via Slack about it.

**Comment by clstokes** [comment]
Rather than constraining updates to operations that were present in the preview, the subsequent `update`, `refresh`, `import`, etc. should run what was shown in the preview or nothing at all. A partially executed set of operations will be a poor user experience and lead to more issues trying to reconcile them.

Another behavior related to this is Pulumi picks up code changes on the filesystem in between a preview completing and selecting `yes` at the `Do you want to perform this update?` prompt. This isn't a common scenario but should still be protected against.

**Comment by lukehoban** [comment]
> A partially executed set of operations will be a poor user experience and lead to more issues trying to reconcile them.

It's in general not possible to guarantee this - things can fail for a multitude of reasons during the update - cloud provider outages, invalid user requirements that are only checked by the provider, changes that have been applied to the cloud environment between the preview and the update, etc.

So in general I believe the best that can be done is to say that we will not try to do anything which wasn't already approved by the user after seeing the preview. 

The deeper challenge is that Pulumi doesn't pre-compute the whole set of work prior to doing it - it actually at a deep level iterates between deploying changes and computing more changes that need to be made (possibly as a result of other deployed changes).  This model would have to be severely constrained to be able to know in advance whether any of the proposed changes might be outside what was in the preview.  This would likely be incompatible with much of the Pulumi code that exists today.  It's definitely possible we'll need to go further in this direction, but it would be a much more disruptive change than what's currently proposed here.

> Another behavior related to this is Pulumi picks up code changes on the filesystem in between a preview completing and selecting yes at the Do you want to perform this update? prompt. This isn't a common scenario but should still be protected against.

Indeed - if we had the proposed feature here - I think we would likely make this interactive mode default into the "constrain the update by the preview" behaviour - so that anything that changes on disk (or anywhere else) that causes the deployment to go outside the bounds of the approved preview would fail interactively.

**Comment by gwkunze** [comment]
This is imho an essential feature, CloudFormation has functionality like this with Change Sets and Terraform has the separate `plan` and `apply` steps for example.

For better integrations in CI/CD steps it should be possible to properly separate the planning and execution steps so that you can have (optional) manual approval. So something similar to Terraform plan-files would be ideal.

**Comment by casey-robertson** [comment]
I echo @gwkunze - that part of TF is nice.

**Comment by kennyjwilli** [comment]
The lack of the guard discussed here has caused significant havoc for one of our stacks. While a `pulumi up -y` was running, I switched branches. The branch I switched to had old Pulumi code that was not compatible with the branch I switched from. Because the preview and update are not "locked' together, the update ran using the old code causing many breaking changes, ultimately rendering the stack entirely broken. I believe this is the scenario @clstokes described in https://github.com/pulumi/pulumi/issues/2318#issuecomment-472085198. This behavior was totally unexpected.

**Comment by kennyjwilli** [comment]
A short term fix for this issue could be to detect if the source files have changed between the preview and deploy. If there has been a change, exit with an error.

**Comment by mazamats** [comment]
Something similar to Terraforms `plan/apply` would be ideal, especially for stacks that take a long time to generate previews.

**Comment by travisgroth** [comment]
Possibly easier, and along the lines of what @kennyjwilli mentioned: have a way to pass the output from a `pulumi preview --json` back into `pulumi up` and error out if the changes don't match the preview.  At the end of the day, the desire is to keep unexpected changes from happening during a `pulumi up`.  

Being able to apply the serialized preview would definitely be better to reduce run times, but the safety of `up` is a much more critical feature.

**Comment by Chumper** [comment]
This feature is also what refrains me from introducing pulumi instead of terraform @ work.
Our usecase currently is that during a PR a terraform plan is automatically generated and committed to the PR as well.
Now when the PR (and the terraform plan) is approved, during the merge exactly this plan is automatically applied.

So far I cannot do that with pulumi which is a critical feature as we cannot make sure that only approved changes (terraform plan) are applied in the infrastructure.

Ideally I would want a `pulumi preview --plan` which will generate a file that can be feed to `pulumi up <path-to-plan>`.
This would be a huge improvement for CI, as I have the feeling, that pulumi is more targeted to manual deployments.

**Comment by MrSimonEmms** [comment]
I think of this as an essential requirement for any system that is provisioned using CI/CD pipelines and a blocker to my projects moving from Terraform.

My usecase is similar to @Chumper's - submit a PR and run `terraform plan -out tfplan` to sanity check everything. Once accepted into the `master` branch, the pipeline again runs the same plan command but then offers the option to accept it and run `terraform apply tfplan`. It's important to have the `tfplan` file present in case a previous version tries being run without replanning as it will then reject it.

**Comment by omerlh** [comment]
A bit of a hack, but what I did in the mean time is exporting the plan as json and creating a sha256 of it:
```
      - uses: docker://pulumi/pulumi
        with:
          entrypoint: bash
          args: -c "pulumi login $PULUMI_BACKEND_URL && pulumi plugin install && pulumi preview -s <> --json --logflow | tee preview.json"
        env:
          PULUMI_BACKEND_URL: <>
          PULUMI_CONFIG_PASSPHRASE: 

      - name: checksum upload
        run: |
          cat preview.json | sha256sum > checksum
          gsutil cp checksum gs://<>/checksum-${{ github.event.pull_request.number }}
```

**Comment by imod** [comment]
If this would exist, it could be integrated into something like https://www.runatlantis.io

**Comment by lukehoban** [comment]
> If this would exist, it could be integrated into something like https://www.runatlantis.io

We definitely do expect support here to be integrated with the [Pulumi Console](https://www.pulumi.com/docs/intro/console/) and the [Pulumi GitHub App](https://www.pulumi.com/docs/guides/continuous-delivery/github-app/).  The primitives will also be in place to integrate a serialized version of the preview constraint into other tools that want to support a managed workflow over Pulumi deployments.

**Comment by tedchang77** [comment]
is this still on schedule for delivery in Q4 2021?

**Comment by emiliza** [comment]
@tedchang77 we are actively working on this, and aiming to get a Public Preview out by end Q4 2021 🤞

**Comment by tedchang77** [comment]
I'm assuming this feature will be supported by the automation api?

**Comment by Frassle** [comment]
> I'm assuming this feature will be supported by the automation api?

Yes. A question on that given these work via files would it make sense for these to just be string options to file paths or would you want us to hide the fact that files are being used here and get the automation api to mange the shuffling of the plan json in and out of temp files?

**Comment by edvald** [comment]
Yeah +1 on that. We'll be making an integration for Garden (garden.io) and tbh we don't mind doing the temp file business, we do that sort of thing all the time :) Especially considering that you might need to implement that individually for all the languages you support.

**Comment by mikhailshilkov** [comment]
Update Plans preview has been released in the Pulumi CLI version 3.24.1. We will publish a blog post that describes this feature this week. Thanks everyone for your patience and support!

**Comment by mikhailshilkov** [comment]
Learn more about Update Plans preview in [Announcing the public preview of Update Plans](https://www.pulumi.com/blog/announcing-public-preview-update-plans/)

**Comment by hcharley** [comment]
Has this feature has made its way onto the roadmap of the automation API as a tracked ticket?

If not, no worries--just curious! Thank you everyone that worked on this btw!

cc: @tedchang77, @Frassle 

[Slack thread I started on this question](https://pulumi-community.slack.com/archives/C019YSXN04B/p1649226983891299).

**Comment by EvanBoyle** [comment]
Issue for automation API support: https://github.com/pulumi/pulumi/issues/9385
