### ISSUE TITLE
Accept `-f` as a shorthand for `--skip-preview`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2321]
In the dev inner loop, it is very common to want to skip previews on every `pulumi up` operation.  Currently, this requires `--skip-preview`, which is cumbersome to type.  

It would be nicer to be able to have this common case be just `pulumi up -f`.

We do have `-y` flags for these commands, but that still spends time doing the preview, which is frequently not desired during active development.

None of the operations which accept `--skip-preview` yet have a `-f`, and this feels like the mosts natural interpretation of a "force" flag for these.  There's a question of whether `--skip-preview` should be aliased to `--force` as well, but I don't feel strongly about that.

Operations which should adopt this:
- `up`
- `refresh`
- `destroy`

**Comment by clstokes** [comment]
`-f/--force` is nice for consistency's sake. 

What if we removed `-y/--skip-preview` in favor of `-f/--force`?

**Comment by mikhailshilkov** [comment]
I actually like `skip-preview` as the full name. `force` is usually for accepting overwrites (like we use it in `new` or in `stack rm`), so it *could* be close to `yes` but doesn't sound like skipping the preview.

For the same reason, I wouldn't use `f` as the short name for `skip-preview`, as it might be confusing. `s` is already used for `stack`.

Maybe we could use `S`? Otherwise, `x` (execute), `g` (go), `k` (sKip), `o` (omit). None of them looks great though.
