### ISSUE TITLE
Version providers

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2389]
Today, we always load the latest version available on the machine of the requested resource provider.  However, the resource provider itself can be loaded by packages at:
1. An older version
2. Multiple different versions within the same program execution

This leads to problems if we ever make a (intentional or not) breaking change in a resource provider, as some of the code in the program may only work correctly with the version of the provider it was authored against.  

We will need to find a way to ensure that we load the specific version(s) required by the program/packages.  This will likely also require that we have the ability to load multiple versions of a provider into the same deployment, and to route resource operations from the program to the right versions of the providers.

Work items:
- [x] RPC interfaces for versioning (https://github.com/pulumi/pulumi/pull/2656 and https://github.com/pulumi/pulumi/pull/2642)
- [x] Load specific versions (https://github.com/pulumi/pulumi/pull/2648)
- [ ] Embed versions into SDK codegen in TF and Kubernetes providers

**Comment by lukehoban** [comment]
Marking as P1 in M22 as this is a critical part of being able to adopt breaking changes in providers, which may be coming from upstream for several of our core providers.

**Comment by joeduffy** [comment]
Strange, I thought we already did this. (I definitely recall very technically deep discussions with Sean and/or Pat about how this would work in terms of RPC and checkpoint file changes.) Did we just design, but not implement, it?

**Comment by lukehoban** [comment]
@swgillespie Is there anything more planned for this in M21 after merging https://github.com/pulumi/pulumi/pull/2483?  Could we update this issue with the steps taken so far and thoughts on what we might want to do as additional future investments?  (Or close this out and open new issues?)

**Comment by swgillespie** [comment]
So far, we have taken fhttps://github.com/pulumi/pulumi/pull/2483, which contains a fix for what was the arguably bug-like behavior of plugin loading: the plugin loader would load plugins that were "newer" than the one requested, which posed a problem if the newer plugin was not compatible with the requested version.

For M21, this was deemed sufficiently troublesome that we took a fix for it. Entering M22, the current state of provider versioning is that the CLI will load exactly the version of the plugin requested by a Pulumi program, and will error if that specific plugin is not available. This should alleviate the immediate pain of some incoming breaking changes we are planning to absorb in some downstream providers, so that this issue is no longer "on fire" and blocking the uptake of new providers.

For M22, we should pursue a more holistic solution to the problem. We discussed a number of options that we can take here and, although it's not clear what the *best* solution is at this point, from my perspective the one that seemed most promising was to have Pulumi resources directly inform the engine of the provider version upon resource registration (concretely, provider packages would embed their version into their source code and pass it to the engine during `registerResource`). This would allow the engine to load exactly the provider binary that is known to be compatible with the source code being used.

In the early M22 timeframe, we'll take a look at our options and understand the technical blockers in place. For the above solution, we will at minimum need to augment the `registerResource` contract to provide a version, embed version information in code generated by `tfgen` and the Kubernetes code generator, and allow the engine to multi-instance provider plugins. The latter issue is known to be tricky.

**Comment by lukehoban** [comment]
See https://github.com/pulumi/pulumi-gcp/issues/115 for a case where users hit issues due to having two copies of `@pulumi/gcp` - in particular:

```
@pulumi/gcp@0.18.0
internal-lib@1.0.0
  @pulumi/gcp@0.17.1
```

Handling this correctly will require support for SxS plugins and much of the additional work outlined in https://github.com/pulumi/pulumi/issues/2389#issuecomment-471136113.

**Comment by ncsibra** [comment]
A related issue, which cause serious problems, described here: https://pulumi-community.slack.com/archives/C84L4E3N1/p1554209058169500

**Comment by rosskevin** [comment]
Even after cleaning out plugins, I'm seeing incorrect older gcp plugins reappear as documented here https://github.com/pulumi/pulumi-gcp/issues/124#issuecomment-479651703

It seems I cannot workaround the issue.

**Comment by lukehoban** [comment]
We got the core of the engine versioning implemented in M22.  We still need to wire this through into the various providers in M23.

**Comment by ellismg** [comment]
We have completed the work here.  When we did so, we discovered an issue which is tracked by #2753, but we'll use that that track the completion of this feature.
