### ISSUE TITLE
Add `pulumi stack rename` to allow you to rename a stack

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2402]
Now that we no longer require stack names to be unique across an organization it's natural to want to rename and existing stack you've created, since we previously recommended to use `<project-name>-<unique-identifier>` as a stack name, e.g (`my-great-project-dev`).

Today, renaming a stack is not a straightforward process.  In addition to backend specific changes, the stack's name is also part of the URN of every resource we've created for a stack, so simply changing the name would cause the engine to believe that it needs to replace every resource.

We should add a `pulumi stack rename` command which should handle both backend specific logic to do the rename (e.g. in the service, updating some metadata about a stack name) and handle the updates needed to the existing checkpoint file such that URNs now have the new stack name.

**Comment by chrsmith** [comment]
Just as an FYI, I do not think we can 100% guarantee the operation is safe. So we want to add a warning by default, such as when trying to delete a stack that still has resources. (And `--yes` or `--force` to bypass automatically.)

Doing a find/replace across resource URNs will cover the majority of cases. But because you can get the stack's name at runtime via [pulumi.getStack](https://pulumi.io/reference/pkg/nodejs/@pulumi/pulumi/index.html#getStack), it's possible to have the stack's name bleed into resource _properties_ too. (And applying the same find/replace could lead to false-positives for a generic stack name.)

In practice I don't think this is going to be a problem, but I can imagine situations where renaming a stack could lead to trouble.

Alternatively, we may want to have the `rename` as a special kind of update. Where the command first previews the changes that would take place if the rename were to be made. That would allow you to see if there were any unexpected or problematic infrastructure changes, before proceeding.

**Comment by lukehoban** [comment]
> But because you can get the stack's name at runtime via pulumi.getStack, it's possible to have the stack's name bleed into resource properties too.

Actually the common case is even worse - `pulumi.getStack()` is frequently used as part of how the "name" of resources is generated, which means every resource would change identity and get recreated on the next update.

> Alternatively, we may want to have the rename as a special kind of update. 

This is an interesting idea...

**Comment by lukehoban** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/2561.

**Comment by 4c74356b41** [comment]
wait-wait, so I can create stacks with the same name. how does that work? how would i differentiate between those?

**Comment by lukehoban** [comment]
> wait-wait, so I can create stacks with the same name. how does that work? how would i differentiate between those?

You cannot create two stacks with the same fully qualified name.  You can have two stacks named, e.g. `dev`, in different projects and/or organizations.  

What specific comment here led you to think there was a potential concern here?

**Comment by 4c74356b41** [comment]
i was just wondering how it works, thats it ;)
