### ISSUE TITLE
Feature-Request: project-wide secrets

### ISSUE THREAD

**Issue by dbilleci-lightstream** [pulumi/pulumi#2445]
I ran into a situation where I have a bit of code that creates an Azure Kubernetes cluster.  For each of these clusters, I would like to use the same service principal client ID and secret.  I plan to launch 3-4 of these clusters under different environments such as QA, Test, Stage, Prod etc.

It seems like a nice feature to add config variables and secrets to the project, which can be read by all stacks to keep credentials DRY rather than having to update them for each stack if needed.

Thoughts?

**Comment by ellismg** [comment]
> Thoughts?

We actually did have this in the past, but removed it because we were not 100% sure it was needed and we were trying to simplify our story.

The way the old model worked is that you could set configuration values in `Pulumi.yaml` and then override them in `Pulumi.<stack-name>.yaml`.  At the time, however, we didn't support secrets applied to a project, they had to be set per stack (because they were encrypted with a per stack key, and we had no notion of a project key).

This is probably a reasonable thing to add back, and https://github.com/pulumi/pulumi/issues/2307 is another instance where we've wanted this.  I do think that if we do this, we do need to support project wide secrets unlike under our older model.

**Comment by casey-robertson** [comment]
we have some use cases for this as well.  Our example we have 3 stacks:

1.  IAM config
2. K8s clusters
3.  Everything that rides on top of K8s - everything in here takes a kubeconfig

We want to automate certmanager for certs.  I'd like to create the service account in my IAM stack, save/export it as a stack secret and then allow the #3 stack to consume that .json.  K8s pods need to mount that secret.  Right now we are forced to do the export as a stack export that's in plain-text in the console and pass it up the chain.  This is in lieu of coming up with our own encrypt/decrypt process.

**Comment by pbzdyl** [comment]
@casey-robertson I would suggest the following approach to your use case:

## In IAM stack
Setup service account in IAM stack and also setup [service account IAM member](https://pulumi.io/reference/pkg/nodejs/@pulumi/gcp/serviceAccount/#IAMMember) with the identity that will run pulumi updates (e.g. individual users or groups or service account) in stack no. 3 so that it gets `roles/iam.serviceAccountKeyAdmin` role for that service account.

## In stack #3:
Create [service account key resource](https://pulumi.io/reference/pkg/nodejs/@pulumi/gcp/serviceAccount/#Key) and then use its [`privateKey`](https://pulumi.io/reference/pkg/nodejs/@pulumi/gcp/serviceAccount/#Key-privateKey) output as and input for your secret entry.

This way you don't need to pass the key itself via stack outputs - you can just create it directly in the stack that needs it and just need to make sure that the GCP identity that will work with pulumi updates in that stack has proper permissions for the service account.

**Comment by davedittrich** [comment]
There is a mechanism for doing this provided by the python_secrets program. It provides a Python class and command line interface that supports environment variable exporting and Jinja templating. I'm currently learning how to use Pulumi to instantiate AWS EC2 instances that will have shared secrets as described in this initial issue.

See:
https://github.com/davedittrich/python_secrets
https://python-secrets.readthedocs.io/en/latest/
https://staff.washington.edu/dittrich/talks/secretsmgmt-toorcon2018.pdf

**Comment by lukehoban** [comment]
This is part of the "hierarchical config" feature being tracked in https://github.com/pulumi/pulumi/issues/2307.  Since that has a lot of upvotes and tracks the broader feature we are most likely to implement to address this need - I'll close this one out and we can continue to track the scenario there
