### ISSUE TITLE
Prevent update lease renewal process from ever stopping while an update is still in progress

### ISSUE THREAD

**Issue by adaniline-traderev** [pulumi/pulumi#2461]
Hi,
It happed few times to me on several different AWS stacks:

Was creating EKS cluster first time, and adding RDS instances second time:

post-step event returned an error: failed to save snapshot: [404] Not Found

error: post-step event returned an error: failed to save snapshot: [404] Not Found: Update '1ac5fad4-38d6-465e-9b21-742c277e252a' not found

```
    Type                             Name                 Status                  Info
     pulumi:pulumi:Stack              rds-test                                     
 >-  ├─ pulumi:pulumi:StackReference  networkStack         read                    
 >-  ├─ pulumi:pulumi:StackReference  eksStack             read                    
 +   ├─ aws:rds:ClusterInstance       cluster_instances-0  created                 
 +   └─ aws:rds:ClusterInstance       cluster_instances-1  **creating failed**     1 error
```

**Comment by adaniline-traderev** [comment]
The other issue, if I follow the steps in the troubleshooting guide for interrupted update - cancel the update, export / import to remove the creating operation, and do refresh, it does not pick up cluster_instances-1, which was actually created in AWS.
I wish there would be some way to refresh the pending creating operation with the existing AWS resource

**Comment by chrsmith** [comment]
Hello @adaniline-traderev , I'm one of the Pulumi engineers who works on the Service-side of things. Thank you for including the error message. From the update ID I could find the relevant set of requests related to your update, and was able to identify what the root problem was.

I was able to identify the problem on our end. For some reason, the background process `pulumi` uses to update the short-lived access token used during the update stopped. So requests made after a certain point started failing due to invalid credentials. (We return 404 instead of 403, to not leak the existence of that particular update to unauthorized clients.)

Hopefully I can figure out the issue and get this resolved, since obviously the failure mode here is pretty bad.

> I wish there would be some way to refresh the pending creating operation with the existing AWS resource

That's definitely something that has come up before. I don't have any context for what would be involved in supporting that type of scenario, but it is on our general radar.

Anyways, sorry for the trouble.

**Comment by chrsmith** [comment]
Closing this out and moving it to another repo. After looking into it, the best way to fix this is to just have the Pulumi Service return a more useful error message than "404 not found".

The core problem is that if the update's lease token has expired -- e.g. if your computer went to sleep for X minutes in the middle of an update -- there is no way to renew it. And arguably we shouldn't. Since the presence of a "live" lease token is essentially the way to communicate that a Pulumi update is in-progress and still ongoing. So recreating a new lease token, is akin to starting an entirely new update for the stack.
