### ISSUE TITLE
embed pulumi in my  program

### ISSUE THREAD

**Issue by foxundermoon** [pulumi/pulumi#2506]
how to manage pulumi resource  and lifecycle by  real language? 
actually not by a command such as `pulumi up`.

`main.js`

```js

import * as pulumi from "pulumi";

function main(){
  if(...){
    pulumi.Up('some stack');
  }else{
    pulumi.Up('other stack');
  }
}

main();

```

then
`node  main.js`

**Comment by forestjohnsonpeoplenet** [comment]
I tried to do this and quickly learned that no one has ever done it, and it would probably be very hard due to the way the pulumi CLI is written. I went into their slack channel to ask about it and one thing that they mentioned was, they have a `--json` flag on the cli which would facilitate the automation of pulumi commands since at very least you wouldn't have to parse the CLI output text

**Comment by lukehoban** [comment]
This is closely related to https://github.com/pulumi/pulumi/issues/2287 which is superficially about testing, but boils down to the same requirement to drive the deployment lifecycle via code within a program in the source language.

**Comment by Place1** [comment]
This would be a really useful feature. My company has a use-case for this, we'd really like to be able to build out a CLI that could be packaged as a single binary (perhaps using pkg/nexe for nodejs or just golang) that is given to dev teams so that they can easily deploy their apps using a standard set of configurations. If this CLI was just an embedded Pulumi program(s) then they could just login to pulumi and start deploying without needing to write anything themselves.

**Comment by mazamats** [comment]
:+1: This would be incredibly useful for running a SaaS.

**Comment by hugbubby** [comment]
The lack of support for programmatically making pulumi deployments is the reason I'm going to be forced to choose Terraform. It's a damn shame, because I would put up with a lot of nonsense to be able to maintain the unusual architecture I have from my existing codebase.

**Comment by lukehoban** [comment]
> The lack of support for programmatically making pulumi deployments is the reason I'm going to be forced to choose Terraform

Curious - what feature of Terraform are you currently using to drive Terraform deployments programmatically?  Is this via the REST APIs and remote execution?  Or via linking in the Terraform engine to a Go application?  Or something else?

**Comment by mikhailshilkov** [comment]
Let's track this in the single place #3901 which is a bit more detailed
