### ISSUE TITLE
Removing props does not actually remove the rules from AWS secgroups

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi#2675]
In https://github.com/pulumi/pulumi-eks/pull/109/files#diff-0dfaec1e9f3a8568a8e2516febe83a69R120 we must set the `ingress` and `egress` objects to empty arrays `[]` instead of removing the line all-together, as doing so does not actually delete any existing secgroup rules on an existing cluster, for example.

This seems to be a bug in either pulumi/pulumi-aws or pulumi/pulumi but most likely the latter.

See for more info:
- https://github.com/pulumi/pulumi-eks/pull/109#issuecomment-486025767
- https://github.com/pulumi/pulumi-eks/pull/109#issuecomment-486461894

**Comment by lukehoban** [comment]
After reading through upstream Terraform AWS Provider docs/issues, my understanding is that this is by design, and required to allow for rules to be managed both separately and inline.  For example, see https://github.com/terraform-providers/terraform-provider-aws/issues/644.

I believe we'll need to work around the upstream semantics here to create the desired affect.
