### ISSUE TITLE
Better Error Messaging when a Plugin is missing

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi#2677]
Can we have better error messaging when a plugin is missing? Ideally, the error message should include something to this effect: "run this command to get said plugin".

Current output:
```
➜  azure-py-aks (ekrengel/azure-hack) ✗ pulumi up
Previewing update (eck-hackathon):

     Type                       Name                        Plan       Info
 +   pulumi:pulumi:Stack        azure-py-aks-eck-hackathon  create
     └─ pulumi:providers:azure  default                                1 error

Diagnostics:
  pulumi:providers:azure (default):
    error: no resource plugin 'azure' found in the workspace or on your $PATH

``

**Comment by chrsmith** [comment]
+1 to doing some sort of improvement for this error, as it has caused a couple of troubleshooting sessions on the Pulumi Community Slack channel as well.

One situation that can lead to this is if you run `yarn install` _before_ `pulumi` is installed on the machine. So while all of the NPM packages are available, somehow the resource provider plug-ins are not. And so to fix that you would need to run `yarn install` a second time.

**Comment by ellismg** [comment]
We did try to do some work here at one point:

https://github.com/pulumi/pulumi/blob/5c86e6c40aad50e9f1f9aa4e22505bc54d1e7e93/pkg/workspace/plugins.go#L61-L70

My guess is that because we are not yet flowing version information from the language SDKs into the engine on what version of the plugin is needed (which is true for the "default" version, which is most common) we don't generate a nicer error message because we wouldn't know what command to tell the user to run.

I would expect that when https://github.com/pulumi/pulumi/issues/2389 this will be fixed up, as folks adopt the newer language SDKs, since we'll always have a requested version.

**Comment by lukehoban** [comment]
We now auto-acquire plugins on-demand (https://github.com/pulumi/pulumi/pull/2560).  This should make it exceedingly rare to still hit this error message.  

I tried a few variants of the scenario here - and all of them led to just silently acquiring the plugin and working as expected with no error.

If folks are still hitting this error - lets open a new issue with details of a repro since a lot has changed in this area.
