### ISSUE TITLE
Docker build output is confusing in Travis, when the resource has a warning

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2708]
A customer reported an issue where their Travis logs looked like the following:

```
docker:image:Image [redacted]  warning: Error response from daemon: manifest for [redacted]:latest not found
docker:image:Image [redacted]  warning: Error response from daemon: manifest for [redacted]:latest not found
docker:image:Image [redacted]  warning: Error response from daemon: manifest for [redacted]:latest not found
docker:image:Image [redacted]  warning: Error response from daemon: manifest for [redacted]:latest not found
docker:image:Image [redacted]  warning: Error response from daemon: manifest for [redacted]:latest not found
```

Looking at their logs in a bit more detail, I suspect we have an issue when our "interactive" output format is used in Travis like this.  I think our logic wants to show the "most important" diagnostics for a resource so when the initial pull of the "latest" image failed (in this case the customer does not push a tagged latest build), we now taint the resource with this warning message.  Any future docker build output causes a new line to be printed in the output, however, it seems like we just end up re-displaying the existing warning over and over, instead of the normal build messages from docker.

This was using `0.17.4` of the CLI.  I suspect we would be able to reproduce this ourselves with relative ease.

**Comment by tvalenta** [comment]
For us, it's readily reproduced by having `docker login` run early in the process in Travis, because docker returns that warning about configuring a password helper to prevent unencrypted credential storage.

I confirmed that out client is correctly detecting the CI environment under Travis and automatically enabling non-interactive mode. The repeated messages, which seem to occur with some relationship to periodic stderr output from the docker CLI, is always the first line returned by docker, but at the end of an operation I do get the entire set of warnings listed under the `Diagnostics` block:
```
Diagnostics:
  docker:image:Image (bar):
    warning: WARNING! Your password will be stored unencrypted in /home/travis/.docker/config.json.
    Configure a credential helper to remove this warning. See
    https://docs.docker.com/engine/reference/commandline/login/#credentials-store
 
    warning: Error response from daemon: manifest for foo/bar:latest not found
 
```

I recall https://github.com/pulumi/pulumi/pull/1640 had addressed something similar. But you also recall that.
