### ISSUE TITLE
Add command to output information for support

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#2715]
When troubleshooting issues we often need to ask users for additional information. This information typically comes from many different sources - the stack, dependencies, etc.

We should add a command or `pulumi help --support-info` (or similar) argument that gathers all of this information automatically for users to submit when they need help or support. 

Items that should be gathered:
- version info - of cli and plugins used
- OS version
- app dependency info - `package.json`, `requirements.txt`, etc
- stack info - name, resource list, any `pending_operations`, etc.
- log location information (probably not the log data themselves but provide the location in case the user wants to provide them too)
- the backend in use - `app.pulumi.com`, local, s3, etc.

This information should be output to stdout so that users can review and "scrub" information they want to omit before sharing.

**Comment by clstokes** [comment]
Related to https://github.com/pulumi/pulumi/issues/6217

**Comment by zyv** [comment]
I think it would be great to have a built-in scrubber for logs and trace files - the nature of pulumi is such that for non-trivial projects the logs & traces will be by definition full of secrets, passwords and what not, and manual scrubbing is really not an option not only because it's next to impossible to "catch them all", but also because manually edited traced can become easily corrupted. Fake simple reproducer projects are not always possible and/or viable.

In the context of #6197, I have put together a simple scrubber in Python 3.8 which appears to do its job - https://gist.github.com/zyv/2798c886279e6d399d2f9bc0a9abdec5 - I have no idea about pulumi internals, so feedback on what else one could reasonably want to mask is welcome so that folks can use it, until a proper solution is integrated in pulumi... which of course I would prefer as contrasted to maintaining a third-party untrusted scrubber, that might be not up to date with regards to the log messages potentially containing secrets.
