### ISSUE TITLE
SerializeFunction should communicate if a secret output was captured

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2718]
With #2678 we now have the ability to mark `Output<T>` as secrets, such that when they flow into resources they are stored in an encrypted form in the checkpoint.  We also flow this information across `all`s and `apply`'s, to track secrets across your program.

However, the one way a secret can leak today is if it is captured by a lambda, which is then serialized.  For now, the serialized function text has to contain the raw value (in order to build an `Output<T>` at Runtime that has the correct value) but there is no way for SerializeFunction to communicate that it captured a secret value and the program text is typed as `string` so we can not make it an `Output<T>`.  This means if you create a cloud function using `pulumi` and secret output, the value will exist in the contents of the text asset for the function source that is stored as part of the deployment.

We should augment SerializeFunction such that it is able to notice one or more secrets were captured, and communicate that as part of the SeralizedFunction return value.  Higher level code which them passes that to a resource would then be able to wrap that in an secret output.  Alternately, we can deprecate this function and create a new version which types text as `Output<string>` such that the right thing happens.

When we make this change, we should move the dynamic provider and the code in `@pulumi/{aws,azure,gcp}` over to using the new form.

**Comment by joeduffy** [comment]
Can we just have this throw for now?

**Comment by ellismg** [comment]
Sure, that’s easy enough, I think.  I’ll open a PR shortly.

**Comment by lukehoban** [comment]
The current state of this is somewhat problematic - especially now that we are auto-assigning secretness to "sensitive" outputs.

If I get a value from some resource (like a password), and then capture it in a lambda (very common), I now get an error.  That error doesn't tell me which captured variable caused the problem, doesn't include a useful call stack, and doesn't tell me how to work around the limitation.

Worse - there is no real way to workaround this in the API.  The best I could come up with was this:

```
        // HACK: This appears to be the only way to workaround the fact that `redshiftPassword` is
        // now a secret but we cannot capture secrets in lambdas.
        (<any>args.warehouse.redshiftPassword).isSecret = Promise.resolve(false);
```

**Comment by lukehoban** [comment]
We should consider an option here where we just allow secrets to be captured, and have that cause the serialized text to be marked as a secret, so that it is encrypted in the checkpoint.  This would not provide runtime encryption in the cloud provider by default, but would still provide the same level of guarntee that Pulumi makes around secrets everywhere else.  We could still provide opt-in capabilities to do more "magic" in the future (like auto-create SecretsManager Secrets and inject runtime code into a Lambda to read from those secrets before passing values back to the user).

For now though - we could get back to on par with the rest of the Pulumi secrets experience with a much simpler option.

**Comment by lukehoban** [comment]
This issue is currently causing `@pulumi/cloud-azure`'s `Topic` to be broken, as it captures the `defaultPrimaryConnectionString` property of an Azure ServiceBus Namespace into a serialized function.  It appears that at some point, this became a secret, which broke these tests: https://travis-ci.com/github/pulumi/pulumi-cloud/builds/210120008#L2021-L2024.

Of course, it's a good thing that this flagged that this secret was being serialized in plain text in the existing implementation, and we don't want to just override that.  We want to do what was called out in https://github.com/pulumi/pulumi/issues/2718#issuecomment-598568690 and ensure that the whole generated archive is marked as secret if needed.
