### ISSUE TITLE
^C during pulumi up leaks a stack

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2720]
If I hit ^C partway through a `pulumi up` that uses a template, it leaks a stack. We should pick one of: 1) wait to create the stack until we have full information so that it can be "transactional", 2) roll back the creation if we don't complete the operation, or 3) warn the user that a stack is leaked and tell them how to remove it.

```
$ pulumi up https://github.com/joeduffy/pulumi-k8s-runner
project name: (pulumi-k8s-runner) app
project description: (A Pulumi program to deploy dusty deck Kubernetes YAML) An App!
stack name: (dev)
Created stack 'dev'
glob: A glob pattern for the Kubernetes YAML files to deploy.: (*.yaml) ^C
```

**Comment by chrsmith** [comment]
Closing this issue out. @jkisk and I looked into it, and the benefit of fixing this issue doesn't justify the amount of refactoring/wiring needed to fix.

There are two "times" when you could cancel the `pulumi up <template-url>`. (1) When we gather stack/configuration information, before the preview/update. And (2) after the preview/update has started.

In both cases "rollback" type behavior isn't always the right choice, because you can run `pulumi up <template-url>` multiple times. (e.g. to update an existing Pulumi stack with any changes from the template.) So in the case where the stack already exists, we don't want to delete it or run a destroy operation, etc.

And even if we did pass through the "was newly created stack" flag, the code we have today would need a lot of refactoring to cleanly support the "destroy/stack rm" to rollback a half-updated stack. (Because of among other things, needing to pass through myriad command-line options like `--debug`, `--parallel`, etc.)

We can revisit this decision in the future, if we find that these leaked stacks are a nuisance for users. But it seems like a reasonable "won't fix" for the time being.
