### ISSUE TITLE
Default provider instance config is required even if all providers in use are first-class

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#2725]
#1695 introduced the notion of a _first-class provider_ - one which is configured via code. For example, one can write TypeScript like this:

```typescript
import * as aws from "@pulumi/aws";

const firstClassProvider = new aws.Provider("test", {
    region: "us-west-2",
});

new aws.s3.Bucket("bucket", {}, {provider: firstClassProvider});
```

In this particular case, `region` is a required configuration point. When running `pulumi up` with this particular program, the CLI complains of a missing `aws:region` configuration item, but for the _default_ provider, likely because of a call to `config.require` for the `region` variable inside the `config` package here:

https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/config/vars.ts#L34

This is particularly problematic for providers where the config is _usually_ derived from the program itself (e.g. configuring the `mysql` provider from an RDS instance) rather than having sensible defaults, since it requires phantom configuration values.

**Comment by lukehoban** [comment]
Today, we report this error:

```
Diagnostics:
  pulumi:pulumi:Stack (aws2725-dev):
    error: Missing required configuration variable 'aws:region'
        please set a value using the command `pulumi config set aws:region <value>`
```

This gets reported from the JavaScript SDK via an autogenerated call to `config.require` injected into the SDK.  As of the existence of 1st-class providers, this is not correct, as the SDK has no de-facto association with any Pulumi config.  If the default provider is used, it will configure itself using Pulumi config, but if an explicit provider is used, it will configure itself via arguments.

If we remove that `config.require` call, a missing required config will still fail the deployment, but with a different error:

```
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: 1 error occurred:
        * missing required configuration key "aws:region": The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
    Set a value using the command `pulumi config set aws:region <value>`.
```

This error is generated from the engine instead, based on a built-for purpose contract with the provider RPC interface.  It is better than the other error for at least three reasons:
1. It includes more explicit information about what is wrong, and what to do about it.  It's actually very helpful.
2. This error reporting path will aggregate up multiple missing required config variables into one response.
3. It is associated with an actual resource, not the `Stack` resource.
4. It is implemented in the engine in one place, instead of code-generated into every individual resource provider.

I cannot come up with any case where it would be better to force this error to be generated via the SDK (as we do today).  We should remove the SDK error reporting, and have the generated SDK code in `vars.ts` just flow config through into the SDK `config` module (if it exists).
