### ISSUE TITLE
Support specifying script to run

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [pulumi/pulumi#2883]
For example if I have one stack, but two different scripts `index1.js`, `index2.js` .
Now to run specific script I should change `package.json` main section. 

It would be useful if we could run specific script with command 'pulumi up/destroy script'. 
Or maybe better, stack should know which script should be ran. So we will have 2 same stacks but they can run different scripts. 

Something like this:  
```
Pulumi.script1.yaml -> index1.js
Pulumi.script2.yaml -> index2.js
```
Thoughts?

**Comment by ellismg** [comment]
Trying to understand the use case here.  Under the current model, we would say you need to have two separate projects - each with their own `Pulumi.yaml` file that had different `index.js`.

I'm wondering what your use case looks like where you have two separate `index1.js` and `index2.js` files.  Are they related to each other somehow?  Do they share a bunch of code in the rest of your project somehow?

If you created a third stack, would you expect to also create an `index3.js` file?

**Comment by Ilchuk-Mihail** [comment]
@ellismg  I faced this in that case if I have one script just simple deployment Fargate service, and second more complicated script to create hosted zone, make alias, issue certificate, setup nlb etc. 

I mean I don't need to run this long running script every time, where I can run simple one and test something. 
Another case: I can have small scripts , like template to issue certificate, setup domain etc, and I can specify which script to run, test it etc.  (Maybe it can be deployed layer by layer ect. )

Maybe it can be considering like dev, prod version, or just like different versions of script.  
Yes, maybe two projects helps with this, but it will be more complicate in my opinion.

**Comment by ellismg** [comment]
@Ilchuk-Mihail 

> I faced this in that case if I have one script just simple deployment Fargate service, and second more complicated script to create hosted zone, make alias, issue certificate, setup nlb etc.
> I mean I don't need to run this long running script every time, where I can run simple one and test something.

Is there a reason you don't want to push these together?  Doing so should be fine from Pulumi's point of view, and in fact we organize much of our infrastructure in the same way.  We have programs that will create ECS clusters, build and push containers to them, allocate ALBs as well as databases, route53 hosted zones and the like.  When we run `pulumi update`, Pulumi will only touched infrastructure that has changed, so the updates are still quite quick.  Once the ALBs or Route53 zones or ACM certs have been provisioned, we don't do any work unless you've changed something about their inputs.

> Maybe it can be considering like dev, prod version, or just like different versions of script.

In general, our model here would be that dev and prod would be produced from the same program (they would just be different stacks targeted via `pulumi stack select`).  If there were differences between prod and dev, you would use `pulumi config` to be able to set configuration values (we use this in some of our internal infrastructure, for example, to use t2.small instances to back our ECS clusters for dev stack, but use larger instances in prod).

I think we are unlikely to make a change like you describe because it really runs counter to our project/stack model.  I do think that if you find that doing a `pulumi update` of a stack with many resources (of which few have changed) is unacceptably slow, we'd like to know about that with some examples, so we can focus on improving that instead of forcing folks to break apart their programs to get speed-ups.

**Comment by nguyenxndaidev** [comment]
> Yes, maybe two projects helps with this, but it will be more complicate in my opinion.

I think spliting to multiple projects is not so complicated.
The problem when split project with `nodejs` is that how to reuse `node_modules`, `package.json`, `tsconfig.json`.

I solve this problem by structuring my project like this:
![image](https://user-images.githubusercontent.com/24372782/67140961-79c0bc80-f25f-11e9-813e-dbd7abe94865.png)

The `node_modules` and package.json at the root project directory so all child projects automatically use this shared `node_modules`.

I also use [pnpm](https://pnpm.js.org) to keep all dependencies in a single repo. This tool makes use of symlinks for that purpose.

I use `extends` to specify [`tsconfig.json` inheritance](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends).

**Comment by bgdnlp** [comment]
I came here looking for the same thing for Python, wanted to change the main entry point from __main__.py to something else to do some quick debugging. I thought maybe there is a config option that can be set with `pulumi config`. Something like `pulumi config set entrypoint myprg.py`. If it's set, then run myprg.py, if it's not then run __main__.py.

Wouldn't that be relatively painful to implement?

**Comment by lukehoban** [comment]
> I came here looking for the same thing for Python, wanted to change the main entry point from __main__.py to something else to do some quick debugging.

You can use `main: ` in the Pulumi.yaml to point to a different folder or file:

```
main: something.py
```

**Comment by lukehoban** [comment]
The initial issue raised here I think has several available workarounds that fit better with the current Pulumi project+stack model, and the general point around configuring entrypoint is well supported by `main: `.  I am going to close this out, if there are any further improvements folks think would be valuable though - feel free to open new issues to track.
