### ISSUE TITLE
`pulumi logout` doesn't logout if you are logged into the filesystem backend.

### ISSUE THREAD

**Issue by davidobrien1985** [pulumi/pulumi#2926]
As mentioned on slack:
https://pulumi-community.slack.com/archives/C84L4E3N1/p1562885985337600

```
pulumi version  
v0.17.21
```

OS: Ubuntu 19.04

Repro steps:
`pulumi login`
* This will log you in to the pulumi service
`pulumi logout`
* this clears `~/.pulumi/credentials.json`
`pulumi login --local`
* configures pulumi to use `local` for state
`pulumi logout`
* this should again clear the credentials file, but it's still pointing locally
```
cat ~/.pulumi/credentials.json
{
    "current": "file://~",
    "accessTokens": {
        "file://~": ""
    }
}
```
`pulumi login`
* this should now prompt for the service access token, but it doesn't.

```
ll -a ~/.pulumi 
total 32K
drwxr-xr-x  6 david david 4.0K Jul 12 09:03 .
drwxr-xr-x 51 david david 4.0K Jul 12 10:05 ..
drwx------  2 david david 4.0K Jul 10 11:34 bin
-rw-------  1 david david   61 Jul 11 11:45 .cachedVersionInfo
-rw-r--r--  1 david david   81 Jul 12 10:04 credentials.json
drwx------ 12 david david 4.0K Jul 10 11:33 plugins
drwx------ 40 david david 4.0K Jul 10 11:54 templates
drwx------  2 david david 4.0K Jul 11 10:47 workspaces
```

**Comment by chrsmith** [comment]
This is a regression from a minor change to the `pulumi login` command in the latest release. The underlying issue is that `pulumi login` will use the "last use" set of credentials, rather than defaulting to use the Pulumi SaaS.

We'll fix this to go back to the earlier behavior, since this caused some CI/CD failures for our own infrastructure recently.

As a workaround, you can explicitly log into the Pulumi SaaS by passing the `--cloud-url` parameter, e.g.:

```
pulumi login https://api.pulumi.com
pulumi login --cloud-url https://api.pulumi.com
```

**Comment by ebdadsetan** [comment]
Hi! Would defaulting back to the pulumi SaaS not disrupt those who switch between a local file and a s3 backend rather than a Pulumi SaaS backend?
It's easier said than done, but would it be a more generally applicable solution to have a set of backends to switch from/to?
