### ISSUE TITLE
Is `latest` still the best version to be setting in Pulumi templates?

### ISSUE THREAD

**Issue by eropple** [pulumi/pulumi#2934]
As Pulumi matures and folks move production workloads into its orbit, setting dependencies like `"@pulumi/pulumi": "latest"` concerns me a little. Right now, in my shop, I'm handling stack management so it's not the biggest deal in the world to set things to reasonable constraints, but I'm a little worried about new projects that might come along without my overly nitpicky eye.

So, a couple questions come to mind:

- What compatibility guarantees are being afforded between Pulumi binary releases and Node packages? If the answer to this isn't "pretty much anything", it might be worth exploring the use of an `asdf` plugin to allow people to use multiple Pulumi versions that explicitly are compatible with the code they've written.
- I'm looking at different minor versions between `@pulumi/aws` (18) and `@pulumi/pulumi` (17). Should maybe Node dependencies, then, be gated to semantically-equivalent releases, e.g. `~0.17.22` for `@pulumi/pulumi` as of this writing?

**Comment by lukehoban** [comment]
Package managers will add lock files, so in practice once a Pulumi program is being developed, it will be locked to the version it was started with.

Currently, Pulumi projects (both `pulumi` CLI and packages) version with semver using a "minor version bump for breaking changes" strategy (since pre-1.0).

If the team developing the program wants to take a stronger dependency on a specific version (because they are aware of a change they need to avoid), they can add a a more specific version constraint to the template.

I think in practice, we have two options for templates:
1. Use `latest` and ensure the templates themselves always work with `latest`.  
2. Hard code in the currently "latest" `^0.18.0` style version.

(2) would require update the templates fairly often, and to some extent duplicates what users get from lockfiles.   It may also not really capture what users "want" as the default.  But it would encode the breaking change bar more explicitly into the default templates.

Certainly once we get to `1.0` we will want to move over to (2).  Before then, I do wonder whether it's net better to do (1) than (2).

**Comment by eropple** [comment]
Package managers do add lock files--my concern is mostly around when those projects are developed. And, yeah, a team developing the program can take that stronger dependency--what I'm asking is if the current state is helping people fall into the pit of success. ;) I've been bitten by this (there was a release of, I think `@pulumi/aws`, that changed behavior--and perhaps then changed it back--recently?) and so yeah, the stuff we're doing has standardized, but we're also pretty high on the know-how-to-use-it curve for both cloud provisioning tools and for NodeJS.

**Comment by stack72** [comment]
@lukehoban we actually changed this yesterday e.g. https://github.com/pulumi/templates/blob/master/aws-typescript/package.json

I think this can be closed?

**Comment by lukehoban** [comment]
Indeed - we now use `^1.0.0` for all packages that have hit 1.0.
