### ISSUE TITLE
Figure out graph queryability

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#30]
A scenario to consider is queryability of resource graphs.  This covers multiple scenarios:

* Simple questions about the contents of a graph ("What versions of Ubuntu am I running?")
* Complex questions that combine static analysis ("What VMs are vulnerability to CVE-Xxx?")
* Registering event notifications off the graph ("Tell me if any of my nodes ever get out of date")
* Even making modifications to the graph based on queries ("Patch all old Ubuntu versions")

Furthermore, this could be exposed in a bot-like interface (text or speech), for real bot-driven IT/configuration management workflows.

There are many graph technologies to consider, however we should keep this in mind as we design.

**Comment by lukehoban** [comment]
@hausdorff implemented a prototype in https://github.com/pulumi/pulumi/pull/2502 of adding checks into the Pulumi deployment process to block or warn on based on rules related to the desired state of a Pulumi deployment.  This addresses a few of the issues above, as well as other "gating" scenarios.  

This issue is rather old, and doesn't really capture the paths we expect to go down going forward.  I suspect we should close this out and open new issues to track the concrete issues we are expect to invest in over coming months.

**Comment by lukehoban** [comment]
We are now pursuing this as part of pulumi/pulumi#2601.
