### ISSUE TITLE
stacks stopped working after organisation rename

### ISSUE THREAD

**Issue by redbaron** [pulumi/pulumi#3086]
Our org was renamed per our requests, but now stacks don't work:

```
Previewing update ($NEWORG/prod):
error: could not deserialize deployment: decrypting secret value: [404] Not Found: Organization '$OLDORG' not found
```

**Comment by redbaron** [comment]
`pulumi stack export`  , then  `sed`, then  `pulumi stack import` done the trick.

**Comment by petrosagg** [comment]
I just hit this issue after moving a stack from a personal account to an org account. @redbaron do you remember what you `sed`ed in the exported JSON? I tried changing the `deployment.secret_providers.project` property from `foo` to `orgname/foo` and get the same error on import

**Comment by redbaron** [comment]
No I can't remember. Try talking to Pulumi devs in their slack.

**Comment by petrosagg** [comment]
I just fixed it, for anyone hitting this in the future you need to change `deployment.secret_providers.owner` to the name of the current organization

**Comment by chrsmith** [comment]
Sorry for the trouble here @petrosagg , and you are correct about the "fix" here. A little more detail:

If you are using the Pulumi Console (https://app.pulumi.com) to manage your secrets, then inside the `secrets_provider` object in your stack's checkpoint file we need to refer to the owner of that stack. (Since each organization x stack pair gets a unique encryption key for managing secrets.)

The Pulumi Service takes care of updating your checkpoint file automatically when transferring stacks or when renaming things. But in this particular case, the service failed to complete its update for your particular checkpoint file. (Will reach out on the community Slack with more info.)
