### ISSUE TITLE
pulumi.Input<T>  doesn't play nice with TS type inference

### ISSUE THREAD

**Issue by redbaron** [pulumi/pulumi#3103]
I am not sure if it is a TS bug/works-as-expected, but thought it is worth reporting.

Following code doesn't compile:

```
import * as gcp from "@pulumi/gcp";
const x = {} as gcp.container.NodePoolArgs["nodeConfig"]["labels"];
```

With error:
```
$ node_modules/.bin/tsc --noEmit --noErrorTruncation test.ts
test.ts:2:58 - error TS2339: Property 'labels' does not exist on type 'Input<{ diskSizeGb?: .....; labels?: Input<{ [key: string]: Input<string>; }>;'
```

so property is definitely there , but it got lost on somehow.

`Unwrap<T>` helps, but I am not sure/do not understand why it is necessary:

```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";
const x = {} as pulumi.Unwrap<gcp.container.NodePoolArgs>["nodeConfig"]["labels"];
```

**Comment by lukehoban** [comment]
> so property is definitely there

No - I don't think it is - an `Input<NodePoolNodeConfig>` does not have a `labels` property.  It *might* have one, but it is a union which includes some types that definitely do not (like `Promise<NodePoolNodeConfig>`).

There's no doubt unions and `Input<T>` in particular are challenging for type level meta-tasks,  but I think that's just part of the overall approach here.

I think the issues noted here are "by design", though if you had more details on the motivating use cases that this prevents or makes difficult, it might make clear whether there is some other change or additional needed to address those.
