### ISSUE TITLE
When RunUpdateTest is true, yarn link does not run in prepare project step

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi#3161]
When RunUpdateTest is true, `yarn link` does not run in the language `prepare<Runtime>Project()` step, as `RunUpdateTest` does not currently work with `peerDependencies` - see [PR comment](https://github.com/pulumi/pulumi/pull/3110/files#r315398952).

**Proposed Solution:**

Removing the `if-check` around each of the following code blocks should allow for existing tests that depend on `peerDependency` to `yarn link` as expected for the initial preview & update step.

`prepareNodeJSProject()`:

https://github.com/pulumi/pulumi/blob/261b69ae6aa6699f4a4eedff1f21be46204c29cc/pkg/testing/integration/program.go#L1377-L1381

`preparePythonProject()`:
https://github.com/pulumi/pulumi/blob/261b69ae6aa6699f4a4eedff1f21be46204c29cc/pkg/testing/integration/program.go#L1446-L1450

Then after the initial preview & update using `peerDependencies` is run, if `RunUpdateTest` is `true` it should be **overriding** the locally linked deps from the previous, initial update with the latest from NPM via `yarn install` or Pypi via `pip install` to test on a second update run.

**Comment by metral** [comment]
It'd also be great to log to stdout that `RunUpdateTest` is running to know when this step is occurring.

**Comment by stack72** [comment]
@metral this isn't quite true - the order should be that, if we run an UpdateTest, then we should be installing latest on the first run and then overriding with the dev dependency on the second run. This is because the dev dependency is, more than likely, building on top of / different to what is in latest

Therefore, I don't believe the solution you have proposed in #3168 is correct... I am trying to work through this now to see what we can do here

**Comment by metral** [comment]
@stack72 Yes you are correct that the order works, but AFAICT the current solution only works when the package is in `dependency`, and generally on our packages we list the package in question as a `peerDependency` to force a local build being installed, rather than putting it as latest in `dependency` as that won't test the local build. 

The goal of the test is to deploy a stack on latest updates of the package in question as a user would, and then locally apply the local build changes and run a preview & update on it to check no errors exist to the update path in question. 

Hence the proposed changes in the order of operations, but in its own separate test:

https://github.com/pulumi/pulumi/blob/243e150bdd30a1d80d2b3dda8b59a828f9b31796/pkg/testing/integration/program.go#L185-L192

**Comment by stack72** [comment]
@metral So I have followed the code through so many times here. The yarn links are actually done against the code as specified in the examples_test.go 

e.g.

```
base := integration.ProgramTestOptions{
		Config: map[string]string{
			"azure:environment": environ,
			"azure:location":    azureLocation,
		},
	}

	jsBase := base.With(integration.ProgramTestOptions{
		Dependencies: []string{
			"@pulumi/azure",
		},
	})
```

So regardless of `peerDependencies` in the package.json for a test, it will link based on that set of specific deps

This is why I added the code in the current way - I am going through all of the options now to see where it fails though

**Comment by metral** [comment]
> So regardless of peerDependencies in the package.json for a test, it will link based on that set of specific deps
> 
> This is why I added the code in the current way - I am going through all of the options now to see where it fails though

The initial update only installs and uses the `dependencies`, not the `peerDependency` which doesn't get installed and run until after the initial update, as your changes set up. The initial updates needs the packaged being tested  / defined in `peerDependency` to be manually installed since it's **not** defined in the `dependency`, if not tests will error out about the package missing

**Comment by stack72** [comment]
Correct - so I'm still failing to see the issue - I mean, pulumi-* is a dependency of our tests so it feels like it should be there. If the dep isn't installed then the code won't work

So even if it's installed, we will link over the top on 1 of 2 scenarios:

1. If it's NOT an update test then we will link over the top immediately
2. If it IS an update test then we will link over the top on the second run

If you still think this isn't correct then let's get on a call tomorrow and discuss what we need to do here. I think the code you are proposing just reverses the way around I deal with it :D I'm not against it, I just can't see where the enhancement comes but maybe I just need to be walked through it specific to your use case is all

**Comment by metral** [comment]
> 1. If it's NOT an update test then we will link over the top immediately

This is the scenario that will fail, as the initial run won't run correctly to get passed this step when`RunLatestUpdateTest` is enabled.

Example: the pulumi-eks pkg in the examples and tests is listed as a `peerDependency` so the initial update run can't execute giving the missing eks package, which does not get installed **until after** the initial update run completes when `RunLatestUpdate` is enabled. Where as I want the initial update to include the eks package and have a stack deployed with that, hence the `yarn add` from latest public, before I link and update it again as the second scenario does with your changes.

The conflict is in the deployment of the initial run when the latest-update step is enabled since we list eks as a `peerDependency` that will not be installed until after the initial update completes. 

I'll work on a simple use case repro and I'll find time tomorrow for us to chat. Hoping this helps explain a bit more context 👍🏼

**Comment by stack72** [comment]
Oh I see what you are saying now - yes that will fail because `pulumi-kuberenetes` isn't actually a peerDependency - it's a fullblown dependency. 

I think we (as a team) generally are liberal with how we use peerDependencies vs dependencies

Ok, lets chat when you get online in the morning 👍

**Comment by ellismg** [comment]
> I think we (as a team) generally are liberal with how we use peerDependencies vs dependencies

I do not believe we are wed to our use of `peerDependencies` for the packages under test in our test projects.

In the very early days of the project, we used this because we were not yet publishing the SDK to NPM at all, instead our SDK installer would lay copies of all our packages into something like `~/.pulumi/node_modules` and run `yarn link` inside each package folder in there, so consumers could run `yarn link` later to "install" our packages.

The other thing we get today with `peerDependencies` is that it means we don't try to download a copy of the package under test during `yarn install`.  This was done for for two reasons:

1. We planned to use `yarn link` anyway to link in the package under test, so whatever content we downloaded would be removed.
2. For cases where packages were not published publicly (which can also happen when we are trying to do the initial build of a new package), `yarn install` will not try to download them.

Since we only ever used the "just built" version of the package under test, this was a fine strategy.  With the move to doing the upgrade testing, this no longer holds.  For any package that we want to do upgrade testing on, we need to ensure that the package under test is list as an actual dependency, to allow `yarn` to install the currently released version of that package.

For @metral's specific issue, I think it would be sufficient to modify the test to move `@pulumi/eks` from `peerDependency` to an actual `dependency`.  In general, I think this would actually be a fine thing for us to do all up.  The only time we would not want to do it is when the package has never been publicly released.  In that case, we wouldn't be able to write an UpdateTest anyway (there's nothing to update from!)

**Comment by metral** [comment]
@ellismg @stack72 Related discussion [doc](https://docs.google.com/document/d/1gO1Ss9ZasstwSIEt9mhv_3BQuQwg7yn1RXzEwr4h5AE/edit#).

> For @metral's specific issue, I think it would be sufficient to modify the test to move @pulumi/eks from peerDependency to an actual dependency. In general, I think this would actually be a fine thing for us to do all up. The only time we would not want to do it is when the package has never been publicly released. In that case, we wouldn't be able to write an UpdateTest anyway (there's nothing to update from!)

What does this change buy us though? By listing `pulumi/eks: latest` in `dependency` we're testing that the *already released* package of eks runs fine across the examples and tests - a set of checks that will / should have already been done before we released it, no?

**Comment by metral** [comment]
> For @metral's specific issue, I think it would be sufficient to modify the test to move @pulumi/eks from peerDependency to an actual dependency. In general, I think this would actually be a fine thing for us to do all up. The only time we would not want to do it is when the package has never been publicly released. In that case, we wouldn't be able to write an UpdateTest anyway (there's nothing to update from!)

Alright, I'll change to all `dependency` listings, and close out https://github.com/pulumi/pulumi/pull/3168.

Thanks everyone
