### ISSUE TITLE
Previews do not reflect the resulting update

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#3190]
When running `up`, the preview is vastly different than the resulting update. For example, making a change to an annotation in a namespace is causing all resources that use that namespace to be previewed as needing a replacement.

In my particular example here we're using the Kubernetes provider, but I've experienced this with GCP's Cloud SQL and other resources as well.

**Comment by pgavlin** [comment]
> When running up, the preview is vastly different than the resulting update. For example, making a change to an annotation in a namespace is causing all resources that use that namespace to be previewed as needing a replacement.

The preview is a conservative estimate of the changes that will be performed as part of the update. Without additional information, the engine must assume that all outputs of a resource may change if any update or replacement is required, and therefore treats all outputs of such a resource as unknown during the preview. These unknowns then flow downstream, causing further differences that will only be picked up during preview. Because this estimate is intended to be conservative, it should only ever be the case that you see fewer, safer changes during the `pulumi update` itself: most replacements become updates, and most updates are not needed.

We are working on plumbing additional information from the providers into the engine s.t. the providers can indicate that even if a resource is being updated or replaced, certain output properties will not change. This should help make the result of a preview less conservative, and closer to the set of changes that will be performed. I can't find an issue tracking this work, so we may as well use this one.

**Comment by nesl247** [comment]
I understand that it is conservative, but it also is rendering the preview 100% useless. How will we ever know if it will actually do a real replacement or not? Some resources cannot be replaced without downtime or data loss. This is a critical issue in my opinion.

**Comment by pgavlin** [comment]
For what it's worth, we did recently make a fix here that did affect the preview experience. Earlier versions of Pulumi incorrectly assumed that any input property that was present during a preview would contain the actual value of the corresponding output property (if any). The SDK would then resolve any missing output properties to the value of the corresponding input. This behavior is not correct--it violates the conservative nature of the preview, and caused user code to run at unexpected times with unexpected values--but re-enabling it may make your experience closer to what you expect. You can set the `PULUMI_ENABLE_LEGACY_APPLY` environment variable to `1` to see how things look with the old behavior.

**Comment by nesl247** [comment]
Thanks for the information. I'll keep an eye here to see when we should start to not use the legacy apply then as we'll definitely have to for now.

**Comment by pgavlin** [comment]
> You can set the `PULUMI_ENABLE_LEGACY_APPLY` environment variable to `1` to see how things look with the old behavior.

Looking at the code, you'll need to set this variable to `true`, not `1`.

**Comment by lukehoban** [comment]
Just to include a few more details here - here's a short repro:

```ts
import * as k8s from "@pulumi/kubernetes";

const myns = new k8s.core.v1.Namespace("myns", {
    metadata: {
        // annotations: {
        //     "something": "else",
        // }
    }
});

const mypod = new k8s.core.v1.Pod("mypod", {
    metadata: {
        namespace: myns.metadata.name,
    },
    spec: {
        containers: [{
            name: "nginx",
            image: "nginx",
        }]
    }
})
```

If the above is deployed, and then the annotation is commented out, a `pulumi preview --diff` will show:

```
$ pulumi preview --diff
Previewing update (foo):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:foo::kube537::pulumi:pulumi:Stack::kube537-foo]
    ~ kubernetes:core/v1:Namespace: (update)
        [id=myns-xwi3qjfl]
        [urn=urn:pulumi:foo::kube537::kubernetes:core/v1:Namespace::myns]
        [provider=urn:pulumi:foo::kube537::pulumi:providers:kubernetes::default_0_25_2::34243091-0311-4e09-82b1-dcaf5567049f]
      ~ metadata: {
          ~ annotations: {
              + something: "else"
            }
        }
    +-kubernetes:core/v1:Pod: (replace)
        [id=myns-xwi3qjfl/mypod-dz9cs62z]
        [urn=urn:pulumi:foo::kube537::kubernetes:core/v1:Pod::mypod]
        [provider=urn:pulumi:foo::kube537::pulumi:providers:kubernetes::default_0_25_2::34243091-0311-4e09-82b1-dcaf5567049f]
      ~ metadata: {
          - namespace: "myns-xwi3qjfl"
        }
```

This is clearly very bad.  It's conservative, but makes the preview something you can't trust anymore.  The formatting of the diff on the `Pod` is also confusing (it says the namespace is being removed - which it isn't).

As noted above - one current workaround is to use `PULUMI_ENABLE_LEGACY_APPLY ` which will produce:

```
$ PULUMI_ENABLE_LEGACY_APPLY=true pulumi preview --diff
Previewing update (foo):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:foo::kube537::pulumi:pulumi:Stack::kube537-foo]
```

But we also need to ensure that the default experience is not overly conservative here and that preview remains useful in these cases.

The core to this is in passing back the information that `namespace.metadata.name` is "stable" - that is, immutable for a given namespace.  I was sure we had an issue tracking this already - but for now we can use this issue to track this improvement that we want to make soon to improve the default experience here (without regressing the fundamental safety of previews).

**Comment by redbaron** [comment]
If there is a way to generate/infer or crowdsource functions `<T>(arg: pulumi.Input<T>) => [keyof ResourceType]` , to know which properties of a resource each arg changes, then predictions could be much more accurate

**Comment by pgavlin** [comment]
> If there is a way to generate/infer or crowdsource functions (arg: keyof ResourceArg) => [keyof ResourceType] , to know which properties of a resource each input arg changes, then predictions could be much more accurate

We have a latent approach to this that uses information about whether or not a change to a particular resource property forces replacement of that resource: if a resource does not require replacement, then no such property may have changed, and must have its current value (otherwise the resource would require replacement).

**Comment by pgavlin** [comment]
> The core to this is in passing back the information that namespace.metadata.name is "stable" - that is, immutable for a given namespace. I was sure we had an issue tracking this already - but for now we can use this issue to track this improvement that we want to make soon to improve the default experience here (without regressing the fundamental safety of previews).

In principle, this approach should work without issue. In practice, I am worried that we are going to run into problems representing partially-stable values in the SDK. Consider an amended version of the original example with the call to `apply` made explicit:

```typescript
import * as k8s from "@pulumi/kubernetes";

const myns = new k8s.core.v1.Namespace("myns", {
    metadata: {
        annotations: {
            "foo": "bar",
        },
    },
});

const mypod = new k8s.core.v1.Pod("mypod", {
    metadata: {
        namespace: myns.metadata.apply(m => m.name),
    },
    spec: {
        containers: [{
            name: "nginx",
            image: "nginx",
        }]
    }
})
```

If this program is deployed, a change is subsequently made to `metadata.annotations` s.t. some piece of the value is not known during a `preview`, and the provider indicates that only `metadata.name` is stable, we will have a partially-stable value for the top-level `metadata` property. Representing this in the engine is straightforward: the `metadata` property will be a map with two entries, `name` and `annotations`, the latter of which is `Computed`. When we unmarshal this value in the SDK, however, we have a problem.

The `metadata` property is typed as `pulumi.Output<outputs.meta.v1.ObjectMeta>`, where `outputs.meta.v1.ObjectMeta` looks like so (some fields omitted for brevity):

```typescript
export interface ObjectMeta {
  /**
   * Annotations is an unstructured key value map stored with a resource that may be set by
   * external tools to store and retrieve arbitrary metadata. They are not queryable and should
   * be preserved when modifying objects. More info:
   * http://kubernetes.io/docs/user-guide/annotations
   */
  readonly annotations: {[key: string]: string}

  /**
   * Name must be unique within a namespace. Is required when creating resources, although some
   * resources may allow a client to request the generation of an appropriate name
   * automatically. Name is primarily intended for creation idempotence and configuration
   * definition. Cannot be updated. More info:
   * http://kubernetes.io/docs/user-guide/identifiers#names
   */
  readonly name: string
}
```

In this type definition, `annotations` is a `{[key: string] string}`. In our example, however, the value of `annotations` is not stable, so we cannot construct an appropriately-typed value for `annotations`.

Offhand, I can think of two approaches to addressing this without making a breaking change:
1. Find a way to intercept accesses to nested unknown properties and throw a well-known exception if any are accessed. I do not know if this is realistic.
2. Provide an option to `apply` (or a second API) that indicates that the callback should run even if the value is not fully known, and fill in unknown properties with a sentinel unknown value. Lifted property accesses would then use this API. This approach has the benefit of an obvious implementation in all of our supported languages.

In the meantime, I think that the original namespace-specific variant of this issue can be worked around by using the namespace's ID (which should always be known if the resource is not being recreated) instead of `metadata.name`.

@lukehoban @CyrusNajmabadi @ellismg thoughts on the two options? Any additional ideas? I'm leaning towards (2) myself.

**Comment by CyrusNajmabadi** [comment]
'2' has come up quite a bit as being something that would be useful in many cases.  By default, it makes sense that we would have to eb conservative and not run `.apply`s during preview.  but i don't see any harm with allowing the caller to opt-into having them run, with the knowledge that some data they read may not be available.

**Comment by lukehoban** [comment]
>  Lifted property accesses would then use this API. 

This is an interesting point - that the lifted property accesses are always "safe" to run in this mode.  That is quite compelling.  And I agree with @CyrusNajmabadi that the idea of offering this mode of `apply` makes sense in the first place.  But even nicer if it can make the lifted property semantics automatically better.

Are there any obvious "downsides" to (2)?

**Comment by pgavlin** [comment]
> Are there any obvious "downsides" to (2)?

None that I can see beyond extra complication in the public API (including some way to represent a nested unknown value and the typing mismatches that may bring).

**Comment by redbaron** [comment]
> We have a latent approach to this that uses information about whether or not a change to a particular resource property forces replacement of that resource: if a resource does not require replacement, then no such property may have changed, and must have its current value (otherwise the resource would require replacement).

Yes, but update case is not covered. When input  property A changes, all outputs are considered to be changing too , but that is too conservative and is at the root of the problem

Initial version of this change tracking framework can surface that  mapping function explicitly , as in for every input ...Args field input return all properties of a Resource. Then it would be possible for interested people to make PRs to refine it.

Evolution of Terraform providers can be a taken conservatively, as in any newly introduced args are to be treated as if they are changing all outputs .


With this approach there is no visible API changes, Pulumi just becomes more accurate in its plans

**Comment by pgavlin** [comment]
> Yes, but update case is not covered. When input property A changes, all outputs are considered to be changing too , but that is too conservative and is at the root of the problem

Not sure what you mean--the approach I describe would allow certain properties to be considered as unchanging even during updates. To start with, we would implement this in the TF-based providers by considering any "requires replacement" property to be unchanged if the resource does not require replacement.

**Comment by pgavlin** [comment]
(we could then extend the capabilities of the TF/Pulumi bridge to allow arbitrary logic to indicate additional stable properties)

**Comment by pgavlin** [comment]
The other approach we could take is to add a flag to each CRUD operation that indicates that the provider should dry-run the operation. This would give the provider the opportunity to provide real property values for the operation, including values that did not exist in the old state (which is not possible with the "stable properties" approach outlined above). Though it is a larger, more disruptive change, this approach would also allow `Create` to return values during preview, which would not be possible with the "stable properties" approach.

**Comment by nesl247** [comment]
@pgavlin That would be my preference. I would expect preview to be a dry run, thus returning exactly the values that it would create. In fact, my personal opinion would be that the update should execute exactly what is done via the preview. Thus it shouldn't recalculate twice. It already knows what it needs to do, and should execute those changes. But that's just my opinion as a user.
