### ISSUE TITLE
Specifying an incorrect API service backend for pulumi login results in a confusing error message

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#3194]
Running `pulumi login` with an invalid managed backend URL results in this error message, which doesn't help identifying the problem.

For example running `pulumi login https://someurl.com`. In most cases, the URL is probably not completely different, but perhaps with a subtle typo, for example, instead of `pulumi login https://api.pulumi.com` (which is valid), if I were to mistype it as `pulumi login https://ap.pulumi.com` it would be nice to know that the problem is with the URL I entered.

```
error: problem logging in: getting user info from <URL>: unmarshalling response object: invalid character '<' looking for beginning of value
```

**Comment by danfhernandez** [comment]
I don't know if this fits within the scope of this ticket but would be good to also update the documentation in pulumi login --help. This is what is there now:

> By default, this will log into `app.pulumi.com`. If you prefer to log into a separate instance
of the Pulumi service, such as Pulumi Enterprise, specify a URL. For example, run
>
>$ pulumi login https://pulumi.acmecorp.com
>
>to log in to a Pulumi Enterprise server running at the pulumi.acmecorp.com domain.

**Comment by praneetloke** [comment]
I just got tripped up by another version of this. This time it was the `logout` command. The `logout` command accepts the backend URL that you want to logout of. The correct backend URL for the managed Pulumi Service is the API URL `https://api.pulumi.com` and not the Console URL `https://app.pulumi.com`. But the CLI will silently exit giving you the impression you have logout.

@emiliza also pointed out that the backend URL that is printed from running `pulumi whoami -v` is misleading. It's actually the Console URL if you are using an HTTP state backend that is either the managed Pulumi Service or a [self-hosted](https://pulumi.com/docs/guides/self-hosted) one.

**Comment by emiliza** [comment]
The initial issue here might actually be fixed. 

`pulumi login https://ap.pulumi.com` produces this, more helpful, message:
>error: problem logging in: getting user info from https://ap.pulumi.com: performing HTTP request: Get "https://ap.pulumi.com/api/user": dial tcp: lookup ap.pulumi.com: no such host

**Comment by djgrove** [comment]
I ran into this today when I was accidentally trying to run `pulumi login https://app.devon.pulumi-dev.io`. Bit different from @emiliza comment because this is a valid URL, just not the correct one. I get:

```
Logging in using access token from PULUMI_ACCESS_TOKEN
error: problem logging in: getting user info from https://app.devon.pulumi-dev.io: unmarshalling response object: invalid character '<' looking for beginning of value
```

Nitpick, and not very high pri as this seems like a workflow _we_ would run into far more than would our customers, but  it could be helpful to output a message a la "HTML response was detected at this URL. Make sure to point to the Pulumi API endpoint for the hosted service". Seems like we could pretty easily detect if the response type is JSON or not and go from there.

**Comment by djgrove** [comment]
I ran into this today when I was accidentally trying to run `pulumi login https://app.devon.pulumi-dev.io`. Bit different from @emiliza comment because this is a valid URL, just not the correct one. I get:

```
Logging in using access token from PULUMI_ACCESS_TOKEN
error: problem logging in: getting user info from https://[MY_DEVSTACK_CONSOLE_ENDPOINT]: unmarshalling response object: invalid character '<' looking for beginning of value
```

Nitpick, and not very high pri as this seems like a workflow _we_ would run into far more than would our customers, but  it could be helpful to output a message like `HTML response was detected at this URL. Make sure you are passing the Pulumi API endpoint for the hosted service and not the endpoint for the Pulumi Console`. Seems like we could pretty easily detect if the response type is JSON or not and go from there.

**Comment by djgrove** [comment]
I ran into this today when I was accidentally trying to run `pulumi login [url_to_pulumi_console]`. Bit different from @emiliza comment because this is a valid URL, just not the correct one. I get:

```
Logging in using access token from PULUMI_ACCESS_TOKEN
error: problem logging in: getting user info from [the url I tried]: unmarshalling response object: invalid character '<' looking for beginning of value
```

Nitpick, and not very high pri as this seems like a workflow _we_ would run into far more than would our customers, but  it could be helpful to output a message like `HTML response was detected at this URL. Make sure you are passing the Pulumi API endpoint for the hosted service and not the endpoint for the Pulumi Console`. Seems like we could pretty easily detect if the response type is JSON or not and go from there.

**Comment by mikhailshilkov** [comment]
I think this has been fixed in its original form.

```
pulumi login https://ap.pulumi.com
Manage your Pulumi stacks by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token:

pulumi login [url_to_pulumi_console] 
zsh: no matches found: [url_to_pulumi_console]

pulumi login https://someurl.com
Manage your Pulumi stacks by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token:
```

Not sure if the access token prompt is clear - but I guess it's related to self-hosted backends? I'll go ahead and close this issue, let's open another one if further improvements are needed.
