### ISSUE TITLE
When cluster object is output, kubeconfig string is omitted

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3203]
In the code below, when `cluster` (the object) and `cluster.kubeconfig` (the string) are exported as outputs then only the `cluster` object is output. If the `cluster` export is removed, then the `kubeconfig` export is output as expected. 

```typescript
import * as awsx from "@pulumi/awsx";
import * as eks from "@pulumi/eks";

const vpc = new awsx.Network("vpc");

const cluster = new eks.Cluster("cluster", {
    vpcId: vpc.vpcId,
    subnetIds: vpc.subnetIds,
    instanceType: "t2.medium",
    desiredCapacity: 2,
    minSize: 1,
    maxSize: 2,
    storageClasses: "gp2",
    deployDashboard: true,
});

export const clusterObj = cluster; // <-- This line causes the `kubeconfig` to not be output. Comment this and `kubeconfig` appears.
export const kubeconfig = cluster.kubeconfig;
```

**Comment by clstokes** [comment]
The order of exports changes this behavior. If `kubeconfig` is exported before `clusterObject`, both are output as expected.

This works:
```typescript
//... 

export const kubeconfig = cluster.kubeconfig; // If this is output before `clusterObj`, it works.
export const clusterObj = cluster; 
```

**Comment by CyrusNajmabadi** [comment]
Yeah, i know what the issue is here.  We have code to prevent infinite loops when emitting stack outputs.  That code should apply *per* output, but is currently applied across *all* outputs.  So, since we see `kubeconfig` when producing the output for `cluster` we ignore it the second time around.

Should not be too difficult to fix.
