### ISSUE TITLE
'Stack not found' random test failures

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3250]
Different tests have occasionally failed recently with `stack not found` errors. The output suggests everything goes fine:

```
Created project 'test-env656393961'

Please enter your desired stack name.

To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).

Created stack 'dev'
...
Your new project is ready to go!
```
until a sudden 404 while trying to delete the stack:
```
--- FAIL: TestCreatingProjectWithDefaultName (29.71s)
    new_test.go:461: 
        	Error Trace:	new_test.go:461
        	            			new_test.go:152
        	Error:      	Received unexpected error:
        	            	[404] Not Found: Stack 'test-env656393961/dev' not found
        	Test:       	TestCreatingProjectWithDefaultName
```

Failures: 

- [TestCreatingProjectWithDefaultName](https://travis-ci.com/pulumi/pulumi/jobs/237507813#L2784)
- [TestCreatingProjectWithArgsSpecifiedName](https://travis-ci.com/pulumi/pulumi/jobs/237507815#L2814)
- [TestTemplates/aws-typescript](https://travis-ci.com/pulumi/pulumi/jobs/237097989#L4003)
- [TestCreatingProjectWithArgsSpecifiedName](https://travis-ci.com/pulumi/pulumi/jobs/236998901#L2793)
- [TestTemplates/packet-python](https://travis-ci.com/pulumi/pulumi/jobs/236733908#L3971).

I wonder if we can track those 404 requests?

**Comment by chrsmith** [comment]
I'll take a look at our request logs. Obviously something is wrong here.

**Comment by CyrusNajmabadi** [comment]
@chrsmith another case: https://travis-ci.com/pulumi/pulumi/builds/128589167

Note this hit a mainline test of TestCreatingProjectWithArgsSpecifiedName.  This feels like some sort of race condition in the service.  It successfully makes the stack, but then responds with 404 if queried too quickly for it immediately after creation.

**Comment by lukehoban** [comment]
Marking P0 - this has caused most  test runs in  `pulumi/pulumi` to fail for the better part of the last week.

If we need to disable these tests while we investigate - let's do that.

**Comment by chrsmith** [comment]
Looking at the test case and associated request logs, it appears that the Pulumi Service is behaving as it should. Though obviously something unexpected is happening during the test's execution.

It's unlikely there is a race condition in the service, since the reads are done from a SQL database with strong consistency. (We don't use a cache or anything when looking up stacks.) It appears that we are trying to get the latest update and export the checkpoint for a stack that has never been updated, which is where that 404 error is coming from.

Looking at the code on my box I can't see anything obvious out of whack, let me take a look at what's in `master` right now...

**Comment by chrsmith** [comment]
OK, I figured out the problem here. It's complicated, but kinda sorta boils down to an existing work item in the Pulumi Service (https://github.com/pulumi/pulumi-service/issues/2810).

The problem (and why it is intermittent) is related to the way we support the older stack identity model (just stack name). Since `pulumi-bot` has thousands of stacks named `dev`, there is a ... ::sigh:: data race related to when we are processing requests.

The work to improve the performance of stack operations has been underway for a while. This bug is just a symptom of us not completing that work. In the mean time, if we delete old test stacks created by `pulumi-bot` that are no longer needed, it will make this error less likely to occur.

**Comment by mikhailshilkov** [comment]
@chrsmith Nice find! Should I change the tests to use the fully qualified name? Two parts or three parts?

**Comment by chrsmith** [comment]
This won't get fixed in M27, but I've started working on the prerequisites to fixing this in the Pulumi Service.

**Comment by chrsmith** [comment]
@mikhailshilkov fixed this with a lame workaround. The underlying Pulumi Service issue will be fixed in the next release with https://github.com/pulumi/pulumi-service/issues/2810.
