### ISSUE TITLE
Compilation errors should go to stderr

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3263]
If I have errors in my TypeScript, I expected that running

```bash
$ pulumi preview 2>errors.txt
```

would allow me to isolate them from the standard console output. Unfortunately, it appears compilation errors are written to stdout. It would be nicer to write to stderr instead.

**Comment by CyrusNajmabadi** [comment]
This would be a little odd given that tsc itself doesn't emit this stuff to stderr.  Other tools that launch tsc (like yarn) don't seem to do this either.  Is this how the ecosystem generally treats chained tools?

**Comment by CyrusNajmabadi** [comment]
> would allow me to isolate them from the standard console output.

Could you give an example of how this would matter?  If tsc fails, we're not going to proceed and do anything else right?

**Comment by CyrusNajmabadi** [comment]
Here's what i see locally, which actually seems like a great, consistent experience to me IMO:

![image](https://user-images.githubusercontent.com/4564579/65632947-c7fbdc00-df8f-11e9-91c2-0acd7549942d.png)

We've got the normal pulumi experience, and we report errors we encounter in our normal fashion to the "Diagnostics" portion of the output.

**Comment by CyrusNajmabadi** [comment]
I looked into this and i don't believe there's anythin we can do here.  The way pulumi works here is that we just call into the normal node `require(user-program-code)` and we report back any errors reported by node as it tries to load/run the program.  

In the case of typescript, we are not actually invoking the typescript compiler itself, or getting the diagnostics in any way.  Instead, we're just inserting typescript into node's module-loading extensibility system.  So we still call `require(...)` node still runs its normal codepaths, it's just that it also not only runs the user code (which can report errors like normal), but will also go through typesript (which will report its own errors, which node will then report as its errors to us).

There isn't really anything (short of scraping messages) that we can do to know that these errors are because of hte typescript scaffolding rather than the code the user is running themselves.  To node, it's the same stuff.

This can also be evidenced by running into the same experience if this was straight javascript (but the javascript itself had an error in it outside of the user code):

![image](https://user-images.githubusercontent.com/4564579/65634576-5de53600-df93-11e9-9857-fbc1d1584e79.png)

This is the same error flow as above (node errors on this module).  The only difference comes down to what the contents of the actual error message is.  i.e. if we see something like `TSError:`.

**Comment by CyrusNajmabadi** [comment]
Closing out as by-design for now.
