### ISSUE TITLE
Provide opt-in setting to disable default providers

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3383]
Default providers (configured using pulumi config, and used whenever an explicit provider is not passed either directly or indirectly) are very useful for getting started, but for robust deployments, it is often desirable to ensure that providers must be passed and configured explicitly.

While it is possible to do so today, it is still very easy to accidentally allow a resource to pick up the ambient/default provider.  

We have taken to encouraging configuring the default provider with invalid configration as a workaround to ensure the default provider cannot accidentally be used - but this only works if you remember to do it for every affected provider (and is an awkward workaround).

We should instead offer an opt-in setting (either an env var or a `pulumi:something` configuration variable) that turns off default providers, making it an error to attempt to register a resource using one.

This is related to a handful of other issues around default providers - where we may want to go even further - but this specific option is a good "lock things down" opt-in we can easily offer today in advance of larger change.

Related: 
* https://github.com/pulumi/pulumi/issues/2059 (allow setting the default provider programmatically)
* https://github.com/pulumi/pulumi/issues/2246 (expose the default provider instance to programs)
* https://github.com/pulumi/pulumi/issues/2917 (adapt API shape to more clearly encourage parenting

**Comment by lukehoban** [comment]
> We have taken to encouraging configuring the default provider with invalid configration as a workaround to ensure the default provider cannot accidentally be used - but this only works if you remember to do it for every affected provider (and is an awkward workaround).

Note that this technique can be used for any of the clouds - for example:
* `pulumi config set kubernetes:kubeconfig invalid`
* `pulumi config set aws:region invalid`
* `pulumi config set azure:environment invalid`
* `pulumi config set gcp:project invalid`

Not ideal - but should work in practice to avoid accidentally picking up ambient credentials.

**Comment by mazamats** [comment]
+1 This would be a great addition, ideally it should be per provider and not across all providers.

Our use case: We've started distributing an abstracted API for deploying onto k8s clusters but in some cases developers have been deploying to whatever their `KUBECONFIG` env var is set to.

**Comment by Dominik-K** [comment]
I suggest another iteration: an opt-in to implicit provider configs should be the default. Best as an explicit :-) global Pulumi config, e.g. sth. like `pulumi --implicit-provider-conf` (and an abbreviation, for sure).

As this would be a breaking change, best as part of the next major release.

**Comment by mitchellmaler** [comment]
Just ran into this issue. My shell sets a KUBECONFIG for my to connect to clusters and I almost modified the wrong cluster because I missed setting the provider on a single resource. I would like to have the kubernetes config have to be specified in the config or first-class and not automatically pulled from my shell or local file.

**Comment by empperi** [comment]
I think this should be implemented soon. This is a major problem that can cause some major havoc very easily.

I would also suggest that this would not be an opt-in via Pulumi config values but instead be driven by code. This is not a configuration thing, this is an aspect of the project. It won't change between different stacks in any reasonable project and if it really does, then one can easily handle that case in the code.

I know the main reason for suggesting the configuration parameter is the potential issue where resources might get read and initialized before this setting would take effect. I haven't looked at the code (yet) how this is implemented but since Pulumi is practically keeping a record of all resources anyway then it should also do this with Kubernetes providers in this regard. Pulumi first reads the configurations and later on does the diffing - there's plenty of time to read the "no default provider" setting and raising an error for all resources that do try to use it.

I was bit by this issue and it screwed up my cluster. Fortunately it was not production but if it had been this had been a catastrophe.  It's been over 1,5 years since this issue was opened, it's way past the time to take care of it.

**Comment by joeduffy** [comment]
@iwahbe @lukehoban I was just replying to an email about this feature and wanted to point them at the docs. Could you point me at them? Neither our site's search nor Google are my friend right now. Thanks.

**Comment by iwahbe** [comment]
@joeduffy I don't think that this feature has been added to our documentation. I'll add a description for the feature here: https://www.pulumi.com/docs/intro/concepts/resources/providers/.
