### ISSUE TITLE
Support moving resources between projects

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi#3389]
Sometimes would be useful to move some resource from one project stack to another project stack, without recreating the resource.
For example, split a monolithic stack to micro stacks.
Currently, the easiest way to move the code to the new stack and import it, then remove from the old stack manually with `pulumi state delete` or exporting the stack and removing the resource and every dependency.
This is a very error-prone process, pulumi should provide an easier way to do these kinds of refactorings.

**Comment by pgavlin** [comment]
Thanks for the suggestion!

One thing you could try today to make things easier is to import the resource into its new stack using the [`import` functionality in the SDK](https://www.pulumi.com/docs/intro/concepts/programming-model/#import). While this doesn't perform a bulk move, it may make the process of moving a single resource to a new stack less error-prone.

We'll have to do some thinking on the right approach here.

**Comment by Jmaharman** [comment]
Definitely wants to work on this, even if it's a recipe provided in the documentation of a few sensible approaches.

**Comment by lukemundy-vgw** [comment]
I'd also be keen to see some work on this. My use case is as follows:

While creating templates for a new service we created a project (and associated stacks) containing an AWS CloudFront distribution and another separate project containing the Fargate service that would run behind it. Initially the idea was we'd create a number of additional Fargate service projects that all ran behind the same CloudFront distribution and so it made sense to be in a separate project. However after more work and thinking about the architecture more, that didn't make sense anymore. We were then left with that first Fargate service being the only service behind that CloudFront distribution but now we're managing two separate projects for infrastructure that is really only related to one service.

It'd be great if there was a straight forward way to transfer resources from one project to the other or just a way to merge a project. It's not the end of the world and I think this use case will be a rare occurrence, but would be nice to have.

In the absence of such functionality, it's likely we'll use the method @pgavlin mentioned of using the `import` option.

**Comment by ncsibra** [comment]
Currently we're using this helper class: 
```typescript
import * as fs from 'fs'

export class StackExport {
  private resources: any[]

  private foundURNs: string[]

  constructor(path: string) {
    this.resources = JSON.parse(fs.readFileSync(path).toString()).deployment.resources
    this.foundURNs = []
  }

  find(predicate: (value: any, index: number, obj: any) => boolean, transform?: (value: any) => any): any | undefined {
    const resource = this.resources.find((value, index, obj) => {
      try {
        return predicate(value, index, obj)
      } catch {
        return false
      }
    })

    if (resource && resource.urn && !this.foundURNs.includes(resource.urn)) {
      this.foundURNs.push(resource.urn)
    }

    if (!transform) {
      return resource
    }

    return transform(resource)
  }

  writeStateDelete(path: string) {
    fs.writeFileSync(
      path,
      this.foundURNs
        .reverse()
        .map((urn) => `pulumi state delete -y '${urn}'`)
        .join(' \\\n  && ') + '\n'
    )
  }
}

export const importFunctions = {
  securityGroupRule: (r: any) =>
    `${r.outputs.securityGroupId}_${r.outputs.type}_${r.outputs.protocol}_${r.outputs.fromPort}_${r.outputs.toPort}` +
    `_${r.outputs.sourceSecurityGroupId || r.outputs.cidrBlocks.join('_')}`,
}
```

Usage: 
1. Export the stack you want to move with `pulumi stack export --file stack.json`
2. Use the StackExport class to find and import the resources in their new place, e.g.:
```typescript
const stackExport = new StackExport(`stack.json`)

new cloudflare.Record(
  `${env}-cname-${zone.name}`,
  {
    zoneId: zone.id,
    type: 'CNAME',
    name: zone.name,
    value: traefik.public.dns,
    proxied: true,
  },
  {
    deleteBeforeReplace: true,
    import: stackExport.find(
      (value) => value.type == 'cloudflare:index/record:Record' && value.inputs.name == zone.name,
      (value) => `${value.outputs.zoneId}/${value.outputs.id}`
    ),
  }
)

stackExport.writeStateDelete('delete.txt')
```
3. Run the import, it will generate a `delete.txt` file which contains the necessary `pulumi state delete` commands in the correct order, e.g.:
```
pulumi state delete -y 'urn:pulumi:...:resourceA' \
  && pulumi state delete -y 'urn:pulumi:...:resourceB'
```
4. Copy and run the state delete commands from the txt file in the original project, done.

Relatively easy to use and the delete commands will always be in the correct order.

**Comment by ringods** [comment]
@pgavlin since your comment is from 2019, could you give an update on how Pulumi sees support for such "refactorings", e.g. moving resources from one stack to another (without destruction/recreation)?

This is something I'm scratching my head on in light of continuous delivery of all the stacks.

**Comment by Aaronontheweb** [comment]
Also interested in doing this - need to refactor our stacks so fewer resources are touched on each deployment

**Comment by geekyme** [comment]
Tried to move my resources from a monolith project to separate microservice projects. It's a real pain especially when the resources have dependencies on each other. 

I tried exporting the state and modifying it manually. It took a lot of time and is very error prone. We do need a much saner way of doing this.

**Comment by bmarinov** [comment]
> 
> 
> Tried to move my resources from a monolith project to separate microservice projects. It's a real pain especially when the resources have dependencies on each other.

I think that what you are describing is the distributed monolith of infrastructure. A different strategy might be less prone to devolving into chaos due to dependencies, hidden or not. We keep all the persistence / storage infra that a group of interdependent service components (called microservices by the general public) together as these are a part of a single logical service. Other infrastructure should not depend on them so we dont end up with too many dependencies between stacks (and generally have less stacks). 
With that said, I would still very much like to see a way of extracting a resource from one stack and importing it in the other. Currently I would be forced to create a new blob storage and move things over if I am to split it in a different stack / project. And this can happen a lot during consolidation and refactoring.

**Comment by darklow** [comment]
If anyone is interested, in order to move projects between organisations I used `pulumi stack export/import`. It seems to me it worked just fine. The only thing that didn't worked is secrets as they are being encrypted. I think you can edit export/import file in order to move just some parts between organisations.

I needed to move whole stack from my personal account to organisation and here is what I did:

```sh
# Temporary comment everything in Pulumi.nodes.yaml file
pulumi stack select my-user/project/stack
pulumi stack export --file user.stack.checkpoint.json

pulumi stack select new-organisation/project/stack
pulumi stack import --file user.stack.checkpoint.json
# Recreate config secrets if any
pulumi refresh
pulumi up
```

**Comment by albertocorrales** [comment]
This feature would be really useful. In my experience, as you get more experience, it is very likely that you want to split your resources into smaller stacks or just refactor and move resources to stack where they make more sense. 

Right now there is not an easy way to do it

**Comment by krishnamauryaext** [comment]
> If anyone is interested, in order to move projects between organisations I used `pulumi stack export/import`. It seems to me it worked just fine. The only thing that didn't worked is secrets as they are being encrypted. I think you can edit export/import file in order to move just some parts between organisations.
> 
> I needed to move whole stack from my personal account to organisation and here is what I did:
> 
> ```shell
> # Temporary comment everything in Pulumi.[stack].yaml file
> pulumi stack select my-user/project/stack
> pulumi stack export --file user.stack.checkpoint.json
> 
> pulumi stack select new-organisation/project/stack
> pulumi stack import --file user.stack.checkpoint.json
> # Recreate config secrets if any
> pulumi refresh
> pulumi up
> ```

I think, above step would copy the existing resource from you personal stack to organisation. You have to do `pulumi destroy` in your personal stack after successful import at other place.

**Comment by agluck91** [comment]
I want to add a plus one to this, the OP's method for moving items in a stack is the same method I have to use, and it is pretty cumbersome.

**Comment by MitchellGerdisch** [comment]
Any such tooling support should also support moving resources that are children of a component resource.

**Comment by lukehoban** [comment]
I've had a few conversations about this recently.  A few thoughts.

It would be great to have a CLI command like `pulumi state transfer` which could move a resource from one project/stack to another.  

Ideally this command could take a set of URNs, as well as an ability to implicitly include parents and/or dependencies.  Likely similar to `--target` on `pulumi up`, to efficiently specify a subset of resources in a stack without necesssarily having to name each one individually.

This command would also take a source and target stack, potentially like `pulumi config cp` which similarly needs to operate on a source and target stack, and would move resources from one to the other.

It would need to handle dependencies that cross the boundary between resources that are "staying" and "leaving".  In the source stack, it would need to add these to stack outputs.  In theory, they can be identified at the property level using "propertyDependencies", and so this can be fully automated, with some "guessing" on the naming pattern for exporting them.  On the target stack, a StackReference to the source stack would need to be generated (if not already present), and all the edges crossing the new boundary would need to rewrite their dependencies (and propertyDependencies) to depend on the stack reference.  

Of course, users would have to update their code bases, and refactor them into two seperate projects.  We likely can't meaningfully automate that - and would just need to provide guidance.  We could in principle code generate the additional (language-specific) stack exports needed for the source stack and StackReference needed for the target stack to slightly simplify this piece of manual work.

But even without any codegen help, this would massively simplify the migration, by not requiring any statefile hacking.  This is also ultiamtely more high fidelity than `pulumi import` because it can support components and can rely on the richer information we have about the resources and their dependencies from the target stack.

**Comment by jbrezina** [comment]
A note from manually transferring resources - the biggest problem for me were encrypted outputs as these are probably encrypted with different inputs in another stack.

**Comment by bsod90** [comment]
> I've had a few conversations about this recently. A few thoughts.
> 
> It would be great to have a CLI command like `pulumi state transfer` which could move a resource from one project/stack to another.
> 
> Ideally this command could take a set of URNs, as well as an ability to implicitly include parents and/or dependencies. Likely similar to `--target` on `pulumi up`, to efficiently specify a subset of resources in a stack without necesssarily having to name each one individually.
> 
> This command would also take a source and target stack, potentially like `pulumi config cp` which similarly needs to operate on a source and target stack, and would move resources from one to the other.
> 
> It would need to handle dependencies that cross the boundary between resources that are "staying" and "leaving". In the source stack, it would need to add these to stack outputs. In theory, they can be identified at the property level using "propertyDependencies", and so this can be fully automated, with some "guessing" on the naming pattern for exporting them. On the target stack, a StackReference to the source stack would need to be generated (if not already present), and all the edges crossing the new boundary would need to rewrite their dependencies (and propertyDependencies) to depend on the stack reference.
> 
> Of course, users would have to update their code bases, and refactor them into two seperate projects. We likely can't meaningfully automate that - and would just need to provide guidance. We could in principle code generate the additional (language-specific) stack exports needed for the source stack and StackReference needed for the target stack to slightly simplify this piece of manual work.
> 
> But even without any codegen help, this would massively simplify the migration, by not requiring any statefile hacking. This is also ultiamtely more high fidelity than `pulumi import` because it can support components and can rely on the richer information we have about the resources and their dependencies from the target stack.

@lukehoban Is there a chance Pulumi would implement something like this, say, by the end of 2023? Our (poorly designed) stack keeps growing and it's already at the point where the slightest update takes 10+ minutes and has the potential of destroying the entire infra. I'd love to split it into multiple "micro stacks", but I'm too afraid to start splitting that giant mess of a state file by myself. Thanks for any guidance 🙏

**Comment by mattfysh** [comment]
so I'm trying to refactor into microstacks as pulumi now recommends, and god almighty this has got to be the most painful week of my career

how has anyone not mentioned this message yet?

> inputs to import do not match the existing resource; importing this resource will fail

also, some providers (looking at you upstash) have implemented importers that don't even work

to @ami-descope - i'm seeing the issue you mentioned with aliases

so I guess I'll be up all night wielding some gnarly stack import/export commands

i used to be absolutely enamoured with pulumi 😢

**Comment by ami-descope** [comment]
From what I understood, the stack and project keys in the alias field or even the urn format is misleading. It makes you think that pulumi can find the project and stack, but the reality is that the stacks and projects are isolated and pulumi doesn't do the lookup

**Comment by casey-robertson-paypal** [comment]
it's pretty poor to have this still open 4+ years later.  it's EXTREMELY common for stack structures (and dev orgs) to morph over time.  Not having guidance on de-monolithing Pulumi projects/stacks is a big miss

**Comment by casey-robertson-paypal** [comment]
@mattfysh - do they officially recommend the micro-stacks somewhere?

**Comment by mattfysh** [comment]
@casey-robertson-paypal in these docs https://www.pulumi.com/docs/using-pulumi/organizing-projects-stacks/

I suggested they add a warning to that page about the lack of a `transfer` command, or at least discuss these challenges in the docs and suggest workarounds. They agreed but that was a couple of months ago and they still haven't added it.

**Comment by justinvp** [comment]
Support for this is now available. See https://www.pulumi.com/blog/move-resources-between-stacks/ for details.
