### ISSUE TITLE
StackReference doesn't support multiple backends

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi#3395]
Currently, I need to use a single `pulumi login gs://bucket/directory` to utilise `StackReference`

This means my stack names, for each project, can have no collisions; as the project name isn't part of the path used to store state.

**Example:**

```
- mybucket/project1/.pulumi/production.json
- mybucket/project2/.pulumi/production.json
```

If I used the same `pulumi login` for these projects, to adopt `StackReference`, I'd have a problem.

If I could specify the complete path in `StackReference`, I think that would allow me to utilise this pattern.

**Comment by lukehoban** [comment]
Just to cross reference - several of the issues here are rooted in https://github.com/pulumi/pulumi/issues/2522.

**Comment by Kukunin** [comment]
Another potential solution is doing something similar as we did with Terraform: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/terraform/state/#RemoteStateReference - having a separate state reader for remote backends: s3, gs etc.

**Comment by justinvp** [comment]
Yes, I think we can close this issue. With #2522, you can now reference stacks within a backend using `organization/<project>/<stack>`, so there's no longer a need to use multiple separate backends to avoid stack name collisions. However, you still cannot reference stacks across backends.

**Comment by sfrique** [comment]
@justinvp is there any plans to be able to reference stacks across backends?

**Comment by eddieatbrumaline** [comment]
> [@justinvp](https://github.com/justinvp) is there any plans to be able to reference stacks across backends?

Bumping this as I am currently looking for this exact feature (I think). 

When using S3 backend, for example, it seems to make sense to put isolated Pulumi projects in different "folders" or paths in the same bucket. Unfortunately, if you do so you will not be able to reference stack outputs across these projects (or so it seems). i.e. In order to make use of stack references your projects must all be configured to use the same path (backend) in the S3 bucket.

If my understanding is correct, I'd love to upvote the prioritzation of this functionality. If my understanding is incorrect, and this is already possible somehow, I'd love to learn how to accomplish this with the S3 backend.

Thanks!
