### ISSUE TITLE
Assertion failure: Two resources aliased to the same URN

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3421]
Under normal usage, I've begun hitting the following assertion:

`panic: fatal: An assertion has failed: Two resources ('urn:pulumi:dev::iac-workshop::awsx:x:ec2:Vpc::default-vpc-eb926d81' and 'urn:pulumi:dev::iac-workshop::awsx:x:ec2:Vpc::default-vpc-00c55568') aliased to the same: 'urn:pulumi:dev::iac-workshop::awsx:x:ec2:Vpc::default-vpc'`

The program is as follows:

```typescript
import * as awsx from "@pulumi/awsx";

const cluster = new awsx.ecs.Cluster("cluster");

const alb = new awsx.lb.ApplicationLoadBalancer(
    "net-lb", { external: true, securityGroups: cluster.securityGroups });
const web = alb.createListener("web", { port: 80, external: true });

const containerImage = awsx.ecs.Image.fromPath("app-img", "./app");

const appService = new awsx.ecs.FargateService("app-svc", {
    cluster,
    taskDefinitionArgs: {
        container: {
            image: containerImage,
            portMappings: [ web ],
        },
    },
    desiredCount: 1,
});

export const url = web.endpoint.hostname;
```

I did a number of updates that led to this outcome, including rebuilding the container image, changing desiredCount, etc. But for the most part, nothing terribly exotic.

The checkpoint file is [TwoUrnCheckpoint.json.gz](https://github.com/pulumi/pulumi/files/3784116/TwoUrnCheckpoint.json.gz)

**Comment by lukehoban** [comment]
> I had deployed my stack to a certain account and accidentally ran the update from a different one.

Ahhh - I was wondering how there could be two different default VPCs when I first looked at this - this makes more sense!

> I make this mistake often — wish we had a way to warn or something 

I *think* that https://github.com/pulumi/pulumi-terraform-bridge/issues/14 will allow us to catch this and either warn or potentially make the change in provider account lead to a replacement of the provider and hence of all the resources managed by that provider.

> I am a little surprised this was the symptom, and obviously we ought not to ever panic for regular operator errors, but I guess priority is lower than I initially thought.

Agreed with this - although until we address https://github.com/pulumi/pulumi-terraform-bridge/issues/14 I suspect there are a *ton* of strange ways that changing accounts can lead to odd failures.  We should consider specifically reporting a real error instead of an assert here.

**Comment by pgavlin** [comment]
The panic originally associated with this report has been fixed--we now return an error in this case. @lukehoban is this tracking anything besides that?

**Comment by lukehoban** [comment]
I think we can close this - the remaining work is in https://github.com/pulumi/pulumi-terraform-bridge/issues/14 - will add a reminder there about warning or replacing on account changes.
