### ISSUE TITLE
Additional CLI verbs for stacks

### ISSUE THREAD

**Issue by m4dc4p** [pulumi/pulumi#3535]
I'm using pulumi to deploy instances of our app for PRs; I have a script that runs when the PR is first opened and on each update. In all cases I'm creating (or updating) a stack specific to that PR.

I'd like to know if a stack exists yet because I have to run init at least once. Right now, I run it everytime but trap the error in cases where the stack already exists.

I'd also like to know if the stack is currently being updated because I'd like to bail out of the deployment script early if that's the case.

**Comment by chrsmith** [comment]
Quick update here:

> I'd like to know if a stack exists yet because I have to run init at least once. Right now, I run it every time but trap the error in cases where the stack already exists.

I don't see a super-elegant way to implement this right now. Since adding a specialized verb to check if a stack exists or not seems a little too specialized.

But we could just return a well-known exit code for the "stack not found" case, which would make `pulumi` much more amenable to scripting. e.g.

```
pulumi stack select foo/bar/baz
# pulumi returns exit code 404 if the stack isn't found.
if [ $? eq 404]; then
     pulumi stack init foo/bar/baz
fi
```

But suggestions/ideas certainly welcome. (cc @justinvp in case you have some thoughts.)

> I'd also like to know if the stack is currently being updated because I'd like to bail out of the deployment script early if that's the case.

This I think we can do without needing a dedicated verb. When you run `pulumi stack` we print summary information about the currently selected stack. It is just a matter of wiring the additional  "is currently being updated" information back to the CLI.

I opened https://github.com/pulumi/pulumi-service/issues/4468 to track doing the work on the Pulumi Service backend.

**Comment by m4dc4p** [comment]
Sounds like a reasonable approach to me.

**Comment by andreujuanc** [comment]
I was surprised that this is not currently implemented in the CLI. Specially since some organizations may have several dozen apps, each with its own environments, etc. 

One cannot just assume that one person is going to manually do init on each project per environment. Or as @m4dc4p is doing, creating a temporary deployment for PRs.

I would suggest for example something like this:
```bash
pulumi stack select foo/bar/baz --non-interactive --create
```
This ideally creates the stack if it doesn't exists, and never asks for any confirmation. Which would make it perfect for CICD pipelines.

Cheers!
