### ISSUE TITLE
.Net 'Core3.0' or 'Standard2.0' for our .Net SDK

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#3579]
Currently we use .Net core 3.0 for our .NET sdk.  This has a few advantages for us. Specifically:

1. 'Core' is effectively the only supported/maintained platform moving forward.  Both 'Standard' and 'Framework' are effectively 'fixed' and won't get more than bug fixes.
2. New versions of C# will not support targeting 'Standard' due to the usage of features that 'Standard' will not support at all (like Default-Interface-Methods).  So we can be used by future versions of the language.
3. We get to use the most modern APIs that .net is supplying (ranges/indexes/async-streams/pipes/json/etc.)

The disadvantage here is that we are locked out from using analyzers *and* having them work in VS.  They are only supported from the command line.

To get analyzers working in VS (which only works with .net standard), we would have to retarget down to .Net Standard 2.0.  However, this comes with a set of disadvantages we would have to be ok with:

1. .Net standard 2.0 is effectively legacy at this point.  It is getting no future attention beyond bug fixes.
2. This means that future C# language versions will not support it, limiting our customers if they want to use those versions.  This impacts us if we want to get their future NRT improvements which might significant improve the usability of our SDK.
3. We will not be able to use any 'modern' .net APIs (either internally on through our surface).  We will have to find and use alternatives and explain to users why they need to use these.

This basically comes down to a question of: Are analyzers worth it to basically lock us into a fixed point in the past and to not be able to keep up with .Net as it moves forward? Or, should we stick with Core and assume that MS will think analyzers are important enough to create a story for them in the future?

**Comment by Liversage** [comment]
Recently .NET Core 3.1 was released. This is an LTS version (Long Term Support) so should definitely be preferred over .NET Core 3.0.

The "matching" .NET Standard version is .NET Standard 2.1 which supports all the newer features and for library projects that don't require what .NET Core 3 provides (like WPF support) this should be the preferred version unless you need to target lower versions.

I don't understand your statement that 'Standard' is 'fixed' and only will get bug fixes moving forward. Perhaps things will change with the next big version of .NET (version 5) where the distinction between 'core' and 'full framework' will go away but that shouldn't affect how you use the current version of .NET Core where framework monikers like `netcoreapp31` and `netstandard21` both are part of the latest version of .NET Core. It is true that some of the features of the latest version of C# (version 8) only works in the latest releases of .NET Core. For a library project you need to target `netstandard21` to enable these features but for older framework versions you can still use new C# features as long as they don't require framework support.

I haven't tried to write my own Roslyn-based analyzer but I'm surprised that analyzers would not work with anything newer than .NET Standard 2.0. Or perhaps I'm misunderstanding your statement? I certainly have analyzers working without problems in my .NET Core 3 projects.

However, as Visual Studio uses .NET full framework I would guess that the analyzer (as a separate project) would have to target .NET Standard 2 (which is compatible with .NET Framework 4.8). Having to use a specific version of a framework to be able to create something that plugs in to a host is not surprising but that doesn't have to affect your choice of framework in other projects.

For broadest reach you should target `netstandard20` but for the newest features `netstandard21` is better. Visual Studio 19.4 is required to be able to develop using `netstandard21`. Analyzers should be written using whatever is required by the platform required to run the analyzer.

**Comment by CyrusNajmabadi** [comment]
> I haven't tried to write my own Roslyn-based analyzer but I'm surprised that analyzers would not work with anything newer than .NET Standard 2.0. Or perhaps I'm misunderstanding your statement? I certainly have analyzers working without problems in my .NET Core 3 projects.

Do you have them loading in VS?

**Comment by Liversage** [comment]
> Do you have them loading in VS? If so, can you point to your .net 3 core analyzer that gets loaded in VS? i'd like to see how you did that.

Again, I fear that I might be misunderstanding exactly what you mean by "loading". However, as I already said you will have to write your analyzer in a way that is compatible with Visual Studio (so it can be loaded into the Visual Studio process), and I'm not surprised that you will have to use full framework or .NET Standard 2.0. That shouldn't affect your choice of framework for your own projects.

And if you for your own projects decide to use the newest version of .NET Core (which is `netcoreapp3.1` and `netstandard2.1`) then you can "load" analyzers in Visual Studio without any problems. Here is a screenshot of a `netcoreapp3.1` project:

![image](https://user-images.githubusercontent.com/3593901/70868156-0ba62680-1f7e-11ea-99ea-fdc065799345.png)

Most of these analyzers are created by Microsoft and to me that is a strong signal that analyzers are an important part of .NET now and in the future.

I guess that if you are writing an SDK and you also want to provide analyzers and you for some reason have decided that everything in your code base should use the same .NET framework then you will have to use .NET Standard 2.0 but that seems like an odd requirement.

On the other hand .NET Standard 2.0 is fine unless you want to use nullable reference types, ranges, default interface implementations and probably a few other C# 8 features. Some of these can actually be used with .NET Standard 2.0 if you don't mind a bit of hacking.

**Comment by CyrusNajmabadi** [comment]
> Again, I fear that I might be misunderstanding exactly what you mean by "loading".

Meaning: someone references our .netcore3 SDK, and inside VS they see our analyzers 'light up' such that we can report issues when they are potentially using the sdk incorrectly.

**Comment by CyrusNajmabadi** [comment]
> However, as I already said you will have to write your analyzer in a way that is compatible with Visual Studio (so it can be loaded into the Visual Studio process)

Right.  And it sounds like that means not using .netcore3, right?

**Comment by CyrusNajmabadi** [comment]
> That shouldn't affect your choice of framework for your own projects.

I'm not understanding this bit.  This *is* "our own project".  So if we are limited in terms of what frameworks we use... then we are affected...

**Comment by CyrusNajmabadi** [comment]
> On the other hand .NET Standard 2.0 is fine unless you want to use nullable reference types, ranges, default interface implementations and probably a few other C# 8 features. 

Yes, but it also limits from other things.  For example, being able to use the new json libraries (i believe) as well has not having full access to all the NRT features.

> Some of these can actually be used with .NET Standard 2.0 if you don't mind a bit of hacking.

I would mind that tbh.  I find whne you go off the supported path, eventually something ends up not working.  And you're then on the hook to deal with that.

**Comment by Liversage** [comment]
> > Again, I fear that I might be misunderstanding exactly what you mean by "loading".
> 
> Meaning: someone references our .netcore3 SDK, and inside VS they see our analyzers 'light up' such that we can report issues when they are potentially using the sdk incorrectly.

To do this use `netstandard2.1` for the SDK (because you said _.netcore3_ and for libraries I think `netstandard` and not `netcoreapp` should be the preferred choice). Write the analyzers using whatever technology required to create a Roslyn-based analyzer that works with Visual Studio.

NuGet packages:

- `Pulumi` - `netstandard2.1`
- `Pulumi.Whatever` - `netstandard2.1`
- `Pulumi.Analyzers` - older version of .NET Standard or full framework (which is required to create an analyzer)

Notice that by creating an SDK that targets `netstandard2.1` you require that your users have the latest version of Visual Studio (16.4). My experience with some larger organizations is that developers may not always be able to upgrade to the latest version. This might prohibit some potential users from being able to use the SDK until later.

I would think that picking the "right" framework for the SDK to gain broad reach while not using a needlessly old version is important. I don't see why the technology used to develop analyzers should factor into this decision. Is there a reason for that?

Also, if you are unsure what you can do in `netstandard2.0` vs. `netstandard2.1` why not start out with the older version with broader reach and then, when you are missing a feature, consider if the value of this feature is worth upgrading your project?

With regards to `System.Text.Json`: This NuGet package is also compatible with .NET Standard 2.0 and full framework so that doesn't force you to use `netstandard2.1`.

For application work I recommend the latest version of .NET Core but for library/SDK work you should consider if not all "downstream" users can use the latest version and perhaps pick a lower version for broader reach.

**Comment by CyrusNajmabadi** [comment]
> Is there a reason for that?

Yes. I would prefer to avoid these arbitrary choices just to appease visual studio. My preference would be to use the same tech/apis/dll for everything we release. It's much simpler and saner. 

I understand this may not be possible. But it would certainly be my preference

**Comment by damianh** [comment]
The point about `netstandard` is to define an API contract that is supported across various version of platforms (netfx, mono, unity, xamarin etc). Packages like `System.Text.Json`, `Microsoft.Extensions.Configuration` etc are expected to be usable across platforms hence they target `netstandard2.x` for reach. Nobody is expecting ASP.NET Core 3.1 to run on any platform other than .NET Core 3.1 hence why it targets `netcoreapp3.1` *only*. Netstandard provides a bridge that is becoming less relevant.

Will pulumi ever be run on anything other than dotnet core i.e. mono/unity/xamarin etc? If not, then there is no point in targeting `netstandard2.0`/`netstandard2.1` - just stick to `netcoreapp`

The question is which netcoreapp version to support. Generally one should stick to LTS version(s). Because pulumi .net support is new and there isn't an existing ecosystem to support, then I will argue that you can skip `netcoreapp2.1` and go straight to `netcoreapp3.1`. When `net5` arrives, you'll likely have to support that and `netcoreapp3.1` concurrently for a period of time. 

The argument of enterprises not being on a version of Visual Studio that supports `netcoreapp3.1` is only something your market research can answer. (Such orgs tend to be conservative (late majority/laggards) so I'd find it surprising if they were Pulumi customers 😉 ) 

Regarding analyzers - yes it looks like they need to be targeting `netstandard2.0` at this time. I expect that to remain the case until at least `net5` and I expect MS will create a future story for that.

So I suggest:
- All Pulumi packages that are not analyzers move to `netcoreapp3.1` (`netcoreapp3.0` support ends March 3, 2020)
- Any Pulumi analyzer packages target netstandard2.0 for the foreseeable future.

What I do not suggest is downgrading all packages because of the analyzer issue.

**Comment by mikhailshilkov** [comment]
I think our decision is to target .NET Core 3.1 for all SDKs. This is tracked in #3740 and I'll start the transition shortly. This is regardless of whether we can make analyzers work, which I suggest tracking in #3808 and #3580.
