### ISSUE TITLE
[BREAKING] Make NodeJS invokes asynchronous in the engine

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3693]
As part of the plan outlined in https://github.com/pulumi/pulumi/issues/3528, we will as part of Pulumi 2.0 make a breaking change to not allow synchronous access to the results of invokes (i.e. `.getAbcd()` methods).  The approach to enabling this in Pulumi 1.0 was not safe for NodeJS, and led to hangs and crashes.

**Comment by lukehoban** [comment]
This is done now in the `2.0` branches.

**Comment by joeduffy** [comment]
I can't wait for the 2.0 release. I just spent 30 minutes debugging why gRPC was failing with mysterious `AssertionError: Failure: Decoder hit an error` errors ... only to realize that `async: true` isn't yet the default for data sources and somehow(?) it was caused by that 🤦‍♂ 

Adding an explicit `async: true` made it go away.

Figured I'd mention it here in case it helps someone down the line when Googling for this error.
