### ISSUE TITLE
Enable `mypy` on Python SDK and get clean on MyPy errors

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3710]
Today we have type annotations on most of our Python SDK, but we do not run any typechecker to validate the types.  We should add this typechecker as an additional linter (and possibly configure default VS Code and other IDE integration settings in this workspace to run it interactively).

When I do try running `mypy` on our existing SDK, I get around 150 errors reported across the core SDK - spot checking, they are indeed all real places where we are disobeying the types (and many could be latent bugs).

Once we are clean, we should make sure we are distributing types as part of our package as defined by  PEP 561 and addressed in https://github.com/pulumi/pulumi/pull/3704.

**Comment by EvanBoyle** [comment]
Technically, the work here will involve some breaking changes. For example: 

https://github.com/pulumi/pulumi/blob/evan/mypy/sdk/python/lib/pulumi/output.py#L110

We believe this is OK because we aren't currently publishing our types. Existing mypy users will likely have a config line ignoring the pulumi package. If anyone is somehow depending on our types today, they aren't correct and this should strictly be an improvement.

I'll be sure to note anything material in the PR if I discover it along the way.
