### ISSUE TITLE
Python: `pylint(no-member)` error on `Resource.id `

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/pulumi#3765]
Even though the code is actually working, `pylint` by default shows an error when I code `resource.id`.
A way to avoid the `pylint` error is to use `getattr(resource, 'id')` but it is verbose and inelegant.

Is there a way to fix this linting error ?

![image](https://user-images.githubusercontent.com/6024791/72570113-4a503900-38bc-11ea-9124-88abb92a18b5.png)

**Comment by lukehoban** [comment]
@LouisAmon I have tried several things - but have not been able to reproduce this.  Do you have a self-contained repro - even just a project folder you could zip up along with its` venv`?  I'm going to close as no-repro for now - but if you or anyone else does still see this - please do let us know and we'll reopen.

**Comment by LouisAmon** [comment]
Fair enough.

I don't have time to come up with a nice example right now but just FYI : the issue is still here.

```
pylint __main__.py
```

Then I obtain the output:
```
__main__.py:127:20: E1101: Instance of 'Zone' has no 'id' member (no-member)
```

(Visual Studio Code does it natively too)

My solution is to put `zone_id=zone` instead of `zone_id=zone.id`, but that'd still a hack

**Comment by lukehoban** [comment]
I've heard a couple more reports of this - so re-opening so that we can look into it further.

**Comment by solidDoWant** [comment]
I am experiencing this on pyling 2.4.4 with pulumi-aws 1.18.0 on pulumi 2.1.0. This shows up on any resource where I refer to the ID.

**Comment by mattberns** [comment]
Also seeing this with pylint. Very confusing. Code is working...

Instance of 'whatever' has no 'id' member

**Comment by justinvp** [comment]
Here's a description of this message from http://pylint-messages.wikidot.com/messages:e1101:

> Used when an object (variable, function, …) is accessed for a non-existent member.
>
> False positives: This message may report object members that are created dynamically, but exist at the time they are accessed.

This is a false positive because `id` isn't set in the initializer method, it's set later in `register_resource` and Pylint isn't able to figure this out statically.

We may be able to address this in the Python SDK by setting `id` earlier in a way that Pylint can figure out.

If that's not possible, another option would be to [implement a Pylint plugin](http://pylint.pycqa.org/en/latest/how_tos/transform_plugins.html) (e.g. `pylint-pulumi`) to make Pylint avoid emitting these messages for such cases. Such a plugin would be similar to the [`pylint-django`](https://github.com/PyCQA/pylint-django) plugin, which is used to workaround similar issues (and more) when using Django. We could publish `pylint-pulumi` to PyPi and update our Python templates to depend on it, along with including a `pylintrc` file that enables the plugin by default.

In the meantime, users can workaround this by adding `# pylint: disable=E1101`, e.g.:

```python
pulumi.export('bucket_name', bucket.id) # pylint: disable=E1101
```

Note: This happens with `urn` as well.
