### ISSUE TITLE
Smaller Docker images, one for each language

### ISSUE THREAD

**Issue by Dominik-K** [pulumi/pulumi#3789]
The current [`pulumi/pulumi` Docker image `v1.8.1.`](https://hub.docker.com/layers/pulumi/pulumi/v1.8.1/images/sha256-e2239928f3dfe52ddb38deda5ddcb41e71e295e4d70fbd1276bd8cfc3e025c88) is **2.44GB** big (compressed: 694.17 MB). Mainly because it contains all frameworks for the different languages. That makes CI builds unnecessary long & using it locally is really uncomfortable, especially when you have small bandwidth available (train, etc.).

I suggest to publish Docker images for each language as a specific image tag. E.g. `pulumi/pulumi:1.8.1-node` for the Typescript version (similar like @Charliekenney23 [suggested](https://github.com/pulumi/pulumi/issues/2891#issue-462439168)). That will reduce the image size down to ca. **200MB** (as @boillodmanuel  [showed it in another issue](https://github.com/pulumi/pulumi/issues/1986#issuecomment-544866074)).

**Comment by piclemx** [comment]
@chrsmith any news on this one?

**Comment by chrsmith** [comment]
No update as of right now, sorry @piclemx . It's something that I've wanted to get to for a while, alas [we've been busy](https://www.pulumi.com/webinars/pulumi-update-2020-04-29/) with a lot of things. However, I will land https://github.com/pulumi/pulumi/pull/4354 soon, which will at least make it much easier to build/test/verify any new containers we publish. So 🤞 this will happen sooner rather than later.

**Comment by piclemx** [comment]
No problem @chrsmith, let me know if you want helps on this. Will be happy to contribue.

**Comment by jaxxstorm** [comment]
@chrsmith after looking at #4599 I had a look at this here:
https://github.com/jaxxstorm/pulumi-docker

Let me know what you think. The images are quite a bit smaller. I'm happy to take this and run with it if you need.

**Comment by chrsmith** [comment]
@jaxxstorm yeah, that's ~exactly what I was thinking we'd want to do! Please do go and run with it :)

There are a few design considerations I think we'd need to answer before we "ship" these, just so that we know how it is we recommend people use them.

- The containers all have `pulumi` as an entry point. For running Pulumi locally that's fine. But when hooked up to a CI/CD system, you usually need to look at the current environment before figuring out what to do. (e.g. on a `pull_request` job type, run a `pulumi preview` against a certain stack. Whereas on a `push` job to `master` run `pulumi up` against one stack, and on a `push` job to the `production` branch, run `pulumi up` against another.)

How you configure or encode that "branch to stack mapping" is something that IMHO would be a great thing for us to spend cycles on. (Not a requirement for publishing slim containers, of course, but as a way to have good instructions for how to _use_ them.)

You can put all that logic into your GitHub Actions workflow or `.travis.yml` file, so there is a solution for now. But in the past we've discussed having a ~/.pulumi/config.json` file or something, that `pulumi` could read and use that to determine what steps to run. (Just food for thought.)

- It doesn't look like the containers are downloading packages from the common, language-specific package manager. (e.g. running `yarn` or `nom install` before `pulumi`.) That's something that we do in the GitHub Actions container that makes things a bit easier to use.

Since in the past, we've had people get confused when running the base Pulumi container and seeing errors about plugins or dependencies not being available.

So we may want to have a language-specific `pulumi.sh` as an entry point, to optionally download dependencies depending on the presence of a lock file or something. (But again, not something we need to block shipping slim downed containers on. It's just a tradeoff between how much work we want to do on behalf of users, vs. requiring users to do that configuration on their own.)

**Comment by jaxxstorm** [comment]
@chrsmith this is great feedback. I think the entrypoint point is very valid, and to (temporarily) get around it, I might actually remove the entrypoint to allow flexibility. For example, testing locally:

```
docker run -e PULUMI_ACCESS_TOKEN=<TOKEN> -v "$(pwd)":/pulumi/projects $IMG /bin/bash -c "npm ci && pulumi preview -s digitalocean"
```

I'll look at creating an entrypoint script like you suggest which does the legwork for users. Should I take this issue for the time being, and we can chat more in our sync this week?

**Comment by chrsmith** [comment]
> I'll look at creating an entrypoint script like you suggest which does the legwork for users

I'd suggest starting with something like https://github.com/pulumi/pulumi/blob/master/dist/actions/entrypoint.sh, which has been slowly accumulating random requests and things. (e.g. evidently if using GCP you need to run `gcloud auth activate-service-account` before `pulumi`, etc.)

> Should I take this issue for the time being, and we can chat more in our sync this week?

Yes, please do. Sadly it's just collecting dust being assigned to me.

Currently we publish two containers, `pulumi/pulumi` (with just the CLI, all runtimes, no entry point) and `pulumi/actions` (all runtimes, custom entry point).

I can see us following a similar pattern for these slimmed down containers. One that just contains the specific language runtime, e.g. `pulumi-go1.13` and another one that has an opinionated entry point for selecting the stack/downloading dependencies. Something like `pulumi-go1.13_cicd`.

So perhaps all that additional work would be part of publishing that latter container. But what you have today is maybe sufficient for shipping the former.

**Comment by lukehoban** [comment]
A meta-question related to this discussion is what are the full set of images we need.  Today we have two:
1. `pulumi/pulumi`
2. `pulumi/actions`

The former has `ENTRYPOINT ["pulumi"]` and the latter has `ENTRYPOINT ["/usr/bin/pulumi-action", "--non-interactive"]` which is a "smarter"/"more opinionated" entrypoint that can automaate some common CI workflows.

And today, the latter builds on top of the former.

I *think* @chrsmith's feedback is relative to containers which serve the needs of things like (2).

More broadly - there are a number of different use-cases for a "pulumi image":
1. A simple way to directly use the `pulumi` CLI on a developer desktop
2. An image to directly use within a CI setup with no modification
3. A base image to use to build a customer environment for a CI setup
4. Probably others?

Which of these use-cases are we trying to serve with each of the images we have now or will have once we've done the work tracked here?

**Comment by piclemx** [comment]
@lukehoban I think the most use case will be more option 2 and 3.

**Comment by tenwit** [comment]
My team and I are dependent on case 1. Quite happy to just have an "actions" image and then use `--entrypoint pulumi` when working locally though.

**Comment by boillodmanuel** [comment]
Hi,
I just wanted to add some insight about this topic.

## Entrypoint

For me it doesn't matter if you set `pulumi` as an entrypoint or not, since it's consistent across all images. Just document how to skip it if needed. Today I use this command :
```bash
docker run --entrypoint="" pulumi/pulumi:v2.0.0 /bin/bash
```
or in my gitlab pipeline (which is less obvious):
```yaml
deploy:
  stage: deploy
  image: 
    name: pulumi/pulumi:v2.1.0
    entrypoint: [""]
  script:
    - pulumi up --stack ${CI_COMMIT_REF_NAME} --non-interactive --yes
```

## Script entrypoint

> So we may want to have a language-specific pulumi.sh as an entry point, to optionally download dependencies depending on the presence of a lock file or something

I'm not sure you can add an entrypoint script that fit everyone needs. 
For example, in some of my cicd pipeline, I do:
- force a pulumi logout / login
- do a npm install from current folder
- do a npm install into two nested folders
- etc.

If you keep the entrypoint very simple, everyone will be able to do what they want. Otherwise, we'd have to override default behaviour (which is not very easy, especially when not documented :) )

In the same way, I sugget to keep it simple and document some use cases to prevent user to get confused.

- locally :
```bash
npm install
docker run ....
```

- ci/cd :
```bash
# in docker image :
pulumi login
npm install
pulumi up...
``` 

## git stuff (stack / branch mapping, PR, ...)

I'll share you what I'm doing with git.

I use gitops approach, and I use a 1-1 mapping between stack and branch. The stack name shoud be the branch name. It's very simple, but works based on convention (no json file required here) 😄 

It works like a charm for branch that matchs with a pulumi stack (ex: `prod` and `dev` branch/stack).

When we create a feature branch (ex: `fix/xxx`), there is no corresponding stack, so we don't do `pulumi up`. But when we open a pull-request against `prod` or `dev` branch, we run a `pulumi preview --stack ${PR_TARGET_BRANCH)` in order to preview changes before merging.

So, the ci/cd pipeline relies on 2 things:
- We have to detect if there is a stack that match the branch name (if there is a `pulumi.<branch>.yml` file)
- We have to detect if we are in a PR or not. In case of PR, we don't use the current branch but the PR target branch. 

That's all. I hope this could help you.

Manuel
