### ISSUE TITLE
Expose the engine's logging interface from the Go SDK.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#3801]
Just what it says on the tin.

**Comment by lukehoban** [comment]
This will be porting this functionality (https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/log.py) into the Go SDK.

I think there are three API design options:
1. `ctx.Log.Info(...)`
1. `ctx.LogInfo(...)`
1. `log.Info(ctx, ...)` in a `"github.com/pulumi/pulumi/sdk/go/pulumi/log" package

My personal preference would be (1) as it seems most consistent with other Pulumi SDKs.  @EvanBoyle @pgavlin @tasiah thoughts?

**Comment by EvanBoyle** [comment]
Do we want to maintain compatibility with the existing engine go logging
interface and the ability to specify verbosity, and filter based on command
line?

**Comment by lukehoban** [comment]
> existing engine go logging interface 

What exactly do you mean by this?  Do you mean the internal `glog` logging inside the engine?  If so then no, that is a different logging mechanism than our enging gRPC logging interface.  The work here is to port the existing engine logging interface that's available to Node.js, Python and .NET to also be available to the Go SDK.

**Comment by tasiah** [comment]
I think (1) would make the most sense for consistency, but because all the information is in `pulumi.Context`, having a new `Log` struct within `pulumi.Context` with some duplicated fields (`pulumrpc.EngineClient`, `context.Context`) would probably make the actual implementation a little stylistically questionable. Because that probably doesn't make much sense, I'm going to implement (1) and then you can see/decide for yourself 😅.
