### ISSUE TITLE
Improve missing required property errors in .NET

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3808]
Ideally we could give you interactive errors (at development time, in the IDE) when you are missing a resource's required property in .NET. Right now, we issue errors dynamically:

```
    error: Running program '/Users/joeduffy/temp/DotNetApp/dotnet-core-tutorial/Infrastructure/bin/Debug/netcoreapp3.0/Infra.dll' failed with an unhandled exception:
    System.ArgumentNullException: [Input] Pulumi.Aws.ElasticLoadBalancingV2.ListenerArgs._defaultActions is required but was not given a value (Parameter '_defaultActions')
       at Pulumi.InputArgs.ToDictionaryAsync()
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**Comment by lukehoban** [comment]
My recollection of the dozens of conversations we had on this topic during design of the Pulumi .NET APIs was:
1. C# does not currently offer any way to express this in its type system
2. Others have built Roslyn analyzers to work around this
3. Building a Roslyn analyzer May have implications for the .NET platform we target (https://github.com/pulumi/pulumi/issues/3579)  

@mikhailshilkov and @CyrusNajmabadi are the experts.

**Comment by ardalon** [comment]
How about something like for example: 
`public class Vpc : CustomResource {
        public Vpc(string name, VpcArgs args, [NullableAttribute(2)] VpcOptions? = null, [NullableAttribute(2)] CustomResourceOptions? options = null);
`
or simply:
`public class Vpc : CustomResource {
        public Vpc(string name, string cidrblock, string someOtherRequiredArg, string yetAnother, [NullableAttribute(2)] VpcOptions? = null, [NullableAttribute(2)] CustomResourceOptions? options = null);
`
This will prompt us to provide what is required (by a nagging squiggly underline in the IDE) as well as a mention in the Errors/Warnings window.

**Comment by mikhailshilkov** [comment]
Hi @ardalon thanks for your ideas!

The first option doesn't prevent you from `new Vpc("name", new VpcArgs())` (unless you use constructor parameters for `VpcArgs` - see below then).

We decided not to use constructor parameters and use property bags instead. Any change in the order of constructor parameters other than appending at the end is a breaking change. Given that we generate our SDKs, it would be pretty hard for us to avoid breaking existing resources. Also, resource APIs may get quite confusing over time as the order of parameters would be defined by the date of their respective introduction.

Arguably, calling a constructor with many arguments is not a great experience in C#, unless they are consistently named.

It's unlikely we'd want to move away from property bags in the nearest future. So, this case track finding a way to enforce filling required properties, either with tooling or with new language features, if they appear.

**Comment by ardalon** [comment]
Hi @mikhailshilkov, thank you -- I'm really enjoying my trial of Pulumi, I'm definitely considering promoting its use over Terraform (TF), especially as I am often trying to inspire a team of devs to embrace Infrastructure as Code (and they are discouraged when I tell them they have to learn yet another DSL).  

Personally speaking, I did not become truly productive with TF until I had found an TF/HCL plugin for intellij (that I still use daily).  It provides basic support for completing resource/module/variable names and highlighting missing required params in every resource block. This is why I'm interested in this particular issue on here, because if we can have those conveniences along with the power of C# it would make Pulumi an even bigger game changer. 

If you're generating your C# SDK (and other languages) then I understand you're limited in what you can do.  Although at some point you may want to take advantage of some of the really powerful language specific features C# offers (for example advanced Dependency Injection support).  I suppose you may consider this once there is wider adoption of Pulumi. 

In the meantime, I've started writing my own factories for Pulumi resource classes as I go and has been working well.

**Comment by mikhailshilkov** [comment]
@ardalon Thanks for taking the time to describe this - really appreciated! It totally makes sense, and we do want our users to feel fully empowered by their programming languages. We'll keep thinking about how to improve this!

**Comment by MisinformedDNA** [comment]
> We decided not to use constructor parameters and use property bags instead. Any change in the order of constructor parameters other than appending at the end is a breaking change. Given that we generate our SDKs, it would be pretty hard for us to avoid breaking existing resources. Also, resource APIs may get quite confusing over time as the order of parameters would be defined by the date of their respective introduction.

@mikhailshilkov A breaking change would not be required if we generated multiple constructors, right?

In the case of KeyVault (since that's what's in front of me), we would have two constructors

```csharp
public KeyVault(string name, KeyVaultArgs args, CustomResourceOptions? options = null);

public KeyVault(string name, string resourceGroupName, KeyVaultArgs args, CustomResourceOptions? options = null);
// or
public KeyVault(string name, ResourceGroup resourceGroup, KeyVaultArgs args, CustomResourceOptions? options = null);
```

or in the case of `KeyVaultArgs`:

```csharp
public KeyVaultArgs();
public KeyVaultArgs(string skuName, string tenantId);
```

All code would continue to work, but there would be a new, improved, optional way.

In terms of auto-generated parameter order, we could have a JSON file defining order and whatever isn't listed in the file would just be put in alphabetical order. Or it would compare against previous runs (or logs from those runs) to keep parameters in the same order.

> calling a constructor with many arguments is not a great experience in C#

I'd argue that's not true, but even if it were, I'd want focus on giving developers a good _Pulumi SDK experience_. It's all about the tight loop and early feedback.

**Comment by MisinformedDNA** [comment]
@lukehoban 

> Others have built Roslyn analyzers to work around this

For Pulumi? Or just in general?

**Comment by lukehoban** [comment]
> @lukehoban
> 
> > Others have built Roslyn analyzers to work around this
> 
> For Pulumi? Or just in general?

For other platforms that face this same problem. I don’t know if anyone who has yet built one for Pulumi. If anyone has or does - please do share here. This issue continues to track delivering such an extension.

**Comment by MisinformedDNA** [comment]
I've never built an analyzer, but I might give it a go. I'll let you know if I get anywhere.

**Comment by Zaid-Ajaj** [comment]
Since [PulumiCSharpAnalyzer](https://github.com/Zaid-Ajaj/pulumi-csharp-analyzer) is released and can be used right now, we can consider this issue as _resolved_. [Blog post](https://github.com/pulumi/pulumi-hugo/pull/1702) is about to be published to tell users more about it
