### ISSUE TITLE
Consider more efficient checkpoint patch protocol

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3930]
At the moment, we upload the entire checkpoint file before and after performing any mutating resource operation. This is theoretically quite wasteful given that the delta implied by any single operation is normally quite small -- as seen below, typically just modifying the checkpoint's update time, the pending operations list, and the resource state for that single resource being modified. The net effect here is a lot more data being sent over the network than is really required, causing performance problems that are exacerbated by number of resources in your stack as well as geography. (These problems are presumably far less bad after https://github.com/pulumi/pulumi/pull/3860 landed, but are still sub-optimal.)

As an experiment, I used [a Go JSON Patch library](https://github.com/mattbaird/jsonpatch) to produce patches from one [`PatchUpdateCheckpoint`](https://github.com/pulumi/pulumi/blob/f6402882c2c1b6ef691d41aca7d06503ca7cfffa/pkg/backend/httpstate/client/client.go#L736) call to the next. This implements [RFC 6902](http://jsonpatch.com/) to communicate only the edits required to the document. The idea is that a new API endpoint would apply patches rather than accepting the entire document.

I tested this on a simple program that creates 100 buckets:

```
import * as aws from "@pulumi/aws";
for (var i = 0; i < 100; i++) {
    const bucket = new aws.s3.Bucket(`my-bucket-${i}`);
}
```

From an empty stack to standing up an entirely new one from scratch, the total amount of JSON checkpoint data to be communicated dropped from 14.04MB to 0.29MB, or a savings of 13.76MB. The average call to `PatchUpdateCheckpoint` went from 141KB to 2.9KB.

Now, I will admit, it's not clear this is a worthwhile tradeoff. For this to work, the API protocol needs to become more complex, and the server would need to do more work to apply the patch. It would need to read the latest known checkpoint and apply the patch, all while maintaining a well-defined ordering of patches. But the savings certainly seem potentially large enough to consider whether this is worthwhile.

Here is an example of one such before/after/patch update:

* [Update Payload N-1](https://github.com/pulumi/pulumi/files/4216823/prev.txt)
* [Update Payload N](https://github.com/pulumi/pulumi/files/4216824/curr.txt) _(what we would have sent)_
* [Patch Payload](https://github.com/pulumi/pulumi/files/4216825/patch.txt) _(what we could hypothetically send instead)_

**Comment by Inkdpixels** [comment]
Is there any timeline for work on this? I got a stack with about 350 resources containing 50 changes to apply and pulumi uploads 420MB in state before actually making any changes on the cloud resources (judging from the CLI output). 

This really is making me unproductive since I cannot deploy as often as I could. Each deployment is taking me around an hour.

**Comment by RobbieMcKinstry** [comment]
@Inkdpixels Two years later, we have an update! 🎉 This is shipping very, very soon (I'm intentionally avoiding getting pinned down on exact dates, but I think "this month" is fair).

We're switching to a diff-based protocol. Our benchmarks indicate a significant performance improvement on average and an improvement in tail latency. We also have more large performance improvements lined up based on this work. Again, I'm trying to avoid giving specific numbers because the results are preliminary and I don't want to over-promise.
