### ISSUE TITLE
How to get the actual output value from StackReference.GetOutput? C#

### ISSUE THREAD

**Issue by sfmskywalker** [pulumi/pulumi#3942]
Hi! I just started experimenting with Pulumi, and so far I love it!

Currently I'm in the process of setting up a CI/CD process where I have one "infra" stack setting up a K8S cluster, and "vertical" services that deploy docker containers. These services have their own Pulumi C# project that read the output from the "infra" stack.

For example:

```csharp
// Get a reference to the infra stack.
var env = Deployment.Instance.StackName;
var infra = new StackReference($"sfmskywalker/aks-cluster/{env}");

// Read image registry output from infra stack.
var registryServer = infra.RequireOutput("container-registry:server");
var registryUser = infra.RequireOutput("container-registry:user");
var registryPassword = infra.RequireOutput("container-registry:password");
```

Now, it's unclear to me how to go about actually using these output values? They are all typed as `Output<object>`. Doing a `.ToString()` simply returns the type name of the object, not the actual value itself.

Interestingly enough however, when I return these values as output like so:

```csharp
return new Dictionary<string, object?>
{
    ["registry-server"] = registryServer,
    ["registry-user"] = registryUser,
    ["registry-password"] = registryPassword,
    ["cluster-name"] = clusterName
};
```

Then the pulumi commandline shows the expected values.

Any pointers are greatly appreciated!

**Comment by mikhailshilkov** [comment]
Hi @sfmskywalker I'm happy you are enjoying Pulumi! I moved the issue to the main repo.

Outputs are a core concept in Pulumi, so it's worth spending time to understand how they work. You would typically use them by:
a) Assigning to input properties of resources
b) Producing new outputs by using `Apply`, `Tuple`, `All`.
Outputs may also contain secret values, and they handle the secrets transparently. 
You can read more in [docs](https://www.pulumi.com/docs/intro/concepts/programming-model/#outputs).

Having said that, if you really need a value of the stack output to control *the flow* (say, in `if` statements) of your dependent stack, you may mark your function `async` and then use [`RequireValueAsync`](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Resources/StackReference.cs#L113) method instead of `RequireOutput`. This will give you a plain object, which you can cast to `string` if that's what your stack output contains. Notice that secrets are not supported in this case.

I recommend using `RequireOutput` if you don't need to control the flow.

Let me know if that helps.

**Comment by sfmskywalker** [comment]
Hi @mikhailshilkov ,

That all makes perfect sense! I followed your instructions and went through the documentation, and it all worked beautifully!.

In case anyone else comes across this, here's what I did:

1. As mentioned, my "infra" project outputs a bunch of details, such as Azure Container Registry connection details (server URL + admin username + password).
2. My "service" project needs the container registry details so it can push a docker image to it.

Here's what makes that work (the following code belongs to the "service" project):

```csharp
// Get a reference to the infra stack.
var env = Deployment.Instance.StackName;
var infra = new StackReference($"sfmskywalker/aks-cluster/{env}");

// Read image registry output from infra stack.
var registryServer = infra.RequireOutput("container-registry:server").Apply(value => (string)value);
var registryUser = infra.RequireOutput("container-registry:user").Apply(value => (string)value);
var registryPassword = infra.RequireOutput("container-registry:password").Apply(value  => (string)value);

// Define a docker image for the service. This will build & push the image to the registry created by the infra stack.
var image = new Image($"my-service", new ImageArgs
{
    Build = "../",
    Registry = new ImageRegistry
    {
        Server = registryServer,
        Username = registryUser!,
        Password = registryPassword
    },
    ImageName = $"{registryServer}/my-service:latest"
});
```

BOOM! Success.

Notice that I had to do an `Apply` operation in order to get the output values of type `Output<string>`, which is required since the `ImageRegistry` object's properties all require an `Input<string>`. I.e. you cannot assign `Output<object>` to `Input<string>`.

Thanks for the help, I really appreciate it!

**Comment by techmouse84** [comment]
I'm running into something similar and this actually mitigate my problem. 
However i don't think this should be the solution. 

`        var albIngressController = new K8s.Helm.V2.Chart("mms-alb", new K8s.Helm.ChartArgs(){
            Chart = "http://storage.googleapis.com/kubernetes-charts-incubator/aws-alb-ingress-controller-1.0.0.tgz",
            Values = Output.Create( new Dictionary<string, object>() 
            {
                { "clusterName" , cluster.Name.Apply(x => x.ToString()) },
                { "autoDiscoverAwsRegion", "true"},
                { "autoDiscoverAwsVpcID", "true"}
            })
        }
        , new ComponentResourceOptions() {
            Provider = k8sProvider
        }
        );
`

the cluster.Name is not expanded correctly when provisioning the controller. the clusterName argument is the type name Pulumi.output[string] or map[] . I believe the reason is due to the use of JsonSerializer in ChartBase.cs which doesn't expand the Output<string> .

If my cluster is provisioned from within the same stack, I wouldn't be able to use RequiredValueAsync. Is there another utility helper that simply returns a Task<T> from an Output<T> ?

**Comment by mikhailshilkov** [comment]
@techmouse84 You should create your dictionary inside `Apply`:

```
Values = cluster.Name.Apply(name => new Dictionary<string, object>() 
{
   { "clusterName" , name },
   { "autoDiscoverAwsRegion", "true"},
   { "autoDiscoverAwsVpcID", "true"}
})

**Comment by gitfool** [comment]
@mikhailshilkov Given this is likely a common pattern, it would be nice to have generic methods, e.g. `GetOutput<T>` and `RequireOutput<T>`, which would be like the existing implementation but throw in a cast inside the backing `Apply`. Thoughts?

**Comment by nickzarate** [comment]
I have a similar problem and am using .NET Framework. I am retrieving Outputs from another Stack and trying to get the actual value of the Output using

```csharp
var outputFromOtherStack = await myStackReference.GetValueAsync("name-of-stack-output")
```

However, because this logic is in the Stack constructor, the constructor finishes before the resources are created. Is there a way to handle async logic in a Stack constructor? I saw a couple PRs that I think addressed this issue, (https://github.com/pulumi/pulumi/pull/3676, https://github.com/pulumi/pulumi/pull/3648) but I couldn't find any examples of solutions that made sense to me (still new to Pulumi).

**Comment by gitfool** [comment]
@nickzarate you can always replace `await` with `.GetAwaiter().GetResult()` but it will execute synchronously.

**Comment by nickzarate** [comment]
@gitfool Nice! Thanks for the quick response. That works great.
