### ISSUE TITLE
Run one-off task?

### ISSUE THREAD

**Issue by phuongnd08** [pulumi/pulumi#3962]
Is Is there a way to run one-off task with pulumi? 
For example on heroku we can do:
`heroku run rails console -a app_name` and can use this to hot patch some data in production. Poissible with pulumi?

**Comment by leezen** [comment]
You could write a program that executes some code that is conditional on some environment variables or configuration you pass. This would ensure that that is only executed when you want. Be aware that if that code is going to affect the state of resources in your stack, the next time your program runs and it doesn't enter that condition, it will want to delete those resources since they're no longer there. I'm not sure if that's what you had in mind. Please re-open if you need more help.
