### ISSUE TITLE
Exporting a default function doesn't run in Node.js

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4017]
In https://github.com/pulumi/pulumi/pull/3321, we added the ability to export a top-level function and have Pulumi run it, helping to make the lack of top-level awaits a little less painful.

Based on [that discussion](https://github.com/pulumi/pulumi/pull/3321#issuecomment-540828258), and my own expectations around how ES6 modules work, I expected to be able to use `default` exports. But that doesn't seem to do the trick. Is this intentional?

For example:

```typescript
module.exports = async function main() {
    ...
}
```

works, whereas in this code:

```typescript
export default async function() {
    ...
}
```

the exported function does not get executed.

**Comment by lukehoban** [comment]
What JavaScript gets generated for the latter?

**Comment by joeduffy** [comment]
When compiled with `tsc -t es6 -m commonjs`, this code

```typescript
export default async function() {
    /*FUNCTION BODY*/
}
```

results in:

```javascript
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
function default_1() {
    return __awaiter(this, void 0, void 0, function* () {
        /*FUNCTION BODY*/
    });
}
exports.default = default_1;
```

**Comment by lukehoban** [comment]
Right.  So it appears in this mode the TypeScript compiler generates code that isn't really directly compatible with Node.js - it doesn't emit a `module.exports = `, but instead uses the special `"default"` name of an export.  I don't think that's something we really should support.

The better path to supporting the use of true ECMAScript Modules will likely be #4130, which will allow truly using ESM instead of compiling down into something that isn't ESM.  I'm going to close this one out and track the path forward in that issue instead.
