### ISSUE TITLE
Installation of Pulumi v1.13.0 on macOS broken

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#4122]
```
curl -L https://get.pulumi.com/ | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5695  100  5695    0     0   5153      0  0:00:01  0:00:01 --:--:--  5153
=== Installing Pulumi v1.13.0 ===
+ Downloading https://get.pulumi.com/releases/sdk/pulumi-v1.13.0-darwin-x64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
error: failed to download https://get.pulumi.com/releases/sdk/pulumi-v1.13.0-darwin-x64.tar.gz

We're sorry, but it looks like something might have gone wrong during installation.
If you need help, please join us on https://slack.pulumi.com/
```

**Comment by lukehoban** [comment]
Working on re-running deployment at https://travis-ci.com/github/pulumi/pulumi/jobs/299666089.

**Comment by pgavlin** [comment]
This is now fixed.

**Comment by RachidAZ** [comment]
@pgavlin 
got the same error msg when running:
curl -fsSL https://get.pulumi.com | sh

output:
=== Installing Pulumi v3.24.1 ===
+ Downloading https://get.pulumi.com/releases/sdk/pulumi-v3.24.1-linux-x64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 63.4M  100 63.4M    0     0  21.8M      0  0:00:02  0:00:02 --:--:-- 21.8M
+ Extracting to /home/rachid/.pulumi/bin
tar: pulumi/pulumi-analyzer-policy: Cannot utime: Operation not permitted
tar: pulumi/pulumi-analyzer-policy-python: Cannot utime: Operation not permitted
tar: pulumi/pulumi-language-python-exec: Cannot utime: Operation not permitted
tar: pulumi/pulumi-resource-pulumi-nodejs: Cannot utime: Operation not permitted
tar: pulumi/pulumi-resource-pulumi-python: Cannot utime: Operation not permitted
tar: pulumi/pulumi: Cannot utime: Operation not permitted
tar: pulumi/pulumi-language-nodejs: Cannot utime: Operation not permitted
tar: pulumi/pulumi-language-python: Cannot utime: Operation not permitted
tar: pulumi/pulumi-language-dotnet: Cannot utime: Operation not permitted
tar: pulumi/pulumi-language-go: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors

**We're sorry, but it looks like something might have gone wrong during installation.
If you need help, please join us on https://slack.pulumi.com/**

**Comment by RachidAZ** [comment]
> 
@Frassle 
yes I have full write permission, and I called it with sudo.
To be noted that indeed I am using WSL from Windows, this can be the reason? what's the workaround in this case?
MAny thanks.

**Comment by Frassle** [comment]
I just tested on WSL and it downloaded fine, so I suspect it's something odd about your specific setup. At any rate, the shell script is just a tar download and extract so you can do those steps manually;
```
$ curl https://get.pulumi.com/releases/sdk/pulumi-v3.24.1-linux-x64.tar.gz -o pulumi-v3.24.1-linux-x64.tar.gz
$ rm -rf ~/.pulumi/bin
$ mkdir -p ~/.pulumi/bin
$ tar xzf pulumi-v3.24.1-linux-x64.tar.gz -C ~/.pulumi/bin --strip-components=1
```

I suspect that last tar command will fail for you given the install script failed. Try adding `-m` to the options to not update timestamps, if your still having issues I'd suggest taking this to stackoverflow or similar because this is just a general problem with linux, tar, and your filesystem and nothing Pulumi specific you'll get a wider range of help with this elsewhere.

**Comment by mikhailshilkov** [comment]
@RachidAZ If you have any follow-up questions, please raise a new issue - our visibility into old closed issues is limited. Thank you!
