### ISSUE TITLE
Pulumi behavior different between Chocolatey vs Installation Script

### ISSUE THREAD

**Issue by toanxyz** [pulumi/pulumi#4129]
We have encountered this issue while using pulumi after installing by Chocolatey. We followed the sample of dynamic provider and when running "pulumi up" we faced the error:

`pulumi error: no resource plugin 'pulumi-nodejs' found in the workspace or on your $PATH`

Then we figured out that when installing by Installation Script, in the "C:\Users\myUser\.pulumi\bin", there is a file called pulumi-resource-pulumi-nodejs.cmd but when installing by Chocolatey there is not and it leads to the error above.

We have removed the version installed by Chocolatey and use the Installation Script and everything works fine.

**Comment by stack72** [comment]
Hi @toanxyz 

My apologies you are finding this error - it has confused me to be totally honest. So the Chocolcately package uses the *exact* same Zip as that you would install when using the installation script. 

All the [install script](https://get.pulumi.com/install.ps1) does is to download the zip and extract it to a location that gets added to your PATH. All the [chocolatey script](https://github.com/pulumi/pulumi-chocolatey/blob/master/pulumi/tools/chocolateyinstall.ps1) does is to download the zip and extract it to your chocolatey tools folder

The chocolatey package has the following files in the nupkg

<img width="440" alt="Screenshot 2020-03-21 at 21 46 03" src="https://user-images.githubusercontent.com/227823/77237134-65da0780-6bbd-11ea-8192-bea3ca126019.png">

The zip has the following files in it

<img width="474" alt="Screenshot 2020-03-21 at 21 41 51" src="https://user-images.githubusercontent.com/227823/77237137-712d3300-6bbd-11ea-8808-6f420f559f47.png">

I'm really stumped by this one - can you install via Chocolatey and inspect the tools folder for me and see if you find the same files?

Paul

**Comment by toanxyz** [comment]
Hi @stack72 

After installing by chocolatey, the folder chocolatey\lib\pulumi\tools\Pulumi\bin is containing exactly the same as you described in the picture above, however, the PATH is chocolatey\bin.

chocolatey\lib\pulumi\tools\Pulumi\bin
![image](https://user-images.githubusercontent.com/6207857/77242502-93609880-6c31-11ea-9612-6d769aba679d.png)

chocolatey\bin
![image](https://user-images.githubusercontent.com/6207857/77242508-a2dfe180-6c31-11ea-8505-dc9d55757b27.png)

And the PATH env is chocolatey\bin
![image](https://user-images.githubusercontent.com/6207857/77242524-d3c01680-6c31-11ea-8fee-dcec28ec5330.png)

It seems like there is a copy from Pulumi\bin to chocolatey\bin, isn't it? The pulumi in chocolatey\bin works fine until we use the dynamic resource and it requires 'pulumi-nodejs'.

**Comment by gep13** [comment]
@stack72 as you were discussing on Twitter with @mkevenaar, the issue here is with regard to what Chocolatey is doing for you automatically, but also what it isn't doing.  Let me try to elaborate...

>@stack72 said...
All the install script does is to download the zip and extract it to a location that gets added to your PATH.

This part isn't quite right...

During the installation of the pulumi package with Chocolatey, the zip file (which is embedded into the pulumi package) is extracted to the pulumi package directory, namely here `C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin`.  Then, on top of this, Chocolatey then creates shims to the executables that it finds within this newly extracted directory.  You can see this in the installation output:

![image](https://user-images.githubusercontent.com/1271146/77472149-6536b080-6e0b-11ea-80ed-b0852f56f295.png)

These shims, are small executable files that are placed into the Chocolatey bin folder, located at `C:\ProgramData\chocolatey\bin` as you can see here:

![image](https://user-images.githubusercontent.com/1271146/77472266-91523180-6e0b-11ea-933e-6c76a568a9cd.png)

These shims aren't the actual pulumi.exe, but rather a small exe that simply "points" to the actual pulumi.exe which is contained within the Chocolatey package directory.

These shims are really useful, as it means that exe's can be immediately available at the command line, since `C:\ProgramData\chocolatey\bin` is already on the system PATH, without needing to add another entry into the path variable.

However, these shims struggle is the exe that has been shimmed "needs" additional resources that are located in the directory that the exe is being shimmed too.  In these scenarios, we would recommend that the Chocolatey installation script be changed to include an entry into the system PATH variable to where the pulumi zip file is extracted to.

Another option, which "might" work, would be to create additional shims for the `*.cmd` files, but I haven't tested that part out.

Does that make sense?  If not, happy to jump on a call at some point to discuss.

**Comment by stack72** [comment]
Thanks for the explanation here @gep13 

Maurice and I are going to jump on a call about this at 1100 CET if you wanna join us? :)

**Comment by gep13** [comment]
@stack72 unfortunately, I won't be able to make that 😢 With the whole social distancing, and working from home thing, the wife and I are now splitting the day looking after the kids.  I take the morning shift (which includes the online school class work) and she works, and she takes the afternoon shift with the kids and I head to work.

**Comment by stack72** [comment]
No worries @gep13 :) We will let you know what we work out

**Comment by stack72** [comment]
After speaking with @mkevenaar here is what we are going to do

update chocolateyInstall to creare .ignore files for the pulumi exe files and thus chocolatey will not create the shims of these files in the chocolatey package directory. The install script will now add the pulumi bin folder to the PATH

We also now need to create an uninstall file to remove the pulumi bin folder from the PATH

This *should* solve the problem we are seeing

**Comment by gep13** [comment]
@stack72 sounds like a plan.

The only slight addition is that you might want to add a step to the installation instructions to close/open the shell/window that was used to run `choco install pulumi` otherwise, the path that has been added to the path won't be available yet.  There is a helper method called `refreshenv` that can be used to achieve the same thing, but this is guartaneed to be available, and depends on their Chocolatey installation.
