### ISSUE TITLE
Using pulumi with a Service Principle that has only permissions within a predefined Azure Resource Group

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi#4164]
In my organization we use Service Principals that are only allowed to create resources within a predifined resource group or acting within this group. 

**My Stack**
```
var resourceGroup = new ResourceGroup("ppwe-playground-pulumi-dev",null, new CustomResourceOptions
{
    ImportId = "ppwe-playground-pulumi-dev" 
});

// Create an Azure Storage Account
var storageAccount = new Account("storage", new AccountArgs
{
    ResourceGroupName = resourceGroup.Name,
    AccountReplicationType = "LRS",
    AccountTier = "Standard",
});
```

When I executed the command `pulumi up` I encountered 2 issues.

**1. Authorization failure**

> Original Error: Cannot register provider Microsoft.BotService with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '24042968-460b-4d11-a242-16c1ace02fa6' with object id '24042968-460b-4d11-a242-16c1ace02fa6' does not have authorization to perform action 'Microsoft.BotService/register/action' over scope '/subscriptions/15b58b7b-f406-4801-9c69-72055ee77f92' or the scope is invalid. If access was recently granted, please refresh your credentials.". 

What is pulumi doing here? Why does it need a BotService? In the documentation there is also no hint about that. What kind of scopes/rights pulumi needs in order to work correctly? Is it possible to disable this feature?

**2. Unable to parse Resource Group ID "ppwe-playground-pulumi-dev"**
How can I tell pulumi to use my already created resource group?

**Edit**
When I give the Service Principal permission to the subscription and run pulumi it is working. When I  remove the permission it is still working. So it seems like pulumi needs to run once and then everything works fine. 

Instead of creating a new Resource Group, I just use the given resource group name when creating an Azure Storage Account and everyhting is working fine.

**Edit 2**
See also: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4440

**Comment by mikhailshilkov** [comment]
Hi @Rookian 

It seems that you already found the answer to your first question in the terraform issue. You may want to set `skipProviderRegistration` to `true`.

To your second question, the `ImportId` should be the resource group ID, not the name, something like `/subscriptions/xyz/resourceGroups/abc`, you can copy it e.g. from the portal.

Note that importing the resource group will make Pulumi manage it from the moment of importing. For example, it will try to delete it if you ever destroy the stack.

Instead of importing, you may want to read the resource group with [this method](https://github.com/pulumi/pulumi-azure/blob/master/sdk/dotnet/Core/GetResourceGroup.cs#L19), or just use its name as a string variable, really.

I hope this helps.

**Comment by Rookian** [comment]
> Hi @Rookian
> 
> It seems that you already found the answer to your first question in the terraform issue. You may want to set `skipProviderRegistration` to `true`.

In order to do that, you add the following line to your pulumi.***.yaml configuration
`  azure:skipProviderRegistration: "true"`
