### ISSUE TITLE
Nodejs resource provider is hitting grpc PROTOCOL_ERROR

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi#4252]
The Pulumi nodejs resource provider appears to be hitting a grpc issue in CI for both pulumi/examples and pulumi/eks and is currently blocking them.

Error:

`[ amples/aws-ts-ec2-provisioners ]     pulumi:providers:pulumi-nodejs default  error: pulumi-nodejs (resource) plugin [/home/travis/.pulumi/bin/pulumi-resource-pulumi-nodejs] did not come alive: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR`

CI logs:
- Eks: https://travis-ci.com/github/pulumi/pulumi-eks/jobs/309519435#L188
- Examples: https://travis-ci.com/github/pulumi/examples/builds/156953281#L3597

Slack thread: https://pulumi.slack.com/archives/C9SGX9QA1/p1585612739246800

Eks is on v1.13.1 of the CLI (it uses latest CLI available publicly)

**Comment by spara** [comment]
I think this is a pulumi account specific problem. I can run the example under my account without error.

**Comment by ekrengel** [comment]
This also also an issue in the [service repo](https://travis-ci.com/github/pulumi/pulumi-service/builds/157309337?utm_medium=notification&utm_source=email)

**Comment by lukehoban** [comment]
If anyone hits this - it is because you are using a `1.x` CLI with a `2.0.0-beta.1` `@pulumi/pulumi`.  That can happen if you are using `latest` in `package.json`, as the `2.0.0-beta.1` release was tagged as `latest`.  For now, you can make sure to specify `^1.0.0` in your `package.json`.  The fix in https://github.com/pulumi/pulumi/pull/4253 will make future `1.x` `pulumi` CLIs compatible with `2.x` SDKs.
