### ISSUE TITLE
Easier way to remove/clear pending operations

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#4265]
Today I am testing a bunch with Pulumi which includes some resources not coming up correctly or even me just canceling it to change some code to restart it.
Currently I have to export, delete the pending operations, then import the stack almost each time which is pretty tedious. 
Could a stack command be added to just automatically clear pending operations that way it is more user friendly?

**Comment by lukehoban** [comment]
We should also seriously reconsider whether we should block updates on "pending operations" at all. We could choose to warn instead of error - allowing updates to continue.  By far the most common case for "pending operations" is a leaked resource creation - which does not actually put a stack in a "stuck" state - it just suggests there may be an out-of-band cleanup step needed.

**Comment by lukehoban** [comment]
My concrete suggestion:
1. Make the current error a warning - and clean up the text of the message
2. Add a `pulumi state clear-pending-operations` that takes care of removing these pending operations (and mention it in the warning)

**Comment by pgavlin** [comment]
> We could choose to warn instead of error - allowing updates to continue. By far the most common case for "pending operations" is a leaked resource creation

We could be a bit more precise here and only warn on pending creates. We could continue to error on pending deletes and updates.

We should also fix `refresh` s.t. it clears pending operations: it was always the intent that that command would resolve these operations.

**Comment by pgavlin** [comment]
For more context, `refresh` was the intended solution because the problem with pending operations is that we don't know the actual state of the resource being changed. In the case of updates and deletes, `refresh` can give us the actual state and resolve the pending operation.

**Comment by lukehoban** [comment]
Good points - updated suggestion:
1. Make the current error a warning 
2. Make `pulumi refresh` report a warning on pending creates, and clear out `pending_operations`.
3. Simplify the warning in (1) to (a) point users to run `pulumi refresh` (b) be simpler and more specific.

**Comment by hugbubby** [comment]
I'm confused as to why there doesn't seem to be a mirror issue in terraform. What do they do and why isn't it applicable here?

**Comment by pgavlin** [comment]
> I'm confused as to why there doesn't seem to be a mirror issue in terraform, where I have literally never encountered issues interrupting an apply before. What do they do and why isn't it applicable here?

AFAIK, Terraform does not use a model its state as a journal. Instead, their approach relies on refreshing prior to each update in order to detect the current state of resources that might have been interrupted while updating.  That approach leaves out the possibility of warning on interrupted creates, etc., and imposes the overhead of refreshing by default.

**Comment by hugbubby** [comment]
> > I'm confused as to why there doesn't seem to be a mirror issue in terraform, where I have literally never encountered issues interrupting an apply before. What do they do and why isn't it applicable here?
> 
> AFAIK, Terraform does not use a model its state as a journal. Instead, their approach relies on refreshing prior to each update in order to detect the current state of resources that might have been interrupted while updating. That approach leaves out the possibility of warning on interrupted creates, etc., and imposes the overhead of refreshing by default.

We ran an automated system for around a year that regularly interrupted terraform in the middle of resource creation several times a day, and there were no problems with interrupted creates/dangling resources. There was no need to warn in these cases, because terraform always determined what happened to the resource being created from the last apply. So the benefit of their system is the ability to interrupt pulumi without the intervention of a systems admin, with the overhead you mention.

We very much enjoy the speed, but since pulumi _does_ have a mostly equivalent refresh function, it seems to me like it should be able to automatically get() and import schrodingers resources like terraform does. There's no inherent need for user intervention here. Otherwise, the pulumi/its automation API becomes very tricky to run in any kind of real production environment where containers/processes are expected to be killable at all times.

**Comment by farvour** [comment]
This happens often enough to warrant commenting on this that one has to create an out-of-band job that basically does all the above described:

1.) Export project and stack file.
2.) Use jq or something to wipe pending_operations
3.) Re-import state back into stack.

As hinted above, a nice flag like --ignore-pending-operations could (and should) do all of this internally for us. Maybe have it depend on the --refresh flag even, since during an interrupted run we generally would want to trust the live state of the provider.

**Comment by farvour** [comment]
> > I'm confused as to why there doesn't seem to be a mirror issue in terraform, where I have literally never encountered issues interrupting an apply before. What do they do and why isn't it applicable here?
> 
> AFAIK, Terraform does not use a model its state as a journal. Instead, their approach relies on refreshing prior to each update in order to detect the current state of resources that might have been interrupted while updating. That approach leaves out the possibility of warning on interrupted creates, etc., and imposes the overhead of refreshing by default.

I'm totally fine with that overhead of requiring `--refresh` if another flag to purge pending ops is included in the CLI. We do that anyway for production deployment pipelines because it's just a Good Idea anyway.. never solely trust the state file IMO.

**Comment by mitchellmaler** [comment]
My current workaround is to run this each time I run into the issue. I created a bash alias/function to make it easy to run.  
`pulumi stack export | jq '.deployment.pending_operations = []' | pulumi stack import --`

**Comment by Frassle** [comment]
Given we have an issue to [look at refreshing by default](https://github.com/pulumi/pulumi/issues/2247) could we not start working on that by changing pending operations to trigger a refresh of the resources listed as pending? Seems safe to just do this as part of `up` and given that the current state is people get an error I can't think of any workflows we'd break by doing this.

**Comment by lukehoban** [comment]
I still believe we should do what's outlined in https://github.com/pulumi/pulumi/issues/4265#issuecomment-721340725.  That is a very simple change, which will in practice make this not blocking, still informative about potential leaks, and easy to dismiss those informational notes.

> could we not start working on that by changing pending operations to trigger a refresh of the resources listed as pending? 

I'm not sure coupling some silent refreshes in is the best idea right now - but I'm also not sure it would help here - the pending operations that matter most are when a create started but never finished (and hence we don't have the ID in the cloud provider).  "refreshing" that would just mean re-running the create, not actually pulling any data from the cloud - since we don't have an ID to pull from.  If the end result was just a modification to the proposal in https://github.com/pulumi/pulumi/issues/4265#issuecomment-721340725 to *always* clear pending operations on any update (so that you get warned exactly once), then I can see that making sense - but it's not really about "refresh" (the proposal above just suggests achieving a similar result by overloading `pulumi refresh` to be the thing that also clear these, as well as refreshing resources that are actually being tracked).

**Comment by Frassle** [comment]
> I'm not sure coupling some silent refreshes in is the best idea right now - but I'm also not sure it would help here - the pending operations that matter most are when a create started but never finished (and hence we don't have the ID in the cloud provider).

I hadn't considered that scenario that's a good point. I can't see how we could automatically resolve this, so maybe these _should_ be errors that the user has to fix. We don't want to just loose track of cloud resources or start mutating unrelated resources that look like they might match. 

> If the end result was just a modification to the proposal in #4265 (comment) to always clear pending operations on any update (so that you get warned exactly once), then I can see that making sense

That now sounds much scarier. Would be very easy for automation scenarios to just leak resources unless operators know to look out for these warnings. A hard fail sounds like the right thing to do there but we just need to make it easy to fix.
Rather than state file editing, maybe once the user has resolved that the operation did or did not create the resource they could tell us with something like `pulumi state clear-pending-create <urn>` or `pulumi state resolve-pending-create <urn> <id>`?

I don't think the above is a problem for updates and deletes though? If we started an update we can just refresh to see how far it got, and likewise if we started a delete we can check if it actually deleted or not with a refresh. Although it's probably actually safe to just do the final operations for these cases without even bothering about the refresh, does delete error if the resource is already deleted?
The only other pending operations are reads and imports which don't modify cloud resources so aren't they always safe to just start from fresh?

Saving the user a cycle here of having to go "run up, see error, run refresh, run up again" seems worthy and is even higher impact for automation scenarios.

**Comment by joeduffy** [comment]
> they could tell us with something like pulumi state clear-pending-create <urn> or pulumi state resolve-pending-create <urn> <id>?

I was pondering the same thing for leaked creates, but more of a middle ground: Don't error out, but do make it a persistent warning. It's a bit of a heavy hammer to fail the update entirely (especially since the presence of it technically does not impair our ability to proceed in any way) but I agree that silently dismissing them as a byproduct of a seemingly unrelated command could be dangerous/surprising/etc. We could also _vastly_ improve this error message, e.g. "warning: A previous attempt to create resource X was interrupted, and we don't have its ID; it might have leaked; if you want to connect this interrupted create to an actual resource that was created, run command `pulumi state resolve-pending-create ...`, otherwise run `pulumi state clear-pending-create ...` to dismiss this warning."

**Comment by farvour** [comment]
> > they could tell us with something like pulumi state clear-pending-create  or pulumi state resolve-pending-create  ?
> 
> I was pondering the same thing for leaked creates, but more of a middle ground: Don't error out, but do make it a persistent warning. It's a bit of a heavy hammer to fail the update entirely (especially since the presence of it technically does not impair our ability to proceed in any way) but I agree that silently dismissing these pending creates as a byproduct of a seemingly unrelated command that can't possibly automatically do the right thing could be dangerous/surprising/etc. We could also _vastly_ improve this error message, e.g. "warning: A previous attempt to create resource X was interrupted, and we don't have its ID; it might have leaked; if you want to connect this interrupted create to an actual resource that was created, first find its ID in your cloud CLI or console, and then run command `pulumi state resolve-pending-create ...`; otherwise, run `pulumi state clear-pending-create ...` to dismiss this warning."

This middle ground would be a welcome change/feature. The heavy hammer you describe is exactly that - aborting the entire run even if the resource creation was leaked. In some rare cases some pending operations are even idempotent depending on the provider which adds insult to injury. Associating DHCP Options set with a VPC in the AWS API comes to mind; even if Pulumi loses the first leaked ID, it doesn't matter since a subsequent call would result in the same condition but a new association ID is generated. That is just one anecdotal example, but I'm sure there are more.

**Comment by Frassle** [comment]
> especially since the presence of it technically does not impair our ability to proceed in any way

Well we could hit name clashes today if the user has put a fixed name, and if we move to deterministic names then those would also clash 😞 It would be fine in cases where the create just didn't happen, and for structural resources.

**Comment by adnang** [comment]
could we have an operation that performs the same action as `pulumi stack export | pulumi stack import`, and be `confirmable`, like `up`  so it prints the resource urns that are in the pending_operations block?

**Comment by Zaid-Ajaj** [comment]
Reopening because #9293 needs to be merged before this is considered resolved

**Comment by alexhwoods** [comment]
Agree this needs to be implemented — here's a script for it though
```bash
STACK=<stack-name>; \
DIR=<directory-name>; \
pulumi stack export --cwd=$DIR --stack=$STACK | \
  jq '.deployment.pending_operations = []' | pulumi stack import --cwd=$DIR --stack=$STACK
```

**Comment by Zaid-Ajaj** [comment]
@mitchellmaler This issue can finally be considered resolved in two ways:
 - `pulumi refresh` will now clear pending operations (except pending CREATE operations)
 - `pulumi up` will not error when there are pending operations, instead it will show a warning that they are there and how to resolve them. 

This behaviour will be available in the upcoming release of pulumi (v3.29.0)

For pending CREATE operations, users still have to manually resolve them from the state by exporting, editing and then importing the stack JSON. We are aware that this is not ideal and we will think of better options to resolve those. For now at least, pending operations won't block subsequent updates

**Comment by nesl247** [comment]
Given that there is still manual work to be done for create operations, shouldn't this remain open then @Zaid-Ajaj ?

**Comment by Zaid-Ajaj** [comment]
>  Given that there is still manual work to be done for create operations, shouldn't this remain open then?

Hi @nesl247, the reason manual work is still required for pending CREATE operations is because we need the users to explicitly decide what to do with them. If pulumi just clears those, you might end up with live cloud resources that are not tracked by pulumi (orphaned resources) and it's better if the users see this and manually check these live resources before clearing them from the pulumi checkpoint files

**Comment by nesl247** [comment]
> > Given that there is still manual work to be done for create operations, shouldn't this remain open then?
> 
> Hi @nesl247, the reason manual work is still required for pending CREATE operations is because we need the users to explicitly decide what to do with them. If pulumi just clears those, you might end up with live cloud resources that are not tracked by pulumi (orphaned resources) and it's better if the users see this and manually check these live resources before clearing them from the pulumi checkpoint files

Understood, but it still requires more manual work than should be required, therefore this issue should remain open IMO. I would expect Pulumi to try to refresh to see if the resource was actually created, if it can't get an answer, then to ask the user if they want to remove it from the stack. There should not be any requirement to manually edit the stack.

**Comment by Frassle** [comment]
> I would expect Pulumi to try to refresh to see if the resource was actually created

We can't. The big problem with pending Creates is that we don't have an ID to lookup because the Create call never returned to give us one, so we can't look up to see if it was created or not.

Having said that there is scope for us at least to provide easier to use commands to manually resolve pending creates as either "did not create" or "created with id <ID>", and maybe we can come up with something better. I'll leave this open to track that.

**Comment by hcharley** [comment]
Regarding pending creates, is it too much scope creep to use fuzzy name matching and create times when there is no ID? 

I realize this probably involves listing and/or searching resources from their provider, but this functionality could also be useful for auto-importing in general if you ever wanted to slap a UI or CLI interactive prompt to let users marry their Pulumi resources with their actual Cloud resources much easier.

**Comment by dixler** [comment]
`pulumi state delete --pending` might be a more idiomatic command

**Comment by iwahbe** [comment]
The resolution we agreed upon is different than what is contained in this thread. For a full description of the resolution, see closing pr: #10394.
