### ISSUE TITLE
Don't remove leading 0 when running `config set`

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#4295]
When running `pulumi config set --path app.version "012345"` for example, the `012345` is a git commit hash. Pulumi thinks this is a number though and sets the value as `12345`.

**Comment by justinvp** [comment]
I like the idea from the community slack of having a `--string` to force the value to be saved as a string.

**Comment by nesl247** [comment]
This is actually a semi-critical issue for us. We're having to fix versions more and more due to the stripping of the leading 0.

I actually don't like the idea @justinvp as it should have a `--int` if you want it to be parsed as an int, with it being a string by default. I think this is what would normally be expected.

**Comment by justinvp** [comment]
> I actually don't like the idea @justinvp as it should have a `--int` if you want it to be parsed as an int, with it being a string by default. I think this is what would normally be expected.

I agree `--int` would have been a nicer design in some ways, but changing it now would be a behavior change that I don't think is worth it, whereas `--string` would address the issue without changing the current behavior.

> This is actually a semi-critical issue for us. We're having to fix versions more and more due to the stripping of the leading 0.

In the meantime, can you workaround by generating a JSON string and setting it via `pulumi config set` without `--path` or setting this one config value as a top-level string value w/out `--path`?

**Comment by nesl247** [comment]
My suggestion would be to break BC since version 2.0 is still coming out, and it would be the perfect time to handle this.

However, that's up to you guys to make the final decision. I prefer breaking BC rather than continuing on with something that works against what I think most people would expect.

I'll have to look into doing it that way. We only just made it possible to even be able to update the 50+ use cases for this with a single change just yesterday.

**Comment by nesl247** [comment]
There's another option here. If the value has a leading `0`, treat it as a string automatically. Are there cases where someone would call `set` and want the leading `0` to be stripped?

**Comment by justinvp** [comment]
Another workaround, in the meantime, would be to prefix or suffix the value so that it won't be convertible to int (e.g. `pulumi config set --path app.version "commit012345"`), and then in the Pulumi program, fix-up the value by stripping the prefix/suffix (e.g. in this case removing the leading "commit" preamble).

> There's another option here. If the value has a leading `0`, treat it as a string automatically. Are there cases where someone would call `set` and want the leading `0` to be stripped?

Yeah, I'm guessing it's unlikely someone would want it to be `int` when there are leading zeros, so I could see checking for the leading zero and treating that as a string automatically. It'd be a behavior change, but I'm guessing it'd be a change that's unlikely to negatively impact anyone.

However, note that we automatically make "true" and "false" bools, so if we're going to make a change here, we should at least consider that as well -- whether we should provide a way to treat "true" or "false" as strings.

**Comment by nesl247** [comment]
I think just making a value with a leading `0` a `string` solves this and doesn't affect anything else. It gives the expectation I think most would have, and leaves the automatic detection for everything else as standard.

A `--string` option if someone really needs to force it then makes sense.

**Comment by justinvp** [comment]
I am good with this approach. It addresses the issue and makes it work the way most would expect, without adding any new surface area. If we ever have a separate need to treat numbers and true/false as strings, we can consider adding the `--string` flag.

**Comment by ljani** [comment]
I have a use case for `--string` or some other way to force strings: I want to store an account ID in my configuration as a string, because the current one was randomly generated to only contain numbers, but it may contain letters as well (eg. `123` vs `z32`).

Currently, I have validation for the configuration object, which validates that the read account id is a string. This is currently failing. I can workaround this by manually editing the `.yaml` and adding quotes around the `123`.
