### ISSUE TITLE
Pulumi GitHub Actions with GCP backed storage backend

### ISSUE THREAD

**Issue by akoenig** [pulumi/pulumi#4327]
I'm currently facing the situation in which using a Google Cloud Storage backed state backend fails within the Pulumi GitHub Action.

I think that performing a `pulumi login` against the [BACKEND_URL](https://github.com/pulumi/pulumi/blob/efe7a599e65637378b9ceeac125386b5effd0d68/dist/actions/entrypoint.sh#L10) should happen **after** the respective service account has been [activated](https://github.com/pulumi/pulumi/blob/efe7a599e65637378b9ceeac125386b5effd0d68/dist/actions/entrypoint.sh#L80).

Is there anything I missed? Otherwise, I would compile a PR for that 🙂

**Comment by leezen** [comment]
I think this is by somewhat "by design" -- I think that service account block was put there for KMS and not really backend login. I think the assumption has been that you already have the right credentials configured in order to log in to your cloud storage backend (whether it's AWS, Azure, or GCP). That being said, it seems silly not to just move the auth step up if we're to use those creds anyway.

@chrsmith am I missing anything?

**Comment by chrsmith** [comment]
Yes, moving the "GCP setup bits" to before we run `pulumi login` is a reasonable suggestion. Would be happy to review a PR to make the change :)

To clarify the purpose of the `entrypoint.sh` script, it is for our GitHub Actions container is to do any obvious initialization steps in order to perform the update. (Most commonly fetching dependencies from PIP or NPM.) Running `gcloud auth activate-service-account` if the we detect certain environment variables falls into that bucket as well.

... so while `pulumi login` and `gcloud auth` are kinda orthogonal concepts, it seems reasonable to just put the `pulumi login` step last so that in the event that Pulumi itself depends on some other machine state, that's already been taken care of.
