### ISSUE TITLE
Unhappy with removal of stackReference.getOutputSync() in 2.0

### ISSUE THREAD

**Issue by slikk66** [pulumi/pulumi#4462]
Just posting an issue to bring up my unhappiness with the removal of synchronous retrieval of outputs from one stack for use in another.

I suppose I understand the desire to remove this feature, but I also think removing it just because it doesn't agree with "the vision" when it was in place and working seems like a bad idea.

I'm of the opinion there is no technical reason why this needed to be removed.

Callbacks are great and all, but sometimes they lead to situations where you can get stuck in "callback hell".

I have a complex app, and in one place I was using synchronous retrieval of outputs for use in another stack, and it was simply easier to do it this way, and I was happier with the execution of the stack reading in a list of output strings from one stack, and iterating over a loop simply in another.

Inside of a stack, I see the benefits of not using synchronous retrieval, and use that pattern in most all areas.  But when working between stacks, it seems like a nice tool to have (fine if it includes some caveats/warnings on the docs).

Still happy with pulumi and recommend it to others, just wanted to provide my feedback as a recent convert to 2.0

**Comment by lukehoban** [comment]
Sorry for the trouble here.

> I'm of the opinion there is no technical reason why this needed to be removed.

Unfortunately, the way these were originally implemented was deeply problematic for Node.js, and led to many cases of hangs, and worse, unpredictable hangs that would be triggered by very subtle changes to code.  We tried many options to keep the simple synchronous APIs that were part of 1.0, but ultimately there was no way within Node.js to deliver reliable and correct support for those APIs, so we needed to remove them.

> Callbacks are great and all, but sometimes they lead to situations where you can get stuck in "callback hell".

A couple of things that may help here.

First, you can use `async/await` to avoid callback hell.  It's still not quite as simple as plain-old synchronous code, but it's close.

Second, Pulumi now supports exporting an `async` function from the entry-point to your program - so that you can easily use `async/await` for your entrypoint.

For example:

```ts
import * as pulumi from "@pulumi/pulumi";

export = async () => {
    const other = new pulumi.StackReference("pulumi/stress-tester/production")
    const val = await other.getOutputValue("url");

    // Stack outputs
    return {
        x: val,
    }
}
```

**Comment by slikk66** [comment]
thanks for the reply @lukehoban ! keep up the good work 👍
