### ISSUE TITLE
Typescript modules can't be require'd in current directory

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#463]
I created a TypeScript module that I then referenced from an `HttpEndpoint` route. I found that if I had to use the bin path to reference. `require("./redis-client")` does **not** work, but `require("./bin/redis-client")` does.

**Comment by CyrusNajmabadi** [comment]
I'm closing this out.  We now have what i think is a great module capturing story with very few (if any) warts in it.  We've also documented our recommended patterns on how to best use pulumi and how imports/modules work there.  Since doign that we haven't run into any further problems.  So i think we're in a good place now.
