### ISSUE TITLE
pulumi --non-interactive stack rm <stack> still requires --yes to be non interactive

### ISSUE THREAD

**Issue by JoseAlban** [pulumi/pulumi#4717]
Expected:
`pulumi --non-interactive stack rm <stack>` removes without prompt

Actual:
`pulumi --non-interactive stack rm --yes <stack>` is needed on CI to remove without prompt

Version:
1.14.1

**Comment by leezen** [comment]
We generally want any destructive operations to include `--yes` so I'd actually consider this 'by design.' That being said, the --non-interactive should actually warn instead of trying to prompt to user, which appears to be a bug.

**Comment by stack72** [comment]
Looks like this can be closed out - I don't get a prompt

```
▶ pulumi --non-interactive stack rm --yes prod
Stack 'prod' has been removed!
```

**Comment by ctrahey** [comment]
@stack72 the bug is that without --yes, it does prompt, seemingly in direct conflict with expectations for a "--non-interactive"

This is prompting for me in 3.150.0

Of course I was glad to find this thread or I would have given up (I needed to rm stacks via xargs). I agree with @leezen that this should have warned me on my first attempt, telling me to add --yes if I was sure, with some note about risk etc... according to your PM's discretion.

**Comment by tgummerer** [comment]
@ctrahey thanks for pointing this out, we just merged https://github.com/pulumi/pulumi/pull/18708, which now starts giving a warning pointing in the direction of `--yes`.
