### ISSUE TITLE
Unable to destroy resources that no longer exists

### ISSUE THREAD

**Issue by eliezio** [pulumi/pulumi#4801]
I'm facing this error with two different providers: MySQL & Okta.

My Pulumi application manages Users and Grants resources from dozens of MySQL servers. Occasionally, one of these servers is deleted without prior notification. After detecting that server is no longer reachable, my application always fails to delete the associated `mysql.User` and `mysql.Grant` resources since the TF-bridged provider fails when after invoking connectToMySQL().

The only way to bypass this blocking state is by manually running `pulumi state delete`!

A similar condition happens when the application tries to delete assignments between an Okta Application and users that were previously deleted or deactivated.

Is there a way to force Pulumi to delete those managed resources, by instructing it to ignore the result of the underlying `Delete` operation?

**Comment by leezen** [comment]
I don't know if there's a great 'safe' way to do what you're describing. By removing the resource from code, but not being able to delete the underlying resource, it won't always be clear that the state itself can be deleted. In which case, you'll have to explicitly provide some action, which in this case is `pulumi state delete`. I'm curious if you have something else in mind?

**Comment by mklueh** [comment]
I was running into the same issue, luckily only on my development stack which relied on resources that no longer existed. The problem was that the cluster did not exist anymore, so all commands that followed failed with

` error: Preview failed: unable to load schema information from the API server:`

`pulumi state delete` did not work for me either.

What I did was deleting the entire stack with 

`pulumi stack  rm dev --force`


However I wouldn´t feel good about doing that when such a thing happens with the production stack for whatever reason, so I´d be interested in getting the local state back in sync in such a case.

Maybe exporting the state as json and editing it manually and reimporting it is the way to go?

**Comment by eliezio** [comment]
One possible solution is a new mechanism that would allow us to declare our resources (User and Grant, in my 1st case) as children of an external resource (a MySQL server). Once we proclaim this external resource as dead, all dependent children will be deleted without trying to access the defunct parent resource.
This would work in my 2nd case as well: I would declare the app-user assignment as a child of externals Okta Application and Okta User parent resources.

**Comment by eliezio** [comment]
At least for the MySQL case, this safe deletion can be activated whenever the provider is also going to be deleted.

**Comment by tcarrio** [comment]
This is an issue that I have been running into with dynamic providers. It would definitely be useful to have some manner of allowing deletion when the resource is not found anymore -- the situation itself implies that the Pulumi state is out of sync with the actual state and allows the Pulumi state to become closer to actuality.

**Comment by pgavlin** [comment]
It might also be possible to address this via refresh. If the provider treated an unreachable server as deleted--much like our kubernetes provider does--then it could also treat the managed resources as deleted. Not sure that that's possible with a TF-backed provider, though.

**Comment by jre21** [comment]
I've run into similar issues a few times with AWS security group rules -- typically when a rule in one security group references a security group managed in a different stack.  If the external security group is deleted, then the AWS also deletes the rule referencing it, and Pulumi can get caught in a loop where it's trying (and failing) to delete a resource that no longer exists.

I think shoehorning retainOnDelete into this use case is a really bad idea.  For both my use case and the ones above, if the resource still exists, then Pulumi really should go out and delete it!  The root problem is that Pulumi's stack state is getting out of sync with the real world (it thinks resources still exist when in actual fact an external process has already deleted them) and a proper fix requires the relevant provider to actually check whether an external service has modified or deleted the resource, update its internal state accordingly, and then generate its plan from this new, accurate, view of the world (which is what normally happens for well-written resources, but isn't happening here).  Failing that, an acceptable workaround would be some way to annotate resources to indicate that if deleting the resource throws an error, Pulumi should just assume they no longer exist.

**Comment by mikhailshilkov** [comment]
I feel like our current answer to the situation when a resource got deleted out of bounds is:
1. Run `pulumi refresh`. Most providers should detect the resource as deleted when trying to read its state.
2. If `pulumi refresh` fails, e.g. when trying to connect to a non-existing cluster, you should use `pulumi state delete` to delete this resource from Pulumi state. It's not a nice workflow, so consider opening in issue in the provider repository so that the provider could fix the refresh operation.
3. `retainOnDelete` option is shipped now - feel free to use it if appropriate.

With this, I don't see what else this issue is tracking, so I'll go ahead and close it. Feel free to open an issue with a new feature that would improve the workflow, either per-provider or in general.
