### ISSUE TITLE
Support libraries exposing `import type` syntax (requiers a typescript 3.8.x upgrade)

### ISSUE THREAD

**Issue by sledorze** [pulumi/pulumi#4949]
Spec:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

**Comment by leezen** [comment]
It'd be great to better understand what doesn't work for you. By default, pulumi uses TS 3.7 (see https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/package.json), but you can always take over TS compilation yourself. Is this issue really asking to bump the default version to 3.8 or are you having trouble with 3.8.x somehow when taking over the compilation yourself?

**Comment by sledorze** [comment]
@leezen I've done that actually now.
However for Pulumi; it would ease the experience a lot to support external d.ts files, whatever the TS version used to build them.
There's potentially a lot of friction otherwise.
We can close or keep open for others..

**Comment by leezen** [comment]
Thanks for clarifying -- just wanted to make sure I understood what was going on and glad to hear you were able to make progress. I'll leave this open to track as I don't think we have anything else tracking this.

**Comment by alvis** [comment]
In general, it's a good practice to use `import type` for type-related imports.
Having said that, the good of using `import type` doesn't apply to pulumi because bundle size is not a concern.

But it's just feel wried that as a day-to-day typescript user, somehow I need to practice differently between other modern typescript projects and pulumi projects. When coding for a pulumi project, I've to constantly have an awareness about which syntax is not supported by pulumi and therefore have to code in the old way.

I thought pulumi uses the typescript version I declared in package.json but turns out it's not.
I got some syntax errors when I perform `pulumi up` while there's no error in my editor.
It took me some time to figure out pulumi is still using 3.7 while we are using 4.4 elsewhere today already.
It's not a big problem, but perhaps the docs should clearly state that.

**Comment by julienp** [comment]
Pulumi ships with TypeScript 3.8.3 by default and `import type` works.

Regarding better support of TypeScript versions, https://github.com/pulumi/pulumi/pull/15622 will ship in the next version of the nodejs sdk and makes it easy to pick the version of TS you want.
