### ISSUE TITLE
Pulumi preview --diff shows secrets in plain text in logs

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi#4957]
`pulumi preview` and `pulumi up`, as expected, display secrets as `[secret]` in logs.

when running a detailed preview in a pipeline, the details include the transformation of the output values.

The new output shows as `-> [secret]` but the original value is visible in plain text and recorded in the logs.

is it possible to disable it or, if not, can I please raise a feature request for this to be added?

Thanks

**Comment by RobbieMcKinstry** [comment]
Hello! I was able to reproduce the issue described herein.

Here's what I did:

1. I started with a simple TypeScript program, marking a resource as secret.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";
import * as aws from "@pulumi/aws-native";

export const bucket = pulumi.secret(new aws.s3.Bucket("robbies-bucket", {
  bucketName: "robbies-bucket",
  tags: [
    { key: "anyone-can-delete-me", value: 'true' },
  ],
}));
```

2. I ran `pulumi up` and approved the change. the apply succeeded.

3. I modified the resource, making sure the modified property would not trigger a `replace-on-change`.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";
import * as aws from "@pulumi/aws-native";

export const bucket = pulumi.secret(new aws.s3.Bucket("robbies-bucket", {
  bucketName: "robbies-bucket",
  tags: [
    { key: "anyone-can-delete-me", value: 'true' },
    { key: "owner", value: 'robbie-mckinstry' },
  ],
}));
```

4. I ran `pulumi preview --diff`, resulting in a rich diff _showing the secreted value_. ([Link](https://app.warp.dev/block/SIn2O6odzeggLk6cfcfyrZ).)

This feels like a bug in our `object_diff` logic in `/pkg/backends/display`, which is eagerly unsecreting objects with diffs.

**Comment by dixler** [comment]
We are discussing potential interventions in the engine to add extra secrets protection to mark outputs secret if there is a secrets inputs with a matching name.

Note that secret propagation is done in the providers. This is technically a providers issue.

An issue has been opened for bridged providers with a reproduction
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1028

**Context**
As of writing, the internals of the diff code show the outputs if they exist else fall back and display the inputs. The inputs will preserve secrecy, but the provider may not propagate the secretness to the outputs. It will cause the display to show a value as secret on first up, but later will show the outputs which may not be marked secret by the provider.

It may be counter-intuitive, but @RobbieMcKinstry's example is flawed because it should be using the `additionalSecretOutputs` resource option to mark outputs secret. When showing the resource diff, the bucket fields are being displayed as they aren't marked secret on the bucket, but marked secret for the output so the diff will display them.
