### ISSUE TITLE
Add `--json` option to emit output in JSON for specific commands

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#496]
Currently the Pulumi CLI only emits command output in colorized text. In order to support more advanced scripting scenarios, we should have a `--format` option to emit data in a variety of formats. Most notably JSON, but perhaps CSV would be useful too.

Documentation for AWS' CLI:
http://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html

Documentation for Google's CLI:
https://cloud.google.com/sdk/gcloud/reference/topic/formats

**Comment by lukehoban** [comment]
We've had a lot of requests for this in the past two weeks.  Those requests have typically been phrased as "is there an SDK for driving Pulumi deployments", but on drilling in, it sounds like the best and most flexible solution in the nearterm to that need will be CLI output that can be programmatically handled.  This would enable arbitrary scripting scenarios against the CLI, as well as enable SDKs to be built on top if needed.

The work here will primarily be about formalizing the data structures that represent the outputs of all/most Pulumi CLI commands, so that these can be serialized to JSON (or in the future possibly other) formats.

**Comment by joeduffy** [comment]
@ellismg Could you add a checklist to this work item, detailing which commands would benefit from this, which ones we have already completed, and which remain (perhaps even with priorities if there is a long list of them)?

**Comment by joeduffy** [comment]
@ellismg Ping on the above ask.

Just ran into a situation where `pulumi config --json` would have been super handy.

**Comment by joeduffy** [comment]
@ellismg Is there any more work planning during M20, given that https://github.com/pulumi/pulumi/pull/2374 has already been merged?

**Comment by ellismg** [comment]
Opened: https://github.com/pulumi/pulumi/issues/2390
