### ISSUE TITLE
Add support for shrink-wrapped plugins.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#5047]
Plugins are currently expected to be single-file executables. In order to support authoring plugins in languages that have more complex distribution mechanisms, we need to add support for plugins that are composed of more than one artifact once installed. Adding support for plugins that are distributed as ZIP files that contain all necessary artifacts (except perhaps the language runtime itself) should suffice.

**Comment by justinvp** [comment]
Plugins are already distributed as .tar.gz files. Each plugin gets installed into its own directory containing the files from the .tar.gz, with the primary loadable executable named `pulumi-<kind>-<name>` among the files. So we already have the support we need.

While not strictly necessary, we should consider adding support for automatically installing dependencies as part of installation of a plugin, so the dependencies do not need to be contained in the .tar.gz itself. There are a couple ways we could do this:

1. The most flexible approach would be to have some file/script of commands to run, e.g. a file could list `npm install` as one of the commands to run.

2. Another approach would be to support an optional `PulumiPlugin.yaml` (similar to `Pulumi.yaml`/`PulumiPolicy.yaml`) that has a `runtime` option, which would be used to install dependencies. For example, if `runtime` is set to `nodejs`, we'd run `npm install` as part of the plugin installation like what we do for programs and policy packs. The downside is this limits us to just the runtimes we know about. The upside is it is more consistent with what we do for programs/policypacks, and we'd be able to take user settings into account, e.g. if `PULUMI_PREFER_YARN` is set, we would use `yarn install` rather than `npm install`.

**Comment by pgavlin** [comment]
> While not strictly necessary, we should consider adding support for automatically installing dependencies as part of installation of a plugin

FWIW, we sort of do need to do this in order to take into account native dependencies in ecosystems like Node.

**Comment by justinvp** [comment]
> FWIW, we sort of do need to do this in order to take into account native dependencies in ecosystems like Node.

Yeah, I do think we want to do it, if only to keep the size down of the plugins we host (and many CI systems support caching dependencies from npm, pypi, etc.). But technically, you could include all the native dependencies in each platform's .tar.gz, since we publish one .tar.gz per platform.

If we're going to be opening this up to make it easier for 3rd parties to write these, we might want to consider adding support for "platform neutral" plugins, so you'd only have to create a single .tar.gz that could work on any supported platform (assuming it doesn't contain any native binaries). But we can consider adding support for this down the road.

**Comment by pgavlin** [comment]
> But technically, you could include all the native dependencies in each platform's .tar.gz, since we publish one .tar.gz per platform.

Ah, that's right. Good point.
