### ISSUE TITLE
Breaking circular dependencies in any way possible

### ISSUE THREAD

**Issue by OliverGrayMLD** [pulumi/pulumi#5216]
I am aware there are already issues such as [this one](https://github.com/pulumi/pulumi/issues/3021) asking if it is possible to fix circular dependencies within Pulumi. This question recieved an "unsatisfying" answer to the whether or not it is supported by Pulumi.

My question is while it might not be supported (yet?), are there any known workarounds to circular situations?

I've been considering something like creating a Dynamic Provider that does an atomic update of the two things involved in the loop. This is obviously not that nice to maintain, so I was wondering if there are any other ideas or alternatives.

**Comment by lukehoban** [comment]
Can you share the specific scenario you have that is leading to this?  The available options typically depend on specifics of the scenario.

One general option is to break the update into two updates - the first that introduce one side of the dependency, the second that introduces the other.  This may require setting some external configuration on whether the first side is already "configured" - which does make this a little more manual - but should work reliably.  

There may be more streamlined approaches depending on the specific scenario.

**Comment by XBeg9** [comment]
@lukehoban as an example, `azure.network.latest.RulesEngine` depends on FrontDoor, and if you want to enable rule from rules engine, you need to use it inside FrontDoor config:
```rulesEngine: {
          id: staticRuleEngine.id
        },
```
Any ideas how to fix this circular dependency?

Thanks

**Comment by leezen** [comment]
I updated https://github.com/pulumi/pulumi/issues/3021 with an example of using Automation API to coordinate separate stacks to resolve the dependency issue. There's no reason that coordination has to occur across separate stacks and could take place as multiple updates to a single stack via Automation API as well. I'm going to close this issue as it's not clear that this issue is tracking anything separate.

In the above example of needing FrontDoor and RulesEngine, you could imagine having a stack that declares the FrontDoor resource (w/o referencing the RulesEngine resource) and a RulesEngine. Then, in a subsequent update coordinated via Automation API, passes that RulesEngine identifier as part of the FrontDoor routing rules config.

**Comment by XBeg9** [comment]
@leezen awesome! I like the idea, thanks for the youtube channel!
