### ISSUE TITLE
Consider standardizing stack selection behavior

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5257]
Pulumi commands accept a `--stack` parameter to use a stack other than the currently selected one, but there is a mix of behavior with this command. Sometimes we set the stack in the workspace when `-s` is passed:

https://github.com/pulumi/pulumi/search?q=%22true+%2F*setCurrent*%2F%22&unscoped_q=%22true+%2F*setCurrent*%2F%22

Sometimes we don't: 

https://github.com/pulumi/pulumi/search?q=%22false+%2F*setCurrent*%2F%22&unscoped_q=%22false+%2F*setCurrent*%2F%22

I think there are two options to rectify this:

1. Take a breaking change in 3.0 and standardize all commands to setStack=false.
2. Add a new flag to be used in combination with --stack: --set-stack=false

**Comment by komalali** [comment]
What's the preferred solution here @EvanBoyle? Do we want the extra flag or just standardize to false?

**Comment by lukehoban** [comment]
From an offline conversation:

> I see... super strange... the entire point of `-s` was to not need to set the global stack for the project, so feels like that's probably a bug that was copied far and wide :disappointed:

Let's fix the meaning of the existing `-s` to not set the stack.  Users can easily set the stack via `pulumi stack select` if needed.  

This was marked as `impact/breaking` because it is (technically - though probably not significantly in practice) a breaking change.  So we will likely need to fix this in a `3.0` branch instead of in `master`.
