### ISSUE TITLE
Windows 10: Failed to locate any of ["python3" "python"] on your PATH

### ISSUE THREAD

**Issue by trevorkennedy** [pulumi/pulumi#5388]
When I try to run `pulumi new aws-python` on Windows 10, I get the error `Failed to locate any of ["python3" "python"] on your PATH.  Have you installed Python 3.6 or greater?` 

I can type `python --version` into the command prompt which returns `Python 3.7.9` so this do the trick...

## Expected Behavior
It should create the project scaffolding

## Current Behavior
Displays the `Failed to locate any of ["python3" "python"] on your PATH.  Have you installed Python 3.6 or greater` error message

## Steps to Reproduce

1. python --version
2. mkdir quickstart
3. cd quickstart
4. pulumi new aws-python

## Context (Environment)
Windows 10 with Python installed (from the Microsoft Store) to C:\Users\USERNAME\AppData\Local\Microsoft\WindowsApps

**Comment by lukehoban** [comment]
Heard another report of this - definitely seems like something is off here - possibly something changed on the windows/Python side?

> I did have one "interesting" hiccup getting started that maybe could be considered a bug, but really is just some strange Windows behavior. I have (well had) Microsoft's store version of Python on my machine. It seems that the Windows store has some funky protection with its installed files. During the initial project creation, I was getting this error. Turns out that the exec.LookPath above that is failing during the chkStat call due to the binary not being readable. (If you want to try to replicate, just run in powershell `Get-Content python.exe` on the store delivered binary.)

**Comment by moerketh** [comment]
Found some more information on [this SO post](https://superuser.com/questions/1437590/typing-python-on-windows-10-version-1903-command-prompt-opens-microsoft-stor) and [this blog](https://www.tiraniddo.dev/2019/09/overview-of-windows-execution-aliases.html)

My understanding is that path %LOCALAPPDATA%\Microsoft\WindowsApps contains Windows Execution Aliases appearing as 0 byte files. This is on the PATH by default, so that when a user types the command such as `python` the windows store app is launched allowing the user to install this app. When the app is installed, the alias is changed to run the app instead. Magic.

**Comment by lukehoban** [comment]
We are working on a fix for this in #5775.  It appears there are some fundamental bugs in Go's handling of these special 0-length reparse-point files, which prevents them from being `exec`d via Go's core libraries.  We are looking into possible workarounds for this to unblock this in the meantime.   

For now though, we recommend using a python.org installation of Python on Windows if possible.

**Comment by viveklak** [comment]
Cut https://github.com/golang/go/issues/42919 to track the underlying issue with go's exec package. We are investigating options to workaround this in the meantime but for now please consider using the python.org or chocolatey installers instead.

**Comment by viveklak** [comment]
Workaround implemented in #5874
