### ISSUE TITLE
[Automation API] Support recovery workflow for nodejs

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5531]
We should expose export/import/cancel similar to what we added for Go https://github.com/pulumi/pulumi/pull/5369

**Comment by roderik** [comment]
I wanted to add some more context from some Slack threads because from my observations the issue is a bit more complex.

- https://pulumi-community.slack.com/archives/C019YSXN04B/p1609161459201200
- https://pulumi-community.slack.com/archives/C019YSXN04B/p1609409517206400

Some background first:

We use the Automation API in Typescript to deploy K8S clusters and services on top of them. This is not a manually run script nor a CI/CD system, but in a typescript based (NestJS) server that uses a job queue (Bull) to schedule all kinds of work, including pulumi up and destroy jobs.

While developing, this server restart on code changes (nodemon) killing jobs in the queue while they are in progress. When in the middle of a GKE cluster creation, this presents some obvious issues, how to continue/recover after the restart. The job queue will retry this job as it neither completed nor failed.

We noticed the following behavior (synthesis of the slack threads):

1. in the pulumi backend, the 'up' run would remain 'running'
2. in the computers process list, a zombie pulumi process was leftover
3. when retrying the `pulumi.up`, the backend reports a 409 (correct because of 1)
4. no code exists to manually handle recovery, cancel, import, export.

5. A secondary issue is that some stack configuration issues, which cause unhandled exceptions in the pulumi binary, do not bubble upwards through the Automation API so they can be caught and in my case, mark the job as failed. The `await up` call would just stall and never complete, locking up the job forever, requiring a restart, and then we have the same effect as the paragraph before.

An example of this is doing `up` to GKE to deploy a GKE cluster with a location set in the GKE cluster config, but no zone in `gcp:zone` configuration. This might be the 6th issue since it is listed as optional in the docs, but it is not.

Now I see there are PR's open for some of the recovery options in 4, but I feel like 2 and 5 are actually closer to the root cause that would make 4 (while useful) not needed.

As to what I (from the outside) think needs to be solved is the following:

1. Exceptions in the pulumi stack configuration/up should bubble up to the Automation API and the calling code. That would solve hanging await up's and allow calling code to deal with it as it sees fit.
2. The automation API should be able to handle SIGINT/SIGTERM and clean up after itself. With cleaning up I think the nicest method would be to kill the pulumi binary in such a way that the binary notifies the backend that it died (as I think it works when running standalone). That would keep the backend in sync with reality and prevent zombie processes. Allowing the client code to recover afterward. And this is where the import/export methods would be extremely helpful to do it in an automated way.

Purely architecturally, I feel that these issues could be handled best / most clean in the pulumi code. Now it is kind of possible for client code to deal with these issues, in a roundabout way.

1. The non-bubbling exceptions are only an initial dev issue. With a bash script and some `killall -9 pulumi` you can clean this up. 
2. The restarting issue workaround is to pause my queues on SIGINT/SIGTERM and wait until they are done processing before actually restarting, and in case of a crash, it is running on k8s anyway so the process disappears when the pod restarts. The addition of the import/export and a refresh will get me into a workable state again.
