### ISSUE TITLE
Enable blue/green deployments

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#554]
Many customers have this as a requirement. Need to flesh out the scenario and exact requirements. 

Came across this relevant post on how to do B/G deployments with Docker: https://github.com/docker/compose/issues/1786#issuecomment-294434786

**Comment by newtack** [comment]
Any update on this?
I may want to use ACI (without Kubernetes) have it running and when a new version comes in, start a new ACI instance, initialize it and only when it is up and running shut down the other instance. Can I do this with Pulumi today? If not, can you please add support for it?

**Comment by knocte** [comment]
> please do open new issues to track those.

Before opening a new issue, can I pick your brain for a minute @lukehoban , to see if my request makes sense.

My team has implemented a blue-green deployment proof of concept with Pulumi (with the aim to evaluate if we should consider Pulumi moving forward). Here I will lay out how it works and the downsides we have detected (so I wonder if I should open new issues that target those downsides, but maybe we have done something wrong, please let us know!).

I'll try to be brief:
- We use Vultr as our cloud provider for VMs and CloudFlare as the DNS managemenet tool.
- We use manual GitHub Actions workflow to initiate a deployment.
- We use F# for the deployment code.

First deployment:
- A stack called "green" gets created, `green.mydomain.com` becomes an A DNS record that points to this new server, server.mydomain.com becomes a CNAME record that points to green.mydomain.com.
(I know, this is a poor-man blue-green deployment, as in, DNS acting as "load-balancer switch", but remember this is just a proof of concept.)

Second deployment:
- A stack called "blue" gets created, `blue.mydomain.com` becomes an A DNS record that points to this new server, server.mydomain.com becomes a CNAME record that points to `blue.mydomain.com`. (Green becomes dormant over time, especially as TTL of DNS expire; we don't mind that this green server is kept alive.)

Third deployment:
- A new stack called "green" gets created, `green.mydomain.com` becomes an A DNS record that points to this new server, server.mydomain.com becomes a CNAME record that points to green.mydomain.com. (Same as the 1st deployment, with just one difference: the old `green` servers gets destroyed.)

From the above you can guess how the 4th deployment goes (same as 3rd but "blue" instead of "green").

The thing we don't like so far is that all the logic that checks if the next deployment is going to be green or blue, needs to be in the YML files of our GitHubAction workflows; ultimately seeming like defeating the purpose of Pulumi (wouldn't it allow us to move our YML to F# essentially?). And if we try to move it out from there, we hit a wall: the "destroy" command available to use from YML (which I guess under the hood calls the "destroy" command of the "pulumi" command line binary) seems to be not available in the API that we find from our F# code. If it was there, I guess this deployment would be able to be simplified greatly; does that make sense?

**Comment by maelp** [comment]
I'm also interested in blue/green or rollout/canary deployments through Pulumi, is that a possibility?
