### ISSUE TITLE
Support for Understanding Output Secrets

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#5653]
This is an issue to bring together the design required to implement #3795 and #2886 and is a requirement for https://github.com/pulumi/pulumi-terraform-bridge/issues/10 to proceed

This issue will house the "design" we choose for the API

Effectively, we need the 2 following-type functions:

pulumi.IsSecretOutput
pulumi.Secret

We need to choose if these are instance methods or static methods.

**Comment by stack72** [comment]
So last week I spoke with @justinvp @mikhailshilkov and @EvanBoyle about this work in all of the respective language SDKs and @justinvp came up with the following scenarios which we all agree would work

1. Static functions
2. Instance functions

These would manifest themselves as following:

### Unsecret

```csharp
var exposedOutput = someOutput.UnsafeUnsecret();
var exposedOutput = Output.Unsecret(someOutput);
```

```typescript
const exposedOutput = pulumi.Unsecret(someOutput);
const exposedOutput = someOutput.Unsecret();
```

```python
exposed_output = Output.unsecret(some_output)
exposed_output = some_output.unsecret()
```

In Go, @EvanBoyle and I discussed that it would be easier to have a Static function that is the opposite of ToSecret and ToSecretwithContext and is more in keeping with the Go SDK

These would be:

```go
exposedOutput := Unsecret(someOutput)
exposedOutput := UnsecretWithContext(ctx, someOutput)
```

With regards to naming, @justinvp suggested we should really point out that Unsecret is actually an operation we don't suggest is good practice by naming the func: `UnsafeUnsecret`

**Comment by mikhailshilkov** [comment]
Do we want to pick one style (static vs instance)?

If we want to hide it from casual use, in C# we could put it to a separate namespace as we did here: https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Core/OutputUtilities.cs

What about the proposal on `IsSecret`?

**Comment by justinvp** [comment]
> TypeScript
> 
> ```ts
> const exposedOutput = pulumi.Unsecret(someOutput);
> const exposedOutput = someOutput.Unsecret();
> ```

Note: For TypeScript the function name should be lower-case.

> With regards to naming, @justinvp suggested we should really point out that Unsecret is actually an operation we don't suggest is good practice by naming the func: `UnsafeUnsecret`

Luke said "perhaps even `unsafe` in the name if warranted" in https://github.com/pulumi/pulumi/issues/3795 and I'm just +1'ing his "perhaps" sentiment. `Unsecret` alone is the obvious, simple, name. `UnsafeUnsecret` is gross, but that's by-design. Including `unsafe` (or `dangerous`) in the name may make folks think twice about using it and makes it a little easier to audit visually during code reviews. But I'm also fine with just `Unsecret` if other folks prefer it.

> Do we want to pick one style (static vs instance)?

Each language should only have one style. Matching the style of the existing `Secret` API in each lang makes sense to me. My only question was whether doing so would be "too discoverable," to Mikhail's point about possibly hiding from casual use. But I also don't want to take the hiding too far, if this is going to be commonly needed for https://github.com/pulumi/pulumi-terraform-bridge/issues/10

> What about the proposal on `IsSecret`?

Also curious about this. Are we punting on https://github.com/pulumi/pulumi/issues/2886 for now? I don't feel strongly about it one way or another, just wondering. If we are going to add it, I'm curious what the signature would look like for Go.

For TypeScript, there's already an existing member that's marked `@internal` that could be made public:

```
export interface OutputInstance<T> {
    /** @internal */ readonly isSecret: Promise<boolean>;
}
```

Python already has a public API (though, it's within a "private implementation details" commented section, so should be moved out of that comment section):

```python
class Output(Generic[T]):
    # Private implementation details - do not document.
    def is_secret(self) -> Awaitable[bool]:
        return self._is_secret
```

Both of those use the instance style. Would C# and Go also use instance style for `IsSecret`?

Or for C# would this live on `OutputUtilities` as Mikhail points to?

```c#
namespace Pulumi.Utilities
{
    public static class OutputUtilities
    {
        // Add it here?
        public static async Task<bool> GetIsSecretAsync<T>(Output<T> output);

        // Existing
        public static async Task<bool> GetIsKnownAsync<T>(Output<T> output);
    }
}
```

**Comment by EvanBoyle** [comment]
Just to clarify, static (untyped) is the only practical path forward for the Go SDK. The instance method approach would involve adding a generated method to every core SDK type and each type in the provider SDKs as well due to Go's lack of generics. Given the problems, we already experience with binary size, and compilation time/memory utilization, this isn't really an option.

**Comment by EvanBoyle** [comment]
> Do we want to pick one style (static vs instance)?

Generally, for SDK and programming model level features, I think we should be OK with a little bit of divergence. Our users working across multiple SDKs is not the common case, so doing the best we can in each language to provide something idiomatic that gels nicely with the "language culture" should be the goal. That being said, special care should be taken for divergences that make things like codegen more difficult, but this instance doesn't seem like one of them.

**Comment by leezen** [comment]
I agree with how it seems this thread has evolved: it’s fine for the languages to diverge in cases like this where the implementation fits better in one case (static for Go) vs. another (instance for TS). I think we should do `IsSecret` in order to make this "feel right". To me, that would also help address some of the safety concerns. I'm not a huge fan of `unsafe` because it's not clear to the developer what unsafe really means. They would be left wondering, "unsafe in what way?" I would prefer to have strong language in the doc string explaining what this does and where you probably do/don't want to use this.

**Comment by lukehoban** [comment]
One additional thing that we might want (or need) to add here.  To address https://github.com/pulumi/pulumi/issues/2718, and for similar use cases, it's important to create an output which may or may not be a secret, depending on a promise for a boolean.  

In Node.js, it is "possible" to do this with code like:

```ts
        const code = pulumi.output(new pulumi.asset.AssetArchive(codePaths));
        (<any>code).isSecret = closure.then(c => c.containsSecrets);
```

However, this requires subverting the public API of `Output`, and may not be long-term stable if we make changes to internals of `Output`.  The equivalent thing also does not work in other languages.  What would be better would be to have a way to (optionally) pass the `isSecret` promise into the `pulumi.output` constructor so that it could decide whether to create a secret or not based on that input promise instead of a prompt decision between calling `pulumi.output` or `pulumi.secret`.

**Comment by stack72** [comment]
All of the SDKs have been updated with this functionality
