### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5662]
We need to make sure that pulumi works correctly on Python 3.9

**Comment by komalali** [comment]
Looks like grpcio is still working through Windows support https://github.com/grpc/grpc/issues/24344

**Comment by komalali** [comment]
`protobuf` doesn't have python 3.9 support yet, so it’s missing the equivalent of the `_message.cpython-38-darwin.so` file that is needed for the `SetAllowOversizeProtos` method. However, it appears we only use that method to override a default that is only really applicable for a k8s bug, more context in [this issue](https://github.com/pulumi/pulumi/issues/3981). 

However, I think we can wrap this in a try/except since it's not always needed, and not having the try/except is causing `Getting Started` workflows for folks using python 3.9 to fail.
