### ISSUE TITLE
Plugins not being automatically installed for new Go + AWS projects on Ubuntu 20 Desktop

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5724]
From https://www.reddit.com/r/devops/comments/jk4lkc/frustrations_with_pulumi_plugins_docs_seem_to_be/

New Go + AWS project on Ubuntu 20 Desktop:

I just signed up for Pulumi and was really impressed at how easy everything was. This was right up until the last step where I ran `pulumi up` and got this error.

```
pulumi:providers:aws (default):     error: no resource plugin 'aws' found in the workspace or on your $PATH
```
 
Nothing on their site seems to explain how to fix this. I already have aws-cli installed and other programs like Terraform amd cloud-nuke work fine with them.

Within five minutes of being frustrated I find myself on their GitHub issues page to find the solution luckily posted by someone having the same issue.

[Issue](https://github.com/pulumi/pulumi/issues/2097) - AWS plugin is not installed and tutorial documentation makes no mention of it

Solution

```
pulumi plugin install resource aws v0.15.0
```

I can't find anything in their docs that say what the latest version is or how to install any other plugins. This is super frustrating because you can't just run pulumi plugin install resource aws because you get an this error

```
error: missing plugin version argument
```

Where is the information about how the pulumi plugins work?

**Comment by justinvp** [comment]
Related: https://github.com/pulumi/pulumi/issues/5725

**Comment by viveklak** [comment]
The issue here seems that ubuntu 20.04 ships with go 1.13.8 by default while we require go 1.14 +. The go language runtime performs a go list command leveraging the program's go.mod that is not supported in go 1.13.8: https://github.com/pulumi/pulumi/blob/a6f8b9b205cdf975421520030a713b9ea489f625/sdk/go/pulumi-language-go/main.go#L194

```
 go version
go version go1.13.8 linux/amd64
> go list -m -json -mod=mod all
-mod=mod not supported (can be '', 'readonly', or 'vendor')
```

Of course this results in an empty response back from language runtime but the CLI doesn't really get any indication of the issue. I suggest we return an error here instead of the empty response? 

CC @justinvp @pgavlin
