### ISSUE TITLE
Reduce verbosity of pulumi/pulumi test runs

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5727]

**Comment by viveklak** [comment]
Some proposed changes here after talking to @komalali:
1. Add an optional quiet environment variable for output like https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/command.go#L34
2. Drop the go routine which prints "still running" since that was a travis hack: https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/command.go#L36
3. Drop the -v flag in https://github.com/pulumi/pulumi/blob/master/Makefile#L76 so we only see test logs for failing tests

@pgavlin could you take a look through the above and see if you concur?

**Comment by pgavlin** [comment]
> Add an optional quiet environment variable for output like https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/command.go#L34

I don't think that we should drop these, but I do think that we should be using [`t.Logf`](https://golang.org/pkg/testing/#T.Logf) rather than `fmt.Printf`. I think that would help ensure that all logging goes through the testing package, which should properly buffer it and render it at the end of the run.

> Drop the go routine which prints "still running" since that was a travis hack: https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/command.go#L36

:+1:

> Drop the -v flag in https://github.com/pulumi/pulumi/blob/master/Makefile#L76 so we only see test logs for failing tests

This seems very reasonable to me.

I think that there's something else that we do s.t. we see all logs streamed as they are emitted, but I can't remember exactly what it is. Whatever it is, we should undo it: we only needed this for Travis to keep it from killing jobs due to a lack of output.

We should also consider dropping the [prefix we attach to test output]( https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/program.go#L1516-L1533). That prefix is only really useful if all of the tests are simultaneously streaming output, and I think that the adjustments you and @komalali have proposed will obviate the need for it.

**Comment by viveklak** [comment]
> > Add an optional quiet environment variable for output like https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/command.go#L34
> 
> I don't think that we should drop these, but I do think that we should be using [`t.Logf`](https://golang.org/pkg/testing/#T.Logf) rather than `fmt.Printf`. I think that would help ensure that all logging goes through the testing package, which should properly buffer it and render it at the end of the run.
> 
> > Drop the go routine which prints "still running" since that was a travis hack: https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/command.go#L36
> 
> 👍
> 
> > Drop the -v flag in https://github.com/pulumi/pulumi/blob/master/Makefile#L76 so we only see test logs for failing tests
> 
> This seems very reasonable to me.
> 

I have made the above changes in https://github.com/pulumi/pulumi/pull/5751. Could I get eyes specifically on https://github.com/pulumi/pulumi/pull/5751/commits/865ef8231932b9613240900efcf7697a8bcf8a8f to make sure I interpreted your suggestion correctly?

> I think that there's something else that we do s.t. we see all logs streamed as they are emitted, but I can't remember exactly what it is. Whatever it is, we should undo it: we only needed this for Travis to keep it from killing jobs due to a lack of output.
> 
> We should also consider dropping the [prefix we attach to test output](https://github.com/pulumi/pulumi/blob/master/pkg/testing/integration/program.go#L1516-L1533). That prefix is only really useful if all of the tests are simultaneously streaming output, and I think that the adjustments you and @komalali have proposed will obviate the need for it.

Good point. Done in https://github.com/pulumi/pulumi/pull/5751/commits/fb0d21030cfb15f5e771932693b282d8675f7597
