### ISSUE TITLE
[codegen/go] Emit externally referenced resources/types

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5794]
Now that we have support for external refs in the schema (#5331), we need to ensure the codegen for each language properly emits those references, including any imports/usings at the top of files where they're used if necessary for the given language.

For example, here are some of the external resources/types referenced by the EKS `Cluster` component:

- (output) `readonly core: CoreData;`
   - `CoreData`
       - `instanceRoles: pulumi.Output<aws.iam.Role[]>;`
       - `encryptionConfig?: pulumi.Output<aws.types.output.eks.ClusterEncryptionConfig>;`
- (input) `instanceType?: pulumi.Input<aws.ec2.InstanceType>;`
- (input) `instanceRole?: pulumi.Input<aws.iam.Role>;`
- (input) `instanceRoles?: pulumi.Input<pulumi.Input<aws.iam.Role>[]>;`
- (input) `storageClasses?: { [name: string]: StorageClass } | EBSVolumeType`
   - `StorageClass`
       - `metadata?: pulumi.Input<k8sInputs.meta.v1.ObjectMeta>`
- (input) `fargate?: boolean | FargateProfile`
   - `FargateProfile`
       - `selectors?: pulumi.Input<pulumi.Input<aws.types.input.eks.FargateProfileSelector>[]>;`

**Comment by viveklak** [comment]
I have support for the external references here: https://github.com/pulumi/pulumi/pull/5826
I have two worries at the moment:
1. Having to add additional input/output types to all resources to support external references causes additional type bloat. While I have anecdotally been able to generate and use the SDK for azure-nextgen with the additional types locally - it doesn't seem sufficient to feel confident that this will work for our users and the resulting risk if the above PR is merged across all provider SDKs. Some options I am considering here:
- [ ] Add a custom runner for the azure-nextgen provider so we can get golang SDK compilation tests and a standardized watermark for overhead (https://github.com/pulumi/pulumi-azure-nextgen-provider/issues/353)
- [ ] Make codegen for external references for resources opt-in for provider SDKs (i.e. only generate the additional types for EKS, Kubernetes, AWS etc. and limit the overriding impact)
2. Getting more E2E test coverage to ensure external reference await logic works correctly in the Go SDK. While basic usage works for EKS I am not able to build confidence that it works across the board. Do we have a set of canonical examples for EKS which should work across all supported languages? I tried to use provider chaining in EKS but failed, however the problem seems to affect Python as well: https://github.com/pulumi/pulumi-eks/issues/501

**Comment by leezen** [comment]
@viveklak I think the second option feels 'limiting' in that we'd be closing off the use of multi-language components for other providers, which we would want to let people author. I suspect the first option is something we'll want to do anyway.

**Comment by viveklak** [comment]
> @viveklak I think the second option feels 'limiting' in that we'd be closing off the use of multi-language components for other providers, which we would want to let people author. I suspect the first option is something we'll want to do anyway.

My main concern is that we impose a penalty on every provider SDK regardless of the utility to multilang components. I understand your perspective as well though. I don't intend this to be a long term blocker but I was hoping we could use this as a controlled release valve - ala a feature flag.

Sadly go modules don't really allow this to be "on demand" inclusion.

**Comment by justinvp** [comment]
@viveklak, RE (1): Do we know what the actual problem is preventing building the azure-nextgen Go SDK? If it's just linting that's OOMing, can we temporarily disable Go linting (which I'm guessing is easier to do than setting up a custom runner)? Or is the concern that somehow consuming the SDK for users will be broken due to the large number of types?

RE (2): I've ported a some tests to Python at https://github.com/pulumi/pulumi-eks/tree/master/examples (dirs with `-py` suffix) and am planning to add more this week. Currently fixing a couple .NET issues preventing the single .NET test from passing (then will work on porting to .NET as well).

**Comment by viveklak** [comment]
> @viveklak, RE (1): Do we know what the actual problem is preventing building the azure-nextgen Go SDK? If it's just linting that's OOMing, can we temporarily disable Go linting (which I'm guessing is easier to do than setting up a custom runner)? Or is the concern that somehow consuming the SDK for users will be broken due to the large number of types?
> 

Building is also a problem - due to the large schema we need to a lot more RAM. CC @stack72 for any additional context I am missing. 

> RE (2): I've ported a some tests to Python at https://github.com/pulumi/pulumi-eks/tree/master/examples (dirs with `-py` suffix) and am planning to add more this week. Currently fixing a couple .NET issues preventing the single .NET test from passing (then will work on porting to .NET as well).

Awesome. I have ported the existing ones. Could you add me to the PR for additional examples you add?

**Comment by justinvp** [comment]
> Building is also a problem - due to the large schema we need to a lot more RAM.

Got it. Adding these additional types doesn't affect the schema, though, right?

**Comment by viveklak** [comment]
Correct no change to schema here. But this would give us a baseline/high watermark for resource requirements for compilation through the go examples in the provider.
