### ISSUE TITLE
pulumi new azure-csharp expects .NET 3.1 when I have 5.0 installed

### ISSUE THREAD

**Issue by ehrnst** [pulumi/pulumi#5913]
Totally new to Pulumi, i followed the [getting started guide for Azure](https://www.pulumi.com/docs/get-started/azure/). I chose to install .NET 5 only but this threw an error on `pulumi new azure-csharp`

Not sure if this is a documentation related issue, or a configuration issue.

## Expected Behavior
expected pulumi to run with net 5

## Current Behavior
got this error message
`The framework 'http://Microsoft.NETCore.App', version '3.1.0' was not found`

## Steps to Reproduce
1. follow 
2.
3.
4.

**Comment by mikhailshilkov** [comment]
@ehrnst Thanks for reporting this.

We currently [hard-code](https://github.com/pulumi/templates/blob/32b6ad11c3900f270f3409d125a4a60103fb3261/azure-csharp/%24%7BPROJECT%7D.csproj#L5) `netcoreapp3.1` in the `csproj` file in the template. We should consider making this configurable.

**Comment by cpeth** [comment]
I had same issue but work around was just to change the generated .csproj file to target `.net5`:

`<TargetFramework>net5.0</TargetFramework>`

**Comment by mikhailshilkov** [comment]
As of July 2022, Pulumi defaults to `net6.0` as the target framework, since it's currently the latest LTS version. If anyone needs to use some other .NET version, they'd need to change their `csproj` file and adjust `TargetFramework`.

I believe that the code in our templates relies on some features on the latest C# (e.g. top-level statements), so I'm not sure that asking for a preferred framework version would be helpful. We'd need to change the code if users picks something older like .NET Core 3.1.

I'll go ahead and close the issue.
