### ISSUE TITLE
version 2.18.0 broke everything

### ISSUE THREAD

**Issue by lth82** [pulumi/pulumi#6158]
Hi 

After upgrade to version 2.18.0 All Pulumi commands stopped working !.  We are completely stuck

## Expected Behavior
Pulumi commands like "up, destroy, preview" should work

## Current Behavior
Most of the Pulumi commands stopped working with this error

error: could not deserialize deployment: malformed resource value: id must be a string

## Steps to Reproduce

1. Have existing state in 2.17.2 .
2. Upgrade to 2.18.0
3. Make a code change
3. Run Pulumi up and apply the change
4. Run Pulumi again and see it fail.

**Comment by piclemx** [comment]
I don't know if this is the same problem of this one https://github.com/pulumi/pulumi/issues/6163

**Comment by lth82** [comment]
Hi @mikhailshilkov 

I will mail you the state. 

Thanks

**Comment by lth82** [comment]
And no downgrading to 2.17.2 did not help.

**Comment by justinvp** [comment]
Here's a summary of this issue:

- This issue affects .NET when passing resources to [`ComponentResource.RegisterOutputs`](https://github.com/pulumi/pulumi/blob/4335a44bfb9ddd5f03ba69fd3278824f1d21362d/sdk/dotnet/Pulumi/Resources/ComponentResource.cs#L52-L70), which is the case when using .NET and [Helm](https://github.com/pulumi/pulumi-kubernetes/blob/63f6322ca9e33d39a2e52afc00dc343f1f4f3369/sdk/dotnet/Helm/V3/Chart.cs#L228).
- The bug causes references to resources in properties to be serialized incorrectly in the state.
- v2.18.1 of the Pulumi CLI rolled back the change that introduced the regression to prevent folks from hitting it, but if you already ran into this on v2.18.0, the incorrect values are already persisted in the state.
- We have since made a change that allows the problematic values in the state to work correctly (https://github.com/pulumi/pulumi/pull/6164). We are planning to release these changes in v2.18.2 today.

If you ran into this problem on v2.18.0 and are currently blocked:

- We are planning to release v2.18.2 of the CLI today with a fix.
- We can provide instructions or help update your state to work again with v2.17.2 (or earlier) or v2.18.1.
