### ISSUE TITLE
Resource type alias doesn't work for one aliased resource parented to another aliased resource

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#6440]
Here is a repro program (with `azure-nextgen 0.6.0`, but I believe this is not provider-specific):

```ts
import * as azure from "@pulumi/azure-nextgen";

const resourceGroup = new azure.resources.v20200801.ResourceGroup("rg", {
    location: "westeurope",
    resourceGroupName: "dfsfsd",
})

const vnet = new azure.network.v20200801.VirtualNetwork("vnet", {
    resourceGroupName: resourceGroup.name,
    addressSpace: {
        addressPrefixes: ["10.2.0.0/16"],
    },
    location: "westeurope",
    virtualNetworkName: "vnet14342"
}, {parent: resourceGroup});
```

Provision the resources with `pulumi up`. Now, change the code to use the `latest` instead of `v20200801` for both resources.

Both resources have aliases between those versions defined. The alias is successfully applied to `ResourceGroup` and it's not replaced. However, the alias is not applied to the `VirtualNetwork` resource. The preview shows the vnet-to-be-deleted at the top-level:

```
     pulumi:pulumi:Stack                                k8s-azure-01-infrastructure-dev             
     ├─ azure-nextgen:resources/latest:ResourceGroup    rg                                          
 +   │  └─ azure-nextgen:network/latest:VirtualNetwork  vnet                             create     
 -   └─ azure-nextgen:network/v20200701:VirtualNetwork  vnet                             delete
 ```

Workaround:

1. Change `ResourceGroup` but not `VirtualNetwork`.
2. `pulumi up` - yes to no changes.
3. Change `VirtualNetwork`.
4. `pulumi up` - yes to no changes.

**Comment by lukehoban** [comment]
The issue here appears to be that our SDKs do not expand the product of child and parent aliases, they only do the union of parent and child aliases.  So in the case above, the aliases that make it to the engine are:

```
urn:pulumi:dev::aliasesparent::azure-native:resources:ResourceGroup$azure-native:network:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources:ResourceGroup$azure-native:network/v20150501preview:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources:ResourceGroup$azure-native:network/v20150615:VirtualNetwork::vnet
...
urn:pulumi:dev::aliasesparent::azure-native:resources/v20151101:ResourceGroup$azure-native:network:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources/v20160201:ResourceGroup$azure-native:network:VirtualNetwork::vnet
...
```

Note that only one of the parent or child alias is applied.  In reality, we also need to expand all pairs of child and parent aliases - so the actual list needs to be:

```
urn:pulumi:dev::aliasesparent::azure-native:resources:ResourceGroup$azure-native:network:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources:ResourceGroup$azure-native:network/v20150501preview:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources:ResourceGroup$azure-native:network/v20150615:VirtualNetwork::vnet
...
urn:pulumi:dev::aliasesparent::azure-native:resources/v20151101:ResourceGroup$azure-native:network:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources/v20151101:ResourceGroup$azure-native:network/v20150501preview:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources/v20151101:ResourceGroup$azure-native:network/v20150615:VirtualNetwork::vnet
...
urn:pulumi:dev::aliasesparent::azure-native:resources/v20160201:ResourceGroup$azure-native:network:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources/v20160201:ResourceGroup$azure-native:network/v20150501preview:VirtualNetwork::vnet
urn:pulumi:dev::aliasesparent::azure-native:resources/v20160201:ResourceGroup$azure-native:network/v20150615:VirtualNetwork::vnet
...
```

In summary:

|      |child|childAlias1|childAlias2|
|------------|-----|-----------|-----------|
|parent      |OK   |OK         |OK         |
|parentAlias1|OK   |NOT OK     |NOT OK     |
|parentAlias2|OK   |NOT OK     |NOT OK     |


I believe this will need to be fixed in the language SDKs.  For Node.js, it looks like this loop will have to include a nested loop over the child aliases:

https://github.com/pulumi/pulumi/blob/3b68ecc0fd398e47b2f4bfc58bb4d91a9a5105bb/sdk/nodejs/resource.ts#L293-L295
