### ISSUE TITLE
`pulumi stack` gets significantly slower with more number of secrets

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6445]
Executing `pulumi stack` gets significantly slower as the number of secrets increase. 

The example in **Steps to reproduce** exhibits this, but this problem gets much worse when secrets are re-used across multiple resources and end up in the stack multiple times - e.g. with `@pulumi/kubernetes.`

A trace shows a call to `api/decryptValue` at least once for each secret in the state file.

## Expected behavior

I would expect some overall decrease in performance as the number of resources in a stack increase, but the slowdown is significant when there are a large number of secrets.

## Current behavior

Results of testing the performance of `pulumi stack` with increasing number of secrets:
```
   1 secrets -  0 seconds
  10 secrets -  0 seconds
 100 secrets -  2 seconds
 500 secrets - 14 seconds
1000 secrets - 31 seconds
```

## Steps to reproduce

1. `git clone https://gist.github.com/c162a4596061b8d92f9298bb70c9bbb1 p-secret-performance`
2. `cd p-secret-performance`
2. `npm i`
3. `npm run repro`

### Output

```
% npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... Done.
Calling [pulumi stack] with [1] secrets took [0] seconds.

Calling [pulumi up] with [10] secrets... Done.
Calling [pulumi stack] with [10] secrets took [0] seconds.

Calling [pulumi up] with [100] secrets... Done.
Calling [pulumi stack] with [100] secrets took [2] seconds.

Calling [pulumi up] with [500] secrets... Done.
Calling [pulumi stack] with [500] secrets took [14] seconds.

Calling [pulumi up] with [1000] secrets... Done.
Calling [pulumi stack] with [1000] secrets took [31] seconds.
``` 

## Context (Environment)

Running on macOS, but I don't expect that it matters.

**Comment by nesl247** [comment]
To add to this, I reported this issue to @clstokes when we had a Kubernetes based project. In that project, we have a `Deployment` that depends upon a `Secret` for `secret.metadata.name`. We also have a `PodDisruptionBudget` and `HorizontalPodAutoscaler` that depend upon `deployment.metadata.name` and also `deployment.metadata.labels`. This is multiplied by about 18 as we have roughly 18 instances of the application in the same stack.

Because of this, we easily hit nearly 300 secrets within our production project, which takes around 90 seconds to run preview/up/stack due to this.

**Comment by lukehoban** [comment]
FWIW - here's what I see for @clstokes' example above - from Australia so my latency is significantly worse than his:

```
Calling [pulumi up] with [1] secrets... Done.
Calling [pulumi stack] with [1] secrets took [1] seconds.

Calling [pulumi up] with [10] secrets... Done.
Calling [pulumi stack] with [10] secrets took [3] seconds.

Calling [pulumi up] with [100] secrets... Done.
Calling [pulumi stack] with [100] secrets took [21] seconds.

Calling [pulumi up] with [500] secrets... Done.
Calling [pulumi stack] with [500] secrets took [98] seconds.
``` 

And I confirm in a trace that each `decryptValue` call takes ~200ms for me, and that these are performed serially.

**Comment by pierskarsenbarg** [comment]
I've run this with a secret provider (in this case KMS in eu-west-1 - my changes to Cameron's code are [here](https://gist.github.com/pierskarsenbarg/65072a2e011d26082a24db523faef0e8#file-repro-ts-L16-L18)) and got this output:

```zsh
❯ npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... Done.
Calling [pulumi stack] with [1] secrets took [1] seconds.

Calling [pulumi up] with [10] secrets... Done.
Calling [pulumi stack] with [10] secrets took [3] seconds.

Calling [pulumi up] with [100] secrets... Done.
Calling [pulumi stack] with [100] secrets took [23] seconds.

Calling [pulumi up] with [500] secrets... Done.
Calling [pulumi stack] with [500] secrets took [102] seconds.

Calling [pulumi up] with [1000] secrets... Done.
Calling [pulumi stack] with [1000] secrets took [211] seconds.
```

Running it whilst using it with the Pulumi KMS, I get the following:

```zsh
❯ npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... Done.
Calling [pulumi stack] with [1] secrets took [1] seconds.

Calling [pulumi up] with [10] secrets... Done.
Calling [pulumi stack] with [10] secrets took [3] seconds.

Calling [pulumi up] with [100] secrets... Done.
Calling [pulumi stack] with [100] secrets took [21] seconds.

Calling [pulumi up] with [500] secrets...and  Done.
Calling [pulumi stack] with [500] secrets took [109] seconds.

Calling [pulumi up] with [1000] secrets... Done.
Calling [pulumi stack] with [1000] secrets took [216] seconds.
```

So not particularly different

**Comment by pierskarsenbarg** [comment]
We've had a few more people having this issue. Had one just now from Germany, and Mitch had one the other day I think.

**Comment by pierskarsenbarg** [comment]
I've run the Pulumi program from Cameron's gist with KMS as a secret provider to get traces. They're attached to this comment
[traces.zip](https://github.com/pulumi/pulumi/files/6130817/traces.zip)

**Comment by lukehoban** [comment]
@pierskarsenbarg The traces you shared appear to be for updates, not for `pulumi stack` operations.  Can you share perf traces for the `pulumi stack` operation? 

The `pulumi update` performance in the traces you did share looks "expected".  It's is dominated by checkpoint writes - with 500 checkpoint writes taking ~300ms each, accounting for the vast majority of long pole time.  That is related to https://github.com/pulumi/pulumi/issues/3298.  There don't appear to be any encrypt/decrypt calls (or at least nothing that takes appreciable time).

**Comment by joeduffy** [comment]
I was curious about this, so took a bit of a look. I too can repro the slowness. A stack with 500 secrets and an empty Go program took me 95 seconds to run a `pulumi preview`.

There seem to be (at least) two places where we perform a full (serial) decryption for every update:

1. In the engine emitter, so that secrets can be masked from stdout: https://github.com/pulumi/pulumi/blob/da2bd2ab043f2588b3a136846da1b97505326f25/pkg/engine/events.go#L209-L223.

2. In the source evaluator/iterator, which runs the program, which then passes the resulting configuration to the language host: https://github.com/pulumi/pulumi/blob/da2bd2ab043f2588b3a136846da1b97505326f25/pkg/resource/deploy/source_eval.go#L96-L100.

There may be other places that do this &mdash; in fact, I am certain of it, because we see 1,500 calls to `DecryptValue` for only 500 secrets &mdash; but these were the two I found that are very definitely always on the critical path.

I put together a quick prototype of parallelizing the decryption. I first tried to figure out how to eliminate the need to do a full decryption, but both of those two above are hard to avoid. That first one seems impossible, since we need to know the full set of secrets before the first line of output is emitted. That second one actually surprises me a bit, because I thought the original design here was to be lazy, and have the language host work in terms of ciphertext up until (and only if) the plaintext is requested, at which point the decryption would be requested of the engine. This seems more performant and more secure.

I also prototyped memozation. I thought the decrypter was meant to do this, but either we're not sharing it as intended between the two code paths above, there is a byval/byref copying issue, and/or I'm imagining how it was supposed to work.

Here are the results:

* as-is today: 95s
* w/ parallelism (p=8): 12s
* w/ parallelism (p=8) and memoization: 6s
* w/ parallelism (p=32): 7s
* w/ parallelism (p=32) and memoization: 3s

Here is a patch with the (admittedly crude) prototype. Warning, there may be race conditions I am unaware of:

```diff
diff --git a/pkg/engine/events.go b/pkg/engine/events.go
index 7e4d6c1fb..02ee89808 100644
--- a/pkg/engine/events.go
+++ b/pkg/engine/events.go
@@ -206,19 +206,29 @@ func makeEventEmitter(events chan<- Event, update UpdateInfo) (eventEmitter, err
 	target := update.GetTarget()
 	var secrets []string
 	if target != nil && target.Config.HasSecureValue() {
+		decrypted, err := target.Config.Decrypt(target.Decrypter)
+		if err != nil {
+			return eventEmitter{}, err
+		}
+
 		for k, v := range target.Config {
 			if !v.Secure() {
 				continue
 			}
 
-			secureValues, err := v.SecureValues(target.Decrypter)
-			if err != nil {
-				return eventEmitter{}, DecryptError{
-					Key: k,
-					Err: err,
-				}
-			}
-			secrets = append(secrets, secureValues...)
+			//
+			// Honestly unsure why we use SecureValues here:
+			//
+			//
+			//	secureValues, err := v.SecureValues(target.Decrypter)
+			//	if err != nil {
+			//		return eventEmitter{}, DecryptError{
+			//			Key: k,
+			//			Err: err,
+			//		}
+			//	}
+
+			secrets = append(secrets, decrypted[k])
 		}
 	}
 
diff --git a/sdk/go/common/resource/config/map.go b/sdk/go/common/resource/config/map.go
index 6bdb97f34..1f6c7c34a 100644
--- a/sdk/go/common/resource/config/map.go
+++ b/sdk/go/common/resource/config/map.go
@@ -18,7 +18,9 @@ import (
 	"encoding/json"
 	"fmt"
 	"strconv"
+	"sync"
 
+	"github.com/hashicorp/go-multierror"
 	"github.com/pkg/errors"
 
 	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
@@ -27,20 +29,83 @@ import (
 
 var errSecureKeyReserved = errors.New(`"secure" key in maps of length 1 are reserved`)
 
+var (
+	decrypterParallelism = 32
+	memoizeDecryption    = true
+)
+
 // Map is a bag of config stored in the settings file.
 type Map map[Key]Value
 
 // Decrypt returns the configuration as a map from module member to decrypted value.
 func (m Map) Decrypt(decrypter Decrypter) (map[Key]string, error) {
+	// Each call to decrypt a value takes 200ms. At the moment, secrets must be decrypted
+	// eagerly for two reasons: 1) to be able to blind output to prevent accidental secrets
+	// leakage, and 2) to initialize the language runtimes which contain decrypted secrets.
+	// The latter should be able to be done more lazily (and securely!) whereas the former
+	// may just very well corner us into maintaining the current eager-decryption design.
+	//
+	// As a lame workaround, we'll parallelize the decryption for all known secrets.
+
+	// We batch up requests with some throttling so we don't overload the server.
+	var keys []Key
+	var values []Value
+	for k, v := range m {
+		keys = append(keys, k)
+		values = append(values, v)
+	}
+
 	r := map[Key]string{}
-	for k, c := range m {
-		v, err := c.Value(decrypter)
-		if err != nil {
-			return nil, err
+	var p int                   // outstanding workers.
+	var lk sync.Mutex           // lock protecting map, counter, and condition variable.
+	waiter := sync.Cond{L: &lk} // condition variable for notifying waiters and others.
+	var result error
+	for i := 0; i < len(keys); i++ {
+		k := keys[i]
+		v := values[i]
+		lk.Lock()
+		if mm := v.memo; memoizeDecryption && mm != nil {
+			// we have a memoized result, use it directly.
+			r[k] = v.memo.(string)
+		} else {
+			for p >= decrypterParallelism {
+				waiter.Wait()
+			}
+
+			p++ // Mark that we're about to create a worker.
+
+			go func() {
+				d, err := v.Value(decrypter)
+
+				// Now store the results and signal a waiter that we're done.
+				lk.Lock()
+				if err != nil {
+					result = multierror.Append(result, err)
+				} else {
+					r[k] = d
+					m[k] = Value{
+						value:  v.value,
+						secure: v.secure,
+						object: v.object,
+						memo:   d,
+					}
+				}
+				p-- // signal that we're done.
+				lk.Unlock()
+				waiter.Signal()
+			}()
 		}
-		r[k] = v
+		lk.Unlock()
 	}
-	return r, nil
+
+	// Finally, wait for all workers.
+	lk.Lock()
+	for p > 0 {
+		waiter.Wait()
+	}
+	lk.Unlock()
+
+	return r, result
 }
 
 func (m Map) Copy(decrypter Decrypter, encrypter Encrypter) (Map, error) {
diff --git a/sdk/go/common/resource/config/value.go b/sdk/go/common/resource/config/value.go
index cbdd8b7a5..da439f6b1 100644
--- a/sdk/go/common/resource/config/value.go
+++ b/sdk/go/common/resource/config/value.go
@@ -28,6 +28,7 @@ type Value struct {
 	value  string
 	secure bool
 	object bool
+	memo   interface{} // a field for memozing information on this value.
 }
 
 func NewSecureValue(v string) Value {
```

**Comment by benesch** [comment]
> I was curious about this, so took a bit of a look. I too can repro the slowness. A stack with 500 secrets and an empty Go program took me 95 seconds to run a `pulumi preview`.
> 
> There seem to be (at least) two places where we perform a full (serial) decryption for every update:
> 
> 1. In the engine emitter, so that secrets can be masked from stdout: https://github.com/pulumi/pulumi/blob/da2bd2ab043f2588b3a136846da1b97505326f25/pkg/engine/events.go#L209-L223
>    .
> 2. In the source evaluator/iterator, which runs the program, which then passes the resulting configuration to the language host: https://github.com/pulumi/pulumi/blob/da2bd2ab043f2588b3a136846da1b97505326f25/pkg/resource/deploy/source_eval.go#L96-L100
>    .
> 
> There may be other places that do this — in fact, I am certain of it, because we see 1,500 calls to `DecryptValue` for only 500 secrets — but these were the two I found that are very definitely always on the critical path.

The big area where we get crushed by secret decryption at @MaterializeInc is via `stack.DeserializeUntypedDeployment`, which serially decrypts the secrets it finds in the stack as it deserializes. We don't actually have many secrets in the config file. Our situation is similar to @nesl247 in that our usage of Kubernetes causes a few sensitive values to proliferate wildly through the stack inputs and outputs.

**Comment by benesch** [comment]
Here's a similar patch that fixes my issue:

```diff
diff --git a/pkg/resource/stack/deployment.go b/pkg/resource/stack/deployment.go
index 111b1db41..778de86fc 100644
--- a/pkg/resource/stack/deployment.go
+++ b/pkg/resource/stack/deployment.go
@@ -18,6 +18,7 @@ import (
 	"encoding/json"
 	"fmt"
 	"reflect"
+	"runtime"
 
 	"github.com/blang/semver"
 	"github.com/pkg/errors"
@@ -232,13 +233,51 @@ func DeserializeDeploymentV3(deployment apitype.DeploymentV3, secretsProv Secret
 	}
 
 	// For every serialized resource vertex, create a ResourceDeployment out of it.
-	var resources []*resource.State
-	for _, res := range deployment.Resources {
-		desres, err := DeserializeResource(res, dec, enc)
-		if err != nil {
-			return nil, err
+	// Deserialize across NCPUs workers to parallelize any secret decryption
+	// that might be required.
+	resources := make([]*resource.State, len(deployment.Resources))
+	{
+		type input struct {
+			i   int
+			res apitype.ResourceV3
+		}
+		type output struct {
+			i      int
+			desres *resource.State
+			err    error
+		}
+		inputCh := make(chan input, len(deployment.Resources))
+		outputCh := make(chan output)
+		for i := 0; i < runtime.NumCPU(); i++ {
+			go func() {
+				for {
+					input, ok := <-inputCh
+					if !ok {
+						return
+					}
+					desres, err := DeserializeResource(input.res, dec, enc)
+					outputCh <- output{
+						i:      input.i,
+						desres: desres,
+						err:    err,
+					}
+				}
+			}()
+		}
+		for i, res := range deployment.Resources {
+			inputCh <- input{
+				i:   i,
+				res: res,
+			}
+		}
+		close(inputCh)
+		for i := 0; i < len(deployment.Resources); i++ {
+			output := <-outputCh
+			if output.err != nil {
+				return nil, output.err
+			}
+			resources[output.i] = output.desres
 		}
-		resources = append(resources, desres)
 	}
 
 	var ops []resource.Operation
diff --git a/pkg/resource/stack/secrets.go b/pkg/resource/stack/secrets.go
index c60e99b91..0e7d34c9b 100644
--- a/pkg/resource/stack/secrets.go
+++ b/pkg/resource/stack/secrets.go
@@ -16,6 +16,7 @@ package stack
 
 import (
 	"encoding/json"
+	"sync"
 
 	"github.com/pkg/errors"
 	"github.com/pulumi/pulumi/pkg/v3/secrets"
@@ -118,6 +119,7 @@ func (csm *cachingSecretsManager) Decrypter() (config.Decrypter, error) {
 type cachingCrypter struct {
 	encrypter config.Encrypter
 	decrypter config.Decrypter
+	mu        sync.Mutex
 	cache     map[*resource.Secret]cacheEntry
 }
 
@@ -148,5 +150,7 @@ func (c *cachingCrypter) encryptSecret(secret *resource.Secret, plaintext string
 
 // insert associates the given secret with the given plain- and ciphertext in the cache.
 func (c *cachingCrypter) insert(secret *resource.Secret, plaintext, ciphertext string) {
+	c.mu.Lock()
+	defer c.mu.Unlock()
 	c.cache[secret] = cacheEntry{plaintext, ciphertext}
 }
```

Same disclaimer as @joeduffy that this is a bit crude. But it's stable enough for my local use.

**Comment by t0yv0** [comment]
Linking also the old idea to benchmark secret-heavy stacks so we are more aware of it: https://github.com/pulumi/home/issues/1570

**Comment by komalali** [comment]
I ran this using a local backend and passphrase secret provider just for fun:
```
⇒  npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... Done.
Calling [pulumi stack] with [1] secrets took [0] seconds.

Calling [pulumi up] with [10] secrets... Done.
Calling [pulumi stack] with [10] secrets took [0] seconds.

Calling [pulumi up] with [100] secrets... Done.
Calling [pulumi stack] with [100] secrets took [0] seconds.

Calling [pulumi up] with [500] secrets... Done.
Calling [pulumi stack] with [500] secrets took [0] seconds.

Calling [pulumi up] with [1000] secrets... Done.
Calling [pulumi stack] with [1000] secrets took [0] seconds.
```
😄 

Anyway, pretty clear that this issue is caused by the serial decryption of secrets during deserialization of the state file, and the roundtrip latency cost paid serially is the real crux of the issue. 

The proposed solution:

We'll add a BulkDecrypt method to the [Decrypter interface](https://github.com/pulumi/pulumi/blob/73a66f48ead301bacf1d7d2833c016cf803b57c1/sdk/go/common/resource/config/crypt.go#L37) that will accept an array of encrypted secrets. For the moment, each backend will just loop over those secrets and decrypt them in parallel. Over time, we can implement a [bulk-decryption endpoint](https://github.com/pulumi/pulumi-service/issues/7450) in the service and have the BulkDecrypt method call it instead.

On the deserialization side, we'll do a first pass through the state and collect all secrets needing decryption. We'll call the BulkDecrypt method to decrypt them all at once and cache the results. We can then do a second pass through state and satisfy all decryption requests from the cache.

**Comment by komalali** [comment]
Spent some more time digging into this and made a few more discoveries that change my original assessment above. The full experiments are described below, but my takeaways are:
* The issue is specific to the service secret provider
* It compounds the time for all operations that require deserializing the state file (update operations, outputs, etc.) - not just `pulumi stack`
* The fix is to bring the service secret provider in alignment with the cloud-backed secret provider

I was originally under the assumption that this affected both cloud and service backends due to @pierskarsenbarg's repro above, but after taking a closer look at it I believe that repro was also using the service secret provider because the secret provider is misconfigured in the [repro code](https://gist.github.com/pierskarsenbarg/65072a2e011d26082a24db523faef0e8#file-repro-ts-L16-L18) (you can see the corrected code required to configure a cloud-backed secrets provider in my experiments below).

## Current state of the world

### Service backend w/ service secret provider

Essentially @clstokes's code as described in the issue but also measuring time taken to run `up`.
[[Code]](https://gist.github.com/komalali/73cd83c2270cd77f50283a06b6a36083/058a0a6bcc3316276db15a73468652ab2cf56d4c)

**Result**
```
⇒  npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... took [3.43] seconds.
Calling [pulumi stack] with [1] secrets took [0.37] seconds.

Calling [pulumi up] with [10] secrets... took [5.35] seconds.
Calling [pulumi stack] with [10] secrets took [0.75] seconds.

Calling [pulumi up] with [100] secrets... took [31.79] seconds.
Calling [pulumi stack] with [100] secrets took [3.88] seconds.

Calling [pulumi up] with [500] secrets... took [183.45] seconds.
Calling [pulumi stack] with [500] secrets took [14.73] seconds.

Calling [pulumi up] with [1000] secrets... took [462.24] seconds.
Calling [pulumi stack] with [1000] secrets took [30.27] seconds.
``` 

### Service backend w/ KMS secret provider

[[Code]](https://gist.github.com/komalali/73cd83c2270cd77f50283a06b6a36083/89777c78eaa2fc74c2e46d79115c9888c62fbce0#file-repro-ts-L23)

**Result**
```
⇒  npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... took [4.80] seconds.
Calling [pulumi stack] with [1] secrets took [0.68] seconds.

Calling [pulumi up] with [10] secrets... took [6.05] seconds.
Calling [pulumi stack] with [10] secrets took [0.72] seconds.

Calling [pulumi up] with [100] secrets... took [21.54] seconds.
Calling [pulumi stack] with [100] secrets took [0.74] seconds.

Calling [pulumi up] with [500] secrets... took [134.53] seconds.
Calling [pulumi stack] with [500] secrets took [0.89] seconds.

Calling [pulumi up] with [1000] secrets... took [374.97] seconds.
Calling [pulumi stack] with [1000] secrets took [0.99] seconds.
```

### Local backend w/ KMS secret provider

[[Code]](https://gist.github.com/komalali/73cd83c2270cd77f50283a06b6a36083/79eaa2f1b7643ac9dca5f59e16e2d36777470e01#file-repro-ts-L23)

**Result**
```
⇒  npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... took [3.30] seconds.
Calling [pulumi stack] with [1] secrets took [0.55] seconds.

Calling [pulumi up] with [10] secrets... took [3.30] seconds.
Calling [pulumi stack] with [10] secrets took [0.59] seconds.

Calling [pulumi up] with [100] secrets... took [5.09] seconds.
Calling [pulumi stack] with [100] secrets took [0.57] seconds.

Calling [pulumi up] with [500] secrets... took [28.73] seconds.
Calling [pulumi stack] with [500] secrets took [0.59] seconds.

Calling [pulumi up] with [1000] secrets... took [92.27] seconds.
Calling [pulumi stack] with [1000] secrets took [0.65] seconds.
```

### Local backend w/ passphrase secret provider

Code is same as above but with `secretsProvider: "passphrase"`

**Result**
```
PULUMI_CONFIG_PASSPHRASE=password npm run repro

> repro
> ./node_modules/ts-node/dist/bin.js repro.ts

Calling [pulumi up] with [1] secrets... took [4.00] seconds.
Calling [pulumi stack] with [1] secrets took [0.57] seconds.

Calling [pulumi up] with [10] secrets... took [3.17] seconds.
Calling [pulumi stack] with [10] secrets took [0.61] seconds.

Calling [pulumi up] with [100] secrets... took [4.89] seconds.
Calling [pulumi stack] with [100] secrets took [0.57] seconds.

Calling [pulumi up] with [500] secrets... took [28.23] seconds.
Calling [pulumi stack] with [500] secrets took [0.62] seconds.

Calling [pulumi up] with [1000] secrets... took [94.14] seconds.
Calling [pulumi stack] with [1000] secrets took [0.65] seconds.
```
