### ISSUE TITLE
Produce console output while waiting for slow-to-create resources

### ISSUE THREAD

**Issue by floyd-may** [pulumi/pulumi#6574]
When resources are slow to create, the pulumi CLI produces no console output while waiting for those resources. When running pulumi in a hosted CI environment like, say, CircleCI, that can cause the CI job to be forcibly terminated. CircleCI, for instance, kills jobs that produce no console output after 10 minutes. Naturally, that means the Pulumi update needs to be cancelled via `pulumi cancel` because it was forcibly killed while it was still running. Therefore, subsequent CI jobs will fail immediately.

# Proposed feature: `--logwaitmessages[=<interval>]` flag

I propose that a flag for the pulumi CLI be added so that a "waiting..." message (or similar) will be output to stdout at least every `interval` seconds, with a sane default (30?). This will prevent pulumi from being auto-killed for producing no output for too long.

**Comment by susanev** [comment]
@dixler heres a few recommendations, pls only take what is useful to you...

- consider displaying feedback messages by default and then having a flag to turn off the feedback messages instead of what is proposed in the issue
- use feedback messages that give as much context and information as possible (e.g, `provisioning 2/4 resources...`); note the ... is a standard pattern to communicate that something is happening so lets try and append that if possible
- if we cant provide a count, consider displaying feedback messages using the Fibonacci sequence for lengths of time, so after 1 minute, 2 minutes, 3 minutes, 5 minutes, 8 minutes, 13 minutes, etc... maxing out at 55 minutes. (e.g, `provisioning...`)

**Comment by floyd-may** [comment]
My preference would be to leave the behavior unchanged with regard to maxing out; i.e. if a slow-to-create resource currently causes Pulumi to time out and give up, I'd say preserve that behavior; otherwise, if Pulumi will currently wait indefinitely, keep _that_ behavior.

**Comment by dixler** [comment]
Any reasons why the spinner is basically disabled in non-interactive mode?
https://github.com/pulumi/pulumi/blob/9df8d3a0281a4dcfe375461a4bab49a10747af4c/pkg/backend/display/diff.go#L55-L60
@Frassle

**Comment by Frassle** [comment]
>Any ideas on why the spinner is basically disabled in non-interactive mode?

The spinner assumes it can mutate the screen buffer by sending backspace chars to Printf. That only works if stdout is pointing to a tty (Which is basically what `IsInteractive` is reporting).

Having said that NewSpinnerAndTicker already has code to check if IsInteractive is true and falls back to just printing plain dots if we don't have a tty. So I'm not sure why this outer check is also here.

**Comment by floyd-may** [comment]
@dixler @pgavlin @Frassle thank you, _thank you_, **thank you** for this! Can one of you possibly tell me when to expect this to be available in the Pulumi CLI?

**Comment by Frassle** [comment]
The next scheduled release is next Wednesday (23rd)
