### ISSUE TITLE
Add ability to ignore files/directories within the project folder when using the `watch` command

### ISSUE THREAD

**Issue by doitadrian** [pulumi/pulumi#6620]
Continuing from https://github.com/pulumi/pulumi/issues/6537, now I have a new question.

Thanks to @pierskarsenbarg, we found what was causing the initial issue.

On my system, I was using the `local` backend, and as I was deploying new stuff, state files (located in `.pulumi` folder) would change, and the watch command would pick up those changes too, hence infinite re-deploys.

The question that I now have is...

Is it possible to tell the `watch` command to ignore the `.pulumi` folder somehow? 

So, only track changes from all folders / files that are located within the Pulumi project, except the folder in which the state files are being saved.

I believe that would resolve the original issue, linked above.

Thanks in advance! 🥂

**Comment by komalali** [comment]
Just to make sure I'm following, is your state file being stored in the same directory as the rest of your pulumi project?

**Comment by doitadrian** [comment]
Exactly.
![image](https://user-images.githubusercontent.com/5121148/112501867-e2cc2e00-8d89-11eb-8281-e7ae8d7c14f2.png)

**Comment by komalali** [comment]
Ah, interesting! The issue seems to be stemming from the fact that the `.pulumi` directory is on the same level as your `Pulumi.yaml` file (and therefore your pulumi project). I would think in that case that even change to your `code` dir would result in endless updates (you could test this by running `watch` and only updating files in `code`). If I'm correct on that hunch, you would need to ignore both `.pulumi` and `code` directories. 

Alternatively, you probably wouldn't hit this if your `Pulumi.dev.yaml` and `Pulumi.yaml` was contained within the `pulumi` directory.

Unfortunately ignoring directories/files within the pulumi project directory (i.e. the directory that contains `Pulumi.yaml`, `Pulumi.dev.yaml`) is not currently an option, but it seems like a reasonable thing to add so we'll track it in this issue.

**Comment by doitadrian** [comment]
Yeah, changing the code would also result in Pulumi redeploying the whole thing, which was really the ultimate goal here.

And just to eliminate any misunderstandings, I am talking about development here, not pre-production / production environments.

In any case, if an additional argument could be added for the `watch` command, that would be awesome. We'd then just ignore the `.pulumi` folder, and that's pretty much it. Basically, live coding and deploying! 

I appreciate the response @komalali, we'll make sure to check this issue from time to time.

Thanks!
🍻

**Comment by komalali** [comment]
>Yeah, changing the code would also result in Pulumi redeploying the whole thing, which was really the ultimate goal here.

Ah, I thought that might be the case but just wanted to make sure! And yeah, moving the state files out of the `api` directory should resolve this as a workaround.

I'm going to rename the issue to make it more generally applicable, thanks for bringing it up!

**Comment by doitadrian** [comment]
Hey @komalali, just wanted to let you know that I tried the above approach, and it seems it works 😊

I think for now, we'll try to do something with this approach, so the flag we've been discussing here, it's not something urgent, at least for us.

https://user-images.githubusercontent.com/5121148/112532563-4154d480-8da9-11eb-8516-065b318b66fc.mov

Thanks again for your and team's assistance!

**Comment by komalali** [comment]
Great news! Thanks for letting us know @doitadrian!

**Comment by doitadrian** [comment]
Just wanted to show off a bit with the almost-final solution we made🙂 🤓

![watch-command-webiny-5b3912494d2565828884b4a03d5aadba](https://user-images.githubusercontent.com/5121148/113026425-5b1b6080-9189-11eb-8ee1-150db7625c4b.gif)

And although we've managed to resolve the initial problem by relocating the state files outside of the Pulumi project, still, the mentioned ignore flags for the CLI would make it 100%. This is basically because of the code structure we have - both source and build files are placed in the Pulumi project folder. 

But all in all, it works, and the missing ignore flag is not a big deal. If the ignore flags gets released in the near future, we'll revisit.

**Comment by doitadrian** [comment]
Hi everybody, just wanted to quickly check in and see if there might be any chance that this makes it into one of the upcoming versions of Pulumi CLI maybe?

I've been thinking more about this and decided to share the exact case that might help with development.

So, ideally, upon executing the `watch` command in a specific folder (Pulumi project), I'd like to tell it to only include the `./pulumi` and `./code/**/build` folders. All other folders / files that are not located in provided folders should not be watched / should not trigger re-deployments.

This is how my Pulumi project folders looks like:

![image](https://user-images.githubusercontent.com/5121148/119491293-08f85500-bd5e-11eb-9e4a-edd76d1dcee2.png)

As an example implementation, in the Node.js world, for watching files / folders, we can use the [chokidar](https://www.npmjs.com/package/chokidar) library, which enables us to specify paths to watch in the following way:

![image](https://user-images.githubusercontent.com/5121148/119490401-15c87900-bd5d-11eb-9741-907e0ecc1862.png)

I think something like this could also make sense with the Pulumi CLI (paths would be passed via an additional argument).

Any thoughts maybe on this idea?

If you are not able to allocate time for this in the near future (I'm sure you're all super busy), maybe I'll try to find some time and see if I can make something of it. Although I never did anything with Go, so I might not progress too fast :) 

Thanks in advance!

**Comment by komalali** [comment]
Hey @doitadrian, I think adding paths to watch is a good idea, but yeah, this issue is unlikely to be prioritized in the near future. If you happen to find some time to pursue it we'd be happy to take a PR. I haven't done a lot of digging myself in this area but I'd start with looking at https://github.com/pulumi/pulumi/blob/master/pkg/backend/watch.go and specifically passing the correct paths to [notify.Watch](https://github.com/pulumi/pulumi/blob/master/pkg/backend/watch.go#L70-L72). The flag itself would need to be added to the [CLI command for watch](https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/watch.go) and then funneled through to the watch function.

Hopefully that's a useful starting point if you want to do this but definitely no pressure 😄

**Comment by doitadrian** [comment]
Thanks @komalali !

**Comment by doitadrian** [comment]
Did some digging, and found out that the `notify` lib that the `watch` command internally uses actually has a separate [`WatchWithFilter`](https://github.com/Zillode/notify/blob/master/notify.go#L71) function that we could use here. 

Step by step... 🙂
