### ISSUE TITLE
Add a resource option to force a replacement

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6753]
There are times when it is important to force a replacement of a resource even if changes to the resource do not indicate they require replacement.  One example is a Kubernetes CustomResourceDefinition, none of whose properties force replacement, even though for many CRDs, they can't actually be updated in place (because of forward-incompatibilites).  

Note that in many cases, a workaround for the lack of this is to change the physical name of the resource - which will generally force replacement.  However, there are cases where it is important to keep the physical name the same, but where delete-before-replace replacement is desired - and no other properties force replacement.

A solution would be to offer a resource option to override the replacement decision coming back from the resource provider itself.  I can see two options for this:
* `forceReplace: boolean` - to indicate that the resource should always be replaced - even if there are no changes
* `replaceOnChange: boolean` - to indicate that if there are any changes, a replacement should be done instead
* `replaceOnChange: string[]` - to indicate that if any of the listed properties reports a change, a replacement should be done instead

The latter two seem more useful, and it is likely that the latter is the most useful in practice.

**Comment by lukemundy-vgw** [comment]
just wanted to add my particular use case here.

we have a handful of AWS Fargate services that tail a bunch of our append-only event store database tables and send the data to an S3 delivery Firehose. Sometimes we need to change the format of the data being sent to the Firehose and as such we typically save the new version of the data into a separate prefix in the S3 bucket.

Currently, if we change the bucket configuration for the Firehose it gets updated in place and new data received will begin going to the new location. However since this change can occur before the Fargate service is updated, it means some data will be sent to the new location but in the old format. If Pulumi were to replace it instead, a new Firehose would be created and then a new firehose ARN would be given to only the new Fargate services, so only new data would go to the new bucket prefix.

To work around this we've done as you've already outlined - changing the name of the resource whenever there's a data format version change, but what I'd like to be able to do is the last option you have suggested.

**Comment by NewbiZ** [comment]
Any update on how/if this was implemented?

I have a use case for Elastic IPs, where I got a public IP that was apparently banned on a number of websites. I would like to recreate this EIP so that I can have a new "clean" public IP that is not blacklisted.

**Comment by lukehoban** [comment]
@NewbiZ See https://www.pulumi.com/docs/intro/concepts/resources/#replaceonchanges for details of the feature that was added to support this.
