### ISSUE TITLE
Unexpected path resolution of virtualenv

### ISSUE THREAD

**Issue by cblegare** [pulumi/pulumi#6844]
First, thanks for pulumi, it's quite nice!

When using both `runtime:options:virtualenv` and `main` option, the virtualenv path is resolved relative to `main` and should be relative to the `Pulumi.yaml` file.

This is unexpected and is enough of an inconsistent UX that IMO is a bug (though you may disagree)

## Expected behavior

When defining relative path from a configuration file (here `Pulumi.yaml`), it is expected that they'll be resolved as relative to the parent folder of this file, not relative to each other.

## Current behavior

```
    Traceback (most recent call last):
      File "/home/me/myproject/venv/bin/pulumi-language-python-exec", line 14, in <module>
        import pulumi
    ModuleNotFoundError: No module named 'pulumi'
    It looks like the Pulumi SDK has not been installed. Have you run pip install?
    If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
 
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

## Steps to reproduce

Given a project structure

```
├── infra/
│   └── __main__.py
├── venv/
└── Pulumi.yaml
```

With Pulumi.yaml

```yaml
name: myproject
description: Nice project
runtime:
  name: python
  options:
    virtualenv: venv
main: infra
```

make sure pulumi is installed

```shell
source venv/bin/activate
pip install pulumi
```

run pulumi

```shell
pulumi up
```

pulumi looks for a virualenv at `/home/me/myproject/infra/venv` but should find it in `/home/me/myproject/venv`

## Workaround

Given the project defined above,

```yaml
name: myproject
description: Nice project
runtime:
  name: python
  options:
    virtualenv: ../venv  # this shoudl do the trick
main: infra
```

---

**EDIT**
-  added workaround

**Comment by t0yv0** [comment]
I can repro the issue but I'm pondering where a clean fix should go.

The context of this issue is `GetRequiredPlugins` call directed at
Python language provider `pulumi-language-python`. The implementation
tries to manage the virtual environment as it needs to actually invoke
Python with the rigtht dependencies:

```
// LanguageRuntime is the interface that the planning monitor uses to drive execution of an interpreter responsible
// for confguring and creating resource objects.
service LanguageRuntime {
    // GetRequiredPlugins computes the complete set of anticipated plugins required by a program.
    rpc GetRequiredPlugins(GetRequiredPluginsRequest) returns (GetRequiredPluginsResponse) {}
...
}

message GetRequiredPluginsRequest {
    string project = 1; // the project name.
    string pwd = 2;     // the program's working directory.
    string program = 3; // the path to the program.
}
```

In my repro it is invoked with this GetRequiredPluginsRequest:

```
{
  "project": "myproject",
  "pwd": "/Users/anton/repro-pulumi-6844/infra",
  "program": "."
}
```

In addition, the following information is available to the language
host:

```
os.Getwd() = "/Users/anton/repro-pulumi-6844/infra"
host.virtualenv = "venv" (parsed from cmd-line arg --virtualenv)
```

The implementation then resolves the abs path of the `venv` against
the `cwd`, which breaks assumptions in the other parts of the
codebase. For example, `pkgs/cmd/pulumi/new.go` has another set of
venv managing functions.

How does the information get populated? It appears that the engine
carries generic code to init language plugins; for example `venv`
param is passed verbatim from `Pulumi.yaml` in a stringly typed map.

I am trying to find a clean way to resolve `Pulumi.yaml` location in
the `GetRequiredPluginsRequest` handler to use that as the basis of
absolute paths, and without changing the engine-plugin protocols too
much. Failing that I am considering to put a hack teaching the engine
generic language plugin code to special-case on Python venv handling
and convert it to abs path before the lang plugin sees it.
