### ISSUE TITLE
Extend Pulumi Package metadata to include where the plugin is published

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi#6931]
To ensure a smooth experience for Pulumi Package consumers (#6932), the Pulumi Package needs to know where its plugin can be downloaded from. We should expand the Pulumi Package metadata (and publishing process) to have this information.

**Comment by iwahbe** [comment]
This was fixed by several of the PRs from https://github.com/pulumi/home/issues/1655 (Note: internal link).
Specifically:
- https://github.com/pulumi/pulumi/issues/7243
- https://github.com/pulumi/pulumi/issues/7245
- https://github.com/pulumi/pulumi/issues/7244
- https://github.com/pulumi/pulumi/issues/8701 (nodejs already had this general facility)
