### ISSUE TITLE
How to run pulumi aws-python inside a docker container?

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi#6973]
I have a pulumi project which is based on `aws-python` template.

And I want to run it inside a [`pulumi/pulumi`](https://hub.docker.com/r/pulumi/pulumi) docker container.

My pulumi backend is an AWS S3 bucket.

Here's my command to run pulumi inside a docker container.

```
docker run -it \
    -e PULUMI_CONFIG_PASSPHRASE=<my_passphrase> \
    -e AWS_ACCESS_KEY_ID=<my_key_id> \
    -e AWS_SECRET_ACCESS_KEY=<my_secret> \
    -e AWS_REGION=ap-northeast-1 \
    -w /app \
    -v $(pwd):/app \
    --entrypoint bash \
    pulumi/pulumi \
    -c "pip install -r requirements.txt && pulumi login s3://<my_bucket> && pulumi preview --stack stage --non-interactive"
```

The error I got with the above command is 

```
Previewing update (stage):

error: failed to discover plugin requirements: The 'virtualenv' option in Pulumi.yaml is set to "venv", but "/app/venv" doesn't appear to be a virtual environment; run the following commands to create the virtual environment and install dependencies into it:

    1. python3 -m venv /app/venv
    2. /app/venv/bin/python -m pip install --upgrade pip setuptools wheel
    3. /app/venv/bin/python -m pip install -r requirements.txt
```

Why does it say that "/app/venv" doesn't appear to be a virtual environment?

How does the program determine if it is a virtual environment?

I've mounted my `venv` folder into the docker container. I think it would be a virtual environment.

I know I can avoid this error by removing `virtualenv` in `Pulumi.yaml` file. But having to remove this option when running inside a docker container is inconvenient.

**Comment by lukehoban** [comment]
What are the contents of the `$(pwd)` folder you are mounting?  You mention it has a `venv` subfolder, is that folder initialized as a virtualenv?

**Comment by lyenliang** [comment]
My `$(pwd)` folder contains the following files:

```
.gitignore
Pulumi.stack1.yaml
Pulumi.stack2.yaml
Pulumi.yaml
README.md
__main__.py
__pycache__
requirements.txt
venv/
```

The `venv` folder is created by running `pulumi new aws-python`. I think it has already been initialized as a virtualenv by pulumi.

**Comment by lukehoban** [comment]
The issue here is that `/app/venv/bin/python` is a symlink, and is a link to a path on your host system, which doesn't exist inside the container.  So when Pulumi tries to use the `python` in the virtual environment, it can't actually access it.  You will need to activate the virtual env within the container so that it is initialized wrt the Python interpreter available there.  If you gitignore the `venv` and then let the container mount a clean git checkout, this should "just work".  I believe this is a somewhat general issue with venvs, where they are not "portable", and must be re-created locally to any given development environment.
