### ISSUE TITLE
PromiseRejectionHandledWarning: Promise rejection was handled asynchronously

### ISSUE THREAD

**Issue by jamesla** [pulumi/pulumi#7043]
(contrived example to show the error).

I'm trying to create a test and getting the error "PromiseRejectionHandledWarning: Promise rejection was handled asynchronously"

```
import { Vpc } from '@pulumi/awsx/ec2';
import { describe, it } from 'mocha';

describe('Network', () => {
  const myvpc: Vpc = new Vpc('test', {
    cidrBlock: '10.0.0.0/16',
  });

  it('should use correct cidr address', (done) => {
    myvpc.vpc.cidrBlock.apply(vpc => {
      done();
    });
  });
});
```

full error is

```
  Network
(node:84386) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:84386) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
```

Does anybody know what is happening here?

**Comment by EvanBoyle** [comment]
Can you share the full example? Are you following the unit testing guide? https://www.pulumi.com/docs/guides/testing/unit/

**Comment by jamesla** [comment]
yes following the examples exactly and other tests are passing fine.

Full example:

```
import * as pulumi from '@pulumi/pulumi';

pulumi.runtime.setMocks({
  newResource(type: string, name: string, inputs: any): { id: string, state: any } {
    const id: string = '12345';

    return {
      id,
      state: {
        ...inputs,
      },
    };
  },
  call(token: string, args: any) {
    return args;
  },
});

import { Vpc } from '@pulumi/awsx/ec2';
import { describe, it } from 'mocha';

describe('Network', () => {
  const myvpc: Vpc = new Vpc('test', {
    cidrBlock: '10.0.0.0/16',
  });

  it('should use correct cidr address', (done) => {
    myvpc.vpc.cidrBlock.apply(vpc => {
      done();
    });
  });
});
```

**Comment by EvanBoyle** [comment]
@jamesla the awsx vpc resource is a fairly complex component resource: https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/ec2/vpc.ts

If I had to guess, the mocks you've provided are not sufficient and the component is throwing somewhere during creation due to missing data. You could try running the tests with the `--trace-warnings` flag, or adding an uncaught handler on the process to get a stack trace that should point you towards where the missing mock data might be.

Here's an old issue that talks through some details of mocking out the VPC component, that might be of use on getting on the right track: https://github.com/pulumi/pulumi-awsx/issues/531

**Comment by jamesla** [comment]
Thanks I'll take a look over there
