### ISSUE TITLE
Backend configuration precedence

### ISSUE THREAD

**Issue by cblegare** [pulumi/pulumi#7155]
Backend configuration in project configuration file takes precedence on commandline argument.  This is an unexpected terminal user interface.

## Expected behavior

Given a backend URL `http://configured-backend` in `Pulumi.yaml`, when I use the command line tool `pulumi login http://some-other-backend`, the later should be used.

I would expect this order of precedence:

- command line argument
- environment variable
- `Pulumi.yaml`

## Current behavior

The URL in `Pulumi.yaml` takes precedence.

**Comment by lukehoban** [comment]
`pulumi login` is a global operation which logs you into a backend.   This is stored in `~/.pulumi`.

For operations within a project scope, they will decide what backend to connect to in the following order:
* If the project specifies a backend, use it
* If the environment variable specifies a backend, use it
* Else, use the default globally set backend established by the most recent call to `pulumi login`.

This is by design to ensure that users do not need to run `pulumi login` to modify the global state when moving between contexts.  

Is there a usage workflow that you feel is particularly difficult to manage with this behaviour?

**Comment by cblegare** [comment]
Then I think this design is wrong, and quite dangerous and absolutely counter-intuitive.

A manual invocation of the command line should have precedence on everything since its the most explicit and direct manifestation of human will (when compared to config file and env var).  As an example, when a project in source code configure a backend, but in specific condition in a CI pipeline I need an other backend, I need to edit the config file (with clever `sed`, `awk` or whatever yaml tool).  How can this make sense?  People always work on projects, the notion of global backend has probably near to 0 use-cases in real life.

Precedence should be ordered the other way around, closely related to the lifecycle of the data.

- **the command line interface**, very clear intention of user and short lived.  The command name itself sounds like it has a time-to-live (`login`).  For this "design" to work as intented, the command would have been named something more like `set-fallback-backend`
- **environment variable**, less explicit but suitable for temporary situations
- **long lived configuration file**, hard to change (most likely require a commit) is the fallback value for a given project

If you want to provide a user-global definition of backend, to it the right way with a user configuration file living under the XDG_CONFIG_HOME for instance.

The key here is communicating clearly intention and purpose.
