### ISSUE TITLE
Ansible Vault Secrets Provider

### ISSUE THREAD

**Issue by designermonkey** [pulumi/pulumi#7164]
Hi there,

I would like to (continue) use Ansible Vault to store encrypted secrets. We're transitioning from Terraform + Ansible over to Pulumi + Ansible and would like to keep our secrets where they are, but I can't find any mention anywhere of using the two together.

Thanks.

**Comment by pierskarsenbarg** [comment]
Hi John,

I've spoken with an engineer internally since your first email this morning and it seems that what you're asking currently isn't possible due to the library we're using to manage those secrets. If you did want to continue to use Ansible Vault, you could use the code you're writing with Pulumi (or even better, using something like our Automation API) to access those secrets, but it wouldn't be baked into Pulumi.
