### ISSUE TITLE
Q: Why is Pulumi appending generated chars to my resource names?

### ISSUE THREAD

**Issue by JordanMarr** [pulumi/pulumi#7368]
I am trying to rewrite my ARM template using Pulumi (first attempt).
How do I prevent it from adding generated characters to the end of every resource name?

## Steps to reproduce

* I create a KeyVault named `jm-mta-kv-test` and then call `pulumi up`
* Pulumi creates this resource: `jm-mta-kv-test3a27918`

Expected: My resource name should be what I specify
Actual: Pulumi appends garbage characters

**Comment by stack72** [comment]
Hi @JordanMarr 

So Pulumi takes the approach of autonaming by default - this is so that users can take advantage of create before destroy scenarios where 2 resources can't be named the same

You can override this at any time by specifying a name to the args of a resource

I have included a link to our docs on this that I hope helps https://www.pulumi.com/docs/intro/concepts/resources/#names

Let us know if the docs need to be more clear here

Paul

**Comment by JordanMarr** [comment]
I see... that's very advanced!  

So then this may be a dead-end for my little test here because I'm using `Pulumi.FSharp.Azure` like so:

```F#
    let kv = KeyVault.keyVault {
        name $"{co}-mta-kv"
        resourceGroup rg.Name
        skuName "standard"
        tenantId myTenantId
    }
```

AFACT, the `name` takes a string.

**Comment by JordanMarr** [comment]
Another small issue this created for me was that it said my name was too long (which now I realize it was calculating it with the appended characters).

**Comment by UnoSD** [comment]
The `Pulumi.FSharp.Azure` helpers would not be supported here as it's not a project from the Pulumi team; but for future reference: the operation `resourceName` maps directly to the name of the resource rather than the Pulumi name. That will do the trick.

**Comment by JordanMarr** [comment]
Thank you Stefano, 
I was looping back here to post the answer but you have already done it. 😄
Closing.
