### ISSUE TITLE
Preview across multi-language boundary is not sufficiently detailed.

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#7464]
A preview that crosses a multi-language component boundary is wrong and not sufficiently detailed. In the preview below, the `launchTemplate` is not a `output<string>`, and not detailed.

![image](https://user-images.githubusercontent.com/293763/124974723-fb332200-dfe1-11eb-8e2d-9cd064ffa618.png)

## Steps to reproduce

See internal slack for more info.

**Comment by justinvp** [comment]
Program: Python
Provider: Go

**Comment by justinvp** [comment]
When an object with a nested output gets passed to a multi-language component, the outputness gets pulled up to the top level instead of staying at the nested level. This happens in the Go SDK when copying the inputs into an args struct. If a struct's field's type is an input or output type, we create an output and set `known` based on whether the value doesn't contain any unknowns.

https://github.com/pulumi/pulumi/blob/7b7f03ea55eb323d84b2be8e4f7b11525e489a23/sdk/go/pulumi/provider.go#L254-L262

I think the solution is the same as #7434. With that, outputs will be marshaled as special objects (similar to archives, assets, and resource refs), which will allow us to keep the outputness at the nested level when unmarshaling, rather than pulling it up to the top level.

**Comment by justinvp** [comment]
Note: A separate but related issue is that (with the current behavior) the top level output is displayed as `output<string>`, which is confusing because we know the top level value isn't a string. #7716 tracks dropping the `<string>` part so that only `output` is emitted for outputs in diffs.

**Comment by emiliza** [comment]
Closing out as a dupe - will be implemented as part of https://github.com/pulumi/pulumi/issues/7434
