### ISSUE TITLE
Bad pattern when setting certain characters in config

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#7501]
Running the following: `pulumi config set foo fc#$alRj_MYpL&ie[Gs` or `pulumi config set bar fc#$alRj_MYpL&ie[Gs --secret` returns the following message for both:

```zsh
[1] 38066
zsh: bad pattern: ie[Gs

[1]  + 38124 done       pulumi config set blah fc#$alRjQ_MYpL
```

and the following value added to the config (both when specifying the `--secret` flag or not):

```yaml
project-name:foo: fc#
``` 

(the value `fc#$alRj_MYpL&ie[Gs` came from a password created with the Random provider)

## Steps to reproduce

1. Create new Pulumi program and stack
2. Type either of the above commands

Expected:  Value added to the config either as plaintext or encrypted, depending on the command
Actual:  Error message and the first three characters added to the config in plaintext

**Comment by komalali** [comment]
I don't believe this is an issue with pulumi, but rather with how zsh parses your input. There are ways around it:

Using quotes:
```
pulumi config set foo "fc#$alRj_MYpL&ie[Gs"
```

Unfortunately this doesn't work all the way, if you run `pulumi config`, you'll see:
```
KEY  VALUE
foo  fc#&ie[Gs
```
This is because the `$` character is parsed as the start of a variable in the shell. So to actually get the correct value, you'll need to escape the `$`:
```
pulumi config set foo "fc#\$alRj_MYpL&ie[Gs"
```
Now, when you run `pulumi config`, you'll see the expected result:
```
KEY  VALUE
foo  fc#$alRj_MYpL&ie[Gs
```
