### ISSUE TITLE
Consistently implement (and document) depends on a component across languages

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7542]
Today. using `dependsOn: [component]` behaves differently depending on whether `component` is a remote or non-remote component, and on what language the `dependsOn` is used in:
1. Depending on a remote component will always wait on all of its children, regardless of the language of the host or guest resource (one exception to this is being fixed in https://github.com/pulumi/pulumi/pull/7541).
2. Depending on a non-remote component in Node.js will:
a. In Node.js and .NET: wait on all of its transitive custom and remote resource children.
b. In Go and Python: not wait on any of its children.

We should ensure this is implemented consistently across language runtimes.

**Comment by emiliza** [comment]
From planning: Initial task- sketch a design, don't just copy pasta node work
cc: @t0yv0 @pgavlin

**Comment by clstokes** [comment]
Per the end user, a fix for Go is more important than Python here, but fixes for both are needed.

**Comment by pgavlin** [comment]
I think that porting the existing logic is fine, but the implementations will definitely be a bit unwieldy.

As far as a longer-term solution for the resource model itself, how about stating that depending on a component depends on all of the children that were known at the time the component's `RegisterResourceOutputs` call was made? This is a behavior that can be implemented in the engine. I believe that it is flexible enough to accommodate even those components that create resources in applies (e.g. Helm charts), provided that those resources are designed s.t. they do not call `RegisterResourceOutputs` until any resource-creating applies have run (e.g. for a Node Helm chart, `RRO` would depend on the `ready` property).

**Comment by t0yv0** [comment]
1. Notes on non-determinism 

I've found this in the docs: "Also inside of its constructor, allocate any child resources, passing the parent option as appropriate to ensure component resource children are parented correctly." Do we actually prohibit or discourage creating children outside the constructor? This seems possible and a source of non-determinism.

It feels a little unfortunate to be stating that our desired semantic is non-deterministic ("all of the children that were known at the time of RegisterResourceOutputs call"), since valid programs can declare children before or after the call. Perhaps this could be slightly amended to making sure that programs that accept children after such time fail with an exception, to direct users to fix it? Still even then, the failure would be non-deterministic.

This may be wishful thinking (out of reach), but is it quite impossible to make sure language SDKs lexically mark off a block where children may be allocated, so we know precisely (as an event) when all children are finished being added and disallow any new children past that point. This can be constructor, or "RegisterResourceOutputs", or something similar.

2. Could we accept "In Go and Python: not wait on any of its children." as the ideal semantic? If `parent-child` relation had no impact on dependency graph at all. This would be quite orthogonal then, and we do not need to worry about sync points on the child-set as much. The user that needs the dependency to be respected can perhaps model it via explicit dependencies (outputs from child that are needed as inputs in the dependent resource, or else depends_on pointing to the child).

3. Any more examples how this plays out in practice? I've not seen enough to have a strong opinion. Or else are we quite sure we got consensus on which behavior we want? If so we can move on to figuring out how to build it.

**Comment by t0yv0** [comment]
Reading through the implementation PRs helped me withdraw my objection to the "children at the time of ...". The user controls program order, and assuming no resources are created in apply, that order determines which children are observed, which is also quite natural to reason about to the user.
