### ISSUE TITLE
TypeScript Testing stuck at resource creation. Timeout Exceeded.

### ISSUE THREAD

**Issue by diego-huerta** [pulumi/pulumi#7561]
Hello, I have an issue writing unit tests in pulumi-ts. It throws me this:

`
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
`

## Steps to reproduce
You can check it here. https://github.com/diego-huerta/pulumi-example.  Try to test it out running yarn run test or use a devugger for seeing that the call get lost when reach a creation statement.

Expected: The tests should be marked as successfull, because its hardcoded that way.
Actual: The call never reaches beyond the resource creation.

**Comment by emiliza** [comment]
The timeout is coming from Mocha, if you wanted you could increase that - but I don't think this would solve your problem since the example's code you shared is pretty bare.

I'm having issues running your example locally, but something here doesn't look quite right: https://github.com/diego-huerta/pulumi-example/blob/master/src/service-example.test.ts#L23-L24

Within `pulumi.all` you should be passing an output, not your ServiceExample class. Also probably shouldn't be creating new resources within the test, but in the ServiceExample itself.

Check out the example here: https://github.com/pulumi/examples/tree/master/testing-unit-ts for some prior art.  Hope this helps!

**Comment by diego-huerta** [comment]
Ok, let me check it out what you said @emiliza Thanks!
I'll be in touch
