### ISSUE TITLE
TF Bridged Provider request : `pulumi-vercel`

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/pulumi#7615]
## Affected feature

New provider for [Vercel](https://vercel.com), a cloud-native service for building and hosting Next.js-based websites.

The most mature TF provider is available here:
https://registry.terraform.io/providers/chronark/vercel/latest/docs

NB: Vercel is a Series C startup that raised $163M [at this point](https://www.crunchbase.com/organization/vercel/company_financials)

NB2: There's also an [issue on their side](https://github.com/vercel/next.js/issues/16643) asking for a Pulumi integration

## Potential use-cases

- Managing DNS across cloud providers
- Centralized secrets / environment variable management

**Comment by kwnath** [comment]
Is there a way to contribute to this?

**Comment by emiliza** [comment]
@kwnath if you're interested in contributing, please take a look at https://github.com/pulumi/pulumi-tf-provider-boilerplate - we'd happily support you in taking this on 😄

**Comment by niklasravnsborg** [comment]
Hey there, is there anyone working on this currently? I might be able to invest some time to get this up and running since I need a Pulumi-Vercel integration.

**Comment by niklasravnsborg** [comment]
Hey @emiliza, I looked into `pulumi-tf-provider-boilerplate` and also into which terraform package I might be able to use as the base terraform provider. 

Currently there are two Terraform providers for Vercel: 

- https://github.com/chronark/terraform-provider-vercel (by chronark)
- https://github.com/vercel/terraform-provider-vercel (by Vercel)

The provider by chronark is based on the established Terraform SDKv2. The provider by Vercel is based on the new [Terraform Plugin Framework](https://github.com/hashicorp/terraform-plugin-framework), which is the upcoming API for developing Terraform plugins. Since the provider by chronark hasn't implemented all Vercel features yet, I would want to use the official plugin by Vercel.

The [pulumi-tf-provider-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate) currently accepts `schema.Provider` of the SDKv2 in `provider/resources.go`. I didn't yet find a way to satisfy the [Provider interface of pulumi-terraform-bridge](https://pkg.go.dev/github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim#Provider) with the new [Terraform Provider by the new plugin framework](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/tfsdk#Provider). Are there any plans to support the new Terraform Plugin Framework in the near future? If so, it would make integration with Vercel much easier.

Links: https://www.terraform.io/plugin/which-sdk

**Comment by rawkode** [comment]
At the end of this month, we'll be doing a new contributor experience event which will show you how to build a bridged provider - from start to finish.

https://www.youtube.com/watch?v=ZjTFaqMrYvY

**Comment by lcswillems** [comment]
@rawkode Why doesn't Pulumi do this bridged provider? Pulumi can teach people how to do it and do it itself in order to save time to people later on

**Comment by rawkode** [comment]
> @rawkode Why doesn't Pulumi do this bridged provider? Pulumi can teach people how to do it and do it itself in order to save time to people later on

Sadly we can’t take on every bridged provider, but we can provider the tooling and resources that help make this easy for the community to contribute. 

I reckon https://github.com/pulumiverse would be a good home for this provider.

**Comment by ringods** [comment]
Linking this attempt by a community user: https://github.com/omercnet/pulumi-vercel

As mentioned before, this one is blocked because the official TV provider by Vercel is already based on the new Terraform Plugin Framework.

**Comment by osdiab** [comment]
Given ongoing progress on support for the above pulumi terraform bridge issue, what is missing that would prevent Vercel’s provider from being bridged? Thanks!

**Comment by varunshoor** [comment]
Any update on this? I have to configure Vercel out of my IaC stack because lack of a supported provider. Vercel has become ubiquitous with Next.js deployments now, lack of Vercel provider is a bummer.

**Comment by omercnet** [comment]
I see there's an updated on the blocking FR, let me try and implement this

**Comment by omercnet** [comment]
https://github.com/omercnet/pulumi-vercel is ready for testing, would appreciate any feedback

**Comment by omercnet** [comment]
published https://github.com/pulumiverse/pulumi-vercel/releases/tag/v0.15.0 !
https://www.npmjs.com/package/@pulumiverse/vercel

**Comment by lcswillems** [comment]
@omercnet Does this mean this issue should be closed?

**Comment by omercnet** [comment]
Yes
