### ISSUE TITLE
[codegen/schema] Add package metadata to the Pulumi schema spec

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#7813]
## Affected feature

Today when we generate resource docs, the docs generator uses a [lookup map](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/gen.go#L62) for mapping a package's name to its "display friendly" name. For example, `aws` -> `Amazon Web Services` etc. It would be good to not rely on the lookup table and instead let that information flow from the schema spec itself so that it becomes the source of truth for that information. I am proposing that we add a `title` property at the root of the spec.

If we could also add `category`, `publisher`, whether or not a package uses TF bridge and the package's availability status (preview vs. ga). `category` would simply be a single string value of a package's category. It's how we categorize packages today on the [API Reference](https://www.pulumi.com/docs/reference/pkg/) and the [Cloud Providers](https://www.pulumi.com/docs/intro/cloud-providers/) pages. As for whether or not a package uses TF bridge we have a few native providers and it would be helpful to discern them from the TF bridge-based providers. The package's availability status is pretty self-explanatory. The `description` property already mentions the preview status of a provider so maybe it's ok to not have a separate field?

Overall, these are the fields I talked about: `title`, `category`, `publisher`, `usesTfBridge`, `availabilityStatus` (the property names are purely suggestions only)

**Comment by infin8x** [comment]
I'd like to propose a slightly different set of schema additions:

| Property            | Type                                       | Required | Description                                                                                                                       |
|---------------------|--------------------------------------------|----------|-----------------------------------------------------------------------------------------------------------------------------------|
| `publisher`         | `string`                                   | Yes      | Publisher is the name of the person or organization that authored and published the package.                                      |
| `displayName`       | `string`                                   | No       | DisplayName is the human-friendly name of the package, used when the package is displayed on Pulumi.com                           |

Then, to @justinvp's suggestion [in Slack](https://pulumi.slack.com/archives/CBUP505U7/p1629513669109600?thread_ts=1629422079.092700&cid=CBUP505U7), I wonder if we can introduce some structure into the `keywords`? For example, could we have keywords like:

- `category:cloud`
- `kind:[terraform-provider|native-provider|component]`

And finally, I wonder if we can drive the availability status (e.g. "public preview" vs. "generally available") off of SemVer, instead of as a distinct metadata item.

@praneetloke @justinvp would love your thoughts?

**Comment by praneetloke** [comment]
@EvanBoyle @infin8x what do you think about also including a `logo` property?

**Comment by infin8x** [comment]
@praneetloke seems good to me.

**Comment by praneetloke** [comment]
@infin8x we already seem to have a [`LogoURL`](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/schema/schema.go#L559) property in the schema spec. We just don't set it right now but should make a work item to start populating that. Without that URL, our docs will fallback to an internal image, if one is available for that package.

**Comment by infin8x** [comment]
> @infin8x Where would be a good place to document the correct category/ and kind/ tags one could use their schema's keywords array? Would that be https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/docs/guides/pulumi-packages/schema.md#pulumi-package-schema?

@praneetloke sorry to take so long to get back to you. Yes, that's a good spot, and then I'll update https://github.com/pulumi/pulumi-hugo-internal/pull/238/files to point to that.

**Comment by praneetloke** [comment]
@infin8x thank you for getting back to me! I opened https://github.com/pulumi/pulumi-hugo/pull/841 to add some examples. I'll add the same note in the code as well so if, one day, we generate the doc for the Pulumi schema itself from the JSON spec it would be in-sync.

**Comment by praneetloke** [comment]
I think we can close this out. What do you think, @EvanBoyle? The only remaining task at this point, as far as I can tell, is to update all TF providers to set values for the new properties as well as add the relevant `category/` labels to each of them. @stack72 is working on that but not sure if that is being tracked separately.

**Comment by EvanBoyle** [comment]
Let's close out. 

@stack72 I opened https://github.com/pulumi/home/issues/1681 to track the TF provider updates and put this into the platform integrations triage board. If you're already tracking this work, feel free to close that issue out
