### ISSUE TITLE
Fail fast

### ISSUE THREAD

**Issue by shinebayar-g** [pulumi/pulumi#8005]
Failed runs could have finished faster for better user experience. I was deleting some stuff and some of the resources failed to delete because of the dependency error. But I had to wait 17 minute to finish the pulumi up. It could fail in few seconds, there is no point in waiting for this long as soon as task is failed.

```
     Type                         Name                 Status                  Info
     pulumi:pulumi:Stack          redacted  **failed**              1 error
 -   ├─ aws:route53:Record        redacted-redacted-lb  deleted
 -   ├─ aws:lb:Listener           redacted-redacted     deleted
 -   ├─ aws:route53:Record        redacted-redacted     deleted
 -   ├─ aws:route53:Record        redacted-redacted     deleted
 -   ├─ aws:route53:Record        redacted-redacted     deleted
 -   ├─ aws:lb:LoadBalancer       redacted-redacted     deleted
 -   ├─ aws:ec2:NetworkInterface  redacted-redacted     **deleting failed**     1 error
 -   ├─ aws:ec2:Instance          redacted-redacted     deleted
 -   ├─ aws:ec2:NetworkInterface  redacted-redacted   **deleting failed**     1 error
 -   ├─ aws:ec2:SecurityGroup     redacted-redacted-lb  **deleting failed**     1 error
 -   ├─ aws:ec2:Instance          redacted-redacted     deleted
 -   ├─ aws:ec2:NetworkInterface  redacted-redacted     **deleting failed**     1 error
 -   ├─ aws:ec2:Instance          redacted-redacted     deleted
 -   └─ aws:lb:TargetGroup        redacted-redacted     deleted

Diagnostics:
  aws:ec2:NetworkInterface (redacted-redacted):
    error: deleting urn:pulumi:redacted::pulumi-redacted::aws:ec2/networkInterface:NetworkInterface::redacted-redacted: 1 error occurred:
        * Error detaching ENI: OperationNotPermitted: The network interface at device index 0 cannot be detached.
        status code: 400, request id: f6ae0f9d-bf89-4688-aa37-ce8477e6d232

  aws:ec2:NetworkInterface (redacted-redacted):
    error: deleting urn:pulumi:redacted::pulumi-redacted::aws:ec2/networkInterface:NetworkInterface::redacted-redacted: 1 error occurred:
        * Error detaching ENI: OperationNotPermitted: The network interface at device index 0 cannot be detached.
        status code: 400, request id: 08753605-e3ad-4469-9cb7-67609cd57f3b

  aws:ec2:SecurityGroup (redacted-redacted-lb):
    error: deleting urn:pulumi:redacted::pulumi-redacted::aws:ec2/securityGroup:SecurityGroup::redacted-redacted-lb: 1 error occurred:
        * Error deleting security group: DependencyViolation: resource sg-06140b4ebc78386a5 has a dependent object
        status code: 400, request id: ba7edd73-2630-45bb-bfb8-29b7d0281372

  pulumi:pulumi:Stack (redacted):
    error: update failed

  aws:ec2:NetworkInterface (redacted-redacted):
    error: deleting urn:pulumi:redacted::pulumi-redacted::aws:ec2/networkInterface:NetworkInterface::redacted-redacted: 1 error occurred:
        * Error detaching ENI: OperationNotPermitted: The network interface at device index 0 cannot be detached.
        status code: 400, request id: dc3455c8-dd33-41f3-96fe-5a6963f68028

Resources:
    - 10 deleted
    122 unchanged

Duration: 17m34s
```

**Comment by pgavlin** [comment]
@shinebayar-g

> I was deleting some stuff and some of the resources failed to delete because of the dependency error. But I had to wait 17 minute to finish the pulumi up. It could fail in few seconds, there is no point in waiting for this long as soon as task is failed.

When a resource operation fails, Pulumi will wait for any in-flight operations to complete before exiting. It will not start any new operations during this time. The reason that the CLI waits for in-flight operations to complete is so that it can track the success or failure of those operations and track the resource's state accordingly. It's unlikely that we will change this behavior to fail as soon as a single operation fails, as that would require cancelling other outstanding operations and would leave the stack in an indeterminate state. This is particularly important in the case of creates, where the actual state of the resource (in particular, whether or not it has been created) is not knowable until the create finishes.

In the case of deletes, you can probably get away with canceling the `pulumi up` manually by pressing Ctrl+C twice and then running `pulumi refresh` prior to the next `pulumi up`. This should work because it is usually possible for a resource provider to accurately detect a deleted resource as part of a `pulumi refresh`.

**Comment by ghostsquad** [comment]
any change this could be made a flag? We have use cases where we want to disable this "fail fast" functionality.
