### ISSUE TITLE
State corruption when destroy fails to remove a resource

### ISSUE THREAD

**Issue by bgelens** [pulumi/pulumi#8164]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Logged earlier in https://github.com/pulumi/pulumi-azure-native/issues/1203

I'm experiencing state corruption during destroy of an explicit target including the `--target-dependents` switch.
A couple of child resources fail to be destroyed resulting in an aborted destroy operation. When I try again, the target resource and all child resources are no longer in the state (while the resources remain to exist in Azure).

Currently using local filesystem for state store as I'm still experimenting.

### Steps to reproduce

1. create resource hierarchy as described above (rg -> sql server -> db -> retention policy)
2. pulumi up (resources are created)
3. pulumi destroy --target sqlserverUrn --target-depend (see failures happening)
4. try again

Expected:  Resources to be removed and no corruption in my state if something did not happen.
Actual: Resources where not removed and I lost track of my resources in the state which where not actually deleted.

**Comment by NinoFloris** [comment]
This also affects --exclude-protected which internally is based on the target functionality

**Comment by antarus12345** [comment]
Unsure if this is the same problem or a different problem but we seemingly encountered a similar issue where:
 - We accidentally broken our trust relationship in an IAM policy.
 - We failed to assume the correct IAM role (e.g. we had AWS_* credentials, but the wrong ones.) We assume this role before executing pulumi. A bug in our code, and we fixed this bug to catch if role assumption fails now.
 - Pulumi was unable to talk to AWS properly and most provider requests returned 403 / 404 errors.
 - Pulumi deleted some resources from the state file (but they were obviously left in AWS, since pulumi had no valid AWS credentials.)

**Comment by joeduffy** [comment]
I assume the assignment to @pgavlin is a mistake?

@Frassle Isn't this directly related to some of the area we recently had troubles with? Or am I drawing a correlation that doesn't exist?

**Comment by Frassle** [comment]
> Isn't this directly related to some of the area we recently had troubles with? Or am I drawing a correlation that doesn't exist?

It's almost definitely related to targets which we've been looking at recently. Although the last targets issue didn't have any suggestion of it removing things from state, was just more resources being updated than expected.
