### ISSUE TITLE
Dynamic providers cannot capture secrets

### ISSUE THREAD

**Issue by jakzo** [pulumi/pulumi#8265]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Handling secrets in dynamic resources the same way as in the [GitHub example here](https://www.pulumi.com/docs/intro/concepts/resources/#example-github-labels-rest-api) results in the secrets being stored in plain text in the state file due to serialisation of the provider (in the GitHub example the `new Ocktokit({auth})` expressions in the dynamic provider cause the `auth` variable to be serialised as a string containing the auth token).

As far as I can tell, the only way to use secrets in dynamic providers is to add them as inputs (not ideal because an auth token should really be config, will fail to update an existing resource if the token is invalidated).

Relates to #4512 #2718

### Steps to reproduce

1. Follow the GitHub example steps to create a dynamic provider
2. Run `pulumi up`
2. Search the stack's state file for the auth token's value

Expected: no matches for the auth token in the state file
Actual: auth token is found in the serialised provider string

**Comment by robertf224** [comment]
+1 on this, not clear what to do here.  and seems like any time you're hitting an external API (one of the obvious use-cases for dynamic providers) you're going to need some credentials you want encrypted

**Comment by nicholasgibson2** [comment]
[This blog post](https://www.pulumi.com/blog/dynamic-providers/#provider-credentials) implies this is possible, but I have yet to find a working example.

**Comment by wimi** [comment]
Any update on this subject. Seems quite important, otherwise ... dynamic providers seem like a credential leak.

**Comment by nicholasgibson2** [comment]
> ### Steps to reproduce
> 1. Follow the GitHub example steps to create a dynamic provider
> 2. Run `pulumi up`
> 3. Search the stack's state file for the auth token's value
> 
> Expected: no matches for the auth token in the state file
> Actual: auth token is found in the serialised provider string

@jakzo where exactly are you seeing the auth token value in the state file? I'm testing with a local state file but not finding it. As a potential workaround I'm testing passing secrets as parameters in the provider constructor.

**Comment by justinvp** [comment]
We should consider defaulting to making the entire serialized provider an encrypted secret.

**Comment by joeduffy** [comment]
Unless I am mistaken, we block this from happening now. So, rather than being a credential leak, the docs example simply does not work. (Which is not great, but better than a security issue!)

There is a bug in the sample too, which should explicitly wrap the token in a secret; i.e.:

```diff
-let auth = "token invalid";
+let auth = pulumi.secret("token invalid");
```

If you do this, Pulumi blocks the capture:

```
    error: Running program '/Users/joeduffy/temp/bugsquash/pulumi-8265/' failed with an unhandled exception:
    <ref *1> Error: Secret outputs cannot be captured by a closure.
        at Object.<anonymous> (/Users/joeduffy/temp/bugsquash/pulumi-8265/node_modules/@pulumi/runtime/closure/serializeClosure.ts:101:15)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/joeduffy/temp/bugsquash/pulumi-8265/node_modules/@pulumi/pulumi/runtime/closure/serializeClosure.js:18:58) {
      promise: Promise { <rejected> [Circular *1] }
    }
```

I believe we can use the same technique [used here](https://github.com/pulumi/pulumi-aws/commit/3344af321a379214b10fbc62682bc6a67bab277f) to set `allowSecrets: true`, and then propagate the resulting secretness such that we encrypt the resulting closure text when it a closure has captured a secret value.

**Comment by joeduffy** [comment]
I've renamed the title; it sounded like we were leaking secrets, but in fact, this is more of a feature request to enable dynamic providers to capture them securely. It turns out this is nuanced. The problem here is that even if we encrypt the resulting `__provider` property, the secret value will still be plaintext without its secretness "on the inside" of the closure. That means any handling of it will subtly not be treated like a secret would. For instance, if you store it on an output property of the dynamic resource -- unless we do additional work -- it would end up in plaintext again.

I also don't know what happens with other languages. In the Node.js SDK, we throw an exception, blocking the secret capture. Do we do that in other languages? I don't think we do ...

This requires deeper thought, and it begs the question of whether we really want to enable this. If we don't, we probably want to do two things

1. Rework this example
1. Ensure all other languages block secrets capture too

**Comment by mattfysh** [comment]
It seems like the cleanest solution is to allow dynamic providers to tap into secrets in the same way as other providers, e.g. `cloudflare:apiToken`

**Comment by joeduffy** [comment]
I agree, that’s more explicit, and even if we do something magic with closure capture, would be a good foundation to have. I don’t offhand know why that doesn’t work. @justinvp Do we just not pass and hydrate the configuration within the dynamic provider process? That wouldn’t seem terribly difficult to do unless I’m missing something?

**Comment by Frassle** [comment]
> Do we just not pass and hydrate the configuration within the dynamic provider process? That wouldn’t seem terribly difficult to do unless I’m missing something?

Dynamic providers are an oddity because the provider code is part of the _resource_ not it's own thing. As such there is no ProviderResource that can be separately configured. I did look at changing this but it's a large change to the interface for what dynamic providers/resources look like. So I don't think we can do config until we do a major version change of the dynamic interfaces.

Feels like the best short term option is to just always mark `__provider` as secret.

**Comment by joeduffy** [comment]
I didn’t entirely follow. What I had in mind is enabling:

```
const t = new Config().getSecret(“apiToken”);
```

from within your dynamic provider code. Today that doesn’t work but it doesn’t seem too difficult to enable this, and it would retain the fact that a secret is a secret transitively, unlike encrypting the closure.

**Comment by Frassle** [comment]
> Today that doesn’t work but it doesn’t seem too difficult to enable this, and it would retain the fact that a secret is a secret transitively, unlike encrypting the closure.

There's three things we'd need to think about to enable that.

One is that today we do not send config to the provider process. There's a few issues about enabling providers to look at all config values and we've so far been err'ing away from doing that because of leaking credentials to all processes.

Two is that dynamic providers as far as the engine can see are all one type of provider (e.g. puluimi-resource-python) and so that's only one config namespace for all dynamic providers in your program. Minor and probably doesn't matter for a lot of cases but worth pointing out.

Thirdly is that Config is in terms of `Output<T>` but providers operate on `PropertyValue` not `Output`. We could probably add support for automatic conversion from Output<T> to PropertyValue in the library layer, but it's another reason this won't just work today.

**Comment by joeduffy** [comment]
Makes sense. That third one is important because it means my claim the the secret could retain its secret nature by doing it this way is incorrect. No matter what, it’s going to end up as plaintext.

**Comment by lukehoban** [comment]
The combination of #13315 (Python) and #13329 (Node.js) addresses the core issue here, in that dynamic providers can now capture secrets and when they do their code is marked as a secret in the state.

This does not though allow the provider itself to receive and return secret values from the provider inputs/outputs to create/update/delete/etc. calls.  That part is a fundamental limitation of the dynamic provider model today, and would require a very significant overhaul of the approach to dynamic providers.  In cases where that is needed, full static providers are still the best bet.  But for common cases of passing credentials into dynamic providers, the new support will ensure those can be accessed as secrets and the sensitive values consumed during deployments, without leaking the secrets into Pulumi state.

**Comment by mattfysh** [comment]
just got tripped up on this issue in a different way, im running my code in a dynamic environment where the endpoint URLs change frequently and my dynamic resource is something that can be deployed to a local microservice over REST

at the top of my provider code I have `const ENDPOINT = requireEnv('XYZ_ENDPOINT')` but this is also, unfortunately, serialized into the `__provider` property

has there been any movement on this issue, e.g. allow dynamic providers to tap into stack config as suggested earlier?

I'm about to reach for `eval('process.env.XYZ_')` please someone stop me!

**Comment by mattfysh** [comment]
christ on a cracker 🍘  even `eval('process.env.X')` is rendered by the pulumi program, I tried to use something more obfuscated `eval('process?.env?.X')` but that was also serialized

**Comment by jcgsville** [comment]
I see how https://github.com/pulumi/pulumi/pull/13329 takes a step in the right direction, but I'm still not seeing how one could practically use dynamic providers for provisioning remote resources that need secrets / api keys. 

```
const fooProvider: pulumi.dynamic.ResourceProvider<{ name: string, apiKey: string }> = {
    create: async ({ name, apiKey }) => {
        await doSomethingToCreateAFoo({ name, apiKey })
        return { id: generateFooId(inputs), outs: {} }
    },
    delete: async (pulumiId: string, outputs) => {
        // How can I use apiKey in here to make a call to delete the instance of foo?
    },
}
```

Would one have to set the API Key as an output in fooProvider.create so that it's available to fooProvider.delete? And if you do that, you would break the ability to delete a resource of the credential was rotated between resource creation and resource deletion. So this seems like it is not a viable option.

**Comment by mattfysh** [comment]
Scrapped together some time to play around with function serialization and found a way to manage secrets, or any value that should not be hard-coded into the __provider property. Values that are baked during provider serialization can cause many issues when trying to work with existing resources

If you read from process.env inside your functions, they won't be serialized when the resource is first created. Here is an example of how to avoid dynamic values ending up in your provider:

```ts
const provider: pulumi.dynamic.ResourceProvider<Inputs, Outputs> = {
  async create() {
    const mySecret = process.env['PROVIDER_SECRET']
    const endpoint = process.env['REMOTE_ENDPOINT']
    const res = await fetch(endpoint, { headers: { 'x-api-key': mySecret // ...
  }
}
```

Using this approach, the next time you run your program it will always use the most up-to-date values from process.env for both *new* and *existing* resources

By comparison, reading from process.env outside the serialized functions will bake in the values from process.env during serialization, which will brick existing resources when those values change

```ts
const mySecret = process.env['PROVIDER_SECRET']

class MyProvider implements pulumi.dynamic.ResourceProvider<Inputs, Outputs> {
  constructor {
    this.endpoint = process.env['REMOTE_ENDPOINT']
  }

  async create() {
    const res = await fetch(this.endpoint, { headers: { 'x-api-key': mySecret // ...
  }
}
```

Both of these approaches (root scope, constructor) should be avoided. in fact, after looking at the serialized output of a class, the constructor is not run at all again after serialization because the provider is serialized into an object, not a class

Going back to OPs [example github provider](https://www.pulumi.com/docs/concepts/resources/dynamic-providers/#example-github-labels-rest-api), the solution there is to read the auth token from process.env in each of the CRUD functions

I opened a new issue for a couple of related serialization problems here - https://github.com/pulumi/pulumi/issues/15485
