### ISSUE TITLE
Explicit dependency specification not working as expected in Python

### ISSUE THREAD

**Issue by tarungidwani** [pulumi/pulumi#8291]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Specifying resource dependencies explicitly when creation of resources is abstracted to functions in Python not working

```python
rg1_name = 'pulumi-demo-rg1-{0}'.format(env)
sa1_name = 'pulumidemo1{0}'.format(env)

rg1 = provision_resource_group(rg1_name)
sa1 = provision_storage_account(sa1_name, rg1_name, pulumi.ResourceOptions(depends_on=[rg1]))
```
![image](https://user-images.githubusercontent.com/17368567/138352078-31f4e055-5d17-40f8-9773-8a0dd3f03126.png)

![image](https://user-images.githubusercontent.com/17368567/138352138-48258134-8214-4ff9-8105-0d3e0f58525e.png)

Expected: Expect Pulumi to detect and honor the order of resource creation 
Actual: Pulumi failing to wait for storage account provisioning before the resource group is created

![image](https://user-images.githubusercontent.com/17368567/138351332-9e88ecb5-4b14-46d5-bd56-65ae51675b7a.png)

**Comment by leonio** [comment]
> Looking at your code, I suspect the issue might be that you create ResourceGroup with build_name so the actual name of the ResourceGroup is not pulumi-demo-rg1-dev but some modification of that name

For what it's worth I had a similar issue with some experimentation code, and this was the issue I ran into. After taking [another look at the docs](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/), it seems that instead of using a hard-coded string, we should be using instance object of the `ResourceGroup` itself.

> All resource properties on the instance object itself are outputs. Outputs are values of type Output<T> , which behave very much like promises. This is necessary because outputs are not fully known until the infrastructure resource has actually completed provisioning, which happens asynchronously. Outputs are also how Pulumi tracks dependencies between resources.

So if `resource_group_name` isn't an `Output` that points to the `ResoureGroup.resource_group_name` property the the storage account won't wait until the resource group is created.
