### ISSUE TITLE
Spurious missing configuration key aws:region errors

### ISSUE THREAD

**Issue by tom-humanloop** [pulumi/pulumi#8489]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Using pulumi `v3.18.1` (have tested with `v3.17.1` and same issue) 

I am using the S3 backend for my stacks. I am using GitHub actions to deploy a stack via `pulumi up`. This works and the stack is available. 

When I run `pulumi refresh` on the same stack from my local machine, I get the following error repeated once per resource: 

```
error: Preview failed: 1 error occurred:
    	* missing required configuration key "aws:region": The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
    Set a value using the command `pulumi config set aws:region <value>`.
``` 

This is strange because that config value is visible in the stack YAML file and set per `pulumi config`: 

```
 $  pulumi config
KEY         VALUE
aws:region  eu-west-2
```

### Steps to reproduce

I'm working on a replication - our stack has a lot of irrelevant stuff in, I'll try to make something more minimal. 

Expected: With the region set, `pulumi refresh` should work locally without error
Actual: The error message as above

**Comment by emiliza** [comment]
This is an interesting issue - I haven't been able to reproduce this, and would love to get a repro if you can manage to get one.

**Comment by thatsmydoing** [comment]
I can confirm also seeing this in pulumi 3.17.1 and pulumi-aws v4.27.2. Setting `AWS_DEFAULT_REGION` seems to be a good workaround.

**Comment by wannessels** [comment]
This is caused by pulumi connecting to the S3 bucket for the backend.
For this, the `aws:` config entries are ignored, so you fall back to the default AWS environment variables. If `AWS_DEFAULT_REGION` is not set, you will get the above error.
Judging by the [go aws pkg](https://pkg.go.dev/gocloud.dev/aws#ConfigFromURLParams), you can add the region to the url. @tom-humanloop can you try adding `&region=eu-west-2` to your s3 backend url?

- The documentation should mention the supported url options
- S3 backend config should allow for more options, such as: region, assume_role_arn, session_name, kms_key. For reference, here are the supported options for s3 backend by terraform: https://www.terraform.io/language/settings/backends/s3
Alternatively, the S3 backend should use a/the configured aws provider to connect.

**Comment by iapetos163** [comment]
I have a similar issue with using `pulumi refresh` but with a different configuration option. I have a stack that uses the DigitalOcean provider and i've configured the `digitalocean:token` option in `Pulumi.{project}.yaml` as described in the [documentation](https://www.pulumi.com/registry/packages/digitalocean/installation-configuration/).

This works when i run `pulumi up`, but upon running `pulumi refresh` all API calls to DigitalOcean get 401 errors. `pulumi refresh` DOES work when i set the `DIGITALOCEAN_TOKEN` environment variable.

**Comment by justinvp** [comment]
Closing this old issue.

Regarding the `digitalocean:token` question, you'll need to run a `pulumi up` first, and then `pulumi refresh` should work (you could also do `pulumi up --refresh`. See https://github.com/pulumi/pulumi-digitalocean/issues/804#issuecomment-2314852020
