### ISSUE TITLE
make objects mutable

### ISSUE THREAD

**Issue by trondhindenes** [pulumi/pulumi#8584]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I'm looking at Pulumi's kubernetes provider, and am noticing that objects aren't mutable. For example this does not work:

```
app_labels = {"app": "nginx"}
deployment = generate_deployment(app_labels)  # returns a pulumi Deployment object
deployment.spec.instances = 2
```

imho an important aspect of using "real" code to provision objects is the ability to create "componentized" functionality, for example 
```
deployment = inject_aws_secrets_csi_mount(deployment)
deployment = inject_datadog_socket_mount(deployment)
```

Especially for Kubernetes it's (IMHO) important to have mutable objects, because the object model is so "deep". While most cloud provider objects are fairly "flat", Kubernetes is extremely nested, quite often 5-6 levels deep and probably even a lot more in some places. This makes it extremely complex to create isolated pieces of functionality without a mutable object model.

cdk8s suffers from the exact same problem, and I tried to write some thoughts about that here:
https://github.com/cdk8s-team/cdk8s/issues/733

It would be interesting to get Pulumi's feedback on the problem, and whether or not it's likely to be improved upon in the future.

**Comment by leezen** [comment]
A couple thoughts:

1. One solution to this would be to pass around the properties bag for a resource instead of the resource itself. In some cases, this won't be possible because you may need the resource to already exist in order to operate against it.
2. In the case of Kubernetes, one of the improvements we are looking to make in the coming year is https://github.com/pulumi/pulumi-kubernetes/issues/264 -- which I think helps solve a particular case (so you could potentially `new ...` and then `.get.update` that resource subsequently).

I'm curious if you have specific use cases in mind and those could be addressed via 'builders' of some sort (i.e. scenario 1 above where you don't need to know any provider outputs) vs. scenarios where you actually need to know something about the output in order to make a subsequent modification to the resource.

**Comment by trondhindenes** [comment]
> A couple thoughts:
> 
> 1. One solution to this would be to pass around the properties bag for a resource instead of the resource itself. In some cases, this won't be possible because you may need the resource to already exist in order to operate against it.
> 2. In the case of Kubernetes, one of the improvements we are looking to make in the coming year is [Allow a model similar to `kubectl apply -f` pulumi-kubernetes#264](https://github.com/pulumi/pulumi-kubernetes/issues/264) -- which I think helps solve a particular case (so you could potentially `new ...` and then `.get.update` that resource subsequently).
> 
> I'm curious if you have specific use cases in mind and those could be addressed via 'builders' of some sort (i.e. scenario 1 above where you don't need to know any provider outputs) vs. scenarios where you actually need to know something about the output in order to make a subsequent modification to the resource.

Thanks for replying!
I think a property bag would kindof negate the point of a strongly typed object model, since one would have to carry around a "non-strongly typed" dict to represent the Deployment object, and then assemble it in some final step. That would reduce pulumi (almost) down to validation only, and kubernetes already has pretty good validation built-in without needing abstractions on top (except for kubectl which takes care if some of the validation).

your point 2 looks interesting. Looking forward to following the work Pulumi does in this space in the time to come!

**Comment by leezen** [comment]
> I think a property bag would kindof negate the point of a strongly typed object model

In all our languages, the bag would be typed. For example, in the case of https://www.pulumi.com/registry/packages/kubernetes/api-docs/apps/v1/deployment/ you'd pass around a `DeploymentArgs` object, which has properties that are also typed. Some parts of this will end up being dict-like, but that would be no different from using the constructor.

**Comment by trondhindenes** [comment]
gotcha, thanks. I'm not  very familiar with Pulumi. It would be awesome to see "advanced" usage examples such as being able to inject a sidecar container into an existing deployment object or similar. I don't have a clear mental picture of how that would look in pulumi using a propertybag. Apologies if this is all in the docs.

**Comment by t0yv0** [comment]
Hi @trondhindenes I've not much experience yet with K8S but I've explored this in Python purely from a programming perspective. To echo @leezen comments, Pulumi lets you manipulate strongly typed "Args" structures that define the arguments to a resource before constructing the resource - these are pure in-memory config structures, and manipulating them is free of effects. Abstractions from your example can be built on them. These are currently mutable, they provide getters and setters.

For example, I played with this code (modified `pulumi new kubernetes-python`):

```python
"""A Kubernetes Python Pulumi program"""

import pulumi
from pulumi_kubernetes.apps.v1 import Deployment, DeploymentSpecArgs, DeploymentStrategyArgs
from pulumi_kubernetes.meta.v1 import LabelSelectorArgs, ObjectMetaArgs
from pulumi_kubernetes.core.v1 import ContainerArgs, PodSpecArgs, PodTemplateSpecArgs

app_labels = { "app": "nginx" }


deployment_spec = DeploymentSpecArgs(
        selector=LabelSelectorArgs(match_labels=app_labels),
        replicas=1,
        template=PodTemplateSpecArgs(
            metadata=ObjectMetaArgs(labels=app_labels),
            spec=PodSpecArgs(containers=[ContainerArgs(name="nginx", image="nginx")])
        ),
    )


deployment_spec.replicas = 2

# print(deployment_spec.strategy.type) # this does not work: AttributeError: 'NoneType' object has no attribute 'type'

deployment_spec.strategy = DeploymentStrategyArgs(type='Recreate')
deployment_spec.strategy.type = 'RollingUpdate'

assert deployment_spec.replicas == 2
assert deployment_spec.strategy.type == 'RollingUpdate'

deployment = Deployment(
    "nginx",
    spec=deployment_spec)

pulumi.export("name", deployment.metadata["name"])
```

So in python the Deployment args bag is spelled `DeploymentSpecArgs`. As you can see its properties and nested properties are mutable already. 

It seems we may have some room for improvement around initializing the nested Args like deployment_spec.strategy to the default values rather than None. This would make it even easier to nested values such as `deployment_spec.strategy.type`.

👍 if this resonates I can open another issue for that. Closing this for now, please reopen if I am missing something here.

**Comment by trondhindenes** [comment]
hi @t0yv0 this makes total sense - thanks for the example. Injecting defaults would certainly help but I wouldn't call it a deal-breaker either.
