### ISSUE TITLE
NodeJS + ESM: no way to set an object as stack output

### ISSUE THREAD

**Issue by awoimbee** [pulumi/pulumi#8725]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Directly relates to ESM: #5161, https://github.com/pulumi/pulumi/issues/4017#issuecomment-601853157

### Steps to reproduce

1. Create a typescript project (defaults to using CommonJS modules)
2. put inside `index.ts`:
    ```typescript
    async function main() { return {helloWorld: 123} };
    export default main();
    ```
3. Run `pulumi up`; stack output is `{default: {"helloWorld": 123}}`, oops, not what we want
4. Update `index.ts`:
    ```typescript
    async function main() { return {helloWorld: 123} };
    module.exports = main();
    ```
5. Run `pulumi up`; stack output is now: `{"helloWorld": 123}`; perfect !
6. Follow these steps to use ESM https://github.com/pulumi/pulumi/issues/5161#issuecomment-1010018506
7. `module.export` isn't available with ESM, only `export` works. :(

Expected: I have a way of settings an object as stack output just like `module.exports = whatever` results in outputs `{ whatever }` 
Actual: `export default whatever` results in outputs `{ default: whatever }`, I have no equivalent to  `module.exports = whatever`.

**Comment by lukehoban** [comment]
To a meaningful extent, this is the expected behaviour of ESM.  With ESM, there is no way to define the set of exports as an object, instead - you specify two sets of things:
1. An optional `default` export value
2. Zero or more named export bindings

ESM also are structured to ensure that the named exports are all statically known names (including the nameless `default` export).  This somewhat intentionally (from the perspective of the ESM language design) prohibits converting an object into a set of exports.

That said, we (Pulumi) own the "meaning" of exports at the top level entrypoint, and can choose to do something "different" than normal ESM.  And indeed, for non-ESM we had the special behaviour that if the exported object was a function, we would invoke it and await it.

In the ESM case, it's a little more awkward due to the fact that you can have both.  But the default Node.js behaviour of treating the default export as a special `default` field in the exported object is particularly unhelpful in Pulumi, so I think the best approach (for now at least) will be to do:
1. If there are named exports and no default export, treat the named exports as the properties of the return object (implicitly not requiring invoking or awaiting, as the result will in this case always be an object)
2. If there is a default export and no named exports, treat the default export value as the module export (including invoking and then awaiting it if necessary as in CommonJS).
3. If there are both a default export and named exports, error.

We handle (1) today, but could introduce (2) and (3) to be more consistent.

We could always loosen (3) in the future with some definition of how to "merge" properties between default exports and named exports - but I think for now it makes sense to just prevent that case.
