### ISSUE TITLE
Unintended API removal blocks K8S resource upgrade

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8784]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

https://github.com/pulumi/pulumi-kubernetes/pull/1876#issuecomment-1016714477

It seems that changes in codegen results in removal of APIs such as ValidatingWebhookConfigurationListTypeOutput which as far as I can see are not intended, and Levi thought the APIs are used. We should investigate this as a potential (blocking) bug in Go codegen. The k8s provider upgrades are waiting on this.

**Comment by iwahbe** [comment]
It looks like the loss of types are the intended effect of https://github.com/pulumi/pulumi/pull/7943. Types are restored when regenerating with `"generateExtraInputTypes": true,`. This makes sense to me since the `*List*` types are part of the external API, and thus not referenced by the SDK. 

@lblackstone Can you confirm that this solution works for you? I'm not 100% sure exactly how you generate providers. To check correctness, I just manually edited the `schema.json` and ran `make ensure k8sgen go_sdk && git diff`.

**Comment by mikhailshilkov** [comment]
Thank you @iwahbe, that makes sense! cc @viveklak and @stack72 - you probably need to set `generateExtraInputTypes: true` for the k8s provider.

**Comment by lblackstone** [comment]
I updated the schema as suggested, and that resolved the problem. Thanks for the help!

Resolved in https://github.com/pulumi/pulumi-kubernetes/pull/1878
