### ISSUE TITLE
Unable to unprotect and Replace resource without modifying the program to have protect as false

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#8871]
## Issue details
Using the automation api we would unprotect resources (similar to running the unprotect command) and then run replace on resources. With the latest pulumi version now it says you must set the protect flag to false on the resource rather than just running the unprotect command (modify state of resource). This completely breaks the workflow of leaving the resource code alone now that we would have to mark each as false. Is there a way to force the replacement of a resource that has been unprotected but the program resource still have protect as true?

### Steps to reproduce

1. Deploy resource with protect flag set to true
2. Run unprotect command on resource URN
3. Run up with target replace on unprotected resource
4. Throws error saying we must remove protect flag.

Expected: Unprotected (in state) Resource is replaced and protected
Actual: Unprotected (in state) Resource is not allowed to be replaced and throws error

This broke our workflow so now will have to just remove the flag on all our resources and leave protection off.

**Comment by mitchellmaler** [comment]
The error we are seeing now is "To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`" which didn't happen before we upgraded which seems like a breaking change of some sort.

**Comment by iwahbe** [comment]
It looks like https://github.com/pulumi/pulumi/commit/67ac4837ec85b441b0454e73924faa19368d3d72 introduced the change.

**Comment by mitchellmaler** [comment]
Does it make sense to roll this back back and/or make this change an opt-in/feature flag that way it doesn’t cause breaking changes to existing workflows like it has for us?

**Comment by Frassle** [comment]
So replace has to look at either old.Protect or goal.Protect. I thought it made more sense to look at goal.Protect because that made it possible to remove the protect flag and change something else in the same update, but yes it does break this flow. 
If we look at just old.Protect then to do a replace you'd have to remove the flag in one up (or use the command as your doing), then make the change to your program as a separate up.

Wondering if maybe the best option is look at both:
| old.Protect | goal.Protect | Replace allowed
| ------------- | ------------- | ------------- |
| False | False  | Yes |
| False | True | Yes |
| True | False | Yes |
| True | True | No |

**Comment by mitchellmaler** [comment]
That makes a lot of sense. That way it would allow a replace if the current/old resource is set to false but the new one to be created will be set to true.

**Comment by Frassle** [comment]
PR raised to match the behavior in the table above

**Comment by mikhailshilkov** [comment]
> Wondering if maybe the best option is look at both:

What was our behavior in the following scenario before #8810?

1. Deploy a resource without protection.
2. Mark the resource as protected in the code and change a property that causes a replacement.
3. Run `pulumi up`.

If I understand your proposal, this operation will succeed now. Doesn't it feel counter-intuitive (as "protect" doesn't work)?

**Comment by Frassle** [comment]
So before #8810 that operation would have succeeded. The old state would of had protect=false so could be deleted, it was only the new state that then had protection applied. 8810 started blocking that operation, this change lets it happen again.

8810 was fixing the _fun_ where you deploy a resource *with* protection, then change a property that causes a replacement we would create the new replacement resource, try to delete the old one and fail because it's protect bit was set. 8810 changed that so we fail before creating the new replacement resource.

8810 was intended to allow you to remove protect and do a replace in the same update but turns out that was still broken (I've added a test and fixed that now).
