### ISSUE TITLE
Support resources not yet created for --target glob patterns

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8956]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Right now, `--target '**:foo'` will only match resources that already exist in the current snapshot. We could expand support for resources that have not yet been created. 

### Affected area/feature
This would involve plumbing globs through the engine, instead of supporting them at the engine boundary.

**Comment by jberkenbilt** [comment]
I'll share my use case for this. I have a provisioning system, currently implemented using a combination of terraform along with other code to initialize stuff after terraform is done. I was thinking this would be a good use case for pulumi, possibly with the automation API. To oversimplify a little, the basic situation is that I have a number of tenants, each of which gets a number of resources. Most of the time, I just want to provision a new tenant and create all its resources without going through the costly process of validating all existing tenants. Sometimes I want to update/verify everything. Sometimes I want to just update all resources connected with a particular type of thing. For example, I may want to make a change to every tenant's IAM role or S3 bucket configuration.

With terraform or pulumi, you're in the classic dilemma of deciding whether to use one big project or lots of small projects. I did a little spike with pulumi of using one big project and then using wild-carded targeted updates. This works quite well and is a lot more flexible than terraform's `-target` option, particularly with `target-dependants`. However, given the lack of ability to target resources that don't yet exist, I can't do  targeted creation of the single custom resource that corresponds to a tenant. This forces me right back to where I am in terraform: I have to either use separate projects for everything or I have to pay the cost of going through all the resource validations for every tenant every time I want to create a new one.

If I end up just having separate projects and using shell for loops to iterate over them, there's not that big an advantage to switching to pulumi. There are still some advantages, so I haven't decided yet, but if this feature existed, it would create a much more compelling argument.

FWIW, I've been using terraform since 2016 and consider myself to be an expert. It took me just a few hours to start feeling comfortable with pulumi. If I don't switch now, I will definitely be watching closely as this has the potential to solve a number of the limitations I've had with terraform.
