### ISSUE TITLE
Support custom plugins from other sources

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#9007]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This is a follow up issue to https://github.com/pulumi/pulumi/pull/8944

That PR changed the plugin download flow for _all_ plugins to try and access private github releases if the relevant environment variables we're set.

We want to remove that flow so that plugins are either:
1) Custom plugins that go via a defined custom flow
2) Official plugins that go via Pulumis download routes (currently get.pulumi.com and github releases) 

Custom plugins should opt-in to mode 1 explicitly, currently this is done via `pluginDownloadURL` but that is not rich enough to describe situations such as private github releases (https://github.com/pulumi/pulumi/issues/8943). There are likely other download sources that users would be interested in and we should design this system such that it can be extended as use cases come up.

This issue is three-fold:
1) Design a new custom plugin download setting that can support both downloads from fixed urls, the github release api, and can be extended to support other download sources as required
2) Remove the download flow added by https://github.com/pulumi/pulumi/pull/8944
3) Depending on 1 but probably deprecate the pluginDownloadURL and remove it on a major version bump

**Comment by ringods** [comment]
For [Pulumiverse](https://github.com/pulumiverse), we want to host the plugins also via Github releases, but on public repositories. The repositories are hosted in the `pulumiverse` Github organization, but the need isn't limited to our organization.

Let's get the discussion going on how to rework this.

# Current CLI

```
$ pulumi plugin install -h
Install one or more plugins.

This command is used manually install plugins required by your program.  It may
be run either with a specific KIND, NAME, and VERSION, or by omitting these and
letting Pulumi compute the set of plugins that may be required by the current
project. If specified VERSION cannot be a range: it must be a specific number.

If you let Pulumi compute the set to download, it is conservative and may end up
downloading more plugins than is strictly necessary.

Usage:
  pulumi plugin install [KIND NAME [VERSION]] [flags]

Flags:
      --exact           Force installation of an exact version match (usually >= is accepted)
  -f, --file string     Install a plugin from a tarball file, instead of downloading it
  -h, --help            help for install
      --reinstall       Reinstall a plugin even if it already exists
      --server string   A URL to download plugins from
```
(ignored the global flags)

# Proposal

## Additional flags

To rework the plugin install in a more generic way, one could add all sorts of flags to support various kind of plugin storage backends. For instance, let's add a flag to define the type of backend to download from:

```
      --backend string   The type of backend to download from. Can be `file`, `https` or `github`
```

 For Github, we could add more flags:

```
      --github-owner string   The Github owner containing the Github repository
      --github-repo string   The Github repository containing the plugin in the Releases section.
```

If we need to add more and more flags for every backend type, this would complicate the CLI quite fast. Probably, this is not the best way to go forward.

## URL handlers

Another way, and **the one I propose**, is to continue use the `--server` option, but implement it with a system of URL handlers. If we take the example of Github releases, we could express the URL like this:

`github://<owner>/<repository>`

or like this:

`https://github.com/<owner>/<repository>`

The advantage of the first way is that we can distinguish the backend based on the URL scheme rather than the domain name. The downside is that it is a non-standard URL scheme. I would prefer the latter and map certain domain names to specific handlers, e.g. `github.com` to `githubSource` retrieving via Github releases.

Using URL handlers, we can deprecate the `-f / --file` flag as we can write `--server file://<location>` as the flag.

Any specific URL handler can lookup backend specific credentials. The Github handler can check if `GITHUB_TOKEN` is specified for private Github releases (CC: @patriziobruno). An S3 handler (`s3://...`) could check for AWS credentials using the AWS SDK standard credential lookup mechanism.

In the case where no `--server` flag is specified, we use the `fallbackSource` to remain backwards compatible.

@Frassle could you review this proposal and loop in on this discussion who needs to be involved?

**Comment by patriziobruno** [comment]
@ringods thanks for looping me in. I definitely like the URL handlers proposal and I agree that using well established schemes is to be preferred, identifying the backend based on the host (or pattern matching), much like most Android apps do.

**Comment by Frassle** [comment]
> much like most Android apps do.

Having not ever really done android development have you got some more info on that?

**Comment by Frassle** [comment]
> Additional flags
> To rework the plugin install in a more generic way, one could add all sorts of flags to support various kind of plugin storage 
> backends. For instance, let's add a flag to define the type of backend to download from:

So this isn't just needed for the `pulumi plugin install` command. When we query programs for what plugins they need they can also send back a url to download it from, and there is also the pluginDownloadUrl resource option that can be used to tell a resource to download and use a specific plugin as well (N.B. This option confuses me as I don't think we download plugins once running 😕).

I _like_ the idea of being pretty explicit and using full objects to describe the plugin sources, so you'd get something like: 
``` { type: "github", org: "pulumiverse", repo: "the-coolest-provider" }```
I don't think `plugin install` would _need_ to take a --backend though, we could just work it out based on what flags we're passed, so something like `pulumi plugin install resource the-coolest-provider --github-org pulumiverse` is very clearly using the github backend. If we get clashing flags we can just error.

Having said that, I think it would probably be _easier_ to retrofit a url scheme on top of our current single string "server url" data flows. I had been thinking of something like `github://github.org/pulumiverse/the-coolest-provider`. That would then also mean that if people had private github installations we're not making decisions based on url host, e.g. you could have something like `github://git.company.org/infrateam/secretprovider`.

But there maybe some merit to the android approach hinted by @patriziobruno above.

**Comment by ringods** [comment]
> Having not ever really done android development have you got some more info on that?

@Frassle Android, iOS but also desktop OS-es, have a way to open a specific app, even a specific resource within the app. For example, Slack uses it's own `slack://` URL scheme to let desktop or mobile apps open when clicked:

https://api.slack.com/reference/deep-linking#client

**Comment by ringods** [comment]
> Having said that, I think it would probably be _easier_ to retrofit a url scheme on top of our current single string "server url" data flows. I had been thinking of something like `github://github.org/pulumiverse/the-coolest-provider`. That would then also mean that if people had private github installations we're not making decisions based on url host, e.g. you could have something like `github://git.company.org/infrateam/secretprovider`.

Good catch. Companies using the enterprise (self-hosted) versions of Github or Gitlab would be served as well this way. That makes the proposal be as follows now, starting mainly with the URL scheme to map it to a handler:

* `file://` for local files
* `github://<host>/<owner>/<repository>/` to support Github SaaS as well as self-hosted options via the [Releases](https://docs.github.com/en/rest/reference/repos#releases) API. Looks up `GITHUB_TOKEN` for private repos.
* `gitlab://<host>/<owner>/<repository>/` to support Gitlab SaaS as well as self-hosted options via the [Releases API](https://docs.gitlab.com/ee/api/releases/). Looks up credentials supported in the [documentation](https://docs.gitlab.com/ee/security/token_overview.html).
* `s3://<bucket>/<path>` to support AWS S3. When using the AWS SDK, there is a standard credential lookup mechanism at play.
* `https://<host>/<path>` fallback to regular HTTP download.

Preferably, we want to use a rich API so implementing the `GetLatestVersion` is an easy task.

@jaxxstorm on Slack you mentioned that Github is already supported now and you gave an example. The `githubSource` in the Pulumi code uses the Github API to retrieve the plugins. Your example uses a plain HTTP file download on a public URL. You gave me an option now for Pulumiverse to already start self-hosting, but I would rather see it going via the Releases API.

**Comment by Frassle** [comment]
We know support http, GitHub, and GitLab as first class download sources. The scheme system can clearly and easily be extended to support more if customer requests come up. Given that I'm going to close this as done.
