### ISSUE TITLE
read-package-tree depreciated

### ISSUE THREAD

**Issue by JakeGinnivan** [pulumi/pulumi#9129]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

As part of good dependency hygine I try to remove deprecation notices when they appear. NPM has deprecated read-package-tree@5.3.1 which is replaced with [arborist](https://www.npmjs.com/package/@npmcli/arborist). 

I can see 2 ways forward

1) Migrate to arborist, there are no decent migration docs and the package is quite a bit larger than the current read-package-tree dependency
2) Inline the read-package-tree code, it's code is pretty simple and could just be absorbed into the pulumi codebase

### Steps to reproduce

1. Install @pulumi/pulumi into an Node project

Expected: No deprecation warning
Actual: Deprecation warning

**Comment by RobbieMcKinstry** [comment]
I'd personally prefer we migrate to arborist. I expect the increase in package size (~450KB) is not a major issue. Personally, I don't believe we should absorb new code into our code base if we can avoid it. We already support a large volume of code since we support six different languages, each with its own runtime and SDK. In the future, we can also minimize the impact of this package with tree shaking and modification. There are existing issues to track that work ([listed here](https://github.com/pulumi/pulumi/issues/11598)).

That's just my 2 cents! :) I'd be happy to accept a PR that removes this deprecation.

**Comment by kmosher** [comment]
This is apparently now tripping some vulnerability scanners for [CWE-772](https://cwe.mitre.org/data/definitions/772.html)

**Comment by data-stack404** [comment]
I'd like to add some context to this: 
Pulumi uses the deprecated package "read-package-tree", which itself is using "read-package-content". This one requires the abandoned package "inflight", that has the mentioned security vulnerability (https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116).
