### ISSUE TITLE
Add a flag to disable code generation to pulumi import

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#9134]
Getting Pulumi into the state is easy with `pulumi import` and we rather handily generate the code you need to add to your stack.

As per this comment: https://github.com/pulumi/pulumi/issues/6032#issuecomment-1059386589

It would be useful to have the mechanism to not generate the code when running `pulumi import` in some situations

**Comment by Frassle** [comment]
I think we should solve the problem in #6032 in a better way as well, but this is a really easy flag to just add.

**Comment by mikhailshilkov** [comment]
What's the downside of code generation that users need to disable it?

**Comment by Frassle** [comment]
> What's the downside of code generation that users need to disable it?

In #6032 its that they wanted to use the same name for resources of different types, but our PCL binder didn't like that because it also uses the given name for variable names which need to be unique. @pgavlin had some thoughts on how to best allow that situation properly.

So we should fix that properly, but the user also requested if they could just turn the code generation off because they don't really need it.
