### ISSUE TITLE
Allow ability to import resources into a component

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#9146]
## Issue details

Currently, when importing a component, you can specify the `--parent` flag like so:

```
pulumi import "aws:iam/role:Role" analytics-eventbridge-to-firehose AnalyticsEventbridgeToFirehoseRole --parent test='urn:pulumi:account-id-us-west-2::org::org:modules:analytics::test'
```

This unfortunately fails if you try to import into a component, because the parent doesn't exist.

You can see another example of this here: https://github.com/pulumi/pulumi/issues/5958#issuecomment-1054962897

It would be great if we could allow importing into a component without having to have the component exist first.

**Comment by Frassle** [comment]
Isn't this that we need to have a way to "import" components. I don't think we could synthesize component state without any user input, we'd need the user to tell us the name and type at least but nothing else is actually needed? Then once the component is imported you could import the other resources with it as a parent.

**Comment by danielrbradley** [comment]
I think this might be related to https://github.com/pulumi/pulumi/issues/5958

Either way we should have a story around how to start using a component where some or all of the resources that would be created already exist and should be imported. Perhaps this can't be a generic engine feature and has to be a per-component design, but we should understand what's possible.

**Comment by gunzy83** [comment]
You can literally create an empty class that extends `pulumi.ComponentResource` and deploy it... as long as the `type` is the same on the 'real' one, Pulumi will update happily after your import.
![image](https://user-images.githubusercontent.com/2989525/218634781-26999eb7-b24f-487d-9cba-31ba55ec4c3a.png)

**Comment by SamuelNeves** [comment]
Hi, we are still facing this issue. Any plans for an official fix? We have many resources that were created without pulumi, and we plan to import them to Pulumi. But since these resources were created using another IaC tool, we planed to build a custom component that will be responsible for implementing some name patterns and default setup of resources. That strategy went very well for new resources, but when we tried to import, we noticed that the `pulumi import` command never created the parent component and raised an error like that.
```
(...)
aws:s3:Bucket (nu-cloud-automation-test2):
 error: Preview failed: unknown parent 'urn:pulumi:test3::pulumi-import-with-components::company:BaseResources:StandardBucket::my-bucket-component-instance' for resource 'urn:pulumi:test3::pulumi-import-with-components::company:BaseResources:StandardBucket$aws:s3/bucket:Bucket::my-bucket-blah-21dsas'
```
 Pulumi version: 3.62.0
```
resources.json
  {"nameTable": {
 "bucket-component": "urn:pulumi:test3::pulumi-import-with-components::company:BaseResources:StandardB ck  ::my-bucket-component-instance",  "awssa-east1":"urn:pulumi:  st3::pulumi-import-with-compone  s::pulumi:providers:aws::awssa  ast1"
 },
 "resources": [
 {
  "type": "aws:s3/bucket:Bucket",
  "name": "my-bucket-blah",
  "id": "my-bucket-blah-21dsas",
  "parent": "bucket-component",
  "provider": "awssa-east1"
 }
]
}
```
In our opinion, the desired solution for that is to generate the parent on the state or at least to give the opportunity to import using a file, using the *name* and *type*.
PS: We understand that it's possible to use some workarounds to do that import, but still desirable to pulumi decrease the friction on that import cases.

**Comment by gunzy83** [comment]
I had a think about this, imports are entirely state operations so why not have flag on the import function for ComponentResource... it would be something like this:
```bash
pulumi import --component-resource gunzy:MyComponent test
```
or similar if using the `-f` option. Then you could run the commands easily or script it and not need to juggle dummy component resource deployments.

**Comment by mikhailshilkov** [comment]
Importing into a component has been possible for a while, but I think we are missing some explanations in the docs. I'll start by giving an example here.

I start with a simple program using `awsx` that defines a VPC:

```ts
import * as awsx from '@pulumi/awsx';

const vpc = new awsx.ec2.Vpc("privateVpc", {
   numberOfAvailabilityZones: 2,
   subnetStrategy: awsx.ec2.SubnetAllocationStrategy.Auto,
   subnetSpecs: [
       { type: awsx.ec2.SubnetType.Private },
   ],
   natGateways: {
      strategy: awsx.ec2.NatGatewayStrategy.None,
   }
});
```

It previews to

```
     Type                                          Name                  Plan       
 +   pulumi:pulumi:Stack                           aws-ts-dev            create     
 +   └─ awsx:ec2:Vpc                               privateVpc            create     
 +      └─ aws:ec2:Vpc                             privateVpc            create     
 +         ├─ aws:ec2:Subnet                       privateVpc-private-1  create     
 +         │  └─ aws:ec2:RouteTable                privateVpc-private-1  create     
 +         │     └─ aws:ec2:RouteTableAssociation  privateVpc-private-1  create     
 +         ├─ aws:ec2:Subnet                       privateVpc-private-2  create     
 +         │  └─ aws:ec2:RouteTable                privateVpc-private-2  create     
 +         │     └─ aws:ec2:RouteTableAssociation  privateVpc-private-2  create     
 +         └─ aws:ec2:InternetGateway              privateVpc            create
```

So, a bunch of resources parented to a component and to each other. So, let's say I have those resources in AWS but not in Pulumi state and I want to import them.

For this purpose, I need to create an import JSON file like this one:

```json
{
    "resources": [
        {
            "type": "awsx:ec2:Vpc",
            "name": "privateVpc",
            "component": true
        },
        {
            "type": "aws:ec2/vpc:Vpc",
            "name": "privateVpcVpc",
            "id": "vpc-0e1d985d94b11b80e",
            "parent": "privateVpc"
        },
        {
            "type": "aws:ec2/internetGateway:InternetGateway",
            "name": "privateVpcIgw",
            "id": "igw-020518b3c3cfecb36",
            "parent": "privateVpcVpc"
        },
        {
            "type": "aws:ec2/subnet:Subnet",
            "name": "privateVpc-private-1",
            "id": "subnet-034be577537bb5e88",
            "parent": "privateVpcVpc"
        },
        {
            "type": "aws:ec2/routeTable:RouteTable",
            "name": "privateVpc-private-1Rtb",
            "id": "rtb-064a8c96c99b142e5",
            "parent": "privateVpc-private-1"
        },
        {
            "type": "aws:ec2/routeTableAssociation:RouteTableAssociation",
            "name": "privateVpc-private-1Rta",
            "id": "subnet-034be577537bb5e88/rtb-064a8c96c99b142e5",
            "parent": "privateVpc-private-1Rtb"
        },
        {
            "type": "aws:ec2/subnet:Subnet",
            "name": "privateVpc-private-2",
            "id": "subnet-05ccfd46266da6830",
            "parent": "privateVpcVpc"
        },
        {
            "type": "aws:ec2/routeTable:RouteTable",
            "name": "privateVpc-private-2Rtb",
            "id": "rtb-087241c0a2f13272b",
            "parent": "privateVpc-private-2"
        },
        {
            "type": "aws:ec2/routeTableAssociation:RouteTableAssociation",
            "name": "privateVpc-private-2Rta",
            "id": "subnet-05ccfd46266da6830/rtb-087241c0a2f13272b",
            "parent": "privateVpc-private-2Rtb"
        }
    ]
}
```

It defines the component resource and all child resources with appropriate parents. Now I can run

```
pulumi import --file import.json
```

In this case, ignore all the code it generates, because I have the relevant code already via awsx usage.

Note: I wasn't able to match resource names exactly, so after the import I had to run a bunch of `pulumi state rename` commands, e.g.

```
pulumi state rename 'urn:pulumi:dev::aws-ts::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::privateVpcVpc' privateVpc
```

I'll follow up to see if this is avoidable.

**Comment by mikhailshilkov** [comment]
I've also added a section in our docs that gives an example: https://www.pulumi.com/docs/using-pulumi/adopting-pulumi/import/#example-import-a-component-with-all-resources

I'll close this issue as resolved. If you have suggestions to improve the experience, please open new more specific issues.
