### ISSUE TITLE
consider suppressing stacktraces in situations where we know it is not helpful

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9230]
## overview
we display stacktraces in situations where it is not helpful to the user. can we detect when it will not provide any help to the user and hide it? or force the user to take a separate action to view it?

**Comment by susanev** [comment]
notes from Zaid
- case-by-case basis and how much effort we want to put effort into it
- not an easy thing to do

**Comment by susanev** [comment]
notes from Pat
- should be careful about how much time we spend here
- should keep in mind that developers are familiar with reading stack traces
- will want to provide some way for folks to access the entire stack trace if they want to

**Comment by dixler** [comment]
I think this is now generally fixed in the CLI(in python and nodejs), but I think there's opportunity to reduce the stack traces in the provider SDKs. PRs
- https://github.com/pulumi/pulumi/pull/10336
- https://github.com/pulumi/pulumi/pull/10465

The only other location that I can think of on the top of my head, are in provider SDKs. I've seen some really large stack traces show up, but I think it'd require some discussion with the providers team.
https://asciinema.org/a/qnJyz7FiaUoeSHXiysKjgQH4l

Any other stack traces we can omit?

**Comment by mikhailshilkov** [comment]
> https://asciinema.org/a/qnJyz7FiaUoeSHXiysKjgQH4l

Noob question - how can I zoom in to see the text?

**Comment by dixler** [comment]
> 

To view it, I drag selected everything and copy pasted it into an editor.

I ran into this issue when trying to repro https://github.com/pulumi/pulumi/issues/10172

**Comment by t0yv0** [comment]
I agree with Kyle, I think we put enough fixes here for the moment. Closing for now.  If you can think of another specific scenario when an unhelpful stack trace is shown, please open another ticket with a repro, this would be super helpful.
