### ISSUE TITLE
Support custom config file locations

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#929]
Add the option for multiple config files, which can themselves be .gitignored. The link between a stack and its config file is stored somewhere in the `.pulumi` folder. See design notes at [Simplifying our config story](https://github.com/pulumi/design/blob/master/meetings/2018/2018-01-25.md).

A few details:
- For a given stack, config can be either in `Pulumi.yaml` or a custom config file, but not both

Open question:
- What happens when a stack is deleted via `stack rm`? Is the config removed from the custom file, similar to Pulumi.yaml, or is there an additional interactive question?

**Comment by ellismg** [comment]
A lot of stuff has changed in the 3 months since I proposed we push this out.  Based on an engagement with a customer we added the ability to specify `config: <path>` and use that as the folder for setting configuration for a stack.  We did not let you change the name of the stack filename, but I think what we have now is good enough to close this instead of re-checking every milestone to see if someone needs something different.  If we get feedback that more control is needed, we'll open a new issue.
