### ISSUE TITLE
PULUMI_CONFIG_PASSPHRASE can not be empty

### ISSUE THREAD

**Issue by jasonyic** [pulumi/pulumi#9489]
### What happened?

I do not use `PULUMI_CONFIG_PASSPHRASE` in the project and `export PULUMI_CONFIG_PASSPHRASE=` just wroks in `3.28.0`. after upgrade to `3.30.0`, I got the following error:
```
error: Preview failed: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase or set PULUMI_CONFIG_PASSPHRASE_FILE to a file containing the passphrase
```
does it mean what support for empty string is removed in this release? thanks

### Steps to reproduce

1. make sure using pulumi `3.30.0`

2. export PULUMI_CONFIG_PASSPHRASE=

3. pulumi preview

### Expected Behavior

should show the preview result

### Actual Behavior

error: Preview failed: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase or set PULUMI_CONFIG_PASSPHRASE_FILE to a file containing the passphrase

### Versions used

3.30.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
We haven't changed any code in this area, so I'm surprised this ever worked.

Workaround for now is to `unset PULUMI_CONFIG_PASSPHRASE` rather than setting it to "". It should be a quick fix for us to check for empty and treat that as unset as well for the next release.

**Comment by jasonyic** [comment]
thanks for the quick response. after `unset PULUMI_CONFIG_PASSPHRASE` & `PULUMI_CONFIG_PASSPHRASE_FILE`, it just prompt me with `error: incorrect passphrase`

**Comment by Frassle** [comment]
If your not setting `PULUMI_CONFIG_PASSPHRASE` it should be prompting you to enter a passphrase instead. Do you get that prompt?

**Comment by Frassle** [comment]
Re-opening this as we've reverted the change that treated PULUMI_CONFIG_PASSPHRASE set to "" the same as it being unset.

I expect all we can do here is maybe try and find a good place for a warning if a user has an empty passphrase that they might have meant to unset CONFIG_PASSPHRASE.

**Comment by joeypunzel** [comment]
Similar issue on my side as well but we're actually pinning to the 3.31.0 version due to this issue . Prior to 3.31.1 upgrade, all our deployments with pulumi were successful with a null PULUMI_CONFIG_PASSPHRASE (i.e. ="") . Now all our deployments fail with pulumi 3.31.1+ because we never setup PULUMI_CONFIG_PASSPHRASE when initializing this stack. 

Is the only option here to spin up a new stack and set the passphrase on a new stack? is there anything I can do to set PULUMI_CONFIG_PASSPHRASE on a pre-existing stack? for us the stack is in production, so we'd like to avoid migrating resources from stack to stack if at all possible. 

would love to stay on the current version (3.32.1) but this is a breaking change for all of our deployments so we have to stay pinned to v3.31.0 until can find a workaround for this issue. any insight would be appreciated

**Comment by raphaelauv** [comment]
with pulumi `3.30.0`

I could do 


```shell
export PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH=true
export PULUMI_CONFIG_PASSPHRASE_FILE=
export PULUMI_CONFIG_PASSPHRASE=
pulumi up
```


now with pulumi  `3.32.1`  if give me 

```shell
export PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH=true
export PULUMI_CONFIG_PASSPHRASE_FILE=
export PULUMI_CONFIG_PASSPHRASE=
pulumi up 
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
```

**Comment by Frassle** [comment]
To both of the above this issue is NOT tracking the problem your describing. It is the instigator issue that led us to making that change to PULUMI_CONFIG_PASSPHRASE, we have now reverted that change and as such have re-opened this issue to work out what we should do in terms of empty passwords given that some users will set them to "" instead of unsetting them.

The next release of pulumi will revert the behavior of PULUMI_CONFIG_PASSPHRASE back to treating "" as an empty passphrase rather than it not being set.

**Comment by raphaelauv** [comment]
it was fix with [v3.33.1](https://github.com/pulumi/pulumi/releases/tag/v3.33.1)

**Comment by Frassle** [comment]
Yeh I thought that, but this is tracking the issue original issue.

> I do not use PULUMI_CONFIG_PASSPHRASE in the project and export PULUMI_CONFIG_PASSPHRASE= just wroks in 3.28.0. after upgrade to 3.30.0, I got the following error:

I suspect this _might_ just be an obscure user error and nothing actually changed to trigger this issue.

@jasonyic have you got any more feedback on this? Are you _sure_ that `export PULUMI_CONFIG_PASSPHRASE=` was working before, because as far as I can tell that used to always result in the password being set to "" not no password.

**Comment by jasonyic** [comment]
sorry for the late reply, export PULUMI_CONFIG_PASSPHRASE= won't work for > 3.30.0, but I can  use `pulumi stack change-secrets-provider passphrase` to migrate the empty passphrase/not set

**Comment by lk-autoops** [comment]
> sorry for the late reply, export PULUMI_CONFIG_PASSPHRASE= won't work for > 3.30.0, but I can use `pulumi stack change-secrets-provider passphrase` to migrate the empty passphrase/not set

I tried this but still asked the passphrase even I did not set any passphrase for it .


`pulumi preview                                 
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
Previewing update (dev):
     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  front_infra-dev  create     1 message`

**Comment by Frassle** [comment]
> even I did not set any passphrase for it .

There is no way to do this, you _must_ have set a passphrase it just might have been the empty string.

**Comment by grant-zukowski-xumo** [comment]
This is still an issue, when running `pulumi login` during a code build stage with a deployspec.yaml I have to set `PULUMI_CONFIG_PASSPHRASE: ''` or the login will fail.  Please re-open this issue.
