### ISSUE TITLE
`pulumi refresh` should update stack outputs

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#9990]
### What happened?

`pulumi refresh` does not update stack references. The only way to update stack references is with a targeted up. 

### Steps to reproduce

Two pulumi programs. 
1. Set an output
2. The second program gets the output from the stack reference
3. change the output value on the first app, then `pulumi up`
4. on the second program run `pulumi refresh`, then `pulumi stack output`

### Expected Behavior

It should update the stack reference. 

### Actual Behavior

It does not update the stack references and the output remains the same. 

### Versions used

github/pulumi_projects/aws-eks-ts2 via  v16.15.0 via  richard-shade-pulumi@dev
❯ pulumi about
CLI
Version      3.35.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.9.1
docker      3.2.0
eks         0.41.0
kubernetes  3.19.4
nodejs      unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I suspect this is because we don't implement Read. Which would also causes issues with trying to import stack references.

**Comment by justinvp** [comment]
> I suspect this is because we don't implement Read

Looks like we do:

https://github.com/pulumi/pulumi/blob/3437d282805bcfb1df2de4ecb952307dbfe8e5cb/pkg/resource/deploy/builtins.go#L153-L169

**Comment by aureq** [comment]
I'll a summarise the discussion I just had with @Frassle

Running `refresh` does affect the state of a stack, however it works in the same way `destroy` works. The relevant Pulumi app is not executed during `refresh` and `destroy` and only the state is used during those operations.

Since stack references are tracked as resources (like any Pulumi resources), the lack of an underlying execution makes it impossible to tie up the stack ref value to a stack output.

IMHO, a bug should be opened to update the stack references values in the state file but a different feature request should be considered to allow execution when calling `refresh`.

**Comment by dixler** [comment]
Seems tangential to https://github.com/pulumi/pulumi/issues/1691

**Comment by Frassle** [comment]
Yes, also https://github.com/pulumi/pulumi/issues/4981

**Comment by arnaldopereira** [comment]
Also #2710

**Comment by lukehoban** [comment]
As noted in the recent replies, this is ultimately the same issue tracked in #2710. The existing behaviour here is currently by design, but we do want to explore paths to change the beahviour of refresh in the future.  For now though, an update is required to re-propagate changes through to stack outputs.
